// Localized content for /entlassungsbericht. German is the SEO base;
// unlisted languages fall back to English. German quotes stay German.
const QUOTE = '"Z. n. Cholezystektomie bei symptomatischer Cholezystolithiasis. Reizlose Wundverhältnisse. Procedere: Fadenzug am 10. postoperativen Tag, körperliche Schonung für 2 Wochen."'

export const CONTENT = {
  de: {
    headerTitle: 'Entlassungsbericht verstehen',
    headerCta: 'Bericht hochladen',
    badge: 'Entlassungsbericht · OP-Bericht · Krankenhausbrief',
    h1a: 'Aus dem Krankenhaus,',
    h1b: 'aber was jetzt?',
    sub: 'Der Entlassungsbericht entscheidet, wie es nach dem Krankenhaus weitergeht. Medyra übersetzt ihn in klare Sprache: was passiert ist, welche Medikamente sich geändert haben und was Sie jetzt tun sollten.',
    cta: 'Bericht jetzt erklären lassen',
    mock: {
      labelIn: 'Im Bericht steht', quote: QUOTE, labelOut: 'Medyra erklärt',
      lines: [
        'Ihre Gallenblase wurde wegen Gallensteinen entfernt, die Beschwerden verursacht haben.',
        'Die Wunde heilt gut, es gibt keine Anzeichen einer Entzündung.',
        'In etwa 10 Tagen werden die Fäden gezogen, danach 2 Wochen körperlich schonen.',
      ],
    },
    cardsLabel: 'Was Sie bekommen',
    cardsTitle: 'Der ganze Bericht, klar erklärt',
    cards: [
      { icon: '🏥', title: 'Was im Krankenhaus passiert ist', desc: 'Aufnahmegrund, Diagnosen und durchgeführte Eingriffe, Absatz für Absatz in klare Sprache übersetzt, ohne Panik und ohne Fachchinesisch.' },
      { icon: '💊', title: 'Geänderte Medikamente', desc: 'Entlassungsberichte ändern oft die Medikation. Medyra zeigt verständlich, was neu ist, was wegfällt und worauf Sie achten sollten.' },
      { icon: '📅', title: 'Was Sie jetzt tun müssen', desc: 'Nachsorge-Termine, Kontrollen, Verhaltensregeln: die Anweisungen aus dem Bericht als klare, ruhige Liste mit Fragen für den Hausarzt.' },
    ],
    jargon: {
      label: 'Beispiele', title: 'Krankenhaus-Deutsch, übersetzt',
      pairs: [
        ['Z. n.', 'Zustand nach, eine frühere Erkrankung oder OP'],
        ['Procedere', 'das weitere Vorgehen, Ihr Fahrplan nach der Entlassung'],
        ['kardiopulmonal stabil', 'Herz und Lunge arbeiten normal'],
        ['reizlose Wundverhältnisse', 'die Wunde heilt gut, keine Entzündung'],
        ['Rekompensation', 'der Körper ist wieder im Gleichgewicht'],
        ['AZ und EZ', 'Allgemeinzustand und Ernährungszustand'],
      ],
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Was kann ich hochladen?', a: 'Entlassungsberichte, Entlassungsbriefe, OP-Berichte und vorläufige Arztbriefe aus dem Krankenhaus, als PDF oder einfach abfotografiert mit dem Handy.' },
      { q: 'Der Bericht ist mehrere Seiten lang. Geht das?', a: 'Ja. Medyra fasst den gesamten Bericht zusammen und erklärt ihn Abschnitt für Abschnitt: Diagnosen, Verlauf, Medikation und die empfohlene Nachsorge.' },
      { q: 'Ersetzt das die Nachsorge beim Hausarzt?', a: 'Nein. Medyra hilft Ihnen, den Bericht zu verstehen und vorbereitet ins Gespräch zu gehen. Die medizinische Nachsorge gehört in ärztliche Hände.' },
      { q: 'Was passiert mit dem Bericht?', a: 'Verschlüsselte Verarbeitung, DSGVO-konformes Hosting in Frankfurt, automatische Löschung nach 30 Tagen (auf Wunsch sofort).' },
    ],
    ctaTitle: 'Gehen Sie vorbereitet in die Nachsorge',
    ctaSub: '3 Dokumente pro Monat kostenlos. DSGVO-konform, verschlüsselt, automatisch gelöscht.',
    ctaButton: 'Entlassungsbericht erklären lassen',
    ctaNote: 'Medyra ersetzt keine ärztliche Beratung. Besprechen Sie Ihre Nachsorge immer mit Ihrer Ärztin oder Ihrem Arzt.',
  },

  en: {
    headerTitle: 'Understand hospital reports',
    headerCta: 'Upload report',
    badge: 'Discharge report · Surgery report · Hospital letter',
    h1a: 'Out of the hospital,',
    h1b: 'but what now?',
    sub: 'The discharge report decides how things continue after the hospital. Medyra translates it into plain language: what happened, which medications changed and what you should do now.',
    cta: 'Explain my report now',
    mock: {
      labelIn: 'The report says', quote: QUOTE, labelOut: 'Medyra explains',
      lines: [
        'Your gallbladder was removed because of gallstones that caused symptoms.',
        'The wound is healing well, there are no signs of inflammation.',
        'Stitches come out in about 10 days, then take it easy physically for 2 weeks.',
      ],
    },
    cardsLabel: 'What you get',
    cardsTitle: 'The whole report, clearly explained',
    cards: [
      { icon: '🏥', title: 'What happened at the hospital', desc: 'Reason for admission, diagnoses and procedures, translated into plain language paragraph by paragraph, without panic and without jargon.' },
      { icon: '💊', title: 'Changed medications', desc: 'Discharge reports often change your medication. Medyra shows clearly what is new, what stops and what to watch out for.' },
      { icon: '📅', title: 'What you need to do now', desc: 'Follow up appointments, checks and instructions from the report as a clear, calm list with questions for your family doctor.' },
    ],
    jargon: {
      label: 'Examples', title: 'Hospital German, translated',
      pairs: [
        ['Z. n.', 'condition after, a previous illness or surgery'],
        ['Procedere', 'the next steps, your roadmap after discharge'],
        ['kardiopulmonal stabil', 'heart and lungs are working normally'],
        ['reizlose Wundverhältnisse', 'the wound is healing well, no inflammation'],
        ['Rekompensation', 'the body is back in balance'],
        ['AZ und EZ', 'general condition and nutritional state'],
      ],
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'What can I upload?', a: 'Discharge reports, discharge letters, surgery reports and preliminary doctor letters from the hospital, as PDF or simply photographed with your phone.' },
      { q: 'The report is several pages long. Is that ok?', a: 'Yes. Medyra summarizes the whole report and explains it section by section: diagnoses, course, medication and the recommended follow up.' },
      { q: 'Does this replace follow up care?', a: 'No. Medyra helps you understand the report and go into the conversation prepared. Medical follow up belongs in medical hands.' },
      { q: 'What happens to the report?', a: 'Encrypted processing, GDPR compliant hosting in Frankfurt, automatic deletion after 30 days (immediately on request).' },
    ],
    ctaTitle: 'Go into your follow up prepared',
    ctaSub: '3 documents per month free. GDPR compliant, encrypted, deleted automatically.',
    ctaButton: 'Explain my discharge report',
    ctaNote: 'Medyra does not replace medical advice. Always discuss your follow up care with your doctor.',
  },

  tr: {
    headerTitle: 'Hastane raporunu anlayın',
    headerCta: 'Rapor yükle',
    badge: 'Taburcu raporu · Ameliyat raporu · Hastane yazısı',
    h1a: 'Hastaneden çıktınız,',
    h1b: 'peki şimdi ne olacak?',
    sub: 'Taburcu raporu, hastaneden sonra işlerin nasıl devam edeceğini belirler. Medyra onu anlaşılır dile çevirir: ne oldu, hangi ilaçlar değişti ve şimdi ne yapmalısınız.',
    cta: 'Raporumu şimdi açıkla',
    mock: {
      labelIn: 'Raporda yazan', quote: QUOTE, labelOut: 'Medyra açıklıyor',
      lines: [
        'Şikayetlere neden olan safra taşları yüzünden safra keseniz alındı.',
        'Yara iyi iyileşiyor, iltihap belirtisi yok.',
        'Dikişler yaklaşık 10 gün sonra alınacak, ardından 2 hafta fiziksel olarak dinlenin.',
      ],
    },
    cardsLabel: 'Ne alırsınız',
    cardsTitle: 'Raporun tamamı, net açıklanmış',
    cards: [
      { icon: '🏥', title: 'Hastanede ne oldu', desc: 'Yatış nedeni, tanılar ve yapılan müdahaleler, paragraf paragraf anlaşılır dile çevrilir; panik ve tıp jargonu olmadan.' },
      { icon: '💊', title: 'Değişen ilaçlar', desc: 'Taburcu raporları çoğu zaman ilaçları değiştirir. Medyra neyin yeni olduğunu, neyin kesildiğini ve nelere dikkat edileceğini net gösterir.' },
      { icon: '📅', title: 'Şimdi ne yapmalısınız', desc: 'Kontrol randevuları ve talimatlar; aile hekiminize sorulacak sorularla birlikte sakin ve net bir liste halinde.' },
    ],
    jargon: {
      label: 'Örnekler', title: 'Hastane Almancası, çevrildi',
      pairs: [
        ['Z. n.', 'sonrası durum; geçirilmiş hastalık veya ameliyat'],
        ['Procedere', 'sonraki adımlar; taburcu sonrası yol haritanız'],
        ['kardiopulmonal stabil', 'kalp ve akciğerler normal çalışıyor'],
        ['reizlose Wundverhältnisse', 'yara iyi iyileşiyor, iltihap yok'],
        ['Rekompensation', 'vücut yeniden dengede'],
        ['AZ und EZ', 'genel durum ve beslenme durumu'],
      ],
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Neler yükleyebilirim?', a: 'Taburcu raporları ve mektupları, ameliyat raporları ve hastaneden gelen ön doktor mektupları; PDF olarak veya telefonla fotoğraflayarak.' },
      { q: 'Rapor birkaç sayfa. Sorun olur mu?', a: 'Hayır. Medyra raporun tamamını özetler ve bölüm bölüm açıklar: tanılar, seyir, ilaçlar ve önerilen takip.' },
      { q: 'Bu, aile hekimi kontrolünün yerine geçer mi?', a: 'Hayır. Medyra raporu anlamanıza ve görüşmeye hazır gitmenize yardımcı olur. Tıbbi takip doktorların işidir.' },
      { q: 'Rapora ne olur?', a: 'Şifreli işleme, Frankfurt’ta GDPR uyumlu barındırma, 30 gün sonra otomatik silme (istekle hemen).' },
    ],
    ctaTitle: 'Kontrole hazırlıklı gidin',
    ctaSub: 'Ayda 3 belge ücretsiz. GDPR uyumlu, şifreli, otomatik silinir.',
    ctaButton: 'Taburcu raporumu açıkla',
    ctaNote: 'Medyra tıbbi danışmanlığın yerini tutmaz. Takibinizi her zaman doktorunuzla görüşün.',
  },

  ar: {
    headerTitle: 'افهم تقرير المستشفى',
    headerCta: 'ارفع التقرير',
    badge: 'تقرير خروج · تقرير عملية · خطاب مستشفى',
    h1a: 'خرجت من المستشفى،',
    h1b: 'لكن ماذا الآن؟',
    sub: 'تقرير الخروج يحدد كيف تستمر الأمور بعد المستشفى. يترجمه Medyra إلى لغة واضحة: ما الذي حدث، وأي أدوية تغيرت، وما الذي يجب فعله الآن.',
    cta: 'اشرح تقريري الآن',
    mock: {
      labelIn: 'ما يقوله التقرير', quote: QUOTE, labelOut: 'Medyra يشرح',
      lines: [
        'أزيلت مرارتك بسبب حصوات سببت الأعراض.',
        'الجرح يلتئم جيداً ولا توجد علامات التهاب.',
        'تُزال الغرز بعد نحو 10 أيام، ثم راحة بدنية لمدة أسبوعين.',
      ],
    },
    cardsLabel: 'ما تحصل عليه',
    cardsTitle: 'التقرير كاملاً، مشروح بوضوح',
    cards: [
      { icon: '🏥', title: 'ما الذي حدث في المستشفى', desc: 'سبب الدخول والتشخيصات والإجراءات، مترجمة فقرة فقرة إلى لغة واضحة، دون قلق ودون مصطلحات معقدة.' },
      { icon: '💊', title: 'الأدوية المتغيرة', desc: 'تقارير الخروج تغيّر الأدوية غالباً. يوضح Medyra ما الجديد وما توقف وما الذي يجب الانتباه إليه.' },
      { icon: '📅', title: 'ما الذي يجب فعله الآن', desc: 'مواعيد المتابعة والفحوصات والتعليمات في قائمة هادئة وواضحة مع أسئلة لطبيب العائلة.' },
    ],
    jargon: {
      label: 'أمثلة', title: 'لغة المستشفى الألمانية، مترجمة',
      pairs: [
        ['Z. n.', 'حالة بعد؛ مرض أو عملية سابقة'],
        ['Procedere', 'الخطوات التالية؛ خارطة طريقك بعد الخروج'],
        ['kardiopulmonal stabil', 'القلب والرئتان يعملان بشكل طبيعي'],
        ['reizlose Wundverhältnisse', 'الجرح يلتئم جيداً، لا التهاب'],
        ['Rekompensation', 'الجسم عاد إلى توازنه'],
        ['AZ und EZ', 'الحالة العامة والحالة الغذائية'],
      ],
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما الذي يمكنني رفعه؟', a: 'تقارير وخطابات الخروج وتقارير العمليات والخطابات الأولية من المستشفى؛ كملف PDF أو بتصويرها بالهاتف.' },
      { q: 'التقرير من عدة صفحات. هل هذا ممكن؟', a: 'نعم. يلخص Medyra التقرير كاملاً ويشرحه قسماً قسماً: التشخيصات والمسار والأدوية والمتابعة الموصى بها.' },
      { q: 'هل يغني هذا عن متابعة الطبيب؟', a: 'لا. يساعدك Medyra على فهم التقرير والذهاب إلى الموعد مستعداً. المتابعة الطبية من اختصاص الأطباء.' },
      { q: 'ماذا يحدث للتقرير؟', a: 'معالجة مشفرة، واستضافة متوافقة مع GDPR في فرانكفورت، وحذف تلقائي بعد 30 يوماً (وفوراً عند الطلب).' },
    ],
    ctaTitle: 'اذهب إلى المتابعة مستعداً',
    ctaSub: '3 مستندات شهرياً مجاناً. متوافق مع GDPR، مشفر، يُحذف تلقائياً.',
    ctaButton: 'اشرح تقرير الخروج',
    ctaNote: 'لا يحل Medyra محل الاستشارة الطبية. ناقش متابعتك دائماً مع طبيبك.',
  },

  ru: {
    headerTitle: 'Понять больничную выписку',
    headerCta: 'Загрузить выписку',
    badge: 'Выписка · Операционный отчёт · Письмо из больницы',
    h1a: 'Из больницы выписали,',
    h1b: 'а что дальше?',
    sub: 'Выписка определяет, как всё пойдёт после больницы. Medyra переводит её на понятный язык: что произошло, какие лекарства изменились и что делать теперь.',
    cta: 'Объяснить мою выписку',
    mock: {
      labelIn: 'В выписке написано', quote: QUOTE, labelOut: 'Medyra объясняет',
      lines: [
        'Вам удалили желчный пузырь из-за камней, которые вызывали жалобы.',
        'Рана заживает хорошо, признаков воспаления нет.',
        'Швы снимут примерно через 10 дней, затем 2 недели физического покоя.',
      ],
    },
    cardsLabel: 'Что вы получаете',
    cardsTitle: 'Вся выписка, понятно объяснённая',
    cards: [
      { icon: '🏥', title: 'Что произошло в больнице', desc: 'Причина госпитализации, диагнозы и проведённые вмешательства, абзац за абзацем на простом языке, без паники и без жаргона.' },
      { icon: '💊', title: 'Изменённые лекарства', desc: 'Выписки часто меняют схему лечения. Medyra ясно показывает, что новое, что отменено и на что обратить внимание.' },
      { icon: '📅', title: 'Что делать теперь', desc: 'Контрольные визиты, обследования и указания из выписки в виде спокойного списка с вопросами для семейного врача.' },
    ],
    jargon: {
      label: 'Примеры', title: 'Больничный немецкий, переведён',
      pairs: [
        ['Z. n.', 'состояние после; перенесённая болезнь или операция'],
        ['Procedere', 'дальнейшие шаги; ваш план после выписки'],
        ['kardiopulmonal stabil', 'сердце и лёгкие работают нормально'],
        ['reizlose Wundverhältnisse', 'рана заживает хорошо, воспаления нет'],
        ['Rekompensation', 'организм снова в равновесии'],
        ['AZ und EZ', 'общее состояние и состояние питания'],
      ],
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Что можно загрузить?', a: 'Выписки, выписные письма, операционные отчёты и предварительные письма из больницы; как PDF или просто сфотографировав телефоном.' },
      { q: 'Выписка на несколько страниц. Это возможно?', a: 'Да. Medyra резюмирует весь документ и объясняет его по разделам: диагнозы, течение, лекарства и рекомендованное наблюдение.' },
      { q: 'Заменяет ли это визит к врачу?', a: 'Нет. Medyra помогает понять документ и прийти на приём подготовленным. Медицинское наблюдение остаётся за врачами.' },
      { q: 'Что происходит с выпиской?', a: 'Зашифрованная обработка, GDPR совместимый хостинг во Франкфурте, автоматическое удаление через 30 дней (по желанию сразу).' },
    ],
    ctaTitle: 'Приходите на приём подготовленным',
    ctaSub: '3 документа в месяц бесплатно. GDPR, шифрование, автоматическое удаление.',
    ctaButton: 'Объяснить мою выписку',
    ctaNote: 'Medyra не заменяет консультацию врача. Всегда обсуждайте наблюдение с вашим врачом.',
  },
}
