// Localized content for /entlassungsbericht. German is the SEO base;
// unlisted languages fall back to English. German quotes stay German.
const QUOTE = '"Z. n. Cholezystektomie bei symptomatischer Cholezystolithiasis. Reizlose Wundverhältnisse. Procedere: Fadenzug am 10. postoperativen Tag, körperliche Schonung für 2 Wochen."'

export const CONTENT = {
  de: {
    headerTitle: 'Entlassungsbericht verstehen',
    headerCta: 'Bericht hochladen',
    badge: 'Entlassungsbericht · OP-Bericht · Krankenhausbrief',
    h1a: 'Aus dem Krankenhaus,',
    h1b: 'aber was jetzt?',
    sub: 'Der Entlassungsbericht entscheidet, wie es nach dem Krankenhaus weitergeht. Medyra übersetzt ihn in klare Sprache: was passiert ist, welche Medikamente sich geändert haben und was Sie jetzt tun sollten.',
    cta: 'Bericht jetzt erklären lassen',
    mock: {
      labelIn: 'Im Bericht steht', quote: QUOTE, labelOut: 'Medyra erklärt',
      lines: [
        'Ihre Gallenblase wurde wegen Gallensteinen entfernt, die Beschwerden verursacht haben.',
        'Die Wunde heilt gut, es gibt keine Anzeichen einer Entzündung.',
        'In etwa 10 Tagen werden die Fäden gezogen, danach 2 Wochen körperlich schonen.',
      ],
    },
    cardsLabel: 'Was Sie bekommen',
    cardsTitle: 'Der ganze Bericht, klar erklärt',
    cards: [
      { icon: '🏥', title: 'Was im Krankenhaus passiert ist', desc: 'Aufnahmegrund, Diagnosen und durchgeführte Eingriffe, Absatz für Absatz in klare Sprache übersetzt, ohne Panik und ohne Fachchinesisch.' },
      { icon: '💊', title: 'Geänderte Medikamente', desc: 'Entlassungsberichte ändern oft die Medikation. Medyra zeigt verständlich, was neu ist, was wegfällt und worauf Sie achten sollten.' },
      { icon: '📅', title: 'Was Sie jetzt tun müssen', desc: 'Nachsorge-Termine, Kontrollen, Verhaltensregeln: die Anweisungen aus dem Bericht als klare, ruhige Liste mit Fragen für den Hausarzt.' },
    ],
    jargon: {
      label: 'Beispiele', title: 'Krankenhaus-Deutsch, übersetzt',
      pairs: [
        ['Z. n.', 'Zustand nach, eine frühere Erkrankung oder OP'],
        ['Procedere', 'das weitere Vorgehen, Ihr Fahrplan nach der Entlassung'],
        ['kardiopulmonal stabil', 'Herz und Lunge arbeiten normal'],
        ['reizlose Wundverhältnisse', 'die Wunde heilt gut, keine Entzündung'],
        ['Rekompensation', 'der Körper ist wieder im Gleichgewicht'],
        ['AZ und EZ', 'Allgemeinzustand und Ernährungszustand'],
      ],
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Was kann ich hochladen?', a: 'Entlassungsberichte, Entlassungsbriefe, OP-Berichte und vorläufige Arztbriefe aus dem Krankenhaus, als PDF oder einfach abfotografiert mit dem Handy.' },
      { q: 'Der Bericht ist mehrere Seiten lang. Geht das?', a: 'Ja. Medyra fasst den gesamten Bericht zusammen und erklärt ihn Abschnitt für Abschnitt: Diagnosen, Verlauf, Medikation und die empfohlene Nachsorge.' },
      { q: 'Ersetzt das die Nachsorge beim Hausarzt?', a: 'Nein. Medyra hilft Ihnen, den Bericht zu verstehen und vorbereitet ins Gespräch zu gehen. Die medizinische Nachsorge gehört in ärztliche Hände.' },
      { q: 'Was passiert mit dem Bericht?', a: 'Verschlüsselte Verarbeitung, DSGVO-konformes Hosting in Frankfurt, automatische Löschung nach 30 Tagen (auf Wunsch sofort).' },
    ],
    ctaTitle: 'Gehen Sie vorbereitet in die Nachsorge',
    ctaSub: '3 Dokumente pro Monat kostenlos. DSGVO-konform, verschlüsselt, automatisch gelöscht.',
    ctaButton: 'Entlassungsbericht erklären lassen',
    ctaNote: 'Medyra ersetzt keine ärztliche Beratung. Besprechen Sie Ihre Nachsorge immer mit Ihrer Ärztin oder Ihrem Arzt.',
  },

  en: {
    headerTitle: 'Understand hospital reports',
    headerCta: 'Upload report',
    badge: 'Discharge report · Surgery report · Hospital letter',
    h1a: 'Out of the hospital,',
    h1b: 'but what now?',
    sub: 'The discharge report decides how things continue after the hospital. Medyra translates it into plain language: what happened, which medications changed and what you should do now.',
    cta: 'Explain my report now',
    mock: {
      labelIn: 'The report says', quote: QUOTE, labelOut: 'Medyra explains',
      lines: [
        'Your gallbladder was removed because of gallstones that caused symptoms.',
        'The wound is healing well, there are no signs of inflammation.',
        'Stitches come out in about 10 days, then take it easy physically for 2 weeks.',
      ],
    },
    cardsLabel: 'What you get',
    cardsTitle: 'The whole report, clearly explained',
    cards: [
      { icon: '🏥', title: 'What happened at the hospital', desc: 'Reason for admission, diagnoses and procedures, translated into plain language paragraph by paragraph, without panic and without jargon.' },
      { icon: '💊', title: 'Changed medications', desc: 'Discharge reports often change your medication. Medyra shows clearly what is new, what stops and what to watch out for.' },
      { icon: '📅', title: 'What you need to do now', desc: 'Follow up appointments, checks and instructions from the report as a clear, calm list with questions for your family doctor.' },
    ],
    jargon: {
      label: 'Examples', title: 'Hospital German, translated',
      pairs: [
        ['Z. n.', 'condition after, a previous illness or surgery'],
        ['Procedere', 'the next steps, your roadmap after discharge'],
        ['kardiopulmonal stabil', 'heart and lungs are working normally'],
        ['reizlose Wundverhältnisse', 'the wound is healing well, no inflammation'],
        ['Rekompensation', 'the body is back in balance'],
        ['AZ und EZ', 'general condition and nutritional state'],
      ],
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'What can I upload?', a: 'Discharge reports, discharge letters, surgery reports and preliminary doctor letters from the hospital, as PDF or simply photographed with your phone.' },
      { q: 'The report is several pages long. Is that ok?', a: 'Yes. Medyra summarizes the whole report and explains it section by section: diagnoses, course, medication and the recommended follow up.' },
      { q: 'Does this replace follow up care?', a: 'No. Medyra helps you understand the report and go into the conversation prepared. Medical follow up belongs in medical hands.' },
      { q: 'What happens to the report?', a: 'Encrypted processing, GDPR compliant hosting in Frankfurt, automatic deletion after 30 days (immediately on request).' },
    ],
    ctaTitle: 'Go into your follow up prepared',
    ctaSub: '3 documents per month free. GDPR compliant, encrypted, deleted automatically.',
    ctaButton: 'Explain my discharge report',
    ctaNote: 'Medyra does not replace medical advice. Always discuss your follow up care with your doctor.',
  },

  tr: {
    headerTitle: 'Hastane raporunu anlayın',
    headerCta: 'Rapor yükle',
    badge: 'Taburcu raporu · Ameliyat raporu · Hastane yazısı',
    h1a: 'Hastaneden çıktınız,',
    h1b: 'peki şimdi ne olacak?',
    sub: 'Taburcu raporu, hastaneden sonra işlerin nasıl devam edeceğini belirler. Medyra onu anlaşılır dile çevirir: ne oldu, hangi ilaçlar değişti ve şimdi ne yapmalısınız.',
    cta: 'Raporumu şimdi açıkla',
    mock: {
      labelIn: 'Raporda yazan', quote: QUOTE, labelOut: 'Medyra açıklıyor',
      lines: [
        'Şikayetlere neden olan safra taşları yüzünden safra keseniz alındı.',
        'Yara iyi iyileşiyor, iltihap belirtisi yok.',
        'Dikişler yaklaşık 10 gün sonra alınacak, ardından 2 hafta fiziksel olarak dinlenin.',
      ],
    },
    cardsLabel: 'Ne alırsınız',
    cardsTitle: 'Raporun tamamı, net açıklanmış',
    cards: [
      { icon: '🏥', title: 'Hastanede ne oldu', desc: 'Yatış nedeni, tanılar ve yapılan müdahaleler, paragraf paragraf anlaşılır dile çevrilir; panik ve tıp jargonu olmadan.' },
      { icon: '💊', title: 'Değişen ilaçlar', desc: 'Taburcu raporları çoğu zaman ilaçları değiştirir. Medyra neyin yeni olduğunu, neyin kesildiğini ve nelere dikkat edileceğini net gösterir.' },
      { icon: '📅', title: 'Şimdi ne yapmalısınız', desc: 'Kontrol randevuları ve talimatlar; aile hekiminize sorulacak sorularla birlikte sakin ve net bir liste halinde.' },
    ],
    jargon: {
      label: 'Örnekler', title: 'Hastane Almancası, çevrildi',
      pairs: [
        ['Z. n.', 'sonrası durum; geçirilmiş hastalık veya ameliyat'],
        ['Procedere', 'sonraki adımlar; taburcu sonrası yol haritanız'],
        ['kardiopulmonal stabil', 'kalp ve akciğerler normal çalışıyor'],
        ['reizlose Wundverhältnisse', 'yara iyi iyileşiyor, iltihap yok'],
        ['Rekompensation', 'vücut yeniden dengede'],
        ['AZ und EZ', 'genel durum ve beslenme durumu'],
      ],
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Neler yükleyebilirim?', a: 'Taburcu raporları ve mektupları, ameliyat raporları ve hastaneden gelen ön doktor mektupları; PDF olarak veya telefonla fotoğraflayarak.' },
      { q: 'Rapor birkaç sayfa. Sorun olur mu?', a: 'Hayır. Medyra raporun tamamını özetler ve bölüm bölüm açıklar: tanılar, seyir, ilaçlar ve önerilen takip.' },
      { q: 'Bu, aile hekimi kontrolünün yerine geçer mi?', a: 'Hayır. Medyra raporu anlamanıza ve görüşmeye hazır gitmenize yardımcı olur. Tıbbi takip doktorların işidir.' },
      { q: 'Rapora ne olur?', a: 'Şifreli işleme, Frankfurt’ta GDPR uyumlu barındırma, 30 gün sonra otomatik silme (istekle hemen).' },
    ],
    ctaTitle: 'Kontrole hazırlıklı gidin',
    ctaSub: 'Ayda 3 belge ücretsiz. GDPR uyumlu, şifreli, otomatik silinir.',
    ctaButton: 'Taburcu raporumu açıkla',
    ctaNote: 'Medyra tıbbi danışmanlığın yerini tutmaz. Takibinizi her zaman doktorunuzla görüşün.',
  },

  ar: {
    headerTitle: 'افهم تقرير المستشفى',
    headerCta: 'ارفع التقرير',
    badge: 'تقرير خروج · تقرير عملية · خطاب مستشفى',
    h1a: 'خرجت من المستشفى،',
    h1b: 'لكن ماذا الآن؟',
    sub: 'تقرير الخروج يحدد كيف تستمر الأمور بعد المستشفى. يترجمه Medyra إلى لغة واضحة: ما الذي حدث، وأي أدوية تغيرت، وما الذي يجب فعله الآن.',
    cta: 'اشرح تقريري الآن',
    mock: {
      labelIn: 'ما يقوله التقرير', quote: QUOTE, labelOut: 'Medyra يشرح',
      lines: [
        'أزيلت مرارتك بسبب حصوات سببت الأعراض.',
        'الجرح يلتئم جيداً ولا توجد علامات التهاب.',
        'تُزال الغرز بعد نحو 10 أيام، ثم راحة بدنية لمدة أسبوعين.',
      ],
    },
    cardsLabel: 'ما تحصل عليه',
    cardsTitle: 'التقرير كاملاً، مشروح بوضوح',
    cards: [
      { icon: '🏥', title: 'ما الذي حدث في المستشفى', desc: 'سبب الدخول والتشخيصات والإجراءات، مترجمة فقرة فقرة إلى لغة واضحة، دون قلق ودون مصطلحات معقدة.' },
      { icon: '💊', title: 'الأدوية المتغيرة', desc: 'تقارير الخروج تغيّر الأدوية غالباً. يوضح Medyra ما الجديد وما توقف وما الذي يجب الانتباه إليه.' },
      { icon: '📅', title: 'ما الذي يجب فعله الآن', desc: 'مواعيد المتابعة والفحوصات والتعليمات في قائمة هادئة وواضحة مع أسئلة لطبيب العائلة.' },
    ],
    jargon: {
      label: 'أمثلة', title: 'لغة المستشفى الألمانية، مترجمة',
      pairs: [
        ['Z. n.', 'حالة بعد؛ مرض أو عملية سابقة'],
        ['Procedere', 'الخطوات التالية؛ خارطة طريقك بعد الخروج'],
        ['kardiopulmonal stabil', 'القلب والرئتان يعملان بشكل طبيعي'],
        ['reizlose Wundverhältnisse', 'الجرح يلتئم جيداً، لا التهاب'],
        ['Rekompensation', 'الجسم عاد إلى توازنه'],
        ['AZ und EZ', 'الحالة العامة والحالة الغذائية'],
      ],
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما الذي يمكنني رفعه؟', a: 'تقارير وخطابات الخروج وتقارير العمليات والخطابات الأولية من المستشفى؛ كملف PDF أو بتصويرها بالهاتف.' },
      { q: 'التقرير من عدة صفحات. هل هذا ممكن؟', a: 'نعم. يلخص Medyra التقرير كاملاً ويشرحه قسماً قسماً: التشخيصات والمسار والأدوية والمتابعة الموصى بها.' },
      { q: 'هل يغني هذا عن متابعة الطبيب؟', a: 'لا. يساعدك Medyra على فهم التقرير والذهاب إلى الموعد مستعداً. المتابعة الطبية من اختصاص الأطباء.' },
      { q: 'ماذا يحدث للتقرير؟', a: 'معالجة مشفرة، واستضافة متوافقة مع GDPR في فرانكفورت، وحذف تلقائي بعد 30 يوماً (وفوراً عند الطلب).' },
    ],
    ctaTitle: 'اذهب إلى المتابعة مستعداً',
    ctaSub: '3 مستندات شهرياً مجاناً. متوافق مع GDPR، مشفر، يُحذف تلقائياً.',
    ctaButton: 'اشرح تقرير الخروج',
    ctaNote: 'لا يحل Medyra محل الاستشارة الطبية. ناقش متابعتك دائماً مع طبيبك.',
  },

  ru: {
    headerTitle: 'Понять больничную выписку',
    headerCta: 'Загрузить выписку',
    badge: 'Выписка · Операционный отчёт · Письмо из больницы',
    h1a: 'Из больницы выписали,',
    h1b: 'а что дальше?',
    sub: 'Выписка определяет, как всё пойдёт после больницы. Medyra переводит её на понятный язык: что произошло, какие лекарства изменились и что делать теперь.',
    cta: 'Объяснить мою выписку',
    mock: {
      labelIn: 'В выписке написано', quote: QUOTE, labelOut: 'Medyra объясняет',
      lines: [
        'Вам удалили желчный пузырь из-за камней, которые вызывали жалобы.',
        'Рана заживает хорошо, признаков воспаления нет.',
        'Швы снимут примерно через 10 дней, затем 2 недели физического покоя.',
      ],
    },
    cardsLabel: 'Что вы получаете',
    cardsTitle: 'Вся выписка, понятно объяснённая',
    cards: [
      { icon: '🏥', title: 'Что произошло в больнице', desc: 'Причина госпитализации, диагнозы и проведённые вмешательства, абзац за абзацем на простом языке, без паники и без жаргона.' },
      { icon: '💊', title: 'Изменённые лекарства', desc: 'Выписки часто меняют схему лечения. Medyra ясно показывает, что новое, что отменено и на что обратить внимание.' },
      { icon: '📅', title: 'Что делать теперь', desc: 'Контрольные визиты, обследования и указания из выписки в виде спокойного списка с вопросами для семейного врача.' },
    ],
    jargon: {
      label: 'Примеры', title: 'Больничный немецкий, переведён',
      pairs: [
        ['Z. n.', 'состояние после; перенесённая болезнь или операция'],
        ['Procedere', 'дальнейшие шаги; ваш план после выписки'],
        ['kardiopulmonal stabil', 'сердце и лёгкие работают нормально'],
        ['reizlose Wundverhältnisse', 'рана заживает хорошо, воспаления нет'],
        ['Rekompensation', 'организм снова в равновесии'],
        ['AZ und EZ', 'общее состояние и состояние питания'],
      ],
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Что можно загрузить?', a: 'Выписки, выписные письма, операционные отчёты и предварительные письма из больницы; как PDF или просто сфотографировав телефоном.' },
      { q: 'Выписка на несколько страниц. Это возможно?', a: 'Да. Medyra резюмирует весь документ и объясняет его по разделам: диагнозы, течение, лекарства и рекомендованное наблюдение.' },
      { q: 'Заменяет ли это визит к врачу?', a: 'Нет. Medyra помогает понять документ и прийти на приём подготовленным. Медицинское наблюдение остаётся за врачами.' },
      { q: 'Что происходит с выпиской?', a: 'Зашифрованная обработка, GDPR совместимый хостинг во Франкфурте, автоматическое удаление через 30 дней (по желанию сразу).' },
    ],
    ctaTitle: 'Приходите на приём подготовленным',
    ctaSub: '3 документа в месяц бесплатно. GDPR, шифрование, автоматическое удаление.',
    ctaButton: 'Объяснить мою выписку',
    ctaNote: 'Medyra не заменяет консультацию врача. Всегда обсуждайте наблюдение с вашим врачом.',
  },

  fr: {
    headerTitle: 'Comprendre le compte-rendu de sortie', headerCta: 'Télécharger le rapport',
    badge: 'Compte-rendu de sortie · Rapport opératoire · Lettre d’hôpital',
    h1a: 'Sorti de l’hôpital,', h1b: 'mais que faire maintenant ?',
    sub: 'Le compte-rendu de sortie détermine la suite après l’hôpital. Medyra le traduit en langage clair : ce qui s’est passé, quels médicaments ont changé et ce que vous devez faire maintenant.',
    cta: 'Expliquer mon rapport maintenant',
    mock: {
      labelIn: 'Le rapport indique', quote: QUOTE, labelOut: 'Medyra explique',
      lines: [
        'Votre vésicule biliaire a été retirée à cause de calculs biliaires qui causaient des symptômes.',
        'La plaie guérit bien, aucun signe d’inflammation.',
        'Les points seront retirés dans environ 10 jours, puis reposez-vous physiquement pendant 2 semaines.',
      ],
    },
    cardsLabel: 'Ce que vous obtenez', cardsTitle: 'Le rapport complet, clairement expliqué',
    cards: [
      { icon: '🏥', title: 'Ce qui s’est passé à l’hôpital', desc: 'Motif d’admission, diagnostics et interventions, traduits en langage clair paragraphe par paragraphe, sans panique ni jargon.' },
      { icon: '💊', title: 'Médicaments modifiés', desc: 'Les comptes-rendus de sortie changent souvent la médication. Medyra montre clairement ce qui est nouveau, ce qui s’arrête et ce à quoi faire attention.' },
      { icon: '📅', title: 'Ce que vous devez faire maintenant', desc: 'Rendez-vous de suivi, contrôles et instructions du rapport sous forme de liste claire et calme, avec des questions pour votre médecin traitant.' },
    ],
    jargon: {
      label: 'Exemples', title: 'Allemand hospitalier, traduit',
      pairs: [
        ['Z. n.', 'état après, une maladie ou opération antérieure'],
        ['Procedere', 'les prochaines étapes, votre feuille de route après la sortie'],
        ['kardiopulmonal stabil', 'le cœur et les poumons fonctionnent normalement'],
        ['reizlose Wundverhältnisse', 'la plaie guérit bien, pas d’inflammation'],
        ['Rekompensation', 'le corps retrouve son équilibre'],
        ['AZ und EZ', 'état général et état nutritionnel'],
      ],
    },
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'Que puis-je télécharger ?', a: 'Comptes-rendus de sortie, lettres de sortie, rapports opératoires et lettres provisoires du médecin de l’hôpital, en PDF ou simplement photographiés avec votre téléphone.' },
      { q: 'Le rapport fait plusieurs pages. Est-ce possible ?', a: 'Oui. Medyra résume l’ensemble du rapport et l’explique section par section : diagnostics, évolution, médication et suivi recommandé.' },
      { q: 'Cela remplace-t-il le suivi chez le médecin traitant ?', a: 'Non. Medyra vous aide à comprendre le rapport et à vous présenter préparé au rendez-vous. Le suivi médical reste entre les mains des médecins.' },
      { q: 'Que devient le rapport ?', a: 'Traitement chiffré, hébergement conforme au RGPD à Francfort, suppression automatique après 30 jours (immédiatement sur demande).' },
    ],
    ctaTitle: 'Présentez-vous préparé au suivi',
    ctaSub: '3 documents par mois gratuits. Conforme au RGPD, chiffré, supprimé automatiquement.',
    ctaButton: 'Expliquer mon compte-rendu de sortie',
    ctaNote: 'Medyra ne remplace pas un avis médical. Discutez toujours de votre suivi avec votre médecin.',
  },

  es: {
    headerTitle: 'Entender el informe de alta', headerCta: 'Subir informe',
    badge: 'Informe de alta · Informe quirúrgico · Carta del hospital',
    h1a: 'Salió del hospital,', h1b: '¿y ahora qué?',
    sub: 'El informe de alta decide cómo continúan las cosas después del hospital. Medyra lo traduce a un lenguaje claro: qué pasó, qué medicamentos cambiaron y qué debe hacer ahora.',
    cta: 'Explicar mi informe ahora',
    mock: {
      labelIn: 'El informe dice', quote: QUOTE, labelOut: 'Medyra explica',
      lines: [
        'Le extirparon la vesícula biliar debido a cálculos que causaban síntomas.',
        'La herida está sanando bien, sin signos de inflamación.',
        'Los puntos se retiran en unos 10 días, luego reposo físico durante 2 semanas.',
      ],
    },
    cardsLabel: 'Lo que obtiene', cardsTitle: 'Todo el informe, claramente explicado',
    cards: [
      { icon: '🏥', title: 'Qué pasó en el hospital', desc: 'Motivo de ingreso, diagnósticos y procedimientos, traducidos a lenguaje claro párrafo a párrafo, sin alarma ni jerga.' },
      { icon: '💊', title: 'Medicamentos modificados', desc: 'Los informes de alta suelen cambiar la medicación. Medyra muestra claramente qué es nuevo, qué se suspende y a qué prestar atención.' },
      { icon: '📅', title: 'Qué debe hacer ahora', desc: 'Citas de seguimiento, controles e instrucciones del informe en una lista clara y tranquila, con preguntas para su médico de cabecera.' },
    ],
    jargon: {
      label: 'Ejemplos', title: 'Alemán hospitalario, traducido',
      pairs: [
        ['Z. n.', 'estado después de, una enfermedad u operación previa'],
        ['Procedere', 'los próximos pasos, su hoja de ruta tras el alta'],
        ['kardiopulmonal stabil', 'el corazón y los pulmones funcionan con normalidad'],
        ['reizlose Wundverhältnisse', 'la herida cicatriza bien, sin inflamación'],
        ['Rekompensation', 'el cuerpo ha recuperado el equilibrio'],
        ['AZ und EZ', 'estado general y estado nutricional'],
      ],
    },
    faqTitle: 'Preguntas frecuentes',
    faq: [
      { q: '¿Qué puedo subir?', a: 'Informes de alta, cartas de alta, informes quirúrgicos y cartas médicas preliminares del hospital, en PDF o simplemente fotografiados con su teléfono.' },
      { q: 'El informe tiene varias páginas. ¿Es posible?', a: 'Sí. Medyra resume todo el informe y lo explica sección por sección: diagnósticos, evolución, medicación y el seguimiento recomendado.' },
      { q: '¿Esto sustituye el seguimiento con el médico de cabecera?', a: 'No. Medyra le ayuda a entender el informe e ir preparado a la consulta. El seguimiento médico queda en manos médicas.' },
      { q: '¿Qué pasa con el informe?', a: 'Procesamiento cifrado, alojamiento conforme al RGPD en Fráncfort, eliminación automática después de 30 días (inmediata si se solicita).' },
    ],
    ctaTitle: 'Vaya preparado a su seguimiento',
    ctaSub: '3 documentos al mes gratis. Conforme al RGPD, cifrado, eliminado automáticamente.',
    ctaButton: 'Explicar mi informe de alta',
    ctaNote: 'Medyra no sustituye el consejo médico. Comente siempre su seguimiento con su médico.',
  },

  it: {
    headerTitle: 'Capire il referto di dimissione', headerCta: 'Carica il referto',
    badge: 'Referto di dimissione · Referto operatorio · Lettera ospedaliera',
    h1a: 'Uscito dall’ospedale,', h1b: 'e adesso?',
    sub: 'Il referto di dimissione determina come procedono le cose dopo l’ospedale. Medyra lo traduce in linguaggio semplice: cosa è successo, quali farmaci sono cambiati e cosa fare ora.',
    cta: 'Spiega il mio referto ora',
    mock: {
      labelIn: 'Il referto dice', quote: QUOTE, labelOut: 'Medyra spiega',
      lines: [
        'La cistifellea è stata rimossa a causa di calcoli biliari che causavano sintomi.',
        'La ferita sta guarendo bene, nessun segno di infiammazione.',
        'I punti verranno rimossi tra circa 10 giorni, poi riposo fisico per 2 settimane.',
      ],
    },
    cardsLabel: 'Cosa ottieni', cardsTitle: 'L’intero referto, spiegato chiaramente',
    cards: [
      { icon: '🏥', title: 'Cosa è successo in ospedale', desc: 'Motivo del ricovero, diagnosi e procedure, tradotti in linguaggio semplice paragrafo per paragrafo, senza allarmismo e senza gergo tecnico.' },
      { icon: '💊', title: 'Farmaci modificati', desc: 'I referti di dimissione spesso cambiano la terapia. Medyra mostra chiaramente cosa è nuovo, cosa viene interrotto e a cosa prestare attenzione.' },
      { icon: '📅', title: 'Cosa devi fare ora', desc: 'Appuntamenti di controllo, visite e istruzioni del referto come lista chiara e tranquilla, con domande per il tuo medico di famiglia.' },
    ],
    jargon: {
      label: 'Esempi', title: 'Tedesco ospedaliero, tradotto',
      pairs: [
        ['Z. n.', 'stato dopo, una malattia o operazione precedente'],
        ['Procedere', 'i prossimi passi, il tuo percorso dopo la dimissione'],
        ['kardiopulmonal stabil', 'cuore e polmoni funzionano normalmente'],
        ['reizlose Wundverhältnisse', 'la ferita guarisce bene, nessuna infiammazione'],
        ['Rekompensation', 'il corpo è tornato in equilibrio'],
        ['AZ und EZ', 'stato generale e stato nutrizionale'],
      ],
    },
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'Cosa posso caricare?', a: 'Referti di dimissione, lettere di dimissione, referti operatori e lettere mediche preliminari dell’ospedale, come PDF o semplicemente fotografati con il telefono.' },
      { q: 'Il referto è lungo diverse pagine. Va bene?', a: 'Sì. Medyra riassume l’intero referto e lo spiega sezione per sezione: diagnosi, decorso, terapia e follow-up consigliato.' },
      { q: 'Questo sostituisce il controllo dal medico di famiglia?', a: 'No. Medyra ti aiuta a capire il referto e ad arrivare preparato al colloquio. Il follow-up medico resta compito dei medici.' },
      { q: 'Cosa succede al referto?', a: 'Elaborazione crittografata, hosting conforme al GDPR a Francoforte, eliminazione automatica dopo 30 giorni (subito su richiesta).' },
    ],
    ctaTitle: 'Vai preparato al tuo controllo',
    ctaSub: '3 documenti al mese gratis. Conforme al GDPR, crittografato, eliminato automaticamente.',
    ctaButton: 'Spiega il mio referto di dimissione',
    ctaNote: 'Medyra non sostituisce il consiglio medico. Discuti sempre il tuo follow-up con il tuo medico.',
  },

  pt: {
    headerTitle: 'Entender o relatório de alta', headerCta: 'Enviar relatório',
    badge: 'Relatório de alta · Relatório cirúrgico · Carta hospitalar',
    h1a: 'Saiu do hospital,', h1b: 'e agora?',
    sub: 'O relatório de alta decide como as coisas continuam após o hospital. A Medyra o traduz para linguagem clara: o que aconteceu, quais medicamentos mudaram e o que você deve fazer agora.',
    cta: 'Explicar meu relatório agora',
    mock: {
      labelIn: 'O relatório diz', quote: QUOTE, labelOut: 'Medyra explica',
      lines: [
        'Sua vesícula biliar foi removida devido a cálculos que causavam sintomas.',
        'A ferida está cicatrizando bem, sem sinais de inflamação.',
        'Os pontos serão retirados em cerca de 10 dias, depois repouso físico por 2 semanas.',
      ],
    },
    cardsLabel: 'O que você recebe', cardsTitle: 'O relatório completo, claramente explicado',
    cards: [
      { icon: '🏥', title: 'O que aconteceu no hospital', desc: 'Motivo da internação, diagnósticos e procedimentos, traduzidos para linguagem clara parágrafo por parágrafo, sem alarme e sem jargão.' },
      { icon: '💊', title: 'Medicamentos alterados', desc: 'Relatórios de alta costumam mudar a medicação. A Medyra mostra claramente o que é novo, o que é interrompido e o que observar.' },
      { icon: '📅', title: 'O que você precisa fazer agora', desc: 'Consultas de acompanhamento, exames e instruções do relatório como uma lista clara e calma, com perguntas para seu médico de família.' },
    ],
    jargon: {
      label: 'Exemplos', title: 'Alemão hospitalar, traduzido',
      pairs: [
        ['Z. n.', 'estado após, uma doença ou cirurgia anterior'],
        ['Procedere', 'os próximos passos, seu roteiro após a alta'],
        ['kardiopulmonal stabil', 'coração e pulmões funcionando normalmente'],
        ['reizlose Wundverhältnisse', 'a ferida está cicatrizando bem, sem inflamação'],
        ['Rekompensation', 'o corpo voltou ao equilíbrio'],
        ['AZ und EZ', 'estado geral e estado nutricional'],
      ],
    },
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'O que posso enviar?', a: 'Relatórios de alta, cartas de alta, relatórios cirúrgicos e cartas médicas preliminares do hospital, em PDF ou simplesmente fotografados com o telefone.' },
      { q: 'O relatório tem várias páginas. Tudo bem?', a: 'Sim. A Medyra resume todo o relatório e o explica seção por seção: diagnósticos, evolução, medicação e o acompanhamento recomendado.' },
      { q: 'Isso substitui o acompanhamento com o médico de família?', a: 'Não. A Medyra ajuda você a entender o relatório e chegar preparado à consulta. O acompanhamento médico continua nas mãos médicas.' },
      { q: 'O que acontece com o relatório?', a: 'Processamento criptografado, hospedagem em conformidade com o RGPD em Frankfurt, exclusão automática após 30 dias (imediatamente a pedido).' },
    ],
    ctaTitle: 'Vá preparado para seu acompanhamento',
    ctaSub: '3 documentos por mês grátis. Conforme o RGPD, criptografado, excluído automaticamente.',
    ctaButton: 'Explicar meu relatório de alta',
    ctaNote: 'A Medyra não substitui o aconselhamento médico. Sempre discuta seu acompanhamento com seu médico.',
  },

  nl: {
    headerTitle: 'Ontslagbrief begrijpen', headerCta: 'Rapport uploaden',
    badge: 'Ontslagbrief · OK-verslag · Ziekenhuisbrief',
    h1a: 'Uit het ziekenhuis,', h1b: 'maar wat nu?',
    sub: 'De ontslagbrief bepaalt hoe het verdergaat na het ziekenhuis. Medyra vertaalt hem naar duidelijke taal: wat er is gebeurd, welke medicatie is veranderd en wat u nu moet doen.',
    cta: 'Leg mijn rapport nu uit',
    mock: {
      labelIn: 'Het rapport zegt', quote: QUOTE, labelOut: 'Medyra legt uit',
      lines: [
        'Uw galblaas is verwijderd vanwege galstenen die klachten veroorzaakten.',
        'De wond geneest goed, geen tekenen van ontsteking.',
        'Hechtingen komen er over ongeveer 10 dagen uit, daarna 2 weken lichamelijk rustig aan doen.',
      ],
    },
    cardsLabel: 'Wat u krijgt', cardsTitle: 'Het hele rapport, duidelijk uitgelegd',
    cards: [
      { icon: '🏥', title: 'Wat er in het ziekenhuis is gebeurd', desc: 'Reden van opname, diagnoses en ingrepen, alinea voor alinea in duidelijke taal vertaald, zonder paniek en zonder jargon.' },
      { icon: '💊', title: 'Gewijzigde medicatie', desc: 'Ontslagbrieven veranderen vaak de medicatie. Medyra laat duidelijk zien wat nieuw is, wat stopt en waar u op moet letten.' },
      { icon: '📅', title: 'Wat u nu moet doen', desc: 'Vervolgafspraken, controles en instructies uit het rapport als een duidelijke, rustige lijst met vragen voor uw huisarts.' },
    ],
    jargon: {
      label: 'Voorbeelden', title: 'Ziekenhuisduits, vertaald',
      pairs: [
        ['Z. n.', 'toestand na, een eerdere ziekte of operatie'],
        ['Procedere', 'de volgende stappen, uw route na ontslag'],
        ['kardiopulmonal stabil', 'hart en longen werken normaal'],
        ['reizlose Wundverhältnisse', 'de wond geneest goed, geen ontsteking'],
        ['Rekompensation', 'het lichaam is weer in balans'],
        ['AZ und EZ', 'algemene toestand en voedingstoestand'],
      ],
    },
    faqTitle: 'Veelgestelde vragen',
    faq: [
      { q: 'Wat kan ik uploaden?', a: 'Ontslagbrieven, ontslagverklaringen, OK-verslagen en voorlopige doktersbrieven van het ziekenhuis, als PDF of gewoon gefotografeerd met uw telefoon.' },
      { q: 'Het rapport is meerdere pagina’s lang. Kan dat?', a: 'Ja. Medyra vat het hele rapport samen en legt het sectie voor sectie uit: diagnoses, verloop, medicatie en de aanbevolen nazorg.' },
      { q: 'Vervangt dit de nazorg bij de huisarts?', a: 'Nee. Medyra helpt u het rapport te begrijpen en voorbereid naar het gesprek te gaan. Medische nazorg blijft in handen van artsen.' },
      { q: 'Wat gebeurt er met het rapport?', a: 'Versleutelde verwerking, AVG-conforme hosting in Frankfurt, automatische verwijdering na 30 dagen (direct op verzoek).' },
    ],
    ctaTitle: 'Ga voorbereid naar uw nazorg',
    ctaSub: '3 documenten per maand gratis. AVG-conform, versleuteld, automatisch verwijderd.',
    ctaButton: 'Leg mijn ontslagbrief uit',
    ctaNote: 'Medyra vervangt geen medisch advies. Bespreek uw nazorg altijd met uw arts.',
  },

  pl: {
    headerTitle: 'Zrozumieć wypis szpitalny', headerCta: 'Prześlij raport',
    badge: 'Wypis szpitalny · Raport operacyjny · Pismo szpitalne',
    h1a: 'Wyszedłeś ze szpitala,', h1b: 'a co teraz?',
    sub: 'Wypis szpitalny decyduje o tym, co dzieje się dalej po szpitalu. Medyra tłumaczy go na prosty język: co się stało, jakie leki się zmieniły i co powinieneś teraz zrobić.',
    cta: 'Wyjaśnij mój raport teraz',
    mock: {
      labelIn: 'W raporcie napisano', quote: QUOTE, labelOut: 'Medyra wyjaśnia',
      lines: [
        'Usunięto ci pęcherzyk żółciowy z powodu kamieni żółciowych powodujących dolegliwości.',
        'Rana goi się dobrze, brak oznak stanu zapalnego.',
        'Szwy zostaną zdjęte za około 10 dni, potem 2 tygodnie oszczędnego trybu życia.',
      ],
    },
    cardsLabel: 'Co otrzymujesz', cardsTitle: 'Cały raport, jasno wyjaśniony',
    cards: [
      { icon: '🏥', title: 'Co wydarzyło się w szpitalu', desc: 'Powód przyjęcia, diagnozy i zabiegi, przetłumaczone na prosty język akapit po akapicie, bez paniki i bez żargonu.' },
      { icon: '💊', title: 'Zmienione leki', desc: 'Wypisy szpitalne często zmieniają leczenie. Medyra jasno pokazuje, co jest nowe, co zostało odstawione i na co zwrócić uwagę.' },
      { icon: '📅', title: 'Co musisz teraz zrobić', desc: 'Wizyty kontrolne, badania i zalecenia z raportu jako jasna, spokojna lista z pytaniami do lekarza rodzinnego.' },
    ],
    jargon: {
      label: 'Przykłady', title: 'Szpitalny niemiecki, przetłumaczony',
      pairs: [
        ['Z. n.', 'stan po, wcześniejsza choroba lub operacja'],
        ['Procedere', 'kolejne kroki, twój plan po wypisie'],
        ['kardiopulmonal stabil', 'serce i płuca pracują prawidłowo'],
        ['reizlose Wundverhältnisse', 'rana goi się dobrze, brak zapalenia'],
        ['Rekompensation', 'organizm wrócił do równowagi'],
        ['AZ und EZ', 'stan ogólny i stan odżywienia'],
      ],
    },
    faqTitle: 'Najczęstsze pytania',
    faq: [
      { q: 'Co mogę przesłać?', a: 'Wypisy szpitalne, listy wypisowe, raporty operacyjne i wstępne pisma lekarskie ze szpitala, jako PDF lub po prostu sfotografowane telefonem.' },
      { q: 'Raport ma kilka stron. Czy to problem?', a: 'Nie. Medyra podsumowuje cały raport i wyjaśnia go sekcja po sekcji: diagnozy, przebieg, leki i zalecaną kontrolę.' },
      { q: 'Czy to zastępuje kontrolę u lekarza rodzinnego?', a: 'Nie. Medyra pomaga zrozumieć raport i przygotować się do rozmowy. Opieka medyczna pozostaje w rękach lekarzy.' },
      { q: 'Co dzieje się z raportem?', a: 'Szyfrowane przetwarzanie, hosting zgodny z RODO we Frankfurcie, automatyczne usunięcie po 30 dniach (natychmiast na żądanie).' },
    ],
    ctaTitle: 'Idź przygotowany na swoją kontrolę',
    ctaSub: '3 dokumenty miesięcznie za darmo. Zgodność z RODO, szyfrowanie, automatyczne usuwanie.',
    ctaButton: 'Wyjaśnij mój wypis szpitalny',
    ctaNote: 'Medyra nie zastępuje porady lekarskiej. Zawsze omawiaj swoją kontrolę z lekarzem.',
  },

  zh: {
    headerTitle: '看懂出院报告', headerCta: '上传报告',
    badge: '出院报告 · 手术报告 · 医院信件',
    h1a: '出院了，', h1b: '但接下来该怎么办？',
    sub: '出院报告决定了出院后事情如何继续。Medyra将其翻译成通俗易懂的语言：发生了什么，哪些药物有变化，以及您现在应该做什么。',
    cta: '立即解释我的报告',
    mock: {
      labelIn: '报告中写道', quote: QUOTE, labelOut: 'Medyra 解释',
      lines: [
        '由于胆结石引起症状，您的胆囊已被切除。',
        '伤口愈合良好，没有炎症迹象。',
        '大约10天后拆线，之后需要2周的身体休养。',
      ],
    },
    cardsLabel: '您将获得', cardsTitle: '整份报告，清晰解释',
    cards: [
      { icon: '🏥', title: '医院里发生了什么', desc: '入院原因、诊断和实施的手术，逐段翻译成通俗语言，不引起恐慌，不使用行话。' },
      { icon: '💊', title: '药物变化', desc: '出院报告通常会改变用药方案。Medyra清楚地显示什么是新增的，什么被停用，以及需要注意什么。' },
      { icon: '📅', title: '您现在需要做什么', desc: '随访预约、复查和报告中的指示，以清晰、平静的清单形式呈现，并附上给家庭医生的问题。' },
    ],
    jargon: {
      label: '示例', title: '医院德语，已翻译',
      pairs: [
        ['Z. n.', '既往状态，先前的疾病或手术'],
        ['Procedere', '后续步骤，出院后的行动计划'],
        ['kardiopulmonal stabil', '心肺功能正常'],
        ['reizlose Wundverhältnisse', '伤口愈合良好，无炎症'],
        ['Rekompensation', '身体恢复平衡'],
        ['AZ und EZ', '一般状态和营养状态'],
      ],
    },
    faqTitle: '常见问题',
    faq: [
      { q: '我可以上传什么？', a: '出院报告、出院信、手术报告和医院的初步医生信件，可以是PDF或直接用手机拍照。' },
      { q: '报告有好几页，可以吗？', a: '可以。Medyra会总结整份报告，并分节解释：诊断、病程、用药和建议的随访。' },
      { q: '这能代替家庭医生的随访吗？', a: '不能。Medyra帮助您理解报告，并让您有准备地参加就诊。医疗随访仍由医生负责。' },
      { q: '报告会怎样处理？', a: '加密处理，符合GDPR标准，托管在法兰克福，30天后自动删除（应要求可立即删除）。' },
    ],
    ctaTitle: '做好准备参加随访',
    ctaSub: '每月3份文件免费。符合GDPR，加密处理，自动删除。',
    ctaButton: '解释我的出院报告',
    ctaNote: 'Medyra 不能替代医疗建议。请始终与您的医生讨论随访事宜。',
  },

  ja: {
    headerTitle: '退院報告書を理解する', headerCta: '報告書をアップロード',
    badge: '退院報告書・手術報告書・病院からの手紙',
    h1a: '退院しましたが、', h1b: '次に何をすればいいですか？',
    sub: '退院報告書は、退院後のことがどう進むかを決めます。Medyraはそれを分かりやすい言葉に翻訳します：何があったのか、どの薬が変わったのか、そして今何をすべきか。',
    cta: '今すぐ報告書を説明する',
    mock: {
      labelIn: '報告書にはこう書かれています', quote: QUOTE, labelOut: 'Medyraが説明します',
      lines: [
        '症状を引き起こしていた胆石のため、胆嚢が摘出されました。',
        '傷は順調に治癒しており、炎症の兆候はありません。',
        '約10日後に抜糸し、その後2週間は体を休めてください。',
      ],
    },
    cardsLabel: '得られるもの', cardsTitle: '報告書全体を分かりやすく説明',
    cards: [
      { icon: '🏥', title: '病院で何が起こったか', desc: '入院理由、診断、実施された処置を、パニックや専門用語を使わず段落ごとに分かりやすく翻訳します。' },
      { icon: '💊', title: '変更された薬', desc: '退院報告書はしばしば薬を変更します。Medyraは何が新しいか、何が中止されたか、何に注意すべきかを明確に示します。' },
      { icon: '📅', title: '今すべきこと', desc: 'フォローアップの予約、検査、報告書の指示を、かかりつけ医への質問付きの明確で落ち着いたリストとして提供します。' },
    ],
    jargon: {
      label: '例', title: '病院のドイツ語、翻訳済み',
      pairs: [
        ['Z. n.', '既往、以前の病気や手術の状態'],
        ['Procedere', '次のステップ、退院後の行動計画'],
        ['kardiopulmonal stabil', '心臓と肺が正常に機能している'],
        ['reizlose Wundverhältnisse', '傷は順調に治癒しており、炎症なし'],
        ['Rekompensation', '体が再びバランスを取り戻した'],
        ['AZ und EZ', '全身状態と栄養状態'],
      ],
    },
    faqTitle: 'よくある質問',
    faq: [
      { q: '何をアップロードできますか？', a: '退院報告書、退院時の手紙、手術報告書、病院からの暫定的な医師の手紙を、PDFまたは携帯電話で撮影した写真としてアップロードできます。' },
      { q: '報告書が数ページあります。大丈夫ですか？', a: 'はい。Medyraは報告書全体を要約し、セクションごとに説明します：診断、経過、薬物療法、推奨されるフォローアップ。' },
      { q: 'これはかかりつけ医のフォローアップの代わりになりますか？', a: 'いいえ。Medyraは報告書を理解し、準備をして診察に臨む手助けをします。医療的なフォローアップは医師の役割です。' },
      { q: '報告書はどうなりますか？', a: '暗号化処理、GDPRに準拠したフランクフルトでのホスティング、30日後の自動削除（希望すれば即時）。' },
    ],
    ctaTitle: '準備をしてフォローアップに臨みましょう',
    ctaSub: '月3件の文書が無料。GDPR準拠、暗号化、自動削除。',
    ctaButton: '退院報告書を説明する',
    ctaNote: 'Medyraは医療アドバイスの代わりにはなりません。フォローアップについては必ず医師と話し合ってください。',
  },

  ko: {
    headerTitle: '퇴원 보고서 이해하기', headerCta: '보고서 업로드',
    badge: '퇴원 보고서 · 수술 보고서 · 병원 편지',
    h1a: '퇴원했는데,', h1b: '이제 어떻게 해야 하나요?',
    sub: '퇴원 보고서는 병원 이후의 진행 방향을 결정합니다. Medyra는 이를 쉬운 언어로 번역합니다: 무슨 일이 있었는지, 어떤 약이 바뀌었는지, 지금 무엇을 해야 하는지.',
    cta: '지금 내 보고서 설명받기',
    mock: {
      labelIn: '보고서 내용', quote: QUOTE, labelOut: 'Medyra 설명',
      lines: [
        '증상을 일으키던 담석 때문에 담낭이 제거되었습니다.',
        '상처가 잘 아물고 있으며 염증 징후가 없습니다.',
        '약 10일 후 실밥을 제거하고, 이후 2주간 신체 활동을 자제해야 합니다.',
      ],
    },
    cardsLabel: '받게 되는 것', cardsTitle: '전체 보고서를 명확하게 설명',
    cards: [
      { icon: '🏥', title: '병원에서 있었던 일', desc: '입원 사유, 진단 및 시행된 처치를 당황스럽지 않고 전문 용어 없이 문단별로 쉬운 언어로 번역합니다.' },
      { icon: '💊', title: '변경된 약물', desc: '퇴원 보고서는 종종 약물을 변경합니다. Medyra는 무엇이 새로운지, 무엇이 중단되는지, 무엇을 주의해야 하는지 명확하게 보여줍니다.' },
      { icon: '📅', title: '지금 해야 할 일', desc: '추적 관찰 예약, 검사 및 보고서의 지침을 가정의에게 물어볼 질문과 함께 명확하고 차분한 목록으로 제공합니다.' },
    ],
    jargon: {
      label: '예시', title: '병원 독일어, 번역됨',
      pairs: [
        ['Z. n.', '이전 상태, 이전 질병 또는 수술'],
        ['Procedere', '다음 단계, 퇴원 후 계획'],
        ['kardiopulmonal stabil', '심장과 폐가 정상적으로 기능함'],
        ['reizlose Wundverhältnisse', '상처가 잘 아물고 있으며 염증 없음'],
        ['Rekompensation', '신체가 다시 균형을 회복함'],
        ['AZ und EZ', '전반적 상태와 영양 상태'],
      ],
    },
    faqTitle: '자주 묻는 질문',
    faq: [
      { q: '무엇을 업로드할 수 있나요?', a: '퇴원 보고서, 퇴원 편지, 수술 보고서 및 병원의 임시 의사 편지를 PDF 또는 휴대폰으로 촬영한 사진으로 업로드할 수 있습니다.' },
      { q: '보고서가 여러 페이지입니다. 괜찮나요?', a: '네. Medyra는 전체 보고서를 요약하고 진단, 경과, 약물 치료 및 권장 후속 조치를 섹션별로 설명합니다.' },
      { q: '이것이 가정의의 후속 진료를 대신하나요?', a: '아니요. Medyra는 보고서를 이해하고 준비된 상태로 진료에 임하도록 도와줍니다. 의료 후속 조치는 의사의 몫입니다.' },
      { q: '보고서는 어떻게 되나요?', a: '암호화된 처리, GDPR을 준수하는 프랑크푸르트 호스팅, 30일 후 자동 삭제(요청 시 즉시 삭제).' },
    ],
    ctaTitle: '준비된 상태로 후속 진료에 임하세요',
    ctaSub: '월 3건 문서 무료. GDPR 준수, 암호화, 자동 삭제.',
    ctaButton: '퇴원 보고서 설명받기',
    ctaNote: 'Medyra는 의료 상담을 대체하지 않습니다. 후속 조치는 항상 의사와 상의하세요.',
  },

  hi: {
    headerTitle: 'डिस्चार्ज रिपोर्ट समझें', headerCta: 'रिपोर्ट अपलोड करें',
    badge: 'डिस्चार्ज रिपोर्ट · ऑपरेशन रिपोर्ट · अस्पताल पत्र',
    h1a: 'अस्पताल से बाहर आ गए,', h1b: 'लेकिन अब क्या?',
    sub: 'डिस्चार्ज रिपोर्ट तय करती है कि अस्पताल के बाद चीज़ें कैसे आगे बढ़ती हैं। Medyra इसे सरल भाषा में अनुवाद करता है: क्या हुआ, कौन सी दवाएं बदलीं और अब आपको क्या करना चाहिए।',
    cta: 'अभी मेरी रिपोर्ट समझाएं',
    mock: {
      labelIn: 'रिपोर्ट में लिखा है', quote: QUOTE, labelOut: 'Medyra समझाता है',
      lines: [
        'लक्षण पैदा करने वाली पित्त की पथरी के कारण आपकी पित्ताशय निकाल दी गई।',
        'घाव अच्छी तरह भर रहा है, सूजन का कोई संकेत नहीं है।',
        'लगभग 10 दिनों में टांके हटाए जाएंगे, फिर 2 सप्ताह शारीरिक आराम करें।',
      ],
    },
    cardsLabel: 'आपको क्या मिलता है', cardsTitle: 'पूरी रिपोर्ट, स्पष्ट रूप से समझाई गई',
    cards: [
      { icon: '🏥', title: 'अस्पताल में क्या हुआ', desc: 'भर्ती होने का कारण, निदान और की गई प्रक्रियाएं, बिना घबराहट और बिना तकनीकी शब्दों के, पैराग्राफ दर पैराग्राफ सरल भाषा में समझाई गई।' },
      { icon: '💊', title: 'बदली गई दवाएं', desc: 'डिस्चार्ज रिपोर्ट अक्सर दवाओं में बदलाव करती है। Medyra स्पष्ट रूप से दिखाता है कि क्या नया है, क्या बंद हो गया है और किस पर ध्यान देना चाहिए।' },
      { icon: '📅', title: 'अब आपको क्या करना है', desc: 'फॉलो-अप अपॉइंटमेंट, जांच और रिपोर्ट के निर्देश, आपके फैमिली डॉक्टर के लिए सवालों के साथ एक स्पष्ट, शांत सूची के रूप में।' },
    ],
    jargon: {
      label: 'उदाहरण', title: 'अस्पताल की जर्मन भाषा, अनुवादित',
      pairs: [
        ['Z. n.', 'बाद की स्थिति, पहले की बीमारी या ऑपरेशन'],
        ['Procedere', 'अगले कदम, डिस्चार्ज के बाद आपकी योजना'],
        ['kardiopulmonal stabil', 'दिल और फेफड़े सामान्य रूप से काम कर रहे हैं'],
        ['reizlose Wundverhältnisse', 'घाव अच्छी तरह भर रहा है, कोई सूजन नहीं'],
        ['Rekompensation', 'शरीर फिर से संतुलन में है'],
        ['AZ und EZ', 'सामान्य स्थिति और पोषण स्थिति'],
      ],
    },
    faqTitle: 'सामान्य प्रश्न',
    faq: [
      { q: 'मैं क्या अपलोड कर सकता हूं?', a: 'डिस्चार्ज रिपोर्ट, डिस्चार्ज पत्र, ऑपरेशन रिपोर्ट और अस्पताल से प्रारंभिक डॉक्टर पत्र, PDF के रूप में या बस फोन से फोटो खींचकर।' },
      { q: 'रिपोर्ट कई पन्नों की है। क्या यह ठीक है?', a: 'हां। Medyra पूरी रिपोर्ट का सारांश देता है और इसे खंड दर खंड समझाता है: निदान, प्रगति, दवाएं और अनुशंसित फॉलो-अप।' },
      { q: 'क्या यह फैमिली डॉक्टर के फॉलो-अप की जगह लेता है?', a: 'नहीं। Medyra आपको रिपोर्ट समझने और तैयार होकर बातचीत में जाने में मदद करता है। चिकित्सा फॉलो-अप डॉक्टरों के हाथ में रहता है।' },
      { q: 'रिपोर्ट का क्या होता है?', a: 'एन्क्रिप्टेड प्रोसेसिंग, GDPR के अनुरूप फ्रैंकफर्ट में होस्टिंग, 30 दिनों के बाद स्वचालित रूप से हटाना (अनुरोध पर तुरंत)।' },
    ],
    ctaTitle: 'अपने फॉलो-अप के लिए तैयार होकर जाएं',
    ctaSub: 'हर महीने 3 दस्तावेज़ मुफ़्त। GDPR अनुरूप, एन्क्रिप्टेड, स्वचालित रूप से हटाया गया।',
    ctaButton: 'मेरी डिस्चार्ज रिपोर्ट समझाएं',
    ctaNote: 'Medyra चिकित्सा सलाह का विकल्प नहीं है। हमेशा अपने फॉलो-अप पर अपने डॉक्टर से चर्चा करें।',
  },

  bn: {
    headerTitle: 'ডিসচার্জ রিপোর্ট বুঝুন', headerCta: 'রিপোর্ট আপলোড করুন',
    badge: 'ডিসচার্জ রিপোর্ট · অপারেশন রিপোর্ট · হাসপাতালের চিঠি',
    h1a: 'হাসপাতাল থেকে বের হয়েছেন,', h1b: 'কিন্তু এখন কী করবেন?',
    sub: 'ডিসচার্জ রিপোর্ট নির্ধারণ করে হাসপাতালের পরে কীভাবে এগিয়ে যাবেন। Medyra এটি সহজ ভাষায় অনুবাদ করে: কী ঘটেছে, কোন ওষুধ পরিবর্তন হয়েছে এবং এখন আপনার কী করা উচিত।',
    cta: 'এখনই আমার রিপোর্ট ব্যাখ্যা করুন',
    mock: {
      labelIn: 'রিপোর্টে লেখা আছে', quote: QUOTE, labelOut: 'Medyra ব্যাখ্যা করে',
      lines: [
        'উপসর্গ সৃষ্টিকারী পিত্তথলির পাথরের কারণে আপনার পিত্তথলি অপসারণ করা হয়েছে।',
        'ক্ষত ভালোভাবে সেরে উঠছে, প্রদাহের কোনো লক্ষণ নেই।',
        'প্রায় ১০ দিন পর সেলাই খোলা হবে, তারপর ২ সপ্তাহ শারীরিক বিশ্রাম নিন।',
      ],
    },
    cardsLabel: 'আপনি যা পাবেন', cardsTitle: 'সম্পূর্ণ রিপোর্ট, স্পষ্টভাবে ব্যাখ্যা করা',
    cards: [
      { icon: '🏥', title: 'হাসপাতালে কী ঘটেছিল', desc: 'ভর্তির কারণ, রোগ নির্ণয় ও সম্পাদিত পদ্ধতি, আতঙ্ক বা প্রযুক্তিগত পরিভাষা ছাড়াই অনুচ্ছেদ অনুসারে সহজ ভাষায় ব্যাখ্যা করা।' },
      { icon: '💊', title: 'পরিবর্তিত ওষুধ', desc: 'ডিসচার্জ রিপোর্ট প্রায়ই ওষুধ পরিবর্তন করে। Medyra স্পষ্টভাবে দেখায় কী নতুন, কী বন্ধ হয়েছে এবং কী লক্ষ্য রাখা উচিত।' },
      { icon: '📅', title: 'এখন আপনার যা করা উচিত', desc: 'ফলো-আপ অ্যাপয়েন্টমেন্ট, পরীক্ষা এবং রিপোর্টের নির্দেশনা, আপনার পারিবারিক ডাক্তারের জন্য প্রশ্নসহ একটি স্পষ্ট, শান্ত তালিকা হিসেবে।' },
    ],
    jargon: {
      label: 'উদাহরণ', title: 'হাসপাতালের জার্মান, অনূদিত',
      pairs: [
        ['Z. n.', 'পরবর্তী অবস্থা, পূর্ববর্তী রোগ বা অপারেশন'],
        ['Procedere', 'পরবর্তী পদক্ষেপ, ডিসচার্জের পরে আপনার পরিকল্পনা'],
        ['kardiopulmonal stabil', 'হৃদয় ও ফুসফুস স্বাভাবিকভাবে কাজ করছে'],
        ['reizlose Wundverhältnisse', 'ক্ষত ভালোভাবে সেরে উঠছে, প্রদাহ নেই'],
        ['Rekompensation', 'শরীর আবার ভারসাম্যে ফিরে এসেছে'],
        ['AZ und EZ', 'সাধারণ অবস্থা এবং পুষ্টির অবস্থা'],
      ],
    },
    faqTitle: 'সাধারণ প্রশ্ন',
    faq: [
      { q: 'আমি কী আপলোড করতে পারি?', a: 'ডিসচার্জ রিপোর্ট, ডিসচার্জ চিঠি, অপারেশন রিপোর্ট এবং হাসপাতালের প্রাথমিক ডাক্তার চিঠি, PDF হিসেবে বা ফোনে ছবি তুলে।' },
      { q: 'রিপোর্টটি বেশ কয়েক পাতার। এটা কি ঠিক আছে?', a: 'হ্যাঁ। Medyra পুরো রিপোর্টের সারসংক্ষেপ করে এবং এটি বিভাগ অনুসারে ব্যাখ্যা করে: রোগ নির্ণয়, অগ্রগতি, ওষুধ এবং প্রস্তাবিত ফলো-আপ।' },
      { q: 'এটি কি পারিবারিক ডাক্তারের ফলো-আপের বিকল্প?', a: 'না। Medyra আপনাকে রিপোর্ট বুঝতে এবং প্রস্তুত হয়ে আলোচনায় যেতে সাহায্য করে। চিকিৎসা ফলো-আপ ডাক্তারদের হাতেই থাকে।' },
      { q: 'রিপোর্টের কী হয়?', a: 'এনক্রিপ্ট করা প্রক্রিয়াকরণ, GDPR সম্মত ফ্রাঙ্কফুর্ট হোস্টিং, ৩০ দিন পর স্বয়ংক্রিয় মুছে ফেলা (অনুরোধে তাৎক্ষণিক)।' },
    ],
    ctaTitle: 'আপনার ফলো-আপের জন্য প্রস্তুত হয়ে যান',
    ctaSub: 'মাসে ৩টি নথি বিনামূল্যে। GDPR সম্মত, এনক্রিপ্টেড, স্বয়ংক্রিয়ভাবে মুছে ফেলা।',
    ctaButton: 'আমার ডিসচার্জ রিপোর্ট ব্যাখ্যা করুন',
    ctaNote: 'Medyra চিকিৎসা পরামর্শের বিকল্প নয়। সবসময় আপনার ফলো-আপ নিয়ে আপনার ডাক্তারের সাথে আলোচনা করুন।',
  },

  ur: {
    headerTitle: 'ڈسچارج رپورٹ سمجھیں', headerCta: 'رپورٹ اپ لوڈ کریں',
    badge: 'ڈسچارج رپورٹ · آپریشن رپورٹ · ہسپتال کا خط',
    h1a: 'ہسپتال سے نکل آئے،', h1b: 'لیکن اب کیا؟',
    sub: 'ڈسچارج رپورٹ طے کرتی ہے کہ ہسپتال کے بعد معاملات کیسے آگے بڑھیں گے۔ Medyra اسے آسان زبان میں ترجمہ کرتا ہے: کیا ہوا، کون سی دوائیں بدلی گئیں اور اب آپ کو کیا کرنا چاہیے۔',
    cta: 'ابھی میری رپورٹ کی وضاحت کریں',
    mock: {
      labelIn: 'رپورٹ میں لکھا ہے', quote: QUOTE, labelOut: 'Medyra وضاحت کرتا ہے',
      lines: [
        'علامات پیدا کرنے والی پتھری کی وجہ سے آپ کی پتہ نکال دی گئی ہے۔',
        'زخم اچھی طرح بھر رہا ہے، سوزش کی کوئی علامت نہیں ہے۔',
        'تقریباً 10 دن بعد ٹانکے ہٹا دیے جائیں گے، پھر 2 ہفتے جسمانی آرام کریں۔',
      ],
    },
    cardsLabel: 'آپ کو کیا ملتا ہے', cardsTitle: 'مکمل رپورٹ، واضح طور پر بیان کی گئی',
    cards: [
      { icon: '🏥', title: 'ہسپتال میں کیا ہوا', desc: 'داخلے کی وجہ، تشخیص اور کی گئی طریقہ کار، بغیر گھبراہٹ اور تکنیکی اصطلاحات کے، پیراگراف بہ پیراگراف آسان زبان میں بیان کی گئی۔' },
      { icon: '💊', title: 'تبدیل شدہ دوائیں', desc: 'ڈسچارج رپورٹس اکثر دوائیں تبدیل کرتی ہیں۔ Medyra واضح طور پر دکھاتا ہے کہ کیا نیا ہے، کیا بند ہوا ہے اور کس پر توجہ دینی چاہیے۔' },
      { icon: '📅', title: 'اب آپ کو کیا کرنا ہے', desc: 'فالو اپ اپائنٹمنٹس، معائنے اور رپورٹ کی ہدایات، آپ کے فیملی ڈاکٹر کے لیے سوالات کے ساتھ ایک واضح، پرسکون فہرست کی صورت میں۔' },
    ],
    jargon: {
      label: 'مثالیں', title: 'ہسپتال کی جرمن، ترجمہ شدہ',
      pairs: [
        ['Z. n.', 'بعد کی حالت، پہلے کی بیماری یا آپریشن'],
        ['Procedere', 'اگلے اقدامات، ڈسچارج کے بعد آپ کا منصوبہ'],
        ['kardiopulmonal stabil', 'دل اور پھیپھڑے نارمل طریقے سے کام کر رہے ہیں'],
        ['reizlose Wundverhältnisse', 'زخم اچھی طرح بھر رہا ہے، کوئی سوزش نہیں'],
        ['Rekompensation', 'جسم دوبارہ توازن میں آ گیا ہے'],
        ['AZ und EZ', 'عمومی حالت اور غذائی حالت'],
      ],
    },
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faq: [
      { q: 'میں کیا اپ لوڈ کر سکتا ہوں؟', a: 'ڈسچارج رپورٹس، ڈسچارج خطوط، آپریشن رپورٹس اور ہسپتال سے ابتدائی ڈاکٹر خطوط، PDF کی صورت میں یا محض فون سے تصویر کھینچ کر۔' },
      { q: 'رپورٹ کئی صفحات پر مشتمل ہے۔ کیا یہ ٹھیک ہے؟', a: 'جی ہاں۔ Medyra پوری رپورٹ کا خلاصہ کرتا ہے اور اسے حصہ بہ حصہ بیان کرتا ہے: تشخیص، پیش رفت، دوائیں اور تجویز کردہ فالو اپ۔' },
      { q: 'کیا یہ فیملی ڈاکٹر کے فالو اپ کا متبادل ہے؟', a: 'نہیں۔ Medyra آپ کو رپورٹ سمجھنے اور تیار ہو کر بات چیت میں جانے میں مدد کرتا ہے۔ طبی فالو اپ ڈاکٹروں کے ہاتھ میں رہتا ہے۔' },
      { q: 'رپورٹ کا کیا ہوتا ہے؟', a: 'خفیہ کاری کے ساتھ پروسیسنگ، GDPR کے مطابق فرینکفرٹ میں ہوسٹنگ، 30 دن بعد خودکار حذف (درخواست پر فوری)۔' },
    ],
    ctaTitle: 'اپنے فالو اپ کے لیے تیار ہو کر جائیں',
    ctaSub: 'ماہانہ 3 دستاویزات مفت۔ GDPR کے مطابق، خفیہ کاری، خودکار حذف۔',
    ctaButton: 'میری ڈسچارج رپورٹ کی وضاحت کریں',
    ctaNote: 'Medyra طبی مشورے کا متبادل نہیں ہے۔ ہمیشہ اپنے فالو اپ پر اپنے ڈاکٹر سے بات کریں۔',
  },
}
