// Localized content for /krankenkasse. German is the SEO base; unlisted
// languages fall back to English. German letter quotes stay German.
const QUOTE = '"Ihrem Antrag auf Kostenübernahme kann nach § 33 SGB V nicht in vollem Umfang entsprochen werden. Gegen diesen Bescheid können Sie innerhalb eines Monats Widerspruch einlegen."'

export const CONTENT = {
  de: {
    headerTitle: 'Krankenkasse verstehen',
    headerCta: 'Brief hochladen',
    badge: 'Bescheid · Ablehnung · Zuzahlung',
    h1a: 'Kassenbriefe ohne',
    h1b: 'Amtsdeutsch',
    sub: 'Briefe der Krankenkasse sind Bürokratie in Reinform. Medyra sagt Ihnen in klarer Sprache, was drinsteht, was es kostet und welche Frist Sie nicht verpassen dürfen. In unter 60 Sekunden.',
    cta: 'Kassenbrief jetzt hochladen',
    mock: {
      labelIn: 'Im Brief steht', quote: QUOTE, labelOut: 'Medyra erklärt',
      lines: [
        'Die Kasse übernimmt die Kosten nur teilweise, nicht komplett.',
        'Sie haben genau 1 Monat Zeit, um Widerspruch einzulegen.',
        'Fragen Sie nach der genauen Begründung, das stärkt Ihren Widerspruch.',
      ],
    },
    cardsLabel: 'Was Sie bekommen',
    cardsTitle: 'Jeder Bescheid, klar erklärt',
    cards: [
      { icon: '📬', title: 'Was der Brief sagt', desc: 'Bewilligung, Ablehnung, Beitragsbescheid oder Erstattungsanfrage: Medyra erkennt die Briefart und fasst den Inhalt in zwei Sätzen zusammen.' },
      { icon: '💶', title: 'Was es Sie kostet', desc: 'Zuzahlungen, Eigenanteile, Erstattungsbeträge und Beitragsänderungen werden klar aufgeschlüsselt, mit allen Beträgen aus dem Brief.' },
      { icon: '⏰', title: 'Fristen und nächste Schritte', desc: 'Widerspruchsfristen, einzureichende Unterlagen und Termine als klare Liste, damit nichts verpasst wird.' },
    ],
    jargon: {
      label: 'Beispiele', title: 'Amtsdeutsch, übersetzt',
      pairs: [
        ['Bescheid', 'die offizielle Entscheidung der Kasse'],
        ['Zuzahlung', 'der Anteil, den Sie selbst bezahlen'],
        ['Widerspruch', 'Ihr Recht, die Entscheidung anzufechten'],
        ['Bewilligung', 'die Kasse übernimmt die Kosten'],
        ['MD-Gutachten', 'eine Prüfung durch den Medizinischen Dienst'],
        ['Satzungsleistung', 'ein Extra, das nur Ihre Kasse anbietet'],
      ],
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Welche Briefe kann ich hochladen?', a: 'Bescheide, Ablehnungen, Zuzahlungs- und Beitragsbriefe, Schreiben zu Hilfsmitteln, Reha oder Krankengeld, von jeder gesetzlichen oder privaten Krankenversicherung.' },
      { q: 'Hilft Medyra bei einer Ablehnung?', a: 'Medyra erklärt, was abgelehnt wurde, warum und welche Frist für einen Widerspruch gilt. Dazu bekommen Sie passende Fragen für Ihre Kasse. Rechtsberatung ersetzt das nicht.' },
      { q: 'Versteht Medyra auch private Krankenversicherungen?', a: 'Ja. Auch PKV-Briefe, Beihilfe-Bescheide und Rechnungserstattungen werden erkannt und verständlich erklärt.' },
      { q: 'Sind meine Daten sicher?', a: 'Ja. Verschlüsselte Verarbeitung, DSGVO-konformes Hosting in Frankfurt, automatische Löschung nach 30 Tagen (auf Wunsch sofort).' },
    ],
    ctaTitle: 'Verpassen Sie keine Frist mehr',
    ctaSub: '3 Dokumente pro Monat kostenlos. DSGVO-konform, verschlüsselt, automatisch gelöscht.',
    ctaButton: 'Kassenbrief erklären lassen',
    ctaNote: 'Medyra ersetzt keine Rechts- oder Sozialberatung.',
  },

  en: {
    headerTitle: 'Understand insurance letters',
    headerCta: 'Upload letter',
    badge: 'Decision · Rejection · Copayment',
    h1a: 'Insurance letters without',
    h1b: 'the bureaucracy German',
    sub: 'Letters from German health insurers are bureaucracy in its purest form. Medyra tells you in plain language what the letter says, what it costs you and which deadline you must not miss. In under 60 seconds.',
    cta: 'Upload insurance letter now',
    mock: {
      labelIn: 'The letter says', quote: QUOTE, labelOut: 'Medyra explains',
      lines: [
        'The insurer covers the costs only partially, not in full.',
        'You have exactly 1 month to file an objection (Widerspruch).',
        'Ask for the exact reasoning, it strengthens your objection.',
      ],
    },
    cardsLabel: 'What you get',
    cardsTitle: 'Every decision letter, clearly explained',
    cards: [
      { icon: '📬', title: 'What the letter says', desc: 'Approval, rejection, contribution notice or reimbursement request: Medyra recognizes the letter type and summarizes it in two sentences.' },
      { icon: '💶', title: 'What it costs you', desc: 'Copayments, own contributions, reimbursements and contribution changes broken down clearly, with all amounts from the letter.' },
      { icon: '⏰', title: 'Deadlines and next steps', desc: 'Objection deadlines, documents to submit and dates as a clear list so nothing gets missed.' },
    ],
    jargon: {
      label: 'Examples', title: 'Bureaucracy German, translated',
      pairs: [
        ['Bescheid', 'the official decision of the insurer'],
        ['Zuzahlung', 'the share you pay yourself'],
        ['Widerspruch', 'your right to contest the decision'],
        ['Bewilligung', 'the insurer covers the costs'],
        ['MD-Gutachten', 'a review by the medical service'],
        ['Satzungsleistung', 'an extra only your insurer offers'],
      ],
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'Which letters can I upload?', a: 'Decisions, rejections, copayment and contribution letters, letters about medical aids, rehab or sick pay, from any statutory or private health insurance.' },
      { q: 'Does Medyra help with a rejection?', a: 'Medyra explains what was rejected, why, and which objection deadline applies. You also get fitting questions for your insurer. It does not replace legal advice.' },
      { q: 'Does Medyra understand private insurance too?', a: 'Yes. PKV letters, Beihilfe decisions and invoice reimbursements are recognized and explained clearly.' },
      { q: 'Is my data safe?', a: 'Yes. Encrypted processing, GDPR compliant hosting in Frankfurt, automatic deletion after 30 days (immediately on request).' },
    ],
    ctaTitle: 'Never miss a deadline again',
    ctaSub: '3 documents per month free. GDPR compliant, encrypted, deleted automatically.',
    ctaButton: 'Explain my insurance letter',
    ctaNote: 'Medyra does not replace legal or social counseling.',
  },

  tr: {
    headerTitle: 'Sigorta yazısını anlayın',
    headerCta: 'Yazıyı yükle',
    badge: 'Karar · Ret · Katkı payı',
    h1a: 'Sigorta yazıları,',
    h1b: 'bürokrasi Almancası olmadan',
    sub: 'Alman sağlık sigortası yazıları bürokrasinin ta kendisidir. Medyra size anlaşılır dille ne yazdığını, size ne kadara mal olacağını ve hangi süreyi kaçırmamanız gerektiğini söyler. 60 saniyeden kısa sürede.',
    cta: 'Sigorta yazısını şimdi yükle',
    mock: {
      labelIn: 'Yazıda yazan', quote: QUOTE, labelOut: 'Medyra açıklıyor',
      lines: [
        'Sigorta masrafları tamamen değil, yalnızca kısmen karşılıyor.',
        'İtiraz (Widerspruch) için tam 1 ayınız var.',
        'Gerekçeyi ayrıntılı sorun; bu itirazınızı güçlendirir.',
      ],
    },
    cardsLabel: 'Ne alırsınız',
    cardsTitle: 'Her karar yazısı, net açıklanmış',
    cards: [
      { icon: '📬', title: 'Yazı ne diyor', desc: 'Onay, ret, prim bildirimi veya geri ödeme talebi: Medyra yazı türünü tanır ve içeriği iki cümlede özetler.' },
      { icon: '💶', title: 'Size maliyeti ne', desc: 'Katkı payları, kendi payınız, geri ödemeler ve prim değişiklikleri; yazıdaki tüm tutarlarla net şekilde açıklanır.' },
      { icon: '⏰', title: 'Süreler ve sonraki adımlar', desc: 'İtiraz süreleri, gerekli belgeler ve tarihler; hiçbir şey kaçmasın diye net bir liste halinde.' },
    ],
    jargon: {
      label: 'Örnekler', title: 'Bürokrasi Almancası, çevrildi',
      pairs: [
        ['Bescheid', 'sigortanın resmi kararı'],
        ['Zuzahlung', 'kendi ödediğiniz pay'],
        ['Widerspruch', 'karara itiraz etme hakkınız'],
        ['Bewilligung', 'sigorta masrafları karşılıyor'],
        ['MD-Gutachten', 'tıbbi servis tarafından yapılan inceleme'],
        ['Satzungsleistung', 'yalnızca sizin sigortanızın sunduğu ekstra'],
      ],
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Hangi yazıları yükleyebilirim?', a: 'Kararlar, retler, katkı payı ve prim yazıları, yardımcı araçlar, rehabilitasyon veya hastalık parası yazıları; yasal veya özel her sigortadan.' },
      { q: 'Medyra ret durumunda yardımcı olur mu?', a: 'Medyra neyin, neden reddedildiğini ve hangi itiraz süresinin geçerli olduğunu açıklar. Ayrıca sigortanıza soracağınız uygun soruları alırsınız. Hukuki danışmanlığın yerine geçmez.' },
      { q: 'Özel sigortaları da anlar mı?', a: 'Evet. PKV yazıları, Beihilfe kararları ve fatura geri ödemeleri de tanınır ve anlaşılır şekilde açıklanır.' },
      { q: 'Verilerim güvende mi?', a: 'Evet. Şifreli işleme, Frankfurt’ta GDPR uyumlu barındırma, 30 gün sonra otomatik silme (istekle hemen).' },
    ],
    ctaTitle: 'Bir daha hiçbir süreyi kaçırmayın',
    ctaSub: 'Ayda 3 belge ücretsiz. GDPR uyumlu, şifreli, otomatik silinir.',
    ctaButton: 'Sigorta yazımı açıkla',
    ctaNote: 'Medyra hukuki veya sosyal danışmanlığın yerini tutmaz.',
  },

  ar: {
    headerTitle: 'افهم خطاب التأمين',
    headerCta: 'ارفع الخطاب',
    badge: 'قرار · رفض · مساهمة',
    h1a: 'خطابات التأمين بلا',
    h1b: 'لغة البيروقراطية',
    sub: 'خطابات التأمين الصحي الألماني بيروقراطية خالصة. يخبرك Medyra بلغة واضحة بما في الخطاب، وكم سيكلفك، وما المهلة التي يجب ألا تفوتها. في أقل من 60 ثانية.',
    cta: 'ارفع خطاب التأمين الآن',
    mock: {
      labelIn: 'ما يقوله الخطاب', quote: QUOTE, labelOut: 'Medyra يشرح',
      lines: [
        'يغطي التأمين التكاليف جزئياً فقط، وليس كاملة.',
        'أمامك شهر واحد بالضبط لتقديم اعتراض (Widerspruch).',
        'اطلب التبرير الدقيق، فهذا يقوي اعتراضك.',
      ],
    },
    cardsLabel: 'ما تحصل عليه',
    cardsTitle: 'كل قرار، مشروح بوضوح',
    cards: [
      { icon: '📬', title: 'ماذا يقول الخطاب', desc: 'موافقة أو رفض أو إشعار اشتراك أو طلب استرداد: يتعرف Medyra على نوع الخطاب ويلخص محتواه في جملتين.' },
      { icon: '💶', title: 'كم يكلفك', desc: 'المساهمات والحصص الذاتية والمبالغ المستردة وتغييرات الاشتراك موضحة بدقة، مع كل المبالغ من الخطاب.' },
      { icon: '⏰', title: 'المهل والخطوات التالية', desc: 'مهل الاعتراض والمستندات المطلوبة والمواعيد في قائمة واضحة كي لا يفوتك شيء.' },
    ],
    jargon: {
      label: 'أمثلة', title: 'لغة الدوائر الرسمية، مترجمة',
      pairs: [
        ['Bescheid', 'القرار الرسمي لشركة التأمين'],
        ['Zuzahlung', 'الحصة التي تدفعها بنفسك'],
        ['Widerspruch', 'حقك في الطعن بالقرار'],
        ['Bewilligung', 'التأمين يتحمل التكاليف'],
        ['MD-Gutachten', 'مراجعة من الخدمة الطبية'],
        ['Satzungsleistung', 'ميزة إضافية تقدمها شركتك فقط'],
      ],
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما الخطابات التي يمكنني رفعها؟', a: 'القرارات والرفض وخطابات المساهمة والاشتراك، وخطابات الوسائل المساعدة وإعادة التأهيل وبدل المرض؛ من أي تأمين قانوني أو خاص.' },
      { q: 'هل يساعد Medyra عند الرفض؟', a: 'يشرح Medyra ما الذي رُفض ولماذا وما مهلة الاعتراض. وتحصل على أسئلة مناسبة لشركة تأمينك. هذا لا يغني عن الاستشارة القانونية.' },
      { q: 'هل يفهم التأمين الخاص أيضاً؟', a: 'نعم. خطابات PKV وقرارات Beihilfe واسترداد الفواتير تُتعرف وتُشرح بوضوح.' },
      { q: 'هل بياناتي آمنة؟', a: 'نعم. معالجة مشفرة، استضافة متوافقة مع GDPR في فرانكفورت، حذف تلقائي بعد 30 يوماً (وفوراً عند الطلب).' },
    ],
    ctaTitle: 'لا تفوت مهلة بعد اليوم',
    ctaSub: '3 مستندات شهرياً مجاناً. متوافق مع GDPR، مشفر، يُحذف تلقائياً.',
    ctaButton: 'اشرح خطاب التأمين',
    ctaNote: 'لا يحل Medyra محل الاستشارة القانونية أو الاجتماعية.',
  },

  ru: {
    headerTitle: 'Понять письмо страховой',
    headerCta: 'Загрузить письмо',
    badge: 'Решение · Отказ · Доплата',
    h1a: 'Письма страховой без',
    h1b: 'канцелярита',
    sub: 'Письма немецкой медицинской страховки это бюрократия в чистом виде. Medyra говорит вам простым языком, что в письме, сколько это стоит и какой срок нельзя пропустить. Меньше чем за 60 секунд.',
    cta: 'Загрузить письмо страховой',
    mock: {
      labelIn: 'В письме написано', quote: QUOTE, labelOut: 'Medyra объясняет',
      lines: [
        'Страховая покрывает расходы лишь частично, не полностью.',
        'У вас ровно 1 месяц, чтобы подать возражение (Widerspruch).',
        'Запросите точное обоснование, это усилит ваше возражение.',
      ],
    },
    cardsLabel: 'Что вы получаете',
    cardsTitle: 'Каждое решение, понятно объяснённое',
    cards: [
      { icon: '📬', title: 'Что говорит письмо', desc: 'Одобрение, отказ, извещение о взносах или запрос возмещения: Medyra распознаёт тип письма и резюмирует содержание в двух предложениях.' },
      { icon: '💶', title: 'Сколько это стоит вам', desc: 'Доплаты, собственные взносы, возмещения и изменения взносов разложены по полочкам, со всеми суммами из письма.' },
      { icon: '⏰', title: 'Сроки и следующие шаги', desc: 'Сроки возражения, необходимые документы и даты в виде понятного списка, чтобы ничего не упустить.' },
    ],
    jargon: {
      label: 'Примеры', title: 'Канцелярский немецкий, переведён',
      pairs: [
        ['Bescheid', 'официальное решение страховой'],
        ['Zuzahlung', 'доля, которую вы платите сами'],
        ['Widerspruch', 'ваше право оспорить решение'],
        ['Bewilligung', 'страховая берёт расходы на себя'],
        ['MD-Gutachten', 'проверка медицинской службой'],
        ['Satzungsleistung', 'бонус, который предлагает только ваша касса'],
      ],
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Какие письма можно загрузить?', a: 'Решения, отказы, письма о доплатах и взносах, письма о медицинских средствах, реабилитации или больничных; от любой государственной или частной страховки.' },
      { q: 'Помогает ли Medyra при отказе?', a: 'Medyra объясняет, что отклонено, почему и какой срок для возражения действует. Плюс подходящие вопросы для вашей страховой. Юридическую консультацию это не заменяет.' },
      { q: 'Понимает ли частные страховки?', a: 'Да. Письма PKV, решения Beihilfe и возмещения счетов распознаются и понятно объясняются.' },
      { q: 'Мои данные в безопасности?', a: 'Да. Зашифрованная обработка, GDPR совместимый хостинг во Франкфурте, автоматическое удаление через 30 дней (по желанию сразу).' },
    ],
    ctaTitle: 'Больше не пропускайте сроки',
    ctaSub: '3 документа в месяц бесплатно. GDPR, шифрование, автоматическое удаление.',
    ctaButton: 'Объяснить письмо страховой',
    ctaNote: 'Medyra не заменяет юридическую или социальную консультацию.',
  },
}
