// Localized content for /krankenkasse. German is the SEO base; unlisted
// languages fall back to English. German letter quotes stay German.
const QUOTE = '"Ihrem Antrag auf Kostenübernahme kann nach § 33 SGB V nicht in vollem Umfang entsprochen werden. Gegen diesen Bescheid können Sie innerhalb eines Monats Widerspruch einlegen."'

export const CONTENT = {
  de: {
    headerTitle: 'Krankenkasse verstehen',
    headerCta: 'Brief hochladen',
    badge: 'Bescheid · Ablehnung · Zuzahlung',
    h1a: 'Kassenbriefe ohne',
    h1b: 'Amtsdeutsch',
    sub: 'Briefe der Krankenkasse sind Bürokratie in Reinform. Medyra sagt Ihnen in klarer Sprache, was drinsteht, was es kostet und welche Frist Sie nicht verpassen dürfen. In unter 60 Sekunden.',
    cta: 'Kassenbrief jetzt hochladen',
    mock: {
      labelIn: 'Im Brief steht', quote: QUOTE, labelOut: 'Medyra erklärt',
      lines: [
        'Die Kasse übernimmt die Kosten nur teilweise, nicht komplett.',
        'Sie haben genau 1 Monat Zeit, um Widerspruch einzulegen.',
        'Fragen Sie nach der genauen Begründung, das stärkt Ihren Widerspruch.',
      ],
    },
    cardsLabel: 'Was Sie bekommen',
    cardsTitle: 'Jeder Bescheid, klar erklärt',
    cards: [
      { icon: '📬', title: 'Was der Brief sagt', desc: 'Bewilligung, Ablehnung, Beitragsbescheid oder Erstattungsanfrage: Medyra erkennt die Briefart und fasst den Inhalt in zwei Sätzen zusammen.' },
      { icon: '💶', title: 'Was es Sie kostet', desc: 'Zuzahlungen, Eigenanteile, Erstattungsbeträge und Beitragsänderungen werden klar aufgeschlüsselt, mit allen Beträgen aus dem Brief.' },
      { icon: '⏰', title: 'Fristen und nächste Schritte', desc: 'Widerspruchsfristen, einzureichende Unterlagen und Termine als klare Liste, damit nichts verpasst wird.' },
    ],
    jargon: {
      label: 'Beispiele', title: 'Amtsdeutsch, übersetzt',
      pairs: [
        ['Bescheid', 'die offizielle Entscheidung der Kasse'],
        ['Zuzahlung', 'der Anteil, den Sie selbst bezahlen'],
        ['Widerspruch', 'Ihr Recht, die Entscheidung anzufechten'],
        ['Bewilligung', 'die Kasse übernimmt die Kosten'],
        ['MD-Gutachten', 'eine Prüfung durch den Medizinischen Dienst'],
        ['Satzungsleistung', 'ein Extra, das nur Ihre Kasse anbietet'],
      ],
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Welche Briefe kann ich hochladen?', a: 'Bescheide, Ablehnungen, Zuzahlungs- und Beitragsbriefe, Schreiben zu Hilfsmitteln, Reha oder Krankengeld, von jeder gesetzlichen oder privaten Krankenversicherung.' },
      { q: 'Hilft Medyra bei einer Ablehnung?', a: 'Medyra erklärt, was abgelehnt wurde, warum und welche Frist für einen Widerspruch gilt. Dazu bekommen Sie passende Fragen für Ihre Kasse. Rechtsberatung ersetzt das nicht.' },
      { q: 'Versteht Medyra auch private Krankenversicherungen?', a: 'Ja. Auch PKV-Briefe, Beihilfe-Bescheide und Rechnungserstattungen werden erkannt und verständlich erklärt.' },
      { q: 'Sind meine Daten sicher?', a: 'Ja. Verschlüsselte Verarbeitung, DSGVO-konformes Hosting in Frankfurt, automatische Löschung nach 30 Tagen (auf Wunsch sofort).' },
    ],
    ctaTitle: 'Verpassen Sie keine Frist mehr',
    ctaSub: '3 Dokumente pro Monat kostenlos. DSGVO-konform, verschlüsselt, automatisch gelöscht.',
    ctaButton: 'Kassenbrief erklären lassen',
    ctaNote: 'Medyra ersetzt keine Rechts- oder Sozialberatung.',
  },

  en: {
    headerTitle: 'Understand insurance letters',
    headerCta: 'Upload letter',
    badge: 'Decision · Rejection · Copayment',
    h1a: 'Insurance letters without',
    h1b: 'the bureaucracy German',
    sub: 'Letters from German health insurers are bureaucracy in its purest form. Medyra tells you in plain language what the letter says, what it costs you and which deadline you must not miss. In under 60 seconds.',
    cta: 'Upload insurance letter now',
    mock: {
      labelIn: 'The letter says', quote: QUOTE, labelOut: 'Medyra explains',
      lines: [
        'The insurer covers the costs only partially, not in full.',
        'You have exactly 1 month to file an objection (Widerspruch).',
        'Ask for the exact reasoning, it strengthens your objection.',
      ],
    },
    cardsLabel: 'What you get',
    cardsTitle: 'Every decision letter, clearly explained',
    cards: [
      { icon: '📬', title: 'What the letter says', desc: 'Approval, rejection, contribution notice or reimbursement request: Medyra recognizes the letter type and summarizes it in two sentences.' },
      { icon: '💶', title: 'What it costs you', desc: 'Copayments, own contributions, reimbursements and contribution changes broken down clearly, with all amounts from the letter.' },
      { icon: '⏰', title: 'Deadlines and next steps', desc: 'Objection deadlines, documents to submit and dates as a clear list so nothing gets missed.' },
    ],
    jargon: {
      label: 'Examples', title: 'Bureaucracy German, translated',
      pairs: [
        ['Bescheid', 'the official decision of the insurer'],
        ['Zuzahlung', 'the share you pay yourself'],
        ['Widerspruch', 'your right to contest the decision'],
        ['Bewilligung', 'the insurer covers the costs'],
        ['MD-Gutachten', 'a review by the medical service'],
        ['Satzungsleistung', 'an extra only your insurer offers'],
      ],
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'Which letters can I upload?', a: 'Decisions, rejections, copayment and contribution letters, letters about medical aids, rehab or sick pay, from any statutory or private health insurance.' },
      { q: 'Does Medyra help with a rejection?', a: 'Medyra explains what was rejected, why, and which objection deadline applies. You also get fitting questions for your insurer. It does not replace legal advice.' },
      { q: 'Does Medyra understand private insurance too?', a: 'Yes. PKV letters, Beihilfe decisions and invoice reimbursements are recognized and explained clearly.' },
      { q: 'Is my data safe?', a: 'Yes. Encrypted processing, GDPR compliant hosting in Frankfurt, automatic deletion after 30 days (immediately on request).' },
    ],
    ctaTitle: 'Never miss a deadline again',
    ctaSub: '3 documents per month free. GDPR compliant, encrypted, deleted automatically.',
    ctaButton: 'Explain my insurance letter',
    ctaNote: 'Medyra does not replace legal or social counseling.',
  },

  tr: {
    headerTitle: 'Sigorta yazısını anlayın',
    headerCta: 'Yazıyı yükle',
    badge: 'Karar · Ret · Katkı payı',
    h1a: 'Sigorta yazıları,',
    h1b: 'bürokrasi Almancası olmadan',
    sub: 'Alman sağlık sigortası yazıları bürokrasinin ta kendisidir. Medyra size anlaşılır dille ne yazdığını, size ne kadara mal olacağını ve hangi süreyi kaçırmamanız gerektiğini söyler. 60 saniyeden kısa sürede.',
    cta: 'Sigorta yazısını şimdi yükle',
    mock: {
      labelIn: 'Yazıda yazan', quote: QUOTE, labelOut: 'Medyra açıklıyor',
      lines: [
        'Sigorta masrafları tamamen değil, yalnızca kısmen karşılıyor.',
        'İtiraz (Widerspruch) için tam 1 ayınız var.',
        'Gerekçeyi ayrıntılı sorun; bu itirazınızı güçlendirir.',
      ],
    },
    cardsLabel: 'Ne alırsınız',
    cardsTitle: 'Her karar yazısı, net açıklanmış',
    cards: [
      { icon: '📬', title: 'Yazı ne diyor', desc: 'Onay, ret, prim bildirimi veya geri ödeme talebi: Medyra yazı türünü tanır ve içeriği iki cümlede özetler.' },
      { icon: '💶', title: 'Size maliyeti ne', desc: 'Katkı payları, kendi payınız, geri ödemeler ve prim değişiklikleri; yazıdaki tüm tutarlarla net şekilde açıklanır.' },
      { icon: '⏰', title: 'Süreler ve sonraki adımlar', desc: 'İtiraz süreleri, gerekli belgeler ve tarihler; hiçbir şey kaçmasın diye net bir liste halinde.' },
    ],
    jargon: {
      label: 'Örnekler', title: 'Bürokrasi Almancası, çevrildi',
      pairs: [
        ['Bescheid', 'sigortanın resmi kararı'],
        ['Zuzahlung', 'kendi ödediğiniz pay'],
        ['Widerspruch', 'karara itiraz etme hakkınız'],
        ['Bewilligung', 'sigorta masrafları karşılıyor'],
        ['MD-Gutachten', 'tıbbi servis tarafından yapılan inceleme'],
        ['Satzungsleistung', 'yalnızca sizin sigortanızın sunduğu ekstra'],
      ],
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Hangi yazıları yükleyebilirim?', a: 'Kararlar, retler, katkı payı ve prim yazıları, yardımcı araçlar, rehabilitasyon veya hastalık parası yazıları; yasal veya özel her sigortadan.' },
      { q: 'Medyra ret durumunda yardımcı olur mu?', a: 'Medyra neyin, neden reddedildiğini ve hangi itiraz süresinin geçerli olduğunu açıklar. Ayrıca sigortanıza soracağınız uygun soruları alırsınız. Hukuki danışmanlığın yerine geçmez.' },
      { q: 'Özel sigortaları da anlar mı?', a: 'Evet. PKV yazıları, Beihilfe kararları ve fatura geri ödemeleri de tanınır ve anlaşılır şekilde açıklanır.' },
      { q: 'Verilerim güvende mi?', a: 'Evet. Şifreli işleme, Frankfurt’ta GDPR uyumlu barındırma, 30 gün sonra otomatik silme (istekle hemen).' },
    ],
    ctaTitle: 'Bir daha hiçbir süreyi kaçırmayın',
    ctaSub: 'Ayda 3 belge ücretsiz. GDPR uyumlu, şifreli, otomatik silinir.',
    ctaButton: 'Sigorta yazımı açıkla',
    ctaNote: 'Medyra hukuki veya sosyal danışmanlığın yerini tutmaz.',
  },

  ar: {
    headerTitle: 'افهم خطاب التأمين',
    headerCta: 'ارفع الخطاب',
    badge: 'قرار · رفض · مساهمة',
    h1a: 'خطابات التأمين بلا',
    h1b: 'لغة البيروقراطية',
    sub: 'خطابات التأمين الصحي الألماني بيروقراطية خالصة. يخبرك Medyra بلغة واضحة بما في الخطاب، وكم سيكلفك، وما المهلة التي يجب ألا تفوتها. في أقل من 60 ثانية.',
    cta: 'ارفع خطاب التأمين الآن',
    mock: {
      labelIn: 'ما يقوله الخطاب', quote: QUOTE, labelOut: 'Medyra يشرح',
      lines: [
        'يغطي التأمين التكاليف جزئياً فقط، وليس كاملة.',
        'أمامك شهر واحد بالضبط لتقديم اعتراض (Widerspruch).',
        'اطلب التبرير الدقيق، فهذا يقوي اعتراضك.',
      ],
    },
    cardsLabel: 'ما تحصل عليه',
    cardsTitle: 'كل قرار، مشروح بوضوح',
    cards: [
      { icon: '📬', title: 'ماذا يقول الخطاب', desc: 'موافقة أو رفض أو إشعار اشتراك أو طلب استرداد: يتعرف Medyra على نوع الخطاب ويلخص محتواه في جملتين.' },
      { icon: '💶', title: 'كم يكلفك', desc: 'المساهمات والحصص الذاتية والمبالغ المستردة وتغييرات الاشتراك موضحة بدقة، مع كل المبالغ من الخطاب.' },
      { icon: '⏰', title: 'المهل والخطوات التالية', desc: 'مهل الاعتراض والمستندات المطلوبة والمواعيد في قائمة واضحة كي لا يفوتك شيء.' },
    ],
    jargon: {
      label: 'أمثلة', title: 'لغة الدوائر الرسمية، مترجمة',
      pairs: [
        ['Bescheid', 'القرار الرسمي لشركة التأمين'],
        ['Zuzahlung', 'الحصة التي تدفعها بنفسك'],
        ['Widerspruch', 'حقك في الطعن بالقرار'],
        ['Bewilligung', 'التأمين يتحمل التكاليف'],
        ['MD-Gutachten', 'مراجعة من الخدمة الطبية'],
        ['Satzungsleistung', 'ميزة إضافية تقدمها شركتك فقط'],
      ],
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما الخطابات التي يمكنني رفعها؟', a: 'القرارات والرفض وخطابات المساهمة والاشتراك، وخطابات الوسائل المساعدة وإعادة التأهيل وبدل المرض؛ من أي تأمين قانوني أو خاص.' },
      { q: 'هل يساعد Medyra عند الرفض؟', a: 'يشرح Medyra ما الذي رُفض ولماذا وما مهلة الاعتراض. وتحصل على أسئلة مناسبة لشركة تأمينك. هذا لا يغني عن الاستشارة القانونية.' },
      { q: 'هل يفهم التأمين الخاص أيضاً؟', a: 'نعم. خطابات PKV وقرارات Beihilfe واسترداد الفواتير تُتعرف وتُشرح بوضوح.' },
      { q: 'هل بياناتي آمنة؟', a: 'نعم. معالجة مشفرة، استضافة متوافقة مع GDPR في فرانكفورت، حذف تلقائي بعد 30 يوماً (وفوراً عند الطلب).' },
    ],
    ctaTitle: 'لا تفوت مهلة بعد اليوم',
    ctaSub: '3 مستندات شهرياً مجاناً. متوافق مع GDPR، مشفر، يُحذف تلقائياً.',
    ctaButton: 'اشرح خطاب التأمين',
    ctaNote: 'لا يحل Medyra محل الاستشارة القانونية أو الاجتماعية.',
  },

  ru: {
    headerTitle: 'Понять письмо страховой',
    headerCta: 'Загрузить письмо',
    badge: 'Решение · Отказ · Доплата',
    h1a: 'Письма страховой без',
    h1b: 'канцелярита',
    sub: 'Письма немецкой медицинской страховки это бюрократия в чистом виде. Medyra говорит вам простым языком, что в письме, сколько это стоит и какой срок нельзя пропустить. Меньше чем за 60 секунд.',
    cta: 'Загрузить письмо страховой',
    mock: {
      labelIn: 'В письме написано', quote: QUOTE, labelOut: 'Medyra объясняет',
      lines: [
        'Страховая покрывает расходы лишь частично, не полностью.',
        'У вас ровно 1 месяц, чтобы подать возражение (Widerspruch).',
        'Запросите точное обоснование, это усилит ваше возражение.',
      ],
    },
    cardsLabel: 'Что вы получаете',
    cardsTitle: 'Каждое решение, понятно объяснённое',
    cards: [
      { icon: '📬', title: 'Что говорит письмо', desc: 'Одобрение, отказ, извещение о взносах или запрос возмещения: Medyra распознаёт тип письма и резюмирует содержание в двух предложениях.' },
      { icon: '💶', title: 'Сколько это стоит вам', desc: 'Доплаты, собственные взносы, возмещения и изменения взносов разложены по полочкам, со всеми суммами из письма.' },
      { icon: '⏰', title: 'Сроки и следующие шаги', desc: 'Сроки возражения, необходимые документы и даты в виде понятного списка, чтобы ничего не упустить.' },
    ],
    jargon: {
      label: 'Примеры', title: 'Канцелярский немецкий, переведён',
      pairs: [
        ['Bescheid', 'официальное решение страховой'],
        ['Zuzahlung', 'доля, которую вы платите сами'],
        ['Widerspruch', 'ваше право оспорить решение'],
        ['Bewilligung', 'страховая берёт расходы на себя'],
        ['MD-Gutachten', 'проверка медицинской службой'],
        ['Satzungsleistung', 'бонус, который предлагает только ваша касса'],
      ],
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Какие письма можно загрузить?', a: 'Решения, отказы, письма о доплатах и взносах, письма о медицинских средствах, реабилитации или больничных; от любой государственной или частной страховки.' },
      { q: 'Помогает ли Medyra при отказе?', a: 'Medyra объясняет, что отклонено, почему и какой срок для возражения действует. Плюс подходящие вопросы для вашей страховой. Юридическую консультацию это не заменяет.' },
      { q: 'Понимает ли частные страховки?', a: 'Да. Письма PKV, решения Beihilfe и возмещения счетов распознаются и понятно объясняются.' },
      { q: 'Мои данные в безопасности?', a: 'Да. Зашифрованная обработка, GDPR совместимый хостинг во Франкфурте, автоматическое удаление через 30 дней (по желанию сразу).' },
    ],
    ctaTitle: 'Больше не пропускайте сроки',
    ctaSub: '3 документа в месяц бесплатно. GDPR, шифрование, автоматическое удаление.',
    ctaButton: 'Объяснить письмо страховой',
    ctaNote: 'Medyra не заменяет юридическую или социальную консультацию.',
  },

  fr: {
    headerTitle: 'Comprendre les lettres de caisse maladie', headerCta: 'Télécharger la lettre',
    badge: 'Décision · Refus · Participation',
    h1a: 'Les lettres de caisse sans', h1b: 'le jargon administratif',
    sub: "Les lettres des caisses d'assurance maladie allemandes sont de la bureaucratie à l'état pur. Medyra vous dit en langage clair ce qu'elle contient, ce qu'elle vous coûte et quel délai vous ne devez pas manquer. En moins de 60 secondes.",
    cta: "Télécharger la lettre d'assurance maintenant",
    mock: {
      labelIn: 'La lettre indique', quote: QUOTE, labelOut: 'Medyra explique',
      lines: [
        "La caisse ne prend en charge les frais que partiellement, pas en totalité.",
        'Vous avez exactement 1 mois pour faire opposition (Widerspruch).',
        'Demandez la justification exacte, cela renforce votre opposition.',
      ],
    },
    cardsLabel: 'Ce que vous obtenez', cardsTitle: 'Chaque décision, clairement expliquée',
    cards: [
      { icon: '📬', title: 'Ce que dit la lettre', desc: 'Approbation, refus, avis de cotisation ou demande de remboursement : Medyra reconnaît le type de lettre et résume le contenu en deux phrases.' },
      { icon: '💶', title: 'Ce que cela vous coûte', desc: 'Participations, part personnelle, remboursements et changements de cotisation clairement détaillés, avec tous les montants de la lettre.' },
      { icon: '⏰', title: 'Délais et prochaines étapes', desc: "Délais d'opposition, documents à soumettre et dates sous forme de liste claire pour ne rien manquer." },
    ],
    jargon: {
      label: 'Exemples', title: 'Allemand administratif, traduit',
      pairs: [
        ['Bescheid', 'la décision officielle de la caisse'],
        ['Zuzahlung', 'la part que vous payez vous-même'],
        ['Widerspruch', 'votre droit de contester la décision'],
        ['Bewilligung', 'la caisse prend en charge les frais'],
        ['MD-Gutachten', 'un examen par le service médical'],
        ['Satzungsleistung', "un extra offert uniquement par votre caisse"],
      ],
    },
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'Quelles lettres puis-je télécharger ?', a: "Décisions, refus, lettres de participation et de cotisation, courriers concernant des dispositifs médicaux, la rééducation ou les indemnités maladie, de toute assurance maladie légale ou privée." },
      { q: "Medyra aide-t-il en cas de refus ?", a: "Medyra explique ce qui a été refusé, pourquoi, et quel délai d'opposition s'applique. Vous obtenez aussi des questions adaptées pour votre caisse. Cela ne remplace pas un conseil juridique." },
      { q: "Medyra comprend-il aussi les assurances privées ?", a: 'Oui. Les lettres PKV, les décisions Beihilfe et les remboursements de factures sont reconnus et expliqués clairement.' },
      { q: 'Mes données sont-elles en sécurité ?', a: 'Oui. Traitement chiffré, hébergement conforme au RGPD à Francfort, suppression automatique après 30 jours (immédiatement sur demande).' },
    ],
    ctaTitle: 'Ne manquez plus jamais un délai',
    ctaSub: '3 documents par mois gratuits. Conforme au RGPD, chiffré, supprimé automatiquement.',
    ctaButton: "Expliquer ma lettre d'assurance",
    ctaNote: 'Medyra ne remplace pas un conseil juridique ou social.',
  },

  es: {
    headerTitle: 'Entender las cartas del seguro médico', headerCta: 'Subir carta',
    badge: 'Resolución · Rechazo · Copago',
    h1a: 'Cartas del seguro sin', h1b: 'la jerga burocrática',
    sub: 'Las cartas de las cajas de seguro médico alemanas son burocracia en estado puro. Medyra le dice en lenguaje claro qué dice la carta, cuánto le cuesta y qué plazo no debe dejar pasar. En menos de 60 segundos.',
    cta: 'Suba su carta del seguro ahora',
    mock: {
      labelIn: 'La carta dice', quote: QUOTE, labelOut: 'Medyra explica',
      lines: [
        'La aseguradora cubre los costos solo parcialmente, no en su totalidad.',
        'Tiene exactamente 1 mes para presentar una objeción (Widerspruch).',
        'Pida la justificación exacta, esto refuerza su objeción.',
      ],
    },
    cardsLabel: 'Lo que obtiene', cardsTitle: 'Cada resolución, claramente explicada',
    cards: [
      { icon: '📬', title: 'Qué dice la carta', desc: 'Aprobación, rechazo, aviso de cotización o solicitud de reembolso: Medyra reconoce el tipo de carta y resume el contenido en dos frases.' },
      { icon: '💶', title: 'Cuánto le cuesta', desc: 'Copagos, aportaciones propias, reembolsos y cambios de cotización claramente desglosados, con todos los importes de la carta.' },
      { icon: '⏰', title: 'Plazos y próximos pasos', desc: 'Plazos de objeción, documentos a presentar y fechas en una lista clara para que no se le escape nada.' },
    ],
    jargon: {
      label: 'Ejemplos', title: 'Alemán burocrático, traducido',
      pairs: [
        ['Bescheid', 'la resolución oficial de la aseguradora'],
        ['Zuzahlung', 'la parte que paga usted mismo'],
        ['Widerspruch', 'su derecho a impugnar la decisión'],
        ['Bewilligung', 'la aseguradora cubre los costos'],
        ['MD-Gutachten', 'una revisión del servicio médico'],
        ['Satzungsleistung', 'un extra que solo ofrece su aseguradora'],
      ],
    },
    faqTitle: 'Preguntas frecuentes',
    faq: [
      { q: '¿Qué cartas puedo subir?', a: 'Resoluciones, rechazos, cartas de copago y cotización, cartas sobre ayudas médicas, rehabilitación o baja por enfermedad, de cualquier seguro médico público o privado.' },
      { q: '¿Medyra ayuda en caso de rechazo?', a: 'Medyra explica qué fue rechazado, por qué y qué plazo de objeción aplica. También recibe preguntas adecuadas para su aseguradora. Esto no sustituye el asesoramiento legal.' },
      { q: '¿Medyra entiende también los seguros privados?', a: 'Sí. Las cartas PKV, las resoluciones de Beihilfe y los reembolsos de facturas se reconocen y explican con claridad.' },
      { q: '¿Están seguros mis datos?', a: 'Sí. Procesamiento cifrado, alojamiento conforme al RGPD en Fráncfort, eliminación automática después de 30 días (inmediata si se solicita).' },
    ],
    ctaTitle: 'No vuelva a perder un plazo',
    ctaSub: '3 documentos al mes gratis. Conforme al RGPD, cifrado, eliminado automáticamente.',
    ctaButton: 'Explicar mi carta del seguro',
    ctaNote: 'Medyra no sustituye el asesoramiento legal o social.',
  },

  it: {
    headerTitle: 'Capire le lettere della cassa malattia', headerCta: 'Carica la lettera',
    badge: 'Decisione · Rifiuto · Compartecipazione',
    h1a: 'Lettere della cassa senza', h1b: 'il burocratese',
    sub: 'Le lettere delle casse malattia tedesche sono burocrazia allo stato puro. Medyra ti dice in linguaggio chiaro cosa c’è scritto, quanto ti costa e quale scadenza non devi perdere. In meno di 60 secondi.',
    cta: 'Carica ora la lettera della cassa',
    mock: {
      labelIn: 'La lettera dice', quote: QUOTE, labelOut: 'Medyra spiega',
      lines: [
        'La cassa copre i costi solo parzialmente, non per intero.',
        'Hai esattamente 1 mese per presentare un ricorso (Widerspruch).',
        'Chiedi la motivazione esatta, questo rafforza il tuo ricorso.',
      ],
    },
    cardsLabel: 'Cosa ottieni', cardsTitle: 'Ogni decisione, spiegata chiaramente',
    cards: [
      { icon: '📬', title: 'Cosa dice la lettera', desc: 'Approvazione, rifiuto, avviso di contributo o richiesta di rimborso: Medyra riconosce il tipo di lettera e riassume il contenuto in due frasi.' },
      { icon: '💶', title: 'Quanto ti costa', desc: 'Compartecipazioni, quote personali, rimborsi e variazioni dei contributi chiaramente dettagliati, con tutti gli importi dalla lettera.' },
      { icon: '⏰', title: 'Scadenze e prossimi passi', desc: 'Scadenze di ricorso, documenti da presentare e date come lista chiara per non perdere nulla.' },
    ],
    jargon: {
      label: 'Esempi', title: 'Tedesco burocratico, tradotto',
      pairs: [
        ['Bescheid', 'la decisione ufficiale della cassa'],
        ['Zuzahlung', 'la quota che paghi tu stesso'],
        ['Widerspruch', 'il tuo diritto di contestare la decisione'],
        ['Bewilligung', 'la cassa copre i costi'],
        ['MD-Gutachten', 'una verifica del servizio medico'],
        ['Satzungsleistung', 'un extra offerto solo dalla tua cassa'],
      ],
    },
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'Quali lettere posso caricare?', a: 'Decisioni, rifiuti, lettere di compartecipazione e contributo, lettere su ausili medici, riabilitazione o indennità di malattia, di qualsiasi assicurazione sanitaria pubblica o privata.' },
      { q: 'Medyra aiuta in caso di rifiuto?', a: 'Medyra spiega cosa è stato rifiutato, perché e quale scadenza di ricorso si applica. Ricevi anche domande adatte per la tua cassa. Non sostituisce la consulenza legale.' },
      { q: 'Medyra capisce anche le assicurazioni private?', a: 'Sì. Le lettere PKV, le decisioni Beihilfe e i rimborsi delle fatture vengono riconosciuti e spiegati chiaramente.' },
      { q: 'I miei dati sono al sicuro?', a: 'Sì. Elaborazione crittografata, hosting conforme al GDPR a Francoforte, eliminazione automatica dopo 30 giorni (subito su richiesta).' },
    ],
    ctaTitle: 'Non perdere più nessuna scadenza',
    ctaSub: '3 documenti al mese gratis. Conforme al GDPR, crittografato, eliminato automaticamente.',
    ctaButton: 'Spiega la mia lettera della cassa',
    ctaNote: 'Medyra non sostituisce la consulenza legale o sociale.',
  },

  pt: {
    headerTitle: 'Entender as cartas do seguro de saúde', headerCta: 'Enviar carta',
    badge: 'Decisão · Recusa · Coparticipação',
    h1a: 'Cartas do seguro sem', h1b: 'o burocratês',
    sub: 'As cartas das seguradoras de saúde alemãs são burocracia em estado puro. A Medyra diz em linguagem clara o que a carta contém, quanto custa e qual prazo você não pode perder. Em menos de 60 segundos.',
    cta: 'Envie a carta do seguro agora',
    mock: {
      labelIn: 'A carta diz', quote: QUOTE, labelOut: 'Medyra explica',
      lines: [
        'A seguradora cobre os custos apenas parcialmente, não integralmente.',
        'Você tem exatamente 1 mês para apresentar uma objeção (Widerspruch).',
        'Peça a justificativa exata, isso fortalece sua objeção.',
      ],
    },
    cardsLabel: 'O que você recebe', cardsTitle: 'Cada decisão, claramente explicada',
    cards: [
      { icon: '📬', title: 'O que a carta diz', desc: 'Aprovação, recusa, aviso de contribuição ou pedido de reembolso: a Medyra reconhece o tipo de carta e resume o conteúdo em duas frases.' },
      { icon: '💶', title: 'Quanto custa para você', desc: 'Coparticipações, contribuições próprias, reembolsos e alterações de contribuição claramente detalhados, com todos os valores da carta.' },
      { icon: '⏰', title: 'Prazos e próximos passos', desc: 'Prazos de objeção, documentos a apresentar e datas como uma lista clara para que nada seja perdido.' },
    ],
    jargon: {
      label: 'Exemplos', title: 'Alemão burocrático, traduzido',
      pairs: [
        ['Bescheid', 'a decisão oficial da seguradora'],
        ['Zuzahlung', 'a parte que você mesmo paga'],
        ['Widerspruch', 'seu direito de contestar a decisão'],
        ['Bewilligung', 'a seguradora cobre os custos'],
        ['MD-Gutachten', 'uma avaliação pelo serviço médico'],
        ['Satzungsleistung', 'um extra oferecido apenas pela sua seguradora'],
      ],
    },
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'Quais cartas posso enviar?', a: 'Decisões, recusas, cartas de coparticipação e contribuição, cartas sobre auxílios médicos, reabilitação ou auxílio-doença, de qualquer seguro de saúde público ou privado.' },
      { q: 'A Medyra ajuda em caso de recusa?', a: 'A Medyra explica o que foi recusado, por quê, e qual prazo de objeção se aplica. Você também recebe perguntas adequadas para sua seguradora. Isso não substitui o aconselhamento jurídico.' },
      { q: 'A Medyra entende também seguros privados?', a: 'Sim. Cartas PKV, decisões Beihilfe e reembolsos de faturas são reconhecidos e explicados claramente.' },
      { q: 'Meus dados estão seguros?', a: 'Sim. Processamento criptografado, hospedagem em conformidade com o RGPD em Frankfurt, exclusão automática após 30 dias (imediatamente a pedido).' },
    ],
    ctaTitle: 'Nunca mais perca um prazo',
    ctaSub: '3 documentos por mês grátis. Conforme o RGPD, criptografado, excluído automaticamente.',
    ctaButton: 'Explicar minha carta do seguro',
    ctaNote: 'A Medyra não substitui o aconselhamento jurídico ou social.',
  },

  nl: {
    headerTitle: 'Zorgverzekeringsbrieven begrijpen', headerCta: 'Brief uploaden',
    badge: 'Besluit · Afwijzing · Eigen bijdrage',
    h1a: 'Verzekeringsbrieven zonder', h1b: 'het bureaucratische Duits',
    sub: 'Brieven van Duitse zorgverzekeraars zijn bureaucratie in zijn zuiverste vorm. Medyra vertelt u in duidelijke taal wat erin staat, wat het u kost en welke termijn u niet mag missen. In minder dan 60 seconden.',
    cta: 'Upload nu uw verzekeringsbrief',
    mock: {
      labelIn: 'De brief zegt', quote: QUOTE, labelOut: 'Medyra legt uit',
      lines: [
        'De verzekeraar vergoedt de kosten slechts gedeeltelijk, niet volledig.',
        'U heeft precies 1 maand om bezwaar (Widerspruch) te maken.',
        'Vraag om de precieze motivering, dat versterkt uw bezwaar.',
      ],
    },
    cardsLabel: 'Wat u krijgt', cardsTitle: 'Elk besluit, duidelijk uitgelegd',
    cards: [
      { icon: '📬', title: 'Wat de brief zegt', desc: 'Goedkeuring, afwijzing, premiebericht of vergoedingsverzoek: Medyra herkent het brieftype en vat de inhoud samen in twee zinnen.' },
      { icon: '💶', title: 'Wat het u kost', desc: 'Eigen bijdragen, eigen aandeel, vergoedingen en premiewijzigingen duidelijk uitgesplitst, met alle bedragen uit de brief.' },
      { icon: '⏰', title: 'Termijnen en volgende stappen', desc: 'Bezwaartermijnen, in te dienen documenten en data als duidelijke lijst zodat niets wordt gemist.' },
    ],
    jargon: {
      label: 'Voorbeelden', title: 'Bureaucratisch Duits, vertaald',
      pairs: [
        ['Bescheid', 'het officiële besluit van de verzekeraar'],
        ['Zuzahlung', 'het deel dat u zelf betaalt'],
        ['Widerspruch', 'uw recht om het besluit aan te vechten'],
        ['Bewilligung', 'de verzekeraar vergoedt de kosten'],
        ['MD-Gutachten', 'een beoordeling door de medische dienst'],
        ['Satzungsleistung', 'een extra die alleen uw verzekeraar aanbiedt'],
      ],
    },
    faqTitle: 'Veelgestelde vragen',
    faq: [
      { q: 'Welke brieven kan ik uploaden?', a: 'Besluiten, afwijzingen, brieven over eigen bijdrage en premie, brieven over hulpmiddelen, revalidatie of ziekengeld, van elke wettelijke of particuliere zorgverzekering.' },
      { q: 'Helpt Medyra bij een afwijzing?', a: 'Medyra legt uit wat is afgewezen, waarom, en welke bezwaartermijn geldt. U krijgt ook passende vragen voor uw verzekeraar. Dit vervangt geen juridisch advies.' },
      { q: 'Begrijpt Medyra ook particuliere verzekeringen?', a: 'Ja. PKV-brieven, Beihilfe-besluiten en factuurvergoedingen worden herkend en duidelijk uitgelegd.' },
      { q: 'Zijn mijn gegevens veilig?', a: 'Ja. Versleutelde verwerking, AVG-conforme hosting in Frankfurt, automatische verwijdering na 30 dagen (direct op verzoek).' },
    ],
    ctaTitle: 'Mis nooit meer een termijn',
    ctaSub: '3 documenten per maand gratis. AVG-conform, versleuteld, automatisch verwijderd.',
    ctaButton: 'Leg mijn verzekeringsbrief uit',
    ctaNote: 'Medyra vervangt geen juridisch of sociaal advies.',
  },

  pl: {
    headerTitle: 'Zrozumieć pisma kasy chorych', headerCta: 'Prześlij pismo',
    badge: 'Decyzja · Odmowa · Dopłata',
    h1a: 'Pisma kasy chorych bez', h1b: 'urzędniczego niemieckiego',
    sub: 'Pisma niemieckich kas chorych to biurokracja w czystej postaci. Medyra mówi ci prostym językiem, co jest w piśmie, ile to kosztuje i jakiego terminu nie możesz przegapić. W mniej niż 60 sekund.',
    cta: 'Prześlij pismo z kasy chorych teraz',
    mock: {
      labelIn: 'W piśmie napisano', quote: QUOTE, labelOut: 'Medyra wyjaśnia',
      lines: [
        'Kasa pokrywa koszty tylko częściowo, nie w całości.',
        'Masz dokładnie 1 miesiąc na złożenie odwołania (Widerspruch).',
        'Poproś o dokładne uzasadnienie, to wzmocni twoje odwołanie.',
      ],
    },
    cardsLabel: 'Co otrzymujesz', cardsTitle: 'Każda decyzja, jasno wyjaśniona',
    cards: [
      { icon: '📬', title: 'Co mówi pismo', desc: 'Zatwierdzenie, odmowa, powiadomienie o składce lub wniosek o zwrot kosztów: Medyra rozpoznaje rodzaj pisma i podsumowuje treść w dwóch zdaniach.' },
      { icon: '💶', title: 'Ile cię to kosztuje', desc: 'Dopłaty, udziały własne, zwroty i zmiany składek jasno rozpisane, ze wszystkimi kwotami z pisma.' },
      { icon: '⏰', title: 'Terminy i następne kroki', desc: 'Terminy odwołań, dokumenty do złożenia i daty jako jasna lista, żeby niczego nie przegapić.' },
    ],
    jargon: {
      label: 'Przykłady', title: 'Urzędniczy niemiecki, przetłumaczony',
      pairs: [
        ['Bescheid', 'oficjalna decyzja kasy chorych'],
        ['Zuzahlung', 'część, którą płacisz sam'],
        ['Widerspruch', 'twoje prawo do zakwestionowania decyzji'],
        ['Bewilligung', 'kasa chorych pokrywa koszty'],
        ['MD-Gutachten', 'kontrola przeprowadzona przez służbę medyczną'],
        ['Satzungsleistung', 'dodatek oferowany tylko przez twoją kasę'],
      ],
    },
    faqTitle: 'Najczęstsze pytania',
    faq: [
      { q: 'Jakie pisma mogę przesłać?', a: 'Decyzje, odmowy, pisma o dopłatach i składkach, pisma o środkach pomocniczych, rehabilitacji lub zasiłku chorobowym, z każdej ustawowej lub prywatnej kasy chorych.' },
      { q: 'Czy Medyra pomaga przy odmowie?', a: 'Medyra wyjaśnia, co zostało odrzucone, dlaczego i jaki termin odwołania obowiązuje. Otrzymujesz też odpowiednie pytania do swojej kasy. To nie zastępuje porady prawnej.' },
      { q: 'Czy Medyra rozumie też prywatne ubezpieczenia?', a: 'Tak. Pisma PKV, decyzje Beihilfe i zwroty rachunków są rozpoznawane i jasno wyjaśniane.' },
      { q: 'Czy moje dane są bezpieczne?', a: 'Tak. Szyfrowane przetwarzanie, hosting zgodny z RODO we Frankfurcie, automatyczne usunięcie po 30 dniach (natychmiast na żądanie).' },
    ],
    ctaTitle: 'Nie przegap już żadnego terminu',
    ctaSub: '3 dokumenty miesięcznie za darmo. Zgodność z RODO, szyfrowanie, automatyczne usuwanie.',
    ctaButton: 'Wyjaśnij moje pismo z kasy chorych',
    ctaNote: 'Medyra nie zastępuje porady prawnej ani socjalnej.',
  },

  zh: {
    headerTitle: '看懂医保信件', headerCta: '上传信件',
    badge: '决定 · 拒绝 · 自付费用',
    h1a: '医保信件不再', h1b: '充满官方术语',
    sub: '德国医保公司的信件是官僚主义的纯粹体现。Medyra用通俗易懂的语言告诉您信中写了什么，需要花费多少，以及不能错过的截止日期。不到60秒。',
    cta: '立即上传您的医保信件',
    mock: {
      labelIn: '信中写道', quote: QUOTE, labelOut: 'Medyra 解释',
      lines: [
        '保险公司只部分承担费用，而非全部。',
        '您有整整1个月的时间提出异议（Widerspruch）。',
        '询问确切的理由，这将加强您的异议。',
      ],
    },
    cardsLabel: '您将获得', cardsTitle: '每个决定，清晰解释',
    cards: [
      { icon: '📬', title: '信中说了什么', desc: '批准、拒绝、缴费通知或报销申请：Medyra识别信件类型并用两句话总结内容。' },
      { icon: '💶', title: '您需要支付多少', desc: '自付费用、自负部分、报销金额和缴费变化，连同信中的所有金额清晰列出。' },
      { icon: '⏰', title: '截止日期和后续步骤', desc: '异议截止日期、需提交的文件和日期，以清晰的列表形式呈现，确保不遗漏任何内容。' },
    ],
    jargon: {
      label: '示例', title: '官方德语，已翻译',
      pairs: [
        ['Bescheid', '保险公司的官方决定'],
        ['Zuzahlung', '您自己支付的部分'],
        ['Widerspruch', '您对决定提出异议的权利'],
        ['Bewilligung', '保险公司承担费用'],
        ['MD-Gutachten', '医疗服务机构的审查'],
        ['Satzungsleistung', '仅由您的保险公司提供的额外福利'],
      ],
    },
    faqTitle: '常见问题',
    faq: [
      { q: '我可以上传哪些信件？', a: '决定书、拒绝信、自付费用和缴费信件、关于医疗辅助器具、康复或病假工资的信件，来自任何法定或私人医疗保险。' },
      { q: 'Medyra在被拒绝时能提供帮助吗？', a: 'Medyra解释了什么被拒绝、为什么被拒绝以及适用的异议截止日期。您还会得到适合向保险公司提出的问题。这不能替代法律咨询。' },
      { q: 'Medyra也能看懂私人保险吗？', a: '可以。PKV信件、Beihilfe决定和账单报销都能被识别并清晰解释。' },
      { q: '我的数据安全吗？', a: '是的。加密处理，符合GDPR标准，托管在法兰克福，30天后自动删除（应要求可立即删除）。' },
    ],
    ctaTitle: '再也不会错过任何截止日期',
    ctaSub: '每月3份文件免费。符合GDPR，加密处理，自动删除。',
    ctaButton: '解释我的医保信件',
    ctaNote: 'Medyra 不能替代法律或社会咨询。',
  },

  ja: {
    headerTitle: '健康保険の手紙を理解する', headerCta: '手紙をアップロード',
    badge: '決定通知・却下・自己負担',
    h1a: '保険の手紙が、', h1b: '役所言葉なしで分かる',
    sub: 'ドイツの健康保険組合からの手紙は、官僚主義そのものです。Medyraは手紙に何が書かれているか、いくらかかるか、そして見逃してはいけない期限を分かりやすい言葉で伝えます。60秒以内で。',
    cta: '今すぐ保険の手紙をアップロード',
    mock: {
      labelIn: '手紙にはこう書かれています', quote: QUOTE, labelOut: 'Medyraが説明します',
      lines: [
        '保険組合は費用の一部のみを負担し、全額ではありません。',
        '異議申し立て（Widerspruch）にはちょうど1か月の猶予があります。',
        '正確な理由を尋ねることで、異議申し立てが強化されます。',
      ],
    },
    cardsLabel: '得られるもの', cardsTitle: 'あらゆる決定通知を明確に説明',
    cards: [
      { icon: '📬', title: '手紙の内容', desc: '承認、却下、保険料通知、払い戻し請求：Medyraは手紙の種類を認識し、内容を2文で要約します。' },
      { icon: '💶', title: 'かかる費用', desc: '自己負担額、自己分担金、払い戻し額、保険料の変更を、手紙に記載された全ての金額とともに明確に分類します。' },
      { icon: '⏰', title: '期限と次のステップ', desc: '異議申し立ての期限、提出すべき書類、日付を見逃さないよう明確なリストにします。' },
    ],
    jargon: {
      label: '例', title: '役所のドイツ語、翻訳済み',
      pairs: [
        ['Bescheid', '保険組合の公式決定'],
        ['Zuzahlung', 'あなた自身が支払う分'],
        ['Widerspruch', '決定に異議を申し立てる権利'],
        ['Bewilligung', '保険組合が費用を負担すること'],
        ['MD-Gutachten', '医療サービスによる審査'],
        ['Satzungsleistung', 'あなたの保険組合だけが提供する特典'],
      ],
    },
    faqTitle: 'よくある質問',
    faq: [
      { q: 'どんな手紙をアップロードできますか？', a: '決定通知、却下通知、自己負担・保険料の手紙、医療補助具、リハビリ、傷病手当に関する手紙を、法定または民間の健康保険から受け取ったものとしてアップロードできます。' },
      { q: 'Medyraは却下された場合に役立ちますか？', a: 'Medyraは何が却下されたか、なぜか、どの異議申し立て期限が適用されるかを説明します。保険組合への適切な質問も得られます。法律相談の代わりにはなりません。' },
      { q: 'Medyraは民間保険も理解しますか？', a: 'はい。PKVの手紙、Beihilfeの決定、請求書の払い戻しも認識され、分かりやすく説明されます。' },
      { q: '私のデータは安全ですか？', a: 'はい。暗号化処理、GDPRに準拠したフランクフルトでのホスティング、30日後の自動削除（希望すれば即時）。' },
    ],
    ctaTitle: '二度と期限を見逃さない',
    ctaSub: '月3件の文書が無料。GDPR準拠、暗号化、自動削除。',
    ctaButton: '保険の手紙を説明する',
    ctaNote: 'Medyraは法律相談や社会福祉相談の代わりにはなりません。',
  },

  ko: {
    headerTitle: '건강보험 편지 이해하기', headerCta: '편지 업로드',
    badge: '결정 · 거부 · 본인 부담금',
    h1a: '보험 편지에서', h1b: '관공서 용어 없이',
    sub: '독일 건강보험사의 편지는 그야말로 관료주의 그 자체입니다. Medyra는 편지에 무엇이 쓰여 있는지, 비용이 얼마인지, 놓치면 안 되는 기한이 언제인지 쉬운 언어로 알려드립니다. 60초 이내에.',
    cta: '지금 보험 편지 업로드하기',
    mock: {
      labelIn: '편지 내용', quote: QUOTE, labelOut: 'Medyra 설명',
      lines: [
        '보험사는 비용을 전액이 아닌 일부만 부담합니다.',
        '이의 신청(Widerspruch)을 위해 정확히 1개월의 시간이 있습니다.',
        '정확한 근거를 요청하세요, 이는 이의 신청을 강화합니다.',
      ],
    },
    cardsLabel: '받게 되는 것', cardsTitle: '모든 결정 통지를 명확하게 설명',
    cards: [
      { icon: '📬', title: '편지 내용', desc: '승인, 거부, 보험료 통지 또는 환급 요청: Medyra는 편지 유형을 인식하고 내용을 두 문장으로 요약합니다.' },
      { icon: '💶', title: '지불해야 할 비용', desc: '본인 부담금, 자기 부담분, 환급액 및 보험료 변경 사항을 편지의 모든 금액과 함께 명확하게 분류합니다.' },
      { icon: '⏰', title: '기한 및 다음 단계', desc: '이의 신청 기한, 제출해야 할 서류 및 날짜를 놓치지 않도록 명확한 목록으로 제공합니다.' },
    ],
    jargon: {
      label: '예시', title: '관공서 독일어, 번역됨',
      pairs: [
        ['Bescheid', '보험사의 공식 결정'],
        ['Zuzahlung', '본인이 직접 지불하는 부분'],
        ['Widerspruch', '결정에 이의를 제기할 권리'],
        ['Bewilligung', '보험사가 비용을 부담함'],
        ['MD-Gutachten', '의료 서비스의 심사'],
        ['Satzungsleistung', '해당 보험사만 제공하는 추가 혜택'],
      ],
    },
    faqTitle: '자주 묻는 질문',
    faq: [
      { q: '어떤 편지를 업로드할 수 있나요?', a: '결정 통지, 거부 통지, 본인 부담금 및 보험료 편지, 보조기구, 재활 또는 상병수당에 관한 편지를 법정 또는 민간 건강보험에서 받은 것으로 업로드할 수 있습니다.' },
      { q: 'Medyra가 거부 통지에 도움이 되나요?', a: 'Medyra는 무엇이 거부되었는지, 왜 거부되었는지, 어떤 이의 신청 기한이 적용되는지 설명합니다. 보험사에 물어볼 적절한 질문도 제공됩니다. 법률 상담을 대체하지는 않습니다.' },
      { q: 'Medyra가 민간 보험도 이해하나요?', a: '네. PKV 편지, Beihilfe 결정, 청구서 환급도 인식되어 명확하게 설명됩니다.' },
      { q: '제 데이터는 안전한가요?', a: '네. 암호화된 처리, GDPR을 준수하는 프랑크푸르트 호스팅, 30일 후 자동 삭제(요청 시 즉시 삭제).' },
    ],
    ctaTitle: '다시는 기한을 놓치지 마세요',
    ctaSub: '월 3건 문서 무료. GDPR 준수, 암호화, 자동 삭제.',
    ctaButton: '보험 편지 설명받기',
    ctaNote: 'Medyra는 법률 또는 사회 상담을 대체하지 않습니다.',
  },

  hi: {
    headerTitle: 'स्वास्थ्य बीमा पत्र समझें', headerCta: 'पत्र अपलोड करें',
    badge: 'निर्णय · अस्वीकृति · सह-भुगतान',
    h1a: 'बीमा पत्र बिना', h1b: 'सरकारी जर्मन भाषा के',
    sub: 'जर्मन स्वास्थ्य बीमा कंपनियों के पत्र शुद्ध रूप से नौकरशाही होते हैं। Medyra आपको सरल भाषा में बताता है कि पत्र में क्या लिखा है, इसकी लागत क्या है और कौन सी समय सीमा आपको नहीं चूकनी चाहिए। 60 सेकंड से भी कम समय में।',
    cta: 'अभी अपना बीमा पत्र अपलोड करें',
    mock: {
      labelIn: 'पत्र में लिखा है', quote: QUOTE, labelOut: 'Medyra समझाता है',
      lines: [
        'बीमा कंपनी लागत का केवल कुछ हिस्सा वहन करती है, पूरा नहीं।',
        'आपके पास आपत्ति (Widerspruch) दर्ज करने के लिए ठीक 1 महीने का समय है।',
        'सटीक कारण पूछें, यह आपकी आपत्ति को मजबूत करता है।',
      ],
    },
    cardsLabel: 'आपको क्या मिलता है', cardsTitle: 'हर निर्णय, स्पष्ट रूप से समझाया गया',
    cards: [
      { icon: '📬', title: 'पत्र में क्या कहा गया है', desc: 'मंजूरी, अस्वीकृति, अंशदान सूचना या प्रतिपूर्ति अनुरोध: Medyra पत्र के प्रकार को पहचानता है और सामग्री को दो वाक्यों में सारांशित करता है।' },
      { icon: '💶', title: 'आपको कितना खर्च आएगा', desc: 'सह-भुगतान, स्वयं का हिस्सा, प्रतिपूर्ति और अंशदान परिवर्तन, पत्र की सभी राशियों के साथ स्पष्ट रूप से विभाजित।' },
      { icon: '⏰', title: 'समय सीमाएं और अगले कदम', desc: 'आपत्ति की समय सीमाएं, जमा करने योग्य दस्तावेज़ और तारीखें एक स्पष्ट सूची के रूप में ताकि कुछ भी न छूटे।' },
    ],
    jargon: {
      label: 'उदाहरण', title: 'सरकारी जर्मन, अनुवादित',
      pairs: [
        ['Bescheid', 'बीमा कंपनी का आधिकारिक निर्णय'],
        ['Zuzahlung', 'वह हिस्सा जो आप स्वयं भुगतान करते हैं'],
        ['Widerspruch', 'निर्णय को चुनौती देने का आपका अधिकार'],
        ['Bewilligung', 'बीमा कंपनी लागत वहन करती है'],
        ['MD-Gutachten', 'चिकित्सा सेवा द्वारा समीक्षा'],
        ['Satzungsleistung', 'एक अतिरिक्त लाभ जो केवल आपकी बीमा कंपनी देती है'],
      ],
    },
    faqTitle: 'सामान्य प्रश्न',
    faq: [
      { q: 'मैं कौन से पत्र अपलोड कर सकता हूं?', a: 'किसी भी सांविधिक या निजी स्वास्थ्य बीमा से निर्णय, अस्वीकृति, सह-भुगतान और अंशदान पत्र, चिकित्सा सहायता, पुनर्वास या बीमार वेतन के बारे में पत्र।' },
      { q: 'क्या Medyra अस्वीकृति में मदद करता है?', a: 'Medyra बताता है कि क्या अस्वीकृत किया गया, क्यों, और कौन सी आपत्ति समय सीमा लागू होती है। आपको अपनी बीमा कंपनी के लिए उपयुक्त सवाल भी मिलते हैं। यह कानूनी सलाह का विकल्प नहीं है।' },
      { q: 'क्या Medyra निजी बीमा को भी समझता है?', a: 'हां। PKV पत्र, Beihilfe निर्णय और बिल प्रतिपूर्ति को पहचाना और स्पष्ट रूप से समझाया जाता है।' },
      { q: 'क्या मेरा डेटा सुरक्षित है?', a: 'हां। एन्क्रिप्टेड प्रोसेसिंग, GDPR के अनुरूप फ्रैंकफर्ट में होस्टिंग, 30 दिनों के बाद स्वचालित रूप से हटाना (अनुरोध पर तुरंत)।' },
    ],
    ctaTitle: 'फिर कभी कोई समय सीमा न चूकें',
    ctaSub: 'हर महीने 3 दस्तावेज़ मुफ़्त। GDPR अनुरूप, एन्क्रिप्टेड, स्वचालित रूप से हटाया गया।',
    ctaButton: 'मेरा बीमा पत्र समझाएं',
    ctaNote: 'Medyra कानूनी या सामाजिक परामर्श का विकल्प नहीं है।',
  },

  bn: {
    headerTitle: 'স্বাস্থ্য বীমার চিঠি বুঝুন', headerCta: 'চিঠি আপলোড করুন',
    badge: 'সিদ্ধান্ত · প্রত্যাখ্যান · সহ-প্রদান',
    h1a: 'বীমা চিঠি ছাড়া', h1b: 'সরকারি জার্মান ভাষা',
    sub: 'জার্মান স্বাস্থ্য বীমা কোম্পানির চিঠি খাঁটি আমলাতন্ত্র। Medyra আপনাকে সহজ ভাষায় বলে দেয় চিঠিতে কী লেখা আছে, এর খরচ কত এবং কোন সময়সীমা আপনার মিস করা উচিত নয়। ৬০ সেকেন্ডেরও কম সময়ে।',
    cta: 'এখনই আপনার বীমা চিঠি আপলোড করুন',
    mock: {
      labelIn: 'চিঠিতে লেখা আছে', quote: QUOTE, labelOut: 'Medyra ব্যাখ্যা করে',
      lines: [
        'বীমা কোম্পানি খরচের শুধুমাত্র একটি অংশ বহন করে, সম্পূর্ণ নয়।',
        'আপত্তি (Widerspruch) দাখিল করার জন্য আপনার কাছে ঠিক ১ মাস সময় আছে।',
        'সঠিক কারণ জিজ্ঞাসা করুন, এটি আপনার আপত্তিকে শক্তিশালী করে।',
      ],
    },
    cardsLabel: 'আপনি যা পাবেন', cardsTitle: 'প্রতিটি সিদ্ধান্ত, স্পষ্টভাবে ব্যাখ্যা করা',
    cards: [
      { icon: '📬', title: 'চিঠিতে কী বলা হয়েছে', desc: 'অনুমোদন, প্রত্যাখ্যান, অবদানের বিজ্ঞপ্তি বা প্রতিদান অনুরোধ: Medyra চিঠির ধরন চিনতে পারে এবং বিষয়বস্তু দুই বাক্যে সংক্ষিপ্ত করে।' },
      { icon: '💶', title: 'আপনার কত খরচ হবে', desc: 'সহ-প্রদান, নিজস্ব অংশ, প্রতিদান এবং অবদানের পরিবর্তন, চিঠির সমস্ত পরিমাণসহ স্পষ্টভাবে বিভক্ত।' },
      { icon: '⏰', title: 'সময়সীমা এবং পরবর্তী পদক্ষেপ', desc: 'আপত্তির সময়সীমা, জমা দেওয়ার নথি এবং তারিখ একটি স্পষ্ট তালিকা হিসেবে যাতে কিছুই বাদ না যায়।' },
    ],
    jargon: {
      label: 'উদাহরণ', title: 'সরকারি জার্মান, অনূদিত',
      pairs: [
        ['Bescheid', 'বীমা কোম্পানির সরকারি সিদ্ধান্ত'],
        ['Zuzahlung', 'যে অংশ আপনি নিজে পরিশোধ করেন'],
        ['Widerspruch', 'সিদ্ধান্তকে চ্যালেঞ্জ করার আপনার অধিকার'],
        ['Bewilligung', 'বীমা কোম্পানি খরচ বহন করে'],
        ['MD-Gutachten', 'মেডিকেল সার্ভিস দ্বারা পর্যালোচনা'],
        ['Satzungsleistung', 'একটি অতিরিক্ত সুবিধা যা শুধুমাত্র আপনার বীমা কোম্পানি দেয়'],
      ],
    },
    faqTitle: 'সাধারণ প্রশ্ন',
    faq: [
      { q: 'আমি কোন কোন চিঠি আপলোড করতে পারি?', a: 'যেকোনো সংবিধিবদ্ধ বা বেসরকারি স্বাস্থ্য বীমা থেকে সিদ্ধান্ত, প্রত্যাখ্যান, সহ-প্রদান ও অবদান সংক্রান্ত চিঠি, চিকিৎসা সহায়ক, পুনর্বাসন বা অসুস্থতা ভাতা সংক্রান্ত চিঠি।' },
      { q: 'Medyra কি প্রত্যাখ্যানে সাহায্য করে?', a: 'Medyra ব্যাখ্যা করে কী প্রত্যাখ্যান করা হয়েছে, কেন, এবং কোন আপত্তির সময়সীমা প্রযোজ্য। আপনি আপনার বীমা কোম্পানির জন্য উপযুক্ত প্রশ্নও পাবেন। এটি আইনি পরামর্শের বিকল্প নয়।' },
      { q: 'Medyra কি বেসরকারি বীমাও বোঝে?', a: 'হ্যাঁ। PKV চিঠি, Beihilfe সিদ্ধান্ত এবং বিল প্রতিদান চেনা যায় এবং স্পষ্টভাবে ব্যাখ্যা করা হয়।' },
      { q: 'আমার তথ্য কি নিরাপদ?', a: 'হ্যাঁ। এনক্রিপ্ট করা প্রক্রিয়াকরণ, GDPR সম্মত ফ্রাঙ্কফুর্ট হোস্টিং, ৩০ দিন পর স্বয়ংক্রিয় মুছে ফেলা (অনুরোধে তাৎক্ষণিক)।' },
    ],
    ctaTitle: 'আর কখনো কোনো সময়সীমা মিস করবেন না',
    ctaSub: 'মাসে ৩টি নথি বিনামূল্যে। GDPR সম্মত, এনক্রিপ্টেড, স্বয়ংক্রিয়ভাবে মুছে ফেলা।',
    ctaButton: 'আমার বীমা চিঠি ব্যাখ্যা করুন',
    ctaNote: 'Medyra আইনি বা সামাজিক পরামর্শের বিকল্প নয়।',
  },

  ur: {
    headerTitle: 'ہیلتھ انشورنس کے خطوط سمجھیں', headerCta: 'خط اپ لوڈ کریں',
    badge: 'فیصلہ · مسترد · شریک ادائیگی',
    h1a: 'انشورنس کے خطوط بغیر', h1b: 'سرکاری جرمن زبان کے',
    sub: 'جرمن ہیلتھ انشورنس کمپنیوں کے خطوط خالص بیوروکریسی ہیں۔ Medyra آپ کو آسان زبان میں بتاتا ہے کہ خط میں کیا لکھا ہے، اس کی لاگت کیا ہے اور کون سی آخری تاریخ آپ کو مس نہیں کرنی چاہیے۔ 60 سیکنڈ سے بھی کم وقت میں۔',
    cta: 'ابھی اپنا انشورنس خط اپ لوڈ کریں',
    mock: {
      labelIn: 'خط میں لکھا ہے', quote: QUOTE, labelOut: 'Medyra وضاحت کرتا ہے',
      lines: [
        'انشورنس کمپنی صرف جزوی طور پر لاگت برداشت کرتی ہے، مکمل طور پر نہیں۔',
        'اعتراض (Widerspruch) درج کرنے کے لیے آپ کے پاس بالکل 1 مہینہ ہے۔',
        'صحیح وجہ پوچھیں، یہ آپ کے اعتراض کو مضبوط کرتا ہے۔',
      ],
    },
    cardsLabel: 'آپ کو کیا ملتا ہے', cardsTitle: 'ہر فیصلہ، واضح طور پر بیان کیا گیا',
    cards: [
      { icon: '📬', title: 'خط میں کیا کہا گیا ہے', desc: 'منظوری، مسترد، تعاون کا نوٹس یا واپسی کی درخواست: Medyra خط کی قسم کو پہچانتا ہے اور مواد کو دو جملوں میں خلاصہ کرتا ہے۔' },
      { icon: '💶', title: 'آپ کو کتنا خرچہ آئے گا', desc: 'شریک ادائیگیاں، اپنا حصہ، واپسی اور تعاون میں تبدیلیاں، خط کی تمام رقوم کے ساتھ واضح طور پر تقسیم کی گئیں۔' },
      { icon: '⏰', title: 'آخری تاریخیں اور اگلے اقدامات', desc: 'اعتراض کی آخری تاریخیں، جمع کرانے والی دستاویزات اور تاریخیں ایک واضح فہرست کی صورت میں تاکہ کچھ بھی مس نہ ہو۔' },
    ],
    jargon: {
      label: 'مثالیں', title: 'سرکاری جرمن، ترجمہ شدہ',
      pairs: [
        ['Bescheid', 'انشورنس کمپنی کا سرکاری فیصلہ'],
        ['Zuzahlung', 'وہ حصہ جو آپ خود ادا کرتے ہیں'],
        ['Widerspruch', 'فیصلے کو چیلنج کرنے کا آپ کا حق'],
        ['Bewilligung', 'انشورنس کمپنی لاگت برداشت کرتی ہے'],
        ['MD-Gutachten', 'میڈیکل سروس کی طرف سے جائزہ'],
        ['Satzungsleistung', 'ایک اضافی سہولت جو صرف آپ کی انشورنس کمپنی دیتی ہے'],
      ],
    },
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faq: [
      { q: 'میں کون سے خطوط اپ لوڈ کر سکتا ہوں؟', a: 'کسی بھی قانونی یا نجی ہیلتھ انشورنس سے فیصلے، مسترد، شریک ادائیگی اور تعاون کے خطوط، طبی امدادی آلات، بحالی یا بیماری کی تنخواہ کے بارے میں خطوط۔' },
      { q: 'کیا Medyra مسترد ہونے کی صورت میں مدد کرتا ہے؟', a: 'Medyra وضاحت کرتا ہے کہ کیا مسترد کیا گیا، کیوں، اور کون سی اعتراض کی آخری تاریخ لاگو ہوتی ہے۔ آپ کو اپنی انشورنس کمپنی کے لیے موزوں سوالات بھی ملتے ہیں۔ یہ قانونی مشورے کا متبادل نہیں ہے۔' },
      { q: 'کیا Medyra نجی انشورنس کو بھی سمجھتا ہے؟', a: 'جی ہاں۔ PKV خطوط، Beihilfe فیصلے اور بل کی واپسی کو پہچانا اور واضح طور پر بیان کیا جاتا ہے۔' },
      { q: 'کیا میرا ڈیٹا محفوظ ہے؟', a: 'جی ہاں۔ خفیہ کاری کے ساتھ پروسیسنگ، GDPR کے مطابق فرینکفرٹ میں ہوسٹنگ، 30 دن بعد خودکار حذف (درخواست پر فوری)۔' },
    ],
    ctaTitle: 'دوبارہ کبھی کوئی آخری تاریخ مس نہ کریں',
    ctaSub: 'ماہانہ 3 دستاویزات مفت۔ GDPR کے مطابق، خفیہ کاری، خودکار حذف۔',
    ctaButton: 'میرا انشورنس خط سمجھائیں',
    ctaNote: 'Medyra قانونی یا سماجی مشورے کا متبادل نہیں ہے۔',
  },
}
