// Localized UI strings for /check. German is the SEO base; unlisted
// languages fall back to English. The interactive checker itself localizes
// separately via next-intl (valueChecker.* keys, all 17 languages).
export const CONTENT = {
  de: {
    headerTitle: 'Laborwert-Checker', headerCta: 'Befund hochladen', back: 'Start',
    badge: 'Kostenlos · Ohne Anmeldung',
    h1a: 'Ist Ihr Laborwert', h1b: 'normal?',
    sub: 'Wert auswählen, Zahl eintippen, sofort sehen, ob er im Referenzbereich liegt. Mit verständlicher Erklärung und möglichen Ursachen.',
    privacy: 'Ihre Eingaben werden nicht gespeichert und nicht übertragen. Die Prüfung läuft direkt in Ihrem Browser.',
    valuesLabel: 'Alle Werte', valuesTitle: 'Laborwerte, einfach erklärt',
    upsellTitle: 'Ein Wert ist nur die halbe Wahrheit',
    upsellText: 'Laborwerte hängen zusammen: Ein niedriges Ferritin erklärt oft ein niedriges Hämoglobin. Laden Sie Ihren kompletten Befund hoch und Medyra erklärt alle Werte im Zusammenhang, in unter 60 Sekunden.',
    upsellCta: 'Ganzen Befund erklären lassen',
    upsellNote: '3 Befunde pro Monat kostenlos · DSGVO-konform · Daten automatisch gelöscht',
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Ist der Laborwert-Checker kostenlos?', a: 'Ja. Der Checker ist komplett kostenlos und ohne Anmeldung nutzbar. Ihre Eingaben werden nicht gespeichert.' },
      { q: 'Welche Blutwerte kann ich prüfen?', a: 'Über 40 gängige Laborwerte: Blutbild (Hämoglobin, Leukozyten, Thrombozyten), Schilddrüse (TSH, FT3, FT4), Stoffwechsel (HbA1c, Cholesterin, LDL, HDL), Entzündung (CRP, BSG), Eisen (Ferritin, Transferrin), Leber, Niere, Elektrolyte und mehr.' },
      { q: 'Woher stammen die Referenzwerte?', a: 'Die Referenzbereiche entsprechen gängigen Laborstandards für Erwachsene. Ihr Labor kann leicht abweichende Bereiche verwenden. Maßgeblich ist immer der Referenzbereich auf Ihrem Befund.' },
      { q: 'Ersetzt der Checker einen Arztbesuch?', a: 'Nein. Der Checker ordnet Werte nur allgemein ein und ist keine medizinische Beratung. Besprechen Sie auffällige Werte immer mit Ihrer Ärztin oder Ihrem Arzt.' },
    ],
    disclaimer: 'Der Laborwert-Checker dient ausschließlich der allgemeinen Information und ersetzt keine ärztliche Beratung, Diagnose oder Behandlung.',
  },
  en: {
    headerTitle: 'Lab Value Checker', headerCta: 'Upload report', back: 'Home',
    badge: 'Free · No signup',
    h1a: 'Is your lab value', h1b: 'normal?',
    sub: 'Pick a value, type your number, and see instantly whether it is in the reference range. With a plain language explanation and possible causes.',
    privacy: 'Your input is not stored and not transmitted. The check runs directly in your browser.',
    valuesLabel: 'All values', valuesTitle: 'Lab values, simply explained',
    upsellTitle: 'One value is only half the truth',
    upsellText: 'Lab values are connected: a low ferritin often explains a low hemoglobin. Upload your complete report and Medyra explains all values in context, in under 60 seconds.',
    upsellCta: 'Explain my full report',
    upsellNote: '3 reports per month free · GDPR compliant · data deleted automatically',
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'Is the lab value checker free?', a: 'Yes. The checker is completely free and works without signup. Your input is not stored.' },
      { q: 'Which blood values can I check?', a: 'Over 40 common lab values: blood count (hemoglobin, leukocytes, platelets), thyroid (TSH, FT3, FT4), metabolism (HbA1c, cholesterol, LDL, HDL), inflammation (CRP, ESR), iron (ferritin, transferrin), liver, kidney, electrolytes and more.' },
      { q: 'Where do the reference ranges come from?', a: 'The ranges follow common lab standards for adults. Your lab may use slightly different ranges. The range on your own report always applies.' },
      { q: 'Does the checker replace a doctor visit?', a: 'No. The checker only classifies values in general terms and is not medical advice. Always discuss abnormal values with your doctor.' },
    ],
    disclaimer: 'The lab value checker is for general information only and does not replace medical advice, diagnosis or treatment.',
  },
  tr: {
    headerTitle: 'Tahlil Değeri Kontrolü', headerCta: 'Rapor yükle', back: 'Ana sayfa',
    badge: 'Ücretsiz · Kayıt gerekmez',
    h1a: 'Tahlil değeriniz', h1b: 'normal mi?',
    sub: 'Değeri seçin, sayınızı yazın ve referans aralığında olup olmadığını anında görün. Anlaşılır açıklama ve olası nedenlerle birlikte.',
    privacy: 'Girdileriniz kaydedilmez ve iletilmez. Kontrol doğrudan tarayıcınızda çalışır.',
    valuesLabel: 'Tüm değerler', valuesTitle: 'Tahlil değerleri, basitçe açıklanmış',
    upsellTitle: 'Tek değer gerçeğin yalnızca yarısıdır',
    upsellText: 'Tahlil değerleri birbirine bağlıdır: düşük ferritin çoğu zaman düşük hemoglobini açıklar. Tam raporunuzu yükleyin, Medyra tüm değerleri bağlam içinde açıklasın; 60 saniyeden kısa sürede.',
    upsellCta: 'Tüm raporumu açıkla',
    upsellNote: 'Ayda 3 rapor ücretsiz · GDPR uyumlu · veriler otomatik silinir',
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Tahlil değeri kontrolü ücretsiz mi?', a: 'Evet. Tamamen ücretsizdir ve kayıt gerektirmez. Girdileriniz kaydedilmez.' },
      { q: 'Hangi kan değerlerini kontrol edebilirim?', a: '40’tan fazla yaygın değer: kan sayımı (hemoglobin, lökosit, trombosit), tiroid (TSH, FT3, FT4), metabolizma (HbA1c, kolesterol, LDL, HDL), iltihap (CRP, sedimantasyon), demir (ferritin, transferrin), karaciğer, böbrek, elektrolitler ve daha fazlası.' },
      { q: 'Referans aralıkları nereden geliyor?', a: 'Aralıklar yetişkinler için yaygın laboratuvar standartlarına uygundur. Laboratuvarınız biraz farklı aralıklar kullanabilir. Her zaman kendi raporunuzdaki aralık geçerlidir.' },
      { q: 'Kontrol doktor ziyaretinin yerine geçer mi?', a: 'Hayır. Kontrol değerleri yalnızca genel olarak sınıflandırır ve tıbbi tavsiye değildir. Anormal değerleri her zaman doktorunuzla görüşün.' },
    ],
    disclaimer: 'Tahlil değeri kontrolü yalnızca genel bilgilendirme içindir; tıbbi danışmanlık, tanı veya tedavinin yerini tutmaz.',
  },
  ar: {
    headerTitle: 'فاحص قيم التحاليل', headerCta: 'ارفع التقرير', back: 'الرئيسية',
    badge: 'مجاني · بدون تسجيل',
    h1a: 'هل قيمة تحليلك', h1b: 'طبيعية؟',
    sub: 'اختر القيمة، أدخل رقمك، وشاهد فوراً إن كانت ضمن النطاق المرجعي. مع شرح مبسط وأسباب محتملة.',
    privacy: 'مدخلاتك لا تُخزن ولا تُرسل. يتم الفحص مباشرة في متصفحك.',
    valuesLabel: 'كل القيم', valuesTitle: 'قيم التحاليل، بشرح مبسط',
    upsellTitle: 'قيمة واحدة نصف الحقيقة فقط',
    upsellText: 'قيم التحاليل مترابطة: انخفاض الفيريتين يفسر غالباً انخفاض الهيموغلوبين. ارفع تقريرك الكامل وسيشرح Medyra كل القيم في سياقها، في أقل من 60 ثانية.',
    upsellCta: 'اشرح تقريري الكامل',
    upsellNote: '3 تقارير شهرياً مجاناً · متوافق مع GDPR · تُحذف البيانات تلقائياً',
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'هل فاحص القيم مجاني؟', a: 'نعم. الفاحص مجاني تماماً ويعمل بدون تسجيل. مدخلاتك لا تُخزن.' },
      { q: 'ما قيم الدم التي يمكنني فحصها؟', a: 'أكثر من 40 قيمة شائعة: تعداد الدم (هيموغلوبين، كريات بيضاء، صفائح)، الغدة الدرقية (TSH, FT3, FT4)، الأيض (HbA1c، كوليسترول، LDL, HDL)، الالتهاب (CRP)، الحديد (فيريتين، ترانسفيرين)، الكبد والكلى والكهارل وغيرها.' },
      { q: 'من أين تأتي النطاقات المرجعية؟', a: 'النطاقات تتبع المعايير المخبرية الشائعة للبالغين. قد يستخدم مختبرك نطاقات مختلفة قليلاً. النطاق في تقريرك هو المعتمد دائماً.' },
      { q: 'هل يغني الفاحص عن زيارة الطبيب؟', a: 'لا. الفاحص يصنف القيم بشكل عام فقط وليس نصيحة طبية. ناقش القيم غير الطبيعية دائماً مع طبيبك.' },
    ],
    disclaimer: 'فاحص قيم التحاليل للمعلومات العامة فقط ولا يحل محل الاستشارة الطبية أو التشخيص أو العلاج.',
  },
  ru: {
    headerTitle: 'Проверка показателей', headerCta: 'Загрузить анализ', back: 'Главная',
    badge: 'Бесплатно · Без регистрации',
    h1a: 'Ваш показатель', h1b: 'в норме?',
    sub: 'Выберите показатель, введите число и сразу увидите, в референсном ли он диапазоне. С понятным объяснением и возможными причинами.',
    privacy: 'Ваши данные не сохраняются и не передаются. Проверка выполняется прямо в браузере.',
    valuesLabel: 'Все показатели', valuesTitle: 'Лабораторные показатели, просто объяснённые',
    upsellTitle: 'Один показатель это лишь половина правды',
    upsellText: 'Показатели связаны между собой: низкий ферритин часто объясняет низкий гемоглобин. Загрузите весь анализ, и Medyra объяснит все значения в контексте, меньше чем за 60 секунд.',
    upsellCta: 'Объяснить весь мой анализ',
    upsellNote: '3 анализа в месяц бесплатно · GDPR · данные удаляются автоматически',
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Проверка показателей бесплатна?', a: 'Да. Полностью бесплатно и без регистрации. Ваши данные не сохраняются.' },
      { q: 'Какие показатели крови можно проверить?', a: 'Более 40 распространённых показателей: общий анализ крови (гемоглобин, лейкоциты, тромбоциты), щитовидная железа (TSH, FT3, FT4), обмен веществ (HbA1c, холестерин, LDL, HDL), воспаление (CRP, СОЭ), железо (ферритин, трансферрин), печень, почки, электролиты и другие.' },
      { q: 'Откуда берутся референсные диапазоны?', a: 'Диапазоны соответствуют распространённым лабораторным стандартам для взрослых. Ваша лаборатория может использовать немного другие. Всегда действителен диапазон в вашем бланке.' },
      { q: 'Заменяет ли проверка визит к врачу?', a: 'Нет. Проверка лишь в общих чертах классифицирует значения и не является медицинской консультацией. Всегда обсуждайте отклонения с врачом.' },
    ],
    disclaimer: 'Проверка показателей служит только для общей информации и не заменяет медицинскую консультацию, диагностику или лечение.',
  },
}
