// Localized UI strings for /check. German is the SEO base; unlisted
// languages fall back to English. The interactive checker itself localizes
// separately via next-intl (valueChecker.* keys, all 17 languages).
export const CONTENT = {
  de: {
    headerTitle: 'Laborwert-Checker', headerCta: 'Befund hochladen', back: 'Start',
    badge: 'Kostenlos · Ohne Anmeldung',
    h1a: 'Ist Ihr Laborwert', h1b: 'normal?',
    sub: 'Wert auswählen, Zahl eintippen, sofort sehen, ob er im Referenzbereich liegt. Mit verständlicher Erklärung und möglichen Ursachen.',
    privacy: 'Ihre Eingaben werden nicht gespeichert und nicht übertragen. Die Prüfung läuft direkt in Ihrem Browser.',
    valuesLabel: 'Alle Werte', valuesTitle: 'Laborwerte, einfach erklärt',
    upsellTitle: 'Ein Wert ist nur die halbe Wahrheit',
    upsellText: 'Laborwerte hängen zusammen: Ein niedriges Ferritin erklärt oft ein niedriges Hämoglobin. Laden Sie Ihren kompletten Befund hoch und Medyra erklärt alle Werte im Zusammenhang, in unter 60 Sekunden.',
    upsellCta: 'Ganzen Befund erklären lassen',
    upsellNote: '3 Befunde pro Monat kostenlos · DSGVO-konform · Daten automatisch gelöscht',
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Ist der Laborwert-Checker kostenlos?', a: 'Ja. Der Checker ist komplett kostenlos und ohne Anmeldung nutzbar. Ihre Eingaben werden nicht gespeichert.' },
      { q: 'Welche Blutwerte kann ich prüfen?', a: 'Über 40 gängige Laborwerte: Blutbild (Hämoglobin, Leukozyten, Thrombozyten), Schilddrüse (TSH, FT3, FT4), Stoffwechsel (HbA1c, Cholesterin, LDL, HDL), Entzündung (CRP, BSG), Eisen (Ferritin, Transferrin), Leber, Niere, Elektrolyte und mehr.' },
      { q: 'Woher stammen die Referenzwerte?', a: 'Die Referenzbereiche entsprechen gängigen Laborstandards für Erwachsene. Ihr Labor kann leicht abweichende Bereiche verwenden. Maßgeblich ist immer der Referenzbereich auf Ihrem Befund.' },
      { q: 'Ersetzt der Checker einen Arztbesuch?', a: 'Nein. Der Checker ordnet Werte nur allgemein ein und ist keine medizinische Beratung. Besprechen Sie auffällige Werte immer mit Ihrer Ärztin oder Ihrem Arzt.' },
    ],
    disclaimer: 'Der Laborwert-Checker dient ausschließlich der allgemeinen Information und ersetzt keine ärztliche Beratung, Diagnose oder Behandlung.',
  },
  en: {
    headerTitle: 'Lab Value Checker', headerCta: 'Upload report', back: 'Home',
    badge: 'Free · No signup',
    h1a: 'Is your lab value', h1b: 'normal?',
    sub: 'Pick a value, type your number, and see instantly whether it is in the reference range. With a plain language explanation and possible causes.',
    privacy: 'Your input is not stored and not transmitted. The check runs directly in your browser.',
    valuesLabel: 'All values', valuesTitle: 'Lab values, simply explained',
    upsellTitle: 'One value is only half the truth',
    upsellText: 'Lab values are connected: a low ferritin often explains a low hemoglobin. Upload your complete report and Medyra explains all values in context, in under 60 seconds.',
    upsellCta: 'Explain my full report',
    upsellNote: '3 reports per month free · GDPR compliant · data deleted automatically',
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'Is the lab value checker free?', a: 'Yes. The checker is completely free and works without signup. Your input is not stored.' },
      { q: 'Which blood values can I check?', a: 'Over 40 common lab values: blood count (hemoglobin, leukocytes, platelets), thyroid (TSH, FT3, FT4), metabolism (HbA1c, cholesterol, LDL, HDL), inflammation (CRP, ESR), iron (ferritin, transferrin), liver, kidney, electrolytes and more.' },
      { q: 'Where do the reference ranges come from?', a: 'The ranges follow common lab standards for adults. Your lab may use slightly different ranges. The range on your own report always applies.' },
      { q: 'Does the checker replace a doctor visit?', a: 'No. The checker only classifies values in general terms and is not medical advice. Always discuss abnormal values with your doctor.' },
    ],
    disclaimer: 'The lab value checker is for general information only and does not replace medical advice, diagnosis or treatment.',
  },
  tr: {
    headerTitle: 'Tahlil Değeri Kontrolü', headerCta: 'Rapor yükle', back: 'Ana sayfa',
    badge: 'Ücretsiz · Kayıt gerekmez',
    h1a: 'Tahlil değeriniz', h1b: 'normal mi?',
    sub: 'Değeri seçin, sayınızı yazın ve referans aralığında olup olmadığını anında görün. Anlaşılır açıklama ve olası nedenlerle birlikte.',
    privacy: 'Girdileriniz kaydedilmez ve iletilmez. Kontrol doğrudan tarayıcınızda çalışır.',
    valuesLabel: 'Tüm değerler', valuesTitle: 'Tahlil değerleri, basitçe açıklanmış',
    upsellTitle: 'Tek değer gerçeğin yalnızca yarısıdır',
    upsellText: 'Tahlil değerleri birbirine bağlıdır: düşük ferritin çoğu zaman düşük hemoglobini açıklar. Tam raporunuzu yükleyin, Medyra tüm değerleri bağlam içinde açıklasın; 60 saniyeden kısa sürede.',
    upsellCta: 'Tüm raporumu açıkla',
    upsellNote: 'Ayda 3 rapor ücretsiz · GDPR uyumlu · veriler otomatik silinir',
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Tahlil değeri kontrolü ücretsiz mi?', a: 'Evet. Tamamen ücretsizdir ve kayıt gerektirmez. Girdileriniz kaydedilmez.' },
      { q: 'Hangi kan değerlerini kontrol edebilirim?', a: '40’tan fazla yaygın değer: kan sayımı (hemoglobin, lökosit, trombosit), tiroid (TSH, FT3, FT4), metabolizma (HbA1c, kolesterol, LDL, HDL), iltihap (CRP, sedimantasyon), demir (ferritin, transferrin), karaciğer, böbrek, elektrolitler ve daha fazlası.' },
      { q: 'Referans aralıkları nereden geliyor?', a: 'Aralıklar yetişkinler için yaygın laboratuvar standartlarına uygundur. Laboratuvarınız biraz farklı aralıklar kullanabilir. Her zaman kendi raporunuzdaki aralık geçerlidir.' },
      { q: 'Kontrol doktor ziyaretinin yerine geçer mi?', a: 'Hayır. Kontrol değerleri yalnızca genel olarak sınıflandırır ve tıbbi tavsiye değildir. Anormal değerleri her zaman doktorunuzla görüşün.' },
    ],
    disclaimer: 'Tahlil değeri kontrolü yalnızca genel bilgilendirme içindir; tıbbi danışmanlık, tanı veya tedavinin yerini tutmaz.',
  },
  ar: {
    headerTitle: 'فاحص قيم التحاليل', headerCta: 'ارفع التقرير', back: 'الرئيسية',
    badge: 'مجاني · بدون تسجيل',
    h1a: 'هل قيمة تحليلك', h1b: 'طبيعية؟',
    sub: 'اختر القيمة، أدخل رقمك، وشاهد فوراً إن كانت ضمن النطاق المرجعي. مع شرح مبسط وأسباب محتملة.',
    privacy: 'مدخلاتك لا تُخزن ولا تُرسل. يتم الفحص مباشرة في متصفحك.',
    valuesLabel: 'كل القيم', valuesTitle: 'قيم التحاليل، بشرح مبسط',
    upsellTitle: 'قيمة واحدة نصف الحقيقة فقط',
    upsellText: 'قيم التحاليل مترابطة: انخفاض الفيريتين يفسر غالباً انخفاض الهيموغلوبين. ارفع تقريرك الكامل وسيشرح Medyra كل القيم في سياقها، في أقل من 60 ثانية.',
    upsellCta: 'اشرح تقريري الكامل',
    upsellNote: '3 تقارير شهرياً مجاناً · متوافق مع GDPR · تُحذف البيانات تلقائياً',
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'هل فاحص القيم مجاني؟', a: 'نعم. الفاحص مجاني تماماً ويعمل بدون تسجيل. مدخلاتك لا تُخزن.' },
      { q: 'ما قيم الدم التي يمكنني فحصها؟', a: 'أكثر من 40 قيمة شائعة: تعداد الدم (هيموغلوبين، كريات بيضاء، صفائح)، الغدة الدرقية (TSH, FT3, FT4)، الأيض (HbA1c، كوليسترول، LDL, HDL)، الالتهاب (CRP)، الحديد (فيريتين، ترانسفيرين)، الكبد والكلى والكهارل وغيرها.' },
      { q: 'من أين تأتي النطاقات المرجعية؟', a: 'النطاقات تتبع المعايير المخبرية الشائعة للبالغين. قد يستخدم مختبرك نطاقات مختلفة قليلاً. النطاق في تقريرك هو المعتمد دائماً.' },
      { q: 'هل يغني الفاحص عن زيارة الطبيب؟', a: 'لا. الفاحص يصنف القيم بشكل عام فقط وليس نصيحة طبية. ناقش القيم غير الطبيعية دائماً مع طبيبك.' },
    ],
    disclaimer: 'فاحص قيم التحاليل للمعلومات العامة فقط ولا يحل محل الاستشارة الطبية أو التشخيص أو العلاج.',
  },
  ru: {
    headerTitle: 'Проверка показателей', headerCta: 'Загрузить анализ', back: 'Главная',
    badge: 'Бесплатно · Без регистрации',
    h1a: 'Ваш показатель', h1b: 'в норме?',
    sub: 'Выберите показатель, введите число и сразу увидите, в референсном ли он диапазоне. С понятным объяснением и возможными причинами.',
    privacy: 'Ваши данные не сохраняются и не передаются. Проверка выполняется прямо в браузере.',
    valuesLabel: 'Все показатели', valuesTitle: 'Лабораторные показатели, просто объяснённые',
    upsellTitle: 'Один показатель это лишь половина правды',
    upsellText: 'Показатели связаны между собой: низкий ферритин часто объясняет низкий гемоглобин. Загрузите весь анализ, и Medyra объяснит все значения в контексте, меньше чем за 60 секунд.',
    upsellCta: 'Объяснить весь мой анализ',
    upsellNote: '3 анализа в месяц бесплатно · GDPR · данные удаляются автоматически',
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Проверка показателей бесплатна?', a: 'Да. Полностью бесплатно и без регистрации. Ваши данные не сохраняются.' },
      { q: 'Какие показатели крови можно проверить?', a: 'Более 40 распространённых показателей: общий анализ крови (гемоглобин, лейкоциты, тромбоциты), щитовидная железа (TSH, FT3, FT4), обмен веществ (HbA1c, холестерин, LDL, HDL), воспаление (CRP, СОЭ), железо (ферритин, трансферрин), печень, почки, электролиты и другие.' },
      { q: 'Откуда берутся референсные диапазоны?', a: 'Диапазоны соответствуют распространённым лабораторным стандартам для взрослых. Ваша лаборатория может использовать немного другие. Всегда действителен диапазон в вашем бланке.' },
      { q: 'Заменяет ли проверка визит к врачу?', a: 'Нет. Проверка лишь в общих чертах классифицирует значения и не является медицинской консультацией. Всегда обсуждайте отклонения с врачом.' },
    ],
    disclaimer: 'Проверка показателей служит только для общей информации и не заменяет медицинскую консультацию, диагностику или лечение.',
  },
  fr: {
    headerTitle: 'Vérificateur de valeurs de laboratoire', headerCta: 'Télécharger le rapport', back: 'Accueil',
    badge: 'Gratuit · Sans inscription',
    h1a: 'Votre valeur de laboratoire', h1b: 'est-elle normale ?',
    sub: 'Choisissez une valeur, saisissez votre chiffre et voyez instantanément si elle est dans la plage de référence. Avec une explication claire et les causes possibles.',
    privacy: 'Vos données ne sont ni enregistrées ni transmises. La vérification s’effectue directement dans votre navigateur.',
    valuesLabel: 'Toutes les valeurs', valuesTitle: 'Valeurs de laboratoire, simplement expliquées',
    upsellTitle: 'Une seule valeur ne dit que la moitié de la vérité',
    upsellText: 'Les valeurs de laboratoire sont liées entre elles : une ferritine basse explique souvent une hémoglobine basse. Téléchargez votre rapport complet et Medyra explique toutes les valeurs en contexte, en moins de 60 secondes.',
    upsellCta: 'Expliquer tout mon rapport',
    upsellNote: '3 rapports par mois gratuits · conforme au RGPD · données supprimées automatiquement',
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'Le vérificateur de valeurs est-il gratuit ?', a: 'Oui. Il est entièrement gratuit et fonctionne sans inscription. Vos données ne sont pas enregistrées.' },
      { q: 'Quelles valeurs sanguines puis-je vérifier ?', a: 'Plus de 40 valeurs courantes : numération sanguine (hémoglobine, leucocytes, plaquettes), thyroïde (TSH, FT3, FT4), métabolisme (HbA1c, cholestérol, LDL, HDL), inflammation (CRP, VS), fer (ferritine, transferrine), foie, rein, électrolytes et plus.' },
      { q: 'D’où viennent les plages de référence ?', a: 'Les plages suivent les normes de laboratoire courantes pour adultes. Votre laboratoire peut utiliser des plages légèrement différentes. La plage indiquée sur votre propre rapport fait toujours foi.' },
      { q: 'Le vérificateur remplace-t-il une visite chez le médecin ?', a: 'Non. Le vérificateur ne fait que classer les valeurs en termes généraux et ne constitue pas un avis médical. Discutez toujours des valeurs anormales avec votre médecin.' },
    ],
    disclaimer: 'Le vérificateur de valeurs de laboratoire est fourni à titre informatif uniquement et ne remplace pas un avis médical, un diagnostic ou un traitement.',
  },
  es: {
    headerTitle: 'Verificador de valores de laboratorio', headerCta: 'Subir informe', back: 'Inicio',
    badge: 'Gratis · Sin registro',
    h1a: '¿Su valor de laboratorio', h1b: 'es normal?',
    sub: 'Elija un valor, escriba su número y vea al instante si está dentro del rango de referencia. Con una explicación clara y posibles causas.',
    privacy: 'Sus datos no se almacenan ni se transmiten. La verificación se realiza directamente en su navegador.',
    valuesLabel: 'Todos los valores', valuesTitle: 'Valores de laboratorio, explicados de forma sencilla',
    upsellTitle: 'Un solo valor es solo la mitad de la verdad',
    upsellText: 'Los valores de laboratorio están conectados: una ferritina baja a menudo explica una hemoglobina baja. Suba su informe completo y Medyra explica todos los valores en contexto, en menos de 60 segundos.',
    upsellCta: 'Explicar todo mi informe',
    upsellNote: '3 informes al mes gratis · conforme al RGPD · datos eliminados automáticamente',
    faqTitle: 'Preguntas frecuentes',
    faq: [
      { q: '¿Es gratuito el verificador de valores?', a: 'Sí. Es completamente gratuito y funciona sin registro. Sus datos no se almacenan.' },
      { q: '¿Qué valores sanguíneos puedo verificar?', a: 'Más de 40 valores comunes: hemograma (hemoglobina, leucocitos, plaquetas), tiroides (TSH, FT3, FT4), metabolismo (HbA1c, colesterol, LDL, HDL), inflamación (PCR, VSG), hierro (ferritina, transferrina), hígado, riñón, electrolitos y más.' },
      { q: '¿De dónde vienen los rangos de referencia?', a: 'Los rangos siguen estándares de laboratorio comunes para adultos. Su laboratorio puede usar rangos ligeramente diferentes. El rango de su propio informe siempre es el que aplica.' },
      { q: '¿El verificador sustituye una visita al médico?', a: 'No. El verificador solo clasifica valores en términos generales y no es un consejo médico. Comente siempre los valores anómalos con su médico.' },
    ],
    disclaimer: 'El verificador de valores de laboratorio es solo para información general y no sustituye el consejo médico, el diagnóstico o el tratamiento.',
  },
  it: {
    headerTitle: 'Verificatore di valori di laboratorio', headerCta: 'Carica il referto', back: 'Home',
    badge: 'Gratis · Senza registrazione',
    h1a: 'Il tuo valore di laboratorio', h1b: 'è normale?',
    sub: 'Scegli un valore, digita il tuo numero e scopri subito se rientra nell’intervallo di riferimento. Con una spiegazione semplice e possibili cause.',
    privacy: 'I tuoi dati non vengono salvati né trasmessi. Il controllo avviene direttamente nel tuo browser.',
    valuesLabel: 'Tutti i valori', valuesTitle: 'Valori di laboratorio, spiegati in modo semplice',
    upsellTitle: 'Un solo valore è solo metà della verità',
    upsellText: 'I valori di laboratorio sono collegati tra loro: una ferritina bassa spesso spiega un’emoglobina bassa. Carica il tuo referto completo e Medyra spiega tutti i valori nel contesto, in meno di 60 secondi.',
    upsellCta: 'Spiega tutto il mio referto',
    upsellNote: '3 referti al mese gratis · conforme al GDPR · dati eliminati automaticamente',
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'Il verificatore di valori è gratuito?', a: 'Sì. È completamente gratuito e funziona senza registrazione. I tuoi dati non vengono salvati.' },
      { q: 'Quali valori del sangue posso verificare?', a: 'Oltre 40 valori comuni: emocromo (emoglobina, leucociti, piastrine), tiroide (TSH, FT3, FT4), metabolismo (HbA1c, colesterolo, LDL, HDL), infiammazione (PCR, VES), ferro (ferritina, transferrina), fegato, rene, elettroliti e altro.' },
      { q: 'Da dove provengono gli intervalli di riferimento?', a: 'Gli intervalli seguono gli standard di laboratorio comuni per gli adulti. Il tuo laboratorio potrebbe usare intervalli leggermente diversi. Vale sempre l’intervallo del tuo referto.' },
      { q: 'Il verificatore sostituisce una visita medica?', a: 'No. Il verificatore classifica i valori solo in termini generali e non è un consiglio medico. Discuti sempre i valori anomali con il tuo medico.' },
    ],
    disclaimer: 'Il verificatore di valori di laboratorio è solo a scopo informativo generale e non sostituisce il consiglio medico, la diagnosi o la terapia.',
  },
  pt: {
    headerTitle: 'Verificador de valores laboratoriais', headerCta: 'Enviar relatório', back: 'Início',
    badge: 'Grátis · Sem cadastro',
    h1a: 'Seu valor laboratorial', h1b: 'está normal?',
    sub: 'Escolha um valor, digite seu número e veja instantaneamente se está dentro da faixa de referência. Com explicação clara e possíveis causas.',
    privacy: 'Seus dados não são armazenados nem transmitidos. A verificação ocorre diretamente no seu navegador.',
    valuesLabel: 'Todos os valores', valuesTitle: 'Valores laboratoriais, explicados de forma simples',
    upsellTitle: 'Um único valor é apenas metade da verdade',
    upsellText: 'Os valores laboratoriais estão conectados: uma ferritina baixa geralmente explica uma hemoglobina baixa. Envie seu relatório completo e a Medyra explica todos os valores em contexto, em menos de 60 segundos.',
    upsellCta: 'Explicar todo o meu relatório',
    upsellNote: '3 relatórios por mês grátis · conforme o RGPD · dados excluídos automaticamente',
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'O verificador de valores é gratuito?', a: 'Sim. É totalmente gratuito e funciona sem cadastro. Seus dados não são armazenados.' },
      { q: 'Quais valores sanguíneos posso verificar?', a: 'Mais de 40 valores comuns: hemograma (hemoglobina, leucócitos, plaquetas), tireoide (TSH, FT3, FT4), metabolismo (HbA1c, colesterol, LDL, HDL), inflamação (PCR, VHS), ferro (ferritina, transferrina), fígado, rim, eletrólitos e mais.' },
      { q: 'De onde vêm as faixas de referência?', a: 'As faixas seguem padrões laboratoriais comuns para adultos. Seu laboratório pode usar faixas ligeiramente diferentes. A faixa do seu próprio relatório sempre prevalece.' },
      { q: 'O verificador substitui uma consulta médica?', a: 'Não. O verificador apenas classifica valores em termos gerais e não é aconselhamento médico. Sempre discuta valores anormais com seu médico.' },
    ],
    disclaimer: 'O verificador de valores laboratoriais é apenas para informação geral e não substitui o aconselhamento médico, diagnóstico ou tratamento.',
  },
  nl: {
    headerTitle: 'Labwaarde-checker', headerCta: 'Rapport uploaden', back: 'Home',
    badge: 'Gratis · Geen registratie',
    h1a: 'Is uw labwaarde', h1b: 'normaal?',
    sub: 'Kies een waarde, typ uw getal in en zie direct of deze binnen het referentiebereik valt. Met duidelijke uitleg en mogelijke oorzaken.',
    privacy: 'Uw invoer wordt niet opgeslagen en niet verzonden. De controle vindt direct in uw browser plaats.',
    valuesLabel: 'Alle waarden', valuesTitle: 'Labwaarden, eenvoudig uitgelegd',
    upsellTitle: 'Eén waarde is slechts het halve verhaal',
    upsellText: 'Labwaarden hangen samen: een lage ferritine verklaart vaak een laag hemoglobine. Upload uw volledige rapport en Medyra legt alle waarden in samenhang uit, in minder dan 60 seconden.',
    upsellCta: 'Leg mijn hele rapport uit',
    upsellNote: '3 rapporten per maand gratis · AVG-conform · gegevens automatisch verwijderd',
    faqTitle: 'Veelgestelde vragen',
    faq: [
      { q: 'Is de labwaarde-checker gratis?', a: 'Ja. De checker is volledig gratis en werkt zonder registratie. Uw invoer wordt niet opgeslagen.' },
      { q: 'Welke bloedwaarden kan ik controleren?', a: 'Meer dan 40 veelvoorkomende waarden: bloedbeeld (hemoglobine, leukocyten, trombocyten), schildklier (TSH, FT3, FT4), stofwisseling (HbA1c, cholesterol, LDL, HDL), ontsteking (CRP, BSE), ijzer (ferritine, transferrine), lever, nier, elektrolyten en meer.' },
      { q: 'Waar komen de referentiewaarden vandaan?', a: 'De bereiken volgen gangbare laboratoriumnormen voor volwassenen. Uw laboratorium kan iets afwijkende bereiken gebruiken. Het bereik op uw eigen rapport is altijd leidend.' },
      { q: 'Vervangt de checker een doktersbezoek?', a: 'Nee. De checker classificeert waarden alleen in algemene termen en is geen medisch advies. Bespreek afwijkende waarden altijd met uw arts.' },
    ],
    disclaimer: 'De labwaarde-checker is uitsluitend bedoeld voor algemene informatie en vervangt geen medisch advies, diagnose of behandeling.',
  },
  pl: {
    headerTitle: 'Sprawdzarka wyników laboratoryjnych', headerCta: 'Prześlij wynik', back: 'Start',
    badge: 'Bezpłatne · Bez rejestracji',
    h1a: 'Czy twój wynik badania', h1b: 'jest prawidłowy?',
    sub: 'Wybierz wartość, wpisz swoją liczbę i od razu zobacz, czy mieści się w zakresie referencyjnym. Z jasnym wyjaśnieniem i możliwymi przyczynami.',
    privacy: 'Twoje dane nie są zapisywane ani przesyłane. Sprawdzenie odbywa się bezpośrednio w twojej przeglądarce.',
    valuesLabel: 'Wszystkie wartości', valuesTitle: 'Wyniki laboratoryjne, prosto wyjaśnione',
    upsellTitle: 'Jedna wartość to tylko połowa prawdy',
    upsellText: 'Wyniki laboratoryjne są ze sobą powiązane: niska ferrytyna często wyjaśnia niską hemoglobinę. Prześlij pełny wynik, a Medyra wyjaśni wszystkie wartości w kontekście, w mniej niż 60 sekund.',
    upsellCta: 'Wyjaśnij cały mój wynik',
    upsellNote: '3 dokumenty miesięcznie za darmo · zgodność z RODO · dane usuwane automatycznie',
    faqTitle: 'Najczęstsze pytania',
    faq: [
      { q: 'Czy sprawdzarka wartości jest bezpłatna?', a: 'Tak. Jest całkowicie bezpłatna i działa bez rejestracji. Twoje dane nie są zapisywane.' },
      { q: 'Jakie wartości krwi mogę sprawdzić?', a: 'Ponad 40 popularnych wartości: morfologia (hemoglobina, leukocyty, płytki krwi), tarczyca (TSH, FT3, FT4), metabolizm (HbA1c, cholesterol, LDL, HDL), stan zapalny (CRP, OB), żelazo (ferrytyna, transferyna), wątroba, nerki, elektrolity i więcej.' },
      { q: 'Skąd pochodzą zakresy referencyjne?', a: 'Zakresy odpowiadają powszechnym standardom laboratoryjnym dla dorosłych. Twoje laboratorium może stosować nieco inne zakresy. Zawsze obowiązuje zakres podany na twoim wyniku.' },
      { q: 'Czy sprawdzarka zastępuje wizytę u lekarza?', a: 'Nie. Sprawdzarka jedynie ogólnie klasyfikuje wartości i nie stanowi porady medycznej. Nieprawidłowe wartości zawsze omawiaj z lekarzem.' },
    ],
    disclaimer: 'Sprawdzarka wyników laboratoryjnych służy wyłącznie celom informacyjnym i nie zastępuje porady medycznej, diagnozy ani leczenia.',
  },
  zh: {
    headerTitle: '化验值检测工具', headerCta: '上传报告', back: '首页',
    badge: '免费 · 无需注册',
    h1a: '您的化验值', h1b: '正常吗？',
    sub: '选择一个数值，输入您的数字，立即查看是否在参考范围内。附带通俗易懂的解释和可能的原因。',
    privacy: '您的输入不会被存储或传输。检测直接在您的浏览器中运行。',
    valuesLabel: '所有数值', valuesTitle: '化验值，简单解释',
    upsellTitle: '单一数值只是真相的一半',
    upsellText: '化验值之间是相互关联的：铁蛋白偏低往往能解释血红蛋白偏低的原因。上传您的完整报告，Medyra会在不到60秒内结合背景解释所有数值。',
    upsellCta: '解释我的完整报告',
    upsellNote: '每月3份文件免费 · 符合GDPR · 数据自动删除',
    faqTitle: '常见问题',
    faq: [
      { q: '化验值检测工具是免费的吗？', a: '是的。该工具完全免费，无需注册即可使用。您的输入不会被存储。' },
      { q: '我可以检测哪些血液指标？', a: '超过40种常见指标：血常规（血红蛋白、白细胞、血小板）、甲状腺（TSH、FT3、FT4）、代谢（HbA1c、胆固醇、LDL、HDL）、炎症（CRP、血沉）、铁（铁蛋白、转铁蛋白）、肝脏、肾脏、电解质等。' },
      { q: '参考范围来自哪里？', a: '参考范围遵循成人常见的实验室标准。您所在的实验室可能使用略有不同的范围。您自己报告上的范围始终适用。' },
      { q: '该工具能代替就医吗？', a: '不能。该工具仅对数值进行大致分类，不构成医疗建议。请始终与您的医生讨论异常数值。' },
    ],
    disclaimer: '化验值检测工具仅供一般信息参考，不能替代医疗建议、诊断或治疗。',
  },
  ja: {
    headerTitle: '検査値チェッカー', headerCta: '報告書をアップロード', back: 'ホーム',
    badge: '無料・登録不要',
    h1a: 'あなたの検査値は', h1b: '正常ですか？',
    sub: '数値を選んで自分の値を入力すると、基準範囲内かどうかがすぐにわかります。分かりやすい説明と考えられる原因付きです。',
    privacy: '入力内容は保存も送信もされません。チェックはブラウザ内で直接行われます。',
    valuesLabel: 'すべての数値', valuesTitle: '検査値を分かりやすく解説',
    upsellTitle: '1つの数値だけでは真実の半分しか分かりません',
    upsellText: '検査値は互いに関連しています：フェリチン値が低いと、多くの場合ヘモグロビン値が低い理由が説明できます。完全な報告書をアップロードすれば、Medyraがすべての数値を背景とともに60秒以内に説明します。',
    upsellCta: '報告書全体を説明する',
    upsellNote: '月3件の文書が無料・GDPR準拠・データは自動削除',
    faqTitle: 'よくある質問',
    faq: [
      { q: '検査値チェッカーは無料ですか？', a: 'はい。完全に無料で、登録なしでご利用いただけます。入力内容は保存されません。' },
      { q: 'どの血液値をチェックできますか？', a: '40種類以上の一般的な値：血球算定（ヘモグロビン、白血球、血小板）、甲状腺（TSH、FT3、FT4）、代謝（HbA1c、コレステロール、LDL、HDL）、炎症（CRP、赤沈）、鉄（フェリチン、トランスフェリン）、肝臓、腎臓、電解質など。' },
      { q: '基準範囲はどこから来ていますか？', a: '基準範囲は成人向けの一般的な検査基準に基づいています。検査機関によって若干異なる範囲を使用することがあります。ご自身の報告書に記載された範囲が常に適用されます。' },
      { q: 'このチェッカーは受診の代わりになりますか？', a: 'いいえ。このチェッカーは数値を一般的に分類するだけで、医療アドバイスではありません。異常な値については必ず医師に相談してください。' },
    ],
    disclaimer: '検査値チェッカーは一般的な情報提供のみを目的としており、医療アドバイス、診断、治療の代わりにはなりません。',
  },
  ko: {
    headerTitle: '검사 수치 확인기', headerCta: '보고서 업로드', back: '홈',
    badge: '무료 · 가입 불필요',
    h1a: '당신의 검사 수치가', h1b: '정상인가요?',
    sub: '수치를 선택하고 숫자를 입력하면 기준 범위 내에 있는지 즉시 확인할 수 있습니다. 쉬운 설명과 가능한 원인도 함께 제공됩니다.',
    privacy: '입력한 내용은 저장되거나 전송되지 않습니다. 확인은 브라우저에서 직접 실행됩니다.',
    valuesLabel: '모든 수치', valuesTitle: '검사 수치를 쉽게 설명',
    upsellTitle: '하나의 수치는 진실의 절반일 뿐입니다',
    upsellText: '검사 수치는 서로 연결되어 있습니다: 낮은 페리틴 수치는 종종 낮은 헤모글로빈 수치를 설명해줍니다. 전체 보고서를 업로드하면 Medyra가 60초 이내에 모든 수치를 맥락과 함께 설명합니다.',
    upsellCta: '전체 보고서 설명받기',
    upsellNote: '월 3건 문서 무료 · GDPR 준수 · 데이터 자동 삭제',
    faqTitle: '자주 묻는 질문',
    faq: [
      { q: '검사 수치 확인기는 무료인가요?', a: '네. 완전히 무료이며 가입 없이 사용할 수 있습니다. 입력한 내용은 저장되지 않습니다.' },
      { q: '어떤 혈액 수치를 확인할 수 있나요?', a: '40개 이상의 일반적인 수치: 혈구 수(헤모글로빈, 백혈구, 혈소판), 갑상선(TSH, FT3, FT4), 대사(HbA1c, 콜레스테롤, LDL, HDL), 염증(CRP, ESR), 철분(페리틴, 트랜스페린), 간, 신장, 전해질 등.' },
      { q: '기준 범위는 어디서 나온 건가요?', a: '범위는 성인을 위한 일반적인 검사 기준을 따릅니다. 검사기관에 따라 약간 다른 범위를 사용할 수 있습니다. 항상 본인의 보고서에 있는 범위가 적용됩니다.' },
      { q: '이 확인기가 병원 방문을 대신할 수 있나요?', a: '아니요. 이 확인기는 수치를 일반적으로 분류할 뿐이며 의료 조언이 아닙니다. 비정상 수치는 항상 의사와 상의하세요.' },
    ],
    disclaimer: '검사 수치 확인기는 일반 정보 제공 목적으로만 사용되며 의료 조언, 진단 또는 치료를 대체하지 않습니다.',
  },
  hi: {
    headerTitle: 'लैब वैल्यू चेकर', headerCta: 'रिपोर्ट अपलोड करें', back: 'होम',
    badge: 'मुफ़्त · बिना साइनअप',
    h1a: 'क्या आपका लैब वैल्यू', h1b: 'सामान्य है?',
    sub: 'एक वैल्यू चुनें, अपना नंबर टाइप करें, और तुरंत देखें कि यह संदर्भ सीमा में है या नहीं। सरल भाषा में स्पष्टीकरण और संभावित कारणों के साथ।',
    privacy: 'आपका इनपुट सहेजा या भेजा नहीं जाता। जांच सीधे आपके ब्राउज़र में होती है।',
    valuesLabel: 'सभी वैल्यू', valuesTitle: 'लैब वैल्यू, सरलता से समझाई गई',
    upsellTitle: 'एक वैल्यू केवल आधा सच बताती है',
    upsellText: 'लैब वैल्यू आपस में जुड़ी होती हैं: कम फेरिटिन अक्सर कम हीमोग्लोबिन की वजह बताता है। अपनी पूरी रिपोर्ट अपलोड करें और Medyra 60 सेकंड से भी कम समय में सभी वैल्यू को संदर्भ सहित समझाएगा।',
    upsellCta: 'मेरी पूरी रिपोर्ट समझाएं',
    upsellNote: 'हर महीने 3 दस्तावेज़ मुफ़्त · GDPR अनुरूप · डेटा स्वचालित रूप से हटाया गया',
    faqTitle: 'सामान्य प्रश्न',
    faq: [
      { q: 'क्या लैब वैल्यू चेकर मुफ़्त है?', a: 'हां। चेकर पूरी तरह मुफ़्त है और बिना साइनअप के काम करता है। आपका इनपुट सहेजा नहीं जाता।' },
      { q: 'मैं कौन से रक्त मूल्यों की जांच कर सकता हूं?', a: '40 से अधिक सामान्य मूल्य: रक्त गणना (हीमोग्लोबिन, ल्यूकोसाइट्स, प्लेटलेट्स), थायरॉइड (TSH, FT3, FT4), मेटाबॉलिज्म (HbA1c, कोलेस्ट्रॉल, LDL, HDL), सूजन (CRP, ESR), आयरन (फेरिटिन, ट्रांसफेरिन), लीवर, किडनी, इलेक्ट्रोलाइट्स और अधिक।' },
      { q: 'संदर्भ सीमाएं कहां से आती हैं?', a: 'सीमाएं वयस्कों के लिए सामान्य प्रयोगशाला मानकों का पालन करती हैं। आपकी प्रयोगशाला थोड़ी अलग सीमाएं उपयोग कर सकती है। हमेशा आपकी अपनी रिपोर्ट पर दी गई सीमा लागू होती है।' },
      { q: 'क्या चेकर डॉक्टर की मुलाकात का विकल्प है?', a: 'नहीं। चेकर केवल सामान्य रूप से वैल्यू को वर्गीकृत करता है और यह चिकित्सा सलाह नहीं है। असामान्य वैल्यू पर हमेशा अपने डॉक्टर से चर्चा करें।' },
    ],
    disclaimer: 'लैब वैल्यू चेकर केवल सामान्य जानकारी के लिए है और चिकित्सा सलाह, निदान या उपचार का विकल्प नहीं है।',
  },
  bn: {
    headerTitle: 'ল্যাব ভ্যালু চেকার', headerCta: 'রিপোর্ট আপলোড করুন', back: 'হোম',
    badge: 'বিনামূল্যে · সাইনআপ ছাড়াই',
    h1a: 'আপনার ল্যাব ভ্যালু কি', h1b: 'স্বাভাবিক?',
    sub: 'একটি ভ্যালু বেছে নিন, আপনার সংখ্যা টাইপ করুন, এবং সাথে সাথে দেখুন এটি রেফারেন্স রেঞ্জের মধ্যে আছে কিনা। সহজ ভাষায় ব্যাখ্যা এবং সম্ভাব্য কারণসহ।',
    privacy: 'আপনার ইনপুট সংরক্ষণ বা প্রেরণ করা হয় না। পরীক্ষাটি সরাসরি আপনার ব্রাউজারে চলে।',
    valuesLabel: 'সব ভ্যালু', valuesTitle: 'ল্যাব ভ্যালু, সহজভাবে ব্যাখ্যা করা',
    upsellTitle: 'একটি ভ্যালু শুধু অর্ধেক সত্য বলে',
    upsellText: 'ল্যাব ভ্যালুগুলি একে অপরের সাথে সংযুক্ত: কম ফেরিটিন প্রায়ই কম হিমোগ্লোবিনের কারণ ব্যাখ্যা করে। আপনার সম্পূর্ণ রিপোর্ট আপলোড করুন এবং Medyra ৬০ সেকেন্ডেরও কম সময়ে সমস্ত ভ্যালু প্রেক্ষাপটসহ ব্যাখ্যা করবে।',
    upsellCta: 'আমার সম্পূর্ণ রিপোর্ট ব্যাখ্যা করুন',
    upsellNote: 'মাসে ৩টি নথি বিনামূল্যে · GDPR সম্মত · তথ্য স্বয়ংক্রিয়ভাবে মুছে ফেলা',
    faqTitle: 'সাধারণ প্রশ্ন',
    faq: [
      { q: 'ল্যাব ভ্যালু চেকার কি বিনামূল্যে?', a: 'হ্যাঁ। চেকারটি সম্পূর্ণ বিনামূল্যে এবং সাইনআপ ছাড়াই কাজ করে। আপনার ইনপুট সংরক্ষণ করা হয় না।' },
      { q: 'আমি কোন রক্তের মান পরীক্ষা করতে পারি?', a: '৪০টিরও বেশি সাধারণ মান: রক্ত গণনা (হিমোগ্লোবিন, লিউকোসাইট, প্লেটলেট), থাইরয়েড (TSH, FT3, FT4), বিপাক (HbA1c, কোলেস্টেরল, LDL, HDL), প্রদাহ (CRP, ESR), আয়রন (ফেরিটিন, ট্রান্সফেরিন), লিভার, কিডনি, ইলেক্ট্রোলাইট এবং আরও অনেক কিছু।' },
      { q: 'রেফারেন্স রেঞ্জ কোথা থেকে আসে?', a: 'রেঞ্জগুলি প্রাপ্তবয়স্কদের জন্য সাধারণ ল্যাব মান অনুসরণ করে। আপনার ল্যাব সামান্য ভিন্ন রেঞ্জ ব্যবহার করতে পারে। আপনার নিজের রিপোর্টের রেঞ্জ সবসময় প্রযোজ্য।' },
      { q: 'চেকার কি ডাক্তারের সাক্ষাতের বিকল্প?', a: 'না। চেকার শুধুমাত্র সাধারণভাবে মান শ্রেণীবদ্ধ করে এবং এটি চিকিৎসা পরামর্শ নয়। অস্বাভাবিক মান নিয়ে সবসময় আপনার ডাক্তারের সাথে আলোচনা করুন।' },
    ],
    disclaimer: 'ল্যাব ভ্যালু চেকার শুধুমাত্র সাধারণ তথ্যের জন্য এবং এটি চিকিৎসা পরামর্শ, নির্ণয় বা চিকিৎসার বিকল্প নয়।',
  },
  ur: {
    headerTitle: 'لیب ویلیو چیکر', headerCta: 'رپورٹ اپ لوڈ کریں', back: 'ہوم',
    badge: 'مفت · بغیر سائن اپ',
    h1a: 'کیا آپ کی لیب ویلیو', h1b: 'نارمل ہے؟',
    sub: 'ایک ویلیو منتخب کریں، اپنا نمبر ٹائپ کریں، اور فوری طور پر دیکھیں کہ یہ حوالہ جاتی حد میں ہے یا نہیں۔ آسان وضاحت اور ممکنہ وجوہات کے ساتھ۔',
    privacy: 'آپ کا ان پٹ محفوظ یا منتقل نہیں کیا جاتا۔ چیک براہ راست آپ کے براؤزر میں چلتا ہے۔',
    valuesLabel: 'تمام اقدار', valuesTitle: 'لیب ویلیوز، آسانی سے بیان کی گئیں',
    upsellTitle: 'ایک ویلیو صرف آدھی حقیقت بتاتی ہے',
    upsellText: 'لیب ویلیوز آپس میں جڑی ہوتی ہیں: کم فیریٹن اکثر کم ہیموگلوبن کی وجہ بتاتا ہے۔ اپنی مکمل رپورٹ اپ لوڈ کریں اور Medyra 60 سیکنڈ سے بھی کم وقت میں تمام اقدار کو سیاق و سباق کے ساتھ بیان کرے گا۔',
    upsellCta: 'میری مکمل رپورٹ کی وضاحت کریں',
    upsellNote: 'ماہانہ 3 دستاویزات مفت · GDPR کے مطابق · ڈیٹا خودکار طور پر حذف',
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faq: [
      { q: 'کیا لیب ویلیو چیکر مفت ہے؟', a: 'جی ہاں۔ چیکر مکمل طور پر مفت ہے اور بغیر سائن اپ کے کام کرتا ہے۔ آپ کا ان پٹ محفوظ نہیں کیا جاتا۔' },
      { q: 'میں کون سی خون کی اقدار چیک کر سکتا ہوں؟', a: '40 سے زیادہ عام اقدار: خون کا شمار (ہیموگلوبن، لیوکوسائٹس، پلیٹلیٹس)، تھائیرائیڈ (TSH، FT3، FT4)، میٹابولزم (HbA1c، کولیسٹرول، LDL، HDL)، سوزش (CRP، ESR)، آئرن (فیریٹن، ٹرانسفیرین)، جگر، گردے، الیکٹرولائٹس اور مزید۔' },
      { q: 'حوالہ جاتی حدیں کہاں سے آتی ہیں؟', a: 'حدیں بالغوں کے لیے عام لیبارٹری معیارات کی پیروی کرتی ہیں۔ آپ کی لیبارٹری قدرے مختلف حدیں استعمال کر سکتی ہے۔ ہمیشہ آپ کی اپنی رپورٹ پر دی گئی حد لاگو ہوتی ہے۔' },
      { q: 'کیا چیکر ڈاکٹر کے دورے کا متبادل ہے؟', a: 'نہیں۔ چیکر صرف عمومی طور پر اقدار کی درجہ بندی کرتا ہے اور یہ طبی مشورہ نہیں ہے۔ غیر معمولی اقدار پر ہمیشہ اپنے ڈاکٹر سے بات کریں۔' },
    ],
    disclaimer: 'لیب ویلیو چیکر صرف عمومی معلومات کے لیے ہے اور طبی مشورے، تشخیص یا علاج کا متبادل نہیں ہے۔',
  },
}
