// Localized content for /arztbrief. German is the SEO base; unlisted
// languages fall back to English. German document quotes and jargon terms
// stay German everywhere: that is what patients hold in their hands.
const QUOTE = '"V. a. degenerative Veränderungen der LWS mit medialer Diskusprotrusion L4/5 ohne Nachweis einer höhergradigen Spinalkanalstenose."'

export const CONTENT = {
  de: {
    headerTitle: 'Arztbrief verstehen',
    headerCta: 'Arztbrief hochladen',
    badge: 'Arztbrief · Entlassungsbericht · MRT-Befund',
    h1a: 'Ihr Arztbrief,',
    h1b: 'endlich verständlich',
    sub: 'Fachbegriffe, Abkürzungen, lateinische Diagnosen: Medyra übersetzt jeden Satz Ihres Befundes in klare Sprache und sagt Ihnen, welche Fragen Sie Ihrer Ärztin stellen sollten. In unter 60 Sekunden.',
    cta: 'Jetzt Arztbrief hochladen',
    mock: {
      labelIn: 'Im Befund steht', quote: QUOTE, labelOut: 'Medyra erklärt',
      lines: [
        'Verdacht auf Verschleiß an der Lendenwirbelsäule, das ist ab dem mittleren Alter sehr häufig.',
        'Eine Bandscheibe zwischen dem 4. und 5. Lendenwirbel wölbt sich leicht vor.',
        'Der Nervenkanal ist nicht stark eingeengt, das ist eine gute Nachricht.',
      ],
    },
    cardsLabel: 'Für jedes Dokument',
    cardsTitle: 'Mehr als nur Laborwerte',
    cards: [
      { icon: '📋', title: 'Arztbrief & Entlassungsbericht', desc: 'Diagnosen, Therapieempfehlungen und Medikationsänderungen aus dem Krankenhaus oder von der Fachärztin, Absatz für Absatz erklärt.' },
      { icon: '🩻', title: 'Radiologie-Befund (MRT, CT, Röntgen)', desc: 'Was bedeutet "unauffällige Raumforderung" oder "degenerative Veränderung"? Jeder Fachbegriff wird übersetzt, ruhig und ohne Panik.' },
      { icon: '🔬', title: 'Pathologie & Laborbefund', desc: 'Gewebebefunde und Laborwerte im Zusammenhang: was gemessen wurde, was auffällig ist und welche Fragen Sie stellen sollten.' },
    ],
    jargon: {
      label: 'Beispiele', title: 'Arzt-Deutsch, übersetzt', sub: 'So klingt Ihr Befund, nachdem Medyra ihn erklärt hat.',
      pairs: [
        ['idiopathisch', 'ohne erkennbare Ursache'],
        ['Adhärenz', 'wie zuverlässig Sie die Therapie einhalten'],
        ['unauffällig', 'alles in Ordnung, kein krankhafter Befund'],
        ['Raumforderung', 'etwas, das Platz einnimmt, muss nicht bösartig sein'],
        ['degenerativ', 'verschleißbedingt, meist altersbedingt'],
        ['V. a.', 'Verdacht auf, noch keine gesicherte Diagnose'],
      ],
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Welche Dokumente kann ich hochladen?', a: 'Arztbriefe, Entlassungsberichte, Radiologie-Befunde (MRT, CT, Röntgen, Ultraschall), Pathologie-Befunde, Laborbefunde und Krankenkassen-Schreiben, als PDF, Foto oder Text.' },
      { q: 'Stellt Medyra Diagnosen?', a: 'Nein. Medyra erklärt, was in Ihrem Dokument steht, in verständlicher Sprache. Diagnose und Therapie gehören in ärztliche Hände. Medyra schlägt Ihnen passende Fragen für das Arztgespräch vor.' },
      { q: 'Was passiert mit meinen Daten?', a: 'Ihre Dokumente werden verschlüsselt verarbeitet, DSGVO-konform in Frankfurt gehostet und standardmäßig nach 30 Tagen automatisch gelöscht.' },
      { q: 'Versteht Medyra auch handschriftliche oder fotografierte Briefe?', a: 'Ja. Sie können den Brief einfach mit dem Handy fotografieren. Gedruckter Text wird zuverlässig erkannt; bei Handschrift hängt es von der Lesbarkeit ab.' },
    ],
    ctaTitle: 'Verstehen Sie, was Ihre Ärzte schreiben',
    ctaSub: '3 Dokumente pro Monat kostenlos. Keine Kreditkarte nötig, DSGVO-konform, Daten werden automatisch gelöscht.',
    ctaButton: 'Arztbrief jetzt erklären lassen',
    ctaNote: 'Medyra ersetzt keine ärztliche Beratung. Besprechen Sie Ihre Befunde immer mit Ihrer Ärztin oder Ihrem Arzt.',
  },

  en: {
    headerTitle: 'Understand doctor letters',
    headerCta: 'Upload doctor letter',
    badge: 'Doctor letter · Discharge report · MRI findings',
    h1a: 'Your German doctor letter,',
    h1b: 'finally understandable',
    sub: 'Medical terms, abbreviations, Latin diagnoses: Medyra translates every sentence of your German medical report into plain language and tells you which questions to ask your doctor. In under 60 seconds.',
    cta: 'Upload your doctor letter now',
    mock: {
      labelIn: 'The report says', quote: QUOTE, labelOut: 'Medyra explains',
      lines: [
        'Suspected wear related changes in the lower spine, very common from middle age.',
        'A disc between the 4th and 5th lumbar vertebrae bulges slightly.',
        'The nerve canal is not strongly narrowed, which is good news.',
      ],
    },
    cardsLabel: 'For every document',
    cardsTitle: 'More than just lab values',
    cards: [
      { icon: '📋', title: 'Doctor letters & discharge reports', desc: 'Diagnoses, therapy recommendations and medication changes from the hospital or specialist, explained paragraph by paragraph.' },
      { icon: '🩻', title: 'Radiology reports (MRI, CT, X-ray)', desc: 'What does "unauffällige Raumforderung" or "degenerative Veränderung" mean? Every term gets translated, calmly and without panic.' },
      { icon: '🔬', title: 'Pathology & lab reports', desc: 'Tissue findings and lab values in context: what was measured, what stands out and which questions you should ask.' },
    ],
    jargon: {
      label: 'Examples', title: 'Doctor German, translated', sub: 'This is what your report sounds like after Medyra explains it.',
      pairs: [
        ['idiopathisch', 'without a recognizable cause'],
        ['Adhärenz', 'how reliably you follow the therapy'],
        ['unauffällig', 'all fine, nothing abnormal found'],
        ['Raumforderung', 'something taking up space, not necessarily malignant'],
        ['degenerativ', 'wear related, usually age related'],
        ['V. a.', 'suspected, not yet a confirmed diagnosis'],
      ],
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'Which documents can I upload?', a: 'Doctor letters, discharge reports, radiology reports (MRI, CT, X-ray, ultrasound), pathology reports, lab reports and health insurance letters, as PDF, photo or text.' },
      { q: 'Does Medyra make diagnoses?', a: 'No. Medyra explains what your document says in plain language. Diagnosis and therapy belong in medical hands. Medyra suggests fitting questions for your doctor visit.' },
      { q: 'What happens to my data?', a: 'Your documents are processed encrypted, hosted GDPR compliant in Frankfurt, and deleted automatically after 30 days by default.' },
      { q: 'Does Medyra read handwritten or photographed letters?', a: 'Yes. Simply photograph the letter with your phone. Printed text is recognized reliably; handwriting depends on legibility.' },
    ],
    ctaTitle: 'Understand what your doctors write',
    ctaSub: '3 documents per month free. No credit card needed, GDPR compliant, data deleted automatically.',
    ctaButton: 'Explain my doctor letter now',
    ctaNote: 'Medyra does not replace medical advice. Always discuss your findings with your doctor.',
  },

  tr: {
    headerTitle: 'Doktor mektubunu anlayın',
    headerCta: 'Mektup yükle',
    badge: 'Doktor mektubu · Taburcu raporu · MR bulgusu',
    h1a: 'Almanca doktor mektubunuz,',
    h1b: 'nihayet anlaşılır',
    sub: 'Tıbbi terimler, kısaltmalar, Latince tanılar: Medyra, Almanca raporunuzun her cümlesini anlaşılır dile çevirir ve doktorunuza hangi soruları sormanız gerektiğini söyler. 60 saniyeden kısa sürede.',
    cta: 'Doktor mektubunu şimdi yükle',
    mock: {
      labelIn: 'Raporda yazan', quote: QUOTE, labelOut: 'Medyra açıklıyor',
      lines: [
        'Bel omurgasında aşınmaya bağlı değişiklik şüphesi, orta yaştan itibaren çok yaygındır.',
        '4. ve 5. bel omurları arasındaki disk hafifçe dışarı taşıyor.',
        'Sinir kanalı ciddi şekilde daralmamış, bu iyi bir haber.',
      ],
    },
    cardsLabel: 'Her belge için',
    cardsTitle: 'Sadece tahlil değerleri değil',
    cards: [
      { icon: '📋', title: 'Doktor mektupları ve taburcu raporları', desc: 'Hastaneden veya uzman doktordan gelen tanılar, tedavi önerileri ve ilaç değişiklikleri, paragraf paragraf açıklanır.' },
      { icon: '🩻', title: 'Radyoloji raporları (MR, BT, röntgen)', desc: '"Unauffällige Raumforderung" ne demek? Her terim sakin bir dille, panik yaratmadan çevrilir.' },
      { icon: '🔬', title: 'Patoloji ve laboratuvar raporları', desc: 'Doku bulguları ve tahlil değerleri bir arada: ne ölçüldü, ne dikkat çekiyor, hangi soruları sormalısınız.' },
    ],
    jargon: {
      label: 'Örnekler', title: 'Doktor Almancası, çevrildi', sub: 'Medyra açıkladıktan sonra raporunuz böyle görünür.',
      pairs: [
        ['idiopathisch', 'belirlenebilir bir nedeni olmayan'],
        ['Adhärenz', 'tedaviye ne kadar düzenli uyduğunuz'],
        ['unauffällig', 'her şey yolunda, anormal bulgu yok'],
        ['Raumforderung', 'yer kaplayan bir oluşum, kötü huylu olmak zorunda değil'],
        ['degenerativ', 'aşınmaya bağlı, genellikle yaşla ilgili'],
        ['V. a.', 'şüphesi var, henüz kesinleşmiş tanı değil'],
      ],
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Hangi belgeleri yükleyebilirim?', a: 'Doktor mektupları, taburcu raporları, radyoloji raporları (MR, BT, röntgen, ultrason), patoloji raporları, tahlil sonuçları ve sigorta yazıları; PDF, fotoğraf veya metin olarak.' },
      { q: 'Medyra tanı koyar mı?', a: 'Hayır. Medyra belgenizde yazanları anlaşılır dille açıklar. Tanı ve tedavi doktorların işidir. Medyra doktor görüşmesi için uygun sorular önerir.' },
      { q: 'Verilerime ne olur?', a: 'Belgeleriniz şifreli işlenir, Frankfurt’ta KVKK/GDPR uyumlu barındırılır ve varsayılan olarak 30 gün sonra otomatik silinir.' },
      { q: 'El yazısı veya fotoğraflı mektupları da anlar mı?', a: 'Evet. Mektubu telefonunuzla fotoğraflamanız yeterli. Basılı metin güvenilir şekilde tanınır; el yazısında okunabilirlik belirleyicidir.' },
    ],
    ctaTitle: 'Doktorlarınızın ne yazdığını anlayın',
    ctaSub: 'Ayda 3 belge ücretsiz. Kredi kartı gerekmez, GDPR uyumlu, veriler otomatik silinir.',
    ctaButton: 'Mektubumu şimdi açıkla',
    ctaNote: 'Medyra tıbbi danışmanlığın yerini tutmaz. Bulgularınızı her zaman doktorunuzla görüşün.',
  },

  ar: {
    headerTitle: 'افهم خطاب الطبيب',
    headerCta: 'ارفع الخطاب',
    badge: 'خطاب طبيب · تقرير خروج · نتائج رنين',
    h1a: 'خطاب طبيبك الألماني،',
    h1b: 'مفهوم أخيراً',
    sub: 'مصطلحات طبية واختصارات وتشخيصات لاتينية: يترجم Medyra كل جملة في تقريرك الألماني إلى لغة بسيطة ويخبرك بالأسئلة التي يجب طرحها على طبيبك. في أقل من 60 ثانية.',
    cta: 'ارفع خطاب الطبيب الآن',
    mock: {
      labelIn: 'ما يقوله التقرير', quote: QUOTE, labelOut: 'Medyra يشرح',
      lines: [
        'اشتباه بتغيرات ناتجة عن التآكل في أسفل العمود الفقري، وهذا شائع جداً من منتصف العمر.',
        'قرص بين الفقرتين القطنيتين الرابعة والخامسة يبرز قليلاً.',
        'قناة الأعصاب ليست ضيقة بشدة، وهذا خبر جيد.',
      ],
    },
    cardsLabel: 'لكل مستند',
    cardsTitle: 'أكثر من مجرد قيم تحاليل',
    cards: [
      { icon: '📋', title: 'خطابات الأطباء وتقارير الخروج', desc: 'التشخيصات وتوصيات العلاج وتغييرات الأدوية من المستشفى أو الطبيب المختص، مشروحة فقرة فقرة.' },
      { icon: '🩻', title: 'تقارير الأشعة (رنين، مقطعية، سينية)', desc: 'ماذا تعني "Raumforderung"؟ كل مصطلح يُترجم بهدوء ودون إثارة قلق.' },
      { icon: '🔬', title: 'تقارير الأنسجة والمختبر', desc: 'نتائج الأنسجة وقيم المختبر في سياقها: ما الذي قيس، وما اللافت، وما الأسئلة التي يجب طرحها.' },
    ],
    jargon: {
      label: 'أمثلة', title: 'لغة الأطباء الألمانية، مترجمة', sub: 'هكذا يبدو تقريرك بعد أن يشرحه Medyra.',
      pairs: [
        ['idiopathisch', 'بدون سبب معروف'],
        ['Adhärenz', 'مدى التزامك بالعلاج'],
        ['unauffällig', 'كل شيء سليم، لا توجد نتيجة مرضية'],
        ['Raumforderung', 'شيء يشغل حيزاً، وليس بالضرورة خبيثاً'],
        ['degenerativ', 'ناتج عن التآكل، غالباً بسبب العمر'],
        ['V. a.', 'اشتباه، وليس تشخيصاً مؤكداً بعد'],
      ],
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما المستندات التي يمكنني رفعها؟', a: 'خطابات الأطباء وتقارير الخروج وتقارير الأشعة (رنين، مقطعية، سينية، موجات صوتية) وتقارير الأنسجة ونتائج المختبر وخطابات التأمين الصحي؛ كملف PDF أو صورة أو نص.' },
      { q: 'هل يضع Medyra تشخيصات؟', a: 'لا. يشرح Medyra ما هو مكتوب في مستندك بلغة مفهومة. التشخيص والعلاج من اختصاص الأطباء. يقترح Medyra أسئلة مناسبة لموعدك الطبي.' },
      { q: 'ماذا يحدث لبياناتي؟', a: 'تُعالج مستنداتك مشفرة، وتُستضاف في فرانكفورت وفق اللائحة الأوروبية لحماية البيانات، وتُحذف تلقائياً بعد 30 يوماً افتراضياً.' },
      { q: 'هل يفهم الخطابات المكتوبة بخط اليد أو المصورة؟', a: 'نعم. صور الخطاب بهاتفك فقط. النص المطبوع يُتعرف عليه بموثوقية؛ وخط اليد يعتمد على وضوحه.' },
    ],
    ctaTitle: 'افهم ما يكتبه أطباؤك',
    ctaSub: '3 مستندات شهرياً مجاناً. لا حاجة لبطاقة ائتمان، متوافق مع GDPR، تُحذف البيانات تلقائياً.',
    ctaButton: 'اشرح خطابي الآن',
    ctaNote: 'لا يحل Medyra محل الاستشارة الطبية. ناقش نتائجك دائماً مع طبيبك.',
  },

  ru: {
    headerTitle: 'Понять письмо врача',
    headerCta: 'Загрузить письмо',
    badge: 'Письмо врача · Выписка · Результаты МРТ',
    h1a: 'Ваше немецкое письмо врача,',
    h1b: 'наконец понятное',
    sub: 'Медицинские термины, сокращения, латинские диагнозы: Medyra переводит каждое предложение вашего немецкого документа на простой язык и подсказывает, какие вопросы задать врачу. Меньше чем за 60 секунд.',
    cta: 'Загрузить письмо врача',
    mock: {
      labelIn: 'В документе написано', quote: QUOTE, labelOut: 'Medyra объясняет',
      lines: [
        'Подозрение на возрастные изменения в поясничном отделе, это очень частое явление со среднего возраста.',
        'Диск между 4 и 5 поясничными позвонками слегка выпячивается.',
        'Нервный канал не сужен сильно, и это хорошая новость.',
      ],
    },
    cardsLabel: 'Для любого документа',
    cardsTitle: 'Больше, чем просто анализы',
    cards: [
      { icon: '📋', title: 'Письма врача и выписки', desc: 'Диагнозы, рекомендации по лечению и изменения в лекарствах из больницы или от специалиста, объяснённые абзац за абзацем.' },
      { icon: '🩻', title: 'Радиология (МРТ, КТ, рентген)', desc: 'Что значит "Raumforderung" или "degenerative Veränderung"? Каждый термин переводится спокойно и без паники.' },
      { icon: '🔬', title: 'Патология и лаборатория', desc: 'Результаты тканей и анализов в контексте: что измерили, что выделяется и какие вопросы стоит задать.' },
    ],
    jargon: {
      label: 'Примеры', title: 'Врачебный немецкий, переведён', sub: 'Так звучит ваш документ после объяснения Medyra.',
      pairs: [
        ['idiopathisch', 'без установленной причины'],
        ['Adhärenz', 'насколько точно вы соблюдаете лечение'],
        ['unauffällig', 'всё в порядке, отклонений не найдено'],
        ['Raumforderung', 'образование, занимающее место, не обязательно злокачественное'],
        ['degenerativ', 'связано с износом, обычно с возрастом'],
        ['V. a.', 'подозрение, ещё не подтверждённый диагноз'],
      ],
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Какие документы можно загрузить?', a: 'Письма врача, выписки, радиологические заключения (МРТ, КТ, рентген, УЗИ), патологию, анализы и письма страховой; как PDF, фото или текст.' },
      { q: 'Ставит ли Medyra диагнозы?', a: 'Нет. Medyra объясняет содержание вашего документа простым языком. Диагноз и лечение остаются за врачами. Medyra предлагает подходящие вопросы для визита к врачу.' },
      { q: 'Что происходит с моими данными?', a: 'Документы обрабатываются в зашифрованном виде, хранятся во Франкфурте в соответствии с GDPR и по умолчанию автоматически удаляются через 30 дней.' },
      { q: 'Понимает ли рукописные или сфотографированные письма?', a: 'Да. Просто сфотографируйте письмо телефоном. Печатный текст распознаётся надёжно; рукописный зависит от разборчивости.' },
    ],
    ctaTitle: 'Понимайте, что пишут ваши врачи',
    ctaSub: '3 документа в месяц бесплатно. Банковская карта не нужна, GDPR, данные удаляются автоматически.',
    ctaButton: 'Объяснить моё письмо',
    ctaNote: 'Medyra не заменяет консультацию врача. Всегда обсуждайте результаты с вашим врачом.',
  },
}
