// Localized content for /arztbrief. German is the SEO base; unlisted
// languages fall back to English. German document quotes and jargon terms
// stay German everywhere: that is what patients hold in their hands.
const QUOTE = '"V. a. degenerative Veränderungen der LWS mit medialer Diskusprotrusion L4/5 ohne Nachweis einer höhergradigen Spinalkanalstenose."'

export const CONTENT = {
  de: {
    headerTitle: 'Arztbrief verstehen',
    headerCta: 'Arztbrief hochladen',
    badge: 'Arztbrief · Entlassungsbericht · MRT-Befund',
    h1a: 'Ihr Arztbrief,',
    h1b: 'endlich verständlich',
    sub: 'Fachbegriffe, Abkürzungen, lateinische Diagnosen: Medyra übersetzt jeden Satz Ihres Befundes in klare Sprache und sagt Ihnen, welche Fragen Sie Ihrer Ärztin stellen sollten. In unter 60 Sekunden.',
    cta: 'Jetzt Arztbrief hochladen',
    mock: {
      labelIn: 'Im Befund steht', quote: QUOTE, labelOut: 'Medyra erklärt',
      lines: [
        'Verdacht auf Verschleiß an der Lendenwirbelsäule, das ist ab dem mittleren Alter sehr häufig.',
        'Eine Bandscheibe zwischen dem 4. und 5. Lendenwirbel wölbt sich leicht vor.',
        'Der Nervenkanal ist nicht stark eingeengt, das ist eine gute Nachricht.',
      ],
    },
    cardsLabel: 'Für jedes Dokument',
    cardsTitle: 'Mehr als nur Laborwerte',
    cards: [
      { icon: '📋', title: 'Arztbrief & Entlassungsbericht', desc: 'Diagnosen, Therapieempfehlungen und Medikationsänderungen aus dem Krankenhaus oder von der Fachärztin, Absatz für Absatz erklärt.' },
      { icon: '🩻', title: 'Radiologie-Befund (MRT, CT, Röntgen)', desc: 'Was bedeutet "unauffällige Raumforderung" oder "degenerative Veränderung"? Jeder Fachbegriff wird übersetzt, ruhig und ohne Panik.' },
      { icon: '🔬', title: 'Pathologie & Laborbefund', desc: 'Gewebebefunde und Laborwerte im Zusammenhang: was gemessen wurde, was auffällig ist und welche Fragen Sie stellen sollten.' },
    ],
    jargon: {
      label: 'Beispiele', title: 'Arzt-Deutsch, übersetzt', sub: 'So klingt Ihr Befund, nachdem Medyra ihn erklärt hat.',
      pairs: [
        ['idiopathisch', 'ohne erkennbare Ursache'],
        ['Adhärenz', 'wie zuverlässig Sie die Therapie einhalten'],
        ['unauffällig', 'alles in Ordnung, kein krankhafter Befund'],
        ['Raumforderung', 'etwas, das Platz einnimmt, muss nicht bösartig sein'],
        ['degenerativ', 'verschleißbedingt, meist altersbedingt'],
        ['V. a.', 'Verdacht auf, noch keine gesicherte Diagnose'],
      ],
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Welche Dokumente kann ich hochladen?', a: 'Arztbriefe, Entlassungsberichte, Radiologie-Befunde (MRT, CT, Röntgen, Ultraschall), Pathologie-Befunde, Laborbefunde und Krankenkassen-Schreiben, als PDF, Foto oder Text.' },
      { q: 'Stellt Medyra Diagnosen?', a: 'Nein. Medyra erklärt, was in Ihrem Dokument steht, in verständlicher Sprache. Diagnose und Therapie gehören in ärztliche Hände. Medyra schlägt Ihnen passende Fragen für das Arztgespräch vor.' },
      { q: 'Was passiert mit meinen Daten?', a: 'Ihre Dokumente werden verschlüsselt verarbeitet, DSGVO-konform in Frankfurt gehostet und standardmäßig nach 30 Tagen automatisch gelöscht.' },
      { q: 'Versteht Medyra auch handschriftliche oder fotografierte Briefe?', a: 'Ja. Sie können den Brief einfach mit dem Handy fotografieren. Gedruckter Text wird zuverlässig erkannt; bei Handschrift hängt es von der Lesbarkeit ab.' },
    ],
    ctaTitle: 'Verstehen Sie, was Ihre Ärzte schreiben',
    ctaSub: '3 Dokumente pro Monat kostenlos. Keine Kreditkarte nötig, DSGVO-konform, Daten werden automatisch gelöscht.',
    ctaButton: 'Arztbrief jetzt erklären lassen',
    ctaNote: 'Medyra ersetzt keine ärztliche Beratung. Besprechen Sie Ihre Befunde immer mit Ihrer Ärztin oder Ihrem Arzt.',
  },

  en: {
    headerTitle: 'Understand doctor letters',
    headerCta: 'Upload doctor letter',
    badge: 'Doctor letter · Discharge report · MRI findings',
    h1a: 'Your German doctor letter,',
    h1b: 'finally understandable',
    sub: 'Medical terms, abbreviations, Latin diagnoses: Medyra translates every sentence of your German medical report into plain language and tells you which questions to ask your doctor. In under 60 seconds.',
    cta: 'Upload your doctor letter now',
    mock: {
      labelIn: 'The report says', quote: QUOTE, labelOut: 'Medyra explains',
      lines: [
        'Suspected wear related changes in the lower spine, very common from middle age.',
        'A disc between the 4th and 5th lumbar vertebrae bulges slightly.',
        'The nerve canal is not strongly narrowed, which is good news.',
      ],
    },
    cardsLabel: 'For every document',
    cardsTitle: 'More than just lab values',
    cards: [
      { icon: '📋', title: 'Doctor letters & discharge reports', desc: 'Diagnoses, therapy recommendations and medication changes from the hospital or specialist, explained paragraph by paragraph.' },
      { icon: '🩻', title: 'Radiology reports (MRI, CT, X-ray)', desc: 'What does "unauffällige Raumforderung" or "degenerative Veränderung" mean? Every term gets translated, calmly and without panic.' },
      { icon: '🔬', title: 'Pathology & lab reports', desc: 'Tissue findings and lab values in context: what was measured, what stands out and which questions you should ask.' },
    ],
    jargon: {
      label: 'Examples', title: 'Doctor German, translated', sub: 'This is what your report sounds like after Medyra explains it.',
      pairs: [
        ['idiopathisch', 'without a recognizable cause'],
        ['Adhärenz', 'how reliably you follow the therapy'],
        ['unauffällig', 'all fine, nothing abnormal found'],
        ['Raumforderung', 'something taking up space, not necessarily malignant'],
        ['degenerativ', 'wear related, usually age related'],
        ['V. a.', 'suspected, not yet a confirmed diagnosis'],
      ],
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'Which documents can I upload?', a: 'Doctor letters, discharge reports, radiology reports (MRI, CT, X-ray, ultrasound), pathology reports, lab reports and health insurance letters, as PDF, photo or text.' },
      { q: 'Does Medyra make diagnoses?', a: 'No. Medyra explains what your document says in plain language. Diagnosis and therapy belong in medical hands. Medyra suggests fitting questions for your doctor visit.' },
      { q: 'What happens to my data?', a: 'Your documents are processed encrypted, hosted GDPR compliant in Frankfurt, and deleted automatically after 30 days by default.' },
      { q: 'Does Medyra read handwritten or photographed letters?', a: 'Yes. Simply photograph the letter with your phone. Printed text is recognized reliably; handwriting depends on legibility.' },
    ],
    ctaTitle: 'Understand what your doctors write',
    ctaSub: '3 documents per month free. No credit card needed, GDPR compliant, data deleted automatically.',
    ctaButton: 'Explain my doctor letter now',
    ctaNote: 'Medyra does not replace medical advice. Always discuss your findings with your doctor.',
  },

  tr: {
    headerTitle: 'Doktor mektubunu anlayın',
    headerCta: 'Mektup yükle',
    badge: 'Doktor mektubu · Taburcu raporu · MR bulgusu',
    h1a: 'Almanca doktor mektubunuz,',
    h1b: 'nihayet anlaşılır',
    sub: 'Tıbbi terimler, kısaltmalar, Latince tanılar: Medyra, Almanca raporunuzun her cümlesini anlaşılır dile çevirir ve doktorunuza hangi soruları sormanız gerektiğini söyler. 60 saniyeden kısa sürede.',
    cta: 'Doktor mektubunu şimdi yükle',
    mock: {
      labelIn: 'Raporda yazan', quote: QUOTE, labelOut: 'Medyra açıklıyor',
      lines: [
        'Bel omurgasında aşınmaya bağlı değişiklik şüphesi, orta yaştan itibaren çok yaygındır.',
        '4. ve 5. bel omurları arasındaki disk hafifçe dışarı taşıyor.',
        'Sinir kanalı ciddi şekilde daralmamış, bu iyi bir haber.',
      ],
    },
    cardsLabel: 'Her belge için',
    cardsTitle: 'Sadece tahlil değerleri değil',
    cards: [
      { icon: '📋', title: 'Doktor mektupları ve taburcu raporları', desc: 'Hastaneden veya uzman doktordan gelen tanılar, tedavi önerileri ve ilaç değişiklikleri, paragraf paragraf açıklanır.' },
      { icon: '🩻', title: 'Radyoloji raporları (MR, BT, röntgen)', desc: '"Unauffällige Raumforderung" ne demek? Her terim sakin bir dille, panik yaratmadan çevrilir.' },
      { icon: '🔬', title: 'Patoloji ve laboratuvar raporları', desc: 'Doku bulguları ve tahlil değerleri bir arada: ne ölçüldü, ne dikkat çekiyor, hangi soruları sormalısınız.' },
    ],
    jargon: {
      label: 'Örnekler', title: 'Doktor Almancası, çevrildi', sub: 'Medyra açıkladıktan sonra raporunuz böyle görünür.',
      pairs: [
        ['idiopathisch', 'belirlenebilir bir nedeni olmayan'],
        ['Adhärenz', 'tedaviye ne kadar düzenli uyduğunuz'],
        ['unauffällig', 'her şey yolunda, anormal bulgu yok'],
        ['Raumforderung', 'yer kaplayan bir oluşum, kötü huylu olmak zorunda değil'],
        ['degenerativ', 'aşınmaya bağlı, genellikle yaşla ilgili'],
        ['V. a.', 'şüphesi var, henüz kesinleşmiş tanı değil'],
      ],
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Hangi belgeleri yükleyebilirim?', a: 'Doktor mektupları, taburcu raporları, radyoloji raporları (MR, BT, röntgen, ultrason), patoloji raporları, tahlil sonuçları ve sigorta yazıları; PDF, fotoğraf veya metin olarak.' },
      { q: 'Medyra tanı koyar mı?', a: 'Hayır. Medyra belgenizde yazanları anlaşılır dille açıklar. Tanı ve tedavi doktorların işidir. Medyra doktor görüşmesi için uygun sorular önerir.' },
      { q: 'Verilerime ne olur?', a: 'Belgeleriniz şifreli işlenir, Frankfurt’ta KVKK/GDPR uyumlu barındırılır ve varsayılan olarak 30 gün sonra otomatik silinir.' },
      { q: 'El yazısı veya fotoğraflı mektupları da anlar mı?', a: 'Evet. Mektubu telefonunuzla fotoğraflamanız yeterli. Basılı metin güvenilir şekilde tanınır; el yazısında okunabilirlik belirleyicidir.' },
    ],
    ctaTitle: 'Doktorlarınızın ne yazdığını anlayın',
    ctaSub: 'Ayda 3 belge ücretsiz. Kredi kartı gerekmez, GDPR uyumlu, veriler otomatik silinir.',
    ctaButton: 'Mektubumu şimdi açıkla',
    ctaNote: 'Medyra tıbbi danışmanlığın yerini tutmaz. Bulgularınızı her zaman doktorunuzla görüşün.',
  },

  ar: {
    headerTitle: 'افهم خطاب الطبيب',
    headerCta: 'ارفع الخطاب',
    badge: 'خطاب طبيب · تقرير خروج · نتائج رنين',
    h1a: 'خطاب طبيبك الألماني،',
    h1b: 'مفهوم أخيراً',
    sub: 'مصطلحات طبية واختصارات وتشخيصات لاتينية: يترجم Medyra كل جملة في تقريرك الألماني إلى لغة بسيطة ويخبرك بالأسئلة التي يجب طرحها على طبيبك. في أقل من 60 ثانية.',
    cta: 'ارفع خطاب الطبيب الآن',
    mock: {
      labelIn: 'ما يقوله التقرير', quote: QUOTE, labelOut: 'Medyra يشرح',
      lines: [
        'اشتباه بتغيرات ناتجة عن التآكل في أسفل العمود الفقري، وهذا شائع جداً من منتصف العمر.',
        'قرص بين الفقرتين القطنيتين الرابعة والخامسة يبرز قليلاً.',
        'قناة الأعصاب ليست ضيقة بشدة، وهذا خبر جيد.',
      ],
    },
    cardsLabel: 'لكل مستند',
    cardsTitle: 'أكثر من مجرد قيم تحاليل',
    cards: [
      { icon: '📋', title: 'خطابات الأطباء وتقارير الخروج', desc: 'التشخيصات وتوصيات العلاج وتغييرات الأدوية من المستشفى أو الطبيب المختص، مشروحة فقرة فقرة.' },
      { icon: '🩻', title: 'تقارير الأشعة (رنين، مقطعية، سينية)', desc: 'ماذا تعني "Raumforderung"؟ كل مصطلح يُترجم بهدوء ودون إثارة قلق.' },
      { icon: '🔬', title: 'تقارير الأنسجة والمختبر', desc: 'نتائج الأنسجة وقيم المختبر في سياقها: ما الذي قيس، وما اللافت، وما الأسئلة التي يجب طرحها.' },
    ],
    jargon: {
      label: 'أمثلة', title: 'لغة الأطباء الألمانية، مترجمة', sub: 'هكذا يبدو تقريرك بعد أن يشرحه Medyra.',
      pairs: [
        ['idiopathisch', 'بدون سبب معروف'],
        ['Adhärenz', 'مدى التزامك بالعلاج'],
        ['unauffällig', 'كل شيء سليم، لا توجد نتيجة مرضية'],
        ['Raumforderung', 'شيء يشغل حيزاً، وليس بالضرورة خبيثاً'],
        ['degenerativ', 'ناتج عن التآكل، غالباً بسبب العمر'],
        ['V. a.', 'اشتباه، وليس تشخيصاً مؤكداً بعد'],
      ],
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما المستندات التي يمكنني رفعها؟', a: 'خطابات الأطباء وتقارير الخروج وتقارير الأشعة (رنين، مقطعية، سينية، موجات صوتية) وتقارير الأنسجة ونتائج المختبر وخطابات التأمين الصحي؛ كملف PDF أو صورة أو نص.' },
      { q: 'هل يضع Medyra تشخيصات؟', a: 'لا. يشرح Medyra ما هو مكتوب في مستندك بلغة مفهومة. التشخيص والعلاج من اختصاص الأطباء. يقترح Medyra أسئلة مناسبة لموعدك الطبي.' },
      { q: 'ماذا يحدث لبياناتي؟', a: 'تُعالج مستنداتك مشفرة، وتُستضاف في فرانكفورت وفق اللائحة الأوروبية لحماية البيانات، وتُحذف تلقائياً بعد 30 يوماً افتراضياً.' },
      { q: 'هل يفهم الخطابات المكتوبة بخط اليد أو المصورة؟', a: 'نعم. صور الخطاب بهاتفك فقط. النص المطبوع يُتعرف عليه بموثوقية؛ وخط اليد يعتمد على وضوحه.' },
    ],
    ctaTitle: 'افهم ما يكتبه أطباؤك',
    ctaSub: '3 مستندات شهرياً مجاناً. لا حاجة لبطاقة ائتمان، متوافق مع GDPR، تُحذف البيانات تلقائياً.',
    ctaButton: 'اشرح خطابي الآن',
    ctaNote: 'لا يحل Medyra محل الاستشارة الطبية. ناقش نتائجك دائماً مع طبيبك.',
  },

  ru: {
    headerTitle: 'Понять письмо врача',
    headerCta: 'Загрузить письмо',
    badge: 'Письмо врача · Выписка · Результаты МРТ',
    h1a: 'Ваше немецкое письмо врача,',
    h1b: 'наконец понятное',
    sub: 'Медицинские термины, сокращения, латинские диагнозы: Medyra переводит каждое предложение вашего немецкого документа на простой язык и подсказывает, какие вопросы задать врачу. Меньше чем за 60 секунд.',
    cta: 'Загрузить письмо врача',
    mock: {
      labelIn: 'В документе написано', quote: QUOTE, labelOut: 'Medyra объясняет',
      lines: [
        'Подозрение на возрастные изменения в поясничном отделе, это очень частое явление со среднего возраста.',
        'Диск между 4 и 5 поясничными позвонками слегка выпячивается.',
        'Нервный канал не сужен сильно, и это хорошая новость.',
      ],
    },
    cardsLabel: 'Для любого документа',
    cardsTitle: 'Больше, чем просто анализы',
    cards: [
      { icon: '📋', title: 'Письма врача и выписки', desc: 'Диагнозы, рекомендации по лечению и изменения в лекарствах из больницы или от специалиста, объяснённые абзац за абзацем.' },
      { icon: '🩻', title: 'Радиология (МРТ, КТ, рентген)', desc: 'Что значит "Raumforderung" или "degenerative Veränderung"? Каждый термин переводится спокойно и без паники.' },
      { icon: '🔬', title: 'Патология и лаборатория', desc: 'Результаты тканей и анализов в контексте: что измерили, что выделяется и какие вопросы стоит задать.' },
    ],
    jargon: {
      label: 'Примеры', title: 'Врачебный немецкий, переведён', sub: 'Так звучит ваш документ после объяснения Medyra.',
      pairs: [
        ['idiopathisch', 'без установленной причины'],
        ['Adhärenz', 'насколько точно вы соблюдаете лечение'],
        ['unauffällig', 'всё в порядке, отклонений не найдено'],
        ['Raumforderung', 'образование, занимающее место, не обязательно злокачественное'],
        ['degenerativ', 'связано с износом, обычно с возрастом'],
        ['V. a.', 'подозрение, ещё не подтверждённый диагноз'],
      ],
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Какие документы можно загрузить?', a: 'Письма врача, выписки, радиологические заключения (МРТ, КТ, рентген, УЗИ), патологию, анализы и письма страховой; как PDF, фото или текст.' },
      { q: 'Ставит ли Medyra диагнозы?', a: 'Нет. Medyra объясняет содержание вашего документа простым языком. Диагноз и лечение остаются за врачами. Medyra предлагает подходящие вопросы для визита к врачу.' },
      { q: 'Что происходит с моими данными?', a: 'Документы обрабатываются в зашифрованном виде, хранятся во Франкфурте в соответствии с GDPR и по умолчанию автоматически удаляются через 30 дней.' },
      { q: 'Понимает ли рукописные или сфотографированные письма?', a: 'Да. Просто сфотографируйте письмо телефоном. Печатный текст распознаётся надёжно; рукописный зависит от разборчивости.' },
    ],
    ctaTitle: 'Понимайте, что пишут ваши врачи',
    ctaSub: '3 документа в месяц бесплатно. Банковская карта не нужна, GDPR, данные удаляются автоматически.',
    ctaButton: 'Объяснить моё письмо',
    ctaNote: 'Medyra не заменяет консультацию врача. Всегда обсуждайте результаты с вашим врачом.',
  },

  fr: {
    headerTitle: 'Comprendre les lettres de médecin', headerCta: 'Télécharger la lettre',
    badge: 'Lettre de médecin · Compte-rendu de sortie · Résultats IRM',
    h1a: 'Votre lettre de médecin allemande,', h1b: 'enfin compréhensible',
    sub: "Termes médicaux, abréviations, diagnostics en latin : Medyra traduit chaque phrase de votre rapport allemand en langage clair et vous indique quelles questions poser à votre médecin. En moins de 60 secondes.",
    cta: 'Télécharger votre lettre de médecin',
    mock: {
      labelIn: 'Le rapport indique', quote: QUOTE, labelOut: 'Medyra explique',
      lines: [
        "Suspicion de modifications liées à l'usure dans le bas du dos, très fréquent à partir de la quarantaine.",
        'Un disque entre la 4e et la 5e vertèbre lombaire fait une légère saillie.',
        'Le canal nerveux n’est pas fortement rétréci, ce qui est une bonne nouvelle.',
      ],
    },
    cardsLabel: 'Pour chaque document', cardsTitle: 'Plus que de simples valeurs de laboratoire',
    cards: [
      { icon: '📋', title: 'Lettres de médecin et comptes-rendus de sortie', desc: "Diagnostics, recommandations thérapeutiques et changements de médication de l'hôpital ou du spécialiste, expliqués paragraphe par paragraphe." },
      { icon: '🩻', title: 'Rapports de radiologie (IRM, scanner, rayons X)', desc: 'Que signifie "unauffällige Raumforderung" ou "degenerative Veränderung" ? Chaque terme est traduit, calmement et sans panique.' },
      { icon: '🔬', title: 'Anatomopathologie et rapports de laboratoire', desc: 'Résultats tissulaires et valeurs de laboratoire en contexte : ce qui a été mesuré, ce qui ressort et quelles questions poser.' },
    ],
    jargon: {
      label: 'Exemples', title: 'Allemand médical, traduit', sub: 'Voici à quoi ressemble votre rapport une fois expliqué par Medyra.',
      pairs: [
        ['idiopathisch', 'sans cause identifiable'],
        ['Adhärenz', 'à quel point vous suivez le traitement'],
        ['unauffällig', 'tout va bien, aucune anomalie détectée'],
        ['Raumforderung', 'quelque chose qui occupe de la place, pas nécessairement malin'],
        ['degenerativ', "lié à l'usure, généralement lié à l'âge"],
        ['V. a.', 'suspicion, pas encore un diagnostic confirmé'],
      ],
    },
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'Quels documents puis-je télécharger ?', a: 'Lettres de médecin, comptes-rendus de sortie, rapports de radiologie (IRM, scanner, rayons X, échographie), rapports d’anatomopathologie, résultats de laboratoire et courriers d’assurance maladie, en PDF, photo ou texte.' },
      { q: 'Medyra pose-t-il des diagnostics ?', a: 'Non. Medyra explique en langage clair ce que dit votre document. Le diagnostic et le traitement restent entre les mains des médecins. Medyra propose des questions adaptées pour votre rendez-vous.' },
      { q: 'Que deviennent mes données ?', a: 'Vos documents sont traités de manière chiffrée, hébergés à Francfort conformément au RGPD, et supprimés automatiquement après 30 jours par défaut.' },
      { q: 'Medyra comprend-il aussi les lettres manuscrites ou photographiées ?', a: 'Oui. Photographiez simplement la lettre avec votre téléphone. Le texte imprimé est reconnu de manière fiable ; pour l’écriture manuscrite, cela dépend de la lisibilité.' },
    ],
    ctaTitle: 'Comprenez ce que vos médecins écrivent',
    ctaSub: '3 documents par mois gratuits. Aucune carte de crédit requise, conforme au RGPD, données supprimées automatiquement.',
    ctaButton: 'Expliquer ma lettre maintenant',
    ctaNote: 'Medyra ne remplace pas un avis médical. Discutez toujours de vos résultats avec votre médecin.',
  },

  es: {
    headerTitle: 'Entender cartas médicas', headerCta: 'Subir carta',
    badge: 'Carta médica · Informe de alta · Resultados de RM',
    h1a: 'Su carta médica alemana,', h1b: 'por fin comprensible',
    sub: 'Términos médicos, abreviaturas, diagnósticos en latín: Medyra traduce cada frase de su informe alemán a un lenguaje claro y le indica qué preguntas hacerle a su médico. En menos de 60 segundos.',
    cta: 'Sube tu carta médica ahora',
    mock: {
      labelIn: 'El informe dice', quote: QUOTE, labelOut: 'Medyra explica',
      lines: [
        'Sospecha de cambios por desgaste en la zona lumbar, muy común a partir de la mediana edad.',
        'Un disco entre la 4ª y 5ª vértebra lumbar sobresale ligeramente.',
        'El canal nervioso no está muy estrechado, lo cual es una buena noticia.',
      ],
    },
    cardsLabel: 'Para cada documento', cardsTitle: 'Más que solo valores de laboratorio',
    cards: [
      { icon: '📋', title: 'Cartas médicas e informes de alta', desc: 'Diagnósticos, recomendaciones de tratamiento y cambios de medicación del hospital o especialista, explicados párrafo a párrafo.' },
      { icon: '🩻', title: 'Informes de radiología (RM, TC, rayos X)', desc: '¿Qué significa "unauffällige Raumforderung" o "degenerative Veränderung"? Cada término se traduce con calma y sin alarma.' },
      { icon: '🔬', title: 'Patología e informes de laboratorio', desc: 'Resultados de tejidos y valores de laboratorio en contexto: qué se midió, qué destaca y qué preguntas hacer.' },
    ],
    jargon: {
      label: 'Ejemplos', title: 'Alemán médico, traducido', sub: 'Así suena su informe después de que Medyra lo explique.',
      pairs: [
        ['idiopathisch', 'sin causa identificable'],
        ['Adhärenz', 'qué tan fielmente sigue el tratamiento'],
        ['unauffällig', 'todo normal, sin hallazgos anómalos'],
        ['Raumforderung', 'algo que ocupa espacio, no necesariamente maligno'],
        ['degenerativ', 'por desgaste, generalmente relacionado con la edad'],
        ['V. a.', 'sospecha, todavía no un diagnóstico confirmado'],
      ],
    },
    faqTitle: 'Preguntas frecuentes',
    faq: [
      { q: '¿Qué documentos puedo subir?', a: 'Cartas médicas, informes de alta, informes de radiología (RM, TC, rayos X, ecografía), informes de patología, resultados de laboratorio y cartas del seguro médico, en PDF, foto o texto.' },
      { q: '¿Medyra hace diagnósticos?', a: 'No. Medyra explica en lenguaje claro lo que dice su documento. El diagnóstico y el tratamiento quedan en manos médicas. Medyra sugiere preguntas adecuadas para su consulta.' },
      { q: '¿Qué pasa con mis datos?', a: 'Sus documentos se procesan cifrados, alojados en Fráncfort conforme al RGPD, y se eliminan automáticamente después de 30 días por defecto.' },
      { q: '¿Entiende cartas manuscritas o fotografiadas?', a: 'Sí. Simplemente fotografíe la carta con su teléfono. El texto impreso se reconoce de forma fiable; la escritura a mano depende de su legibilidad.' },
    ],
    ctaTitle: 'Entienda lo que escriben sus médicos',
    ctaSub: '3 documentos al mes gratis. No se necesita tarjeta de crédito, conforme al RGPD, datos eliminados automáticamente.',
    ctaButton: 'Explicar mi carta ahora',
    ctaNote: 'Medyra no sustituye el consejo médico. Comente siempre sus resultados con su médico.',
  },

  it: {
    headerTitle: 'Capire le lettere del medico', headerCta: 'Carica la lettera',
    badge: 'Lettera del medico · Referto di dimissione · Risultati RM',
    h1a: 'La tua lettera medica tedesca,', h1b: 'finalmente comprensibile',
    sub: 'Termini medici, abbreviazioni, diagnosi in latino: Medyra traduce ogni frase del tuo referto tedesco in un linguaggio semplice e ti dice quali domande fare al tuo medico. In meno di 60 secondi.',
    cta: 'Carica ora la tua lettera medica',
    mock: {
      labelIn: 'Il referto dice', quote: QUOTE, labelOut: 'Medyra spiega',
      lines: [
        'Sospetto di alterazioni da usura nella zona lombare, molto comune dalla mezza età in poi.',
        'Un disco tra la 4ª e la 5ª vertebra lombare sporge leggermente.',
        'Il canale nervoso non è molto ristretto, il che è una buona notizia.',
      ],
    },
    cardsLabel: 'Per ogni documento', cardsTitle: 'Più che semplici valori di laboratorio',
    cards: [
      { icon: '📋', title: 'Lettere del medico e referti di dimissione', desc: 'Diagnosi, raccomandazioni terapeutiche e cambi di farmaci dall’ospedale o dallo specialista, spiegati paragrafo per paragrafo.' },
      { icon: '🩻', title: 'Referti di radiologia (RM, TC, raggi X)', desc: 'Cosa significa "unauffällige Raumforderung" o "degenerative Veränderung"? Ogni termine viene tradotto con calma e senza allarmismo.' },
      { icon: '🔬', title: 'Anatomia patologica e referti di laboratorio', desc: 'Risultati dei tessuti e valori di laboratorio nel contesto: cosa è stato misurato, cosa risalta e quali domande fare.' },
    ],
    jargon: {
      label: 'Esempi', title: 'Tedesco medico, tradotto', sub: 'Ecco come suona il tuo referto dopo la spiegazione di Medyra.',
      pairs: [
        ['idiopathisch', 'senza causa identificabile'],
        ['Adhärenz', 'quanto fedelmente segui la terapia'],
        ['unauffällig', 'tutto normale, nessun reperto anomalo'],
        ['Raumforderung', 'qualcosa che occupa spazio, non necessariamente maligno'],
        ['degenerativ', 'da usura, di solito legato all’età'],
        ['V. a.', 'sospetto, non ancora una diagnosi confermata'],
      ],
    },
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'Quali documenti posso caricare?', a: 'Lettere del medico, referti di dimissione, referti di radiologia (RM, TC, raggi X, ecografia), referti di anatomia patologica, risultati di laboratorio e lettere dell’assicurazione sanitaria, come PDF, foto o testo.' },
      { q: 'Medyra fa diagnosi?', a: 'No. Medyra spiega in linguaggio semplice cosa dice il tuo documento. Diagnosi e terapia restano compito dei medici. Medyra suggerisce domande adatte per la tua visita.' },
      { q: 'Cosa succede ai miei dati?', a: 'I tuoi documenti vengono elaborati in modo crittografato, ospitati a Francoforte in conformità al GDPR, ed eliminati automaticamente dopo 30 giorni per impostazione predefinita.' },
      { q: 'Capisce anche lettere scritte a mano o fotografate?', a: 'Sì. Basta fotografare la lettera con il telefono. Il testo stampato viene riconosciuto in modo affidabile; per la scrittura a mano dipende dalla leggibilità.' },
    ],
    ctaTitle: 'Capisci cosa scrivono i tuoi medici',
    ctaSub: '3 documenti al mese gratis. Nessuna carta di credito richiesta, conforme al GDPR, dati eliminati automaticamente.',
    ctaButton: 'Spiega la mia lettera ora',
    ctaNote: 'Medyra non sostituisce il consiglio medico. Discuti sempre i tuoi risultati con il tuo medico.',
  },

  pt: {
    headerTitle: 'Entender cartas médicas', headerCta: 'Enviar carta',
    badge: 'Carta médica · Relatório de alta · Resultados de RM',
    h1a: 'Sua carta médica alemã,', h1b: 'finalmente compreensível',
    sub: 'Termos médicos, abreviaturas, diagnósticos em latim: a Medyra traduz cada frase do seu relatório alemão para linguagem simples e diz quais perguntas fazer ao seu médico. Em menos de 60 segundos.',
    cta: 'Envie sua carta médica agora',
    mock: {
      labelIn: 'O relatório diz', quote: QUOTE, labelOut: 'Medyra explica',
      lines: [
        'Suspeita de alterações por desgaste na região lombar, muito comum a partir da meia-idade.',
        'Um disco entre a 4ª e a 5ª vértebra lombar projeta-se levemente.',
        'O canal nervoso não está muito estreitado, o que é uma boa notícia.',
      ],
    },
    cardsLabel: 'Para cada documento', cardsTitle: 'Mais do que apenas valores laboratoriais',
    cards: [
      { icon: '📋', title: 'Cartas médicas e relatórios de alta', desc: 'Diagnósticos, recomendações de tratamento e mudanças de medicação do hospital ou especialista, explicados parágrafo por parágrafo.' },
      { icon: '🩻', title: 'Relatórios de radiologia (RM, TC, raio X)', desc: 'O que significa "unauffällige Raumforderung" ou "degenerative Veränderung"? Cada termo é traduzido com calma e sem alarme.' },
      { icon: '🔬', title: 'Patologia e relatórios laboratoriais', desc: 'Resultados de tecidos e valores laboratoriais em contexto: o que foi medido, o que se destaca e quais perguntas fazer.' },
    ],
    jargon: {
      label: 'Exemplos', title: 'Alemão médico, traduzido', sub: 'É assim que seu relatório soa depois que a Medyra o explica.',
      pairs: [
        ['idiopathisch', 'sem causa identificável'],
        ['Adhärenz', 'quão fielmente você segue o tratamento'],
        ['unauffällig', 'tudo normal, nenhum achado anômalo'],
        ['Raumforderung', 'algo que ocupa espaço, não necessariamente maligno'],
        ['degenerativ', 'por desgaste, geralmente relacionado à idade'],
        ['V. a.', 'suspeita, ainda não um diagnóstico confirmado'],
      ],
    },
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'Quais documentos posso enviar?', a: 'Cartas médicas, relatórios de alta, relatórios de radiologia (RM, TC, raio X, ultrassom), relatórios de patologia, resultados laboratoriais e cartas do seguro saúde, em PDF, foto ou texto.' },
      { q: 'A Medyra faz diagnósticos?', a: 'Não. A Medyra explica em linguagem simples o que diz o seu documento. Diagnóstico e tratamento continuam nas mãos médicas. A Medyra sugere perguntas adequadas para sua consulta.' },
      { q: 'O que acontece com meus dados?', a: 'Seus documentos são processados de forma criptografada, hospedados em Frankfurt em conformidade com o RGPD, e excluídos automaticamente após 30 dias por padrão.' },
      { q: 'Entende cartas manuscritas ou fotografadas?', a: 'Sim. Basta fotografar a carta com o telefone. Texto impresso é reconhecido de forma confiável; a escrita à mão depende da legibilidade.' },
    ],
    ctaTitle: 'Entenda o que seus médicos escrevem',
    ctaSub: '3 documentos por mês grátis. Sem necessidade de cartão de crédito, conforme o RGPD, dados excluídos automaticamente.',
    ctaButton: 'Explicar minha carta agora',
    ctaNote: 'A Medyra não substitui o aconselhamento médico. Sempre discuta seus resultados com seu médico.',
  },

  nl: {
    headerTitle: 'Doktersbrieven begrijpen', headerCta: 'Brief uploaden',
    badge: 'Doktersbrief · Ontslagbrief · MRI-uitslag',
    h1a: 'Uw Duitse doktersbrief,', h1b: 'eindelijk begrijpelijk',
    sub: 'Medische termen, afkortingen, Latijnse diagnoses: Medyra vertaalt elke zin van uw Duitse rapport naar duidelijke taal en vertelt u welke vragen u aan uw arts moet stellen. In minder dan 60 seconden.',
    cta: 'Upload nu uw doktersbrief',
    mock: {
      labelIn: 'Het rapport zegt', quote: QUOTE, labelOut: 'Medyra legt uit',
      lines: [
        'Vermoeden van slijtage gerelateerde veranderingen in de onderrug, zeer gebruikelijk vanaf middelbare leeftijd.',
        'Een schijf tussen de 4e en 5e lendenwervel puilt licht uit.',
        'Het zenuwkanaal is niet sterk vernauwd, wat goed nieuws is.',
      ],
    },
    cardsLabel: 'Voor elk document', cardsTitle: 'Meer dan alleen labwaarden',
    cards: [
      { icon: '📋', title: 'Doktersbrieven en ontslagbrieven', desc: 'Diagnoses, therapieaanbevelingen en medicatiewijzigingen van het ziekenhuis of specialist, alinea voor alinea uitgelegd.' },
      { icon: '🩻', title: 'Radiologieverslagen (MRI, CT, röntgen)', desc: 'Wat betekent "unauffällige Raumforderung" of "degenerative Veränderung"? Elke term wordt rustig en zonder paniek vertaald.' },
      { icon: '🔬', title: 'Pathologie en laboratoriumverslagen', desc: 'Weefselresultaten en labwaarden in context: wat er is gemeten, wat opvalt en welke vragen u moet stellen.' },
    ],
    jargon: {
      label: 'Voorbeelden', title: 'Doktersduits, vertaald', sub: 'Zo klinkt uw rapport nadat Medyra het heeft uitgelegd.',
      pairs: [
        ['idiopathisch', 'zonder aanwijsbare oorzaak'],
        ['Adhärenz', 'hoe trouw u de behandeling volgt'],
        ['unauffällig', 'alles normaal, geen afwijkende bevinding'],
        ['Raumforderung', 'iets dat ruimte inneemt, niet per se kwaadaardig'],
        ['degenerativ', 'door slijtage, meestal leeftijdsgebonden'],
        ['V. a.', 'vermoeden, nog geen bevestigde diagnose'],
      ],
    },
    faqTitle: 'Veelgestelde vragen',
    faq: [
      { q: 'Welke documenten kan ik uploaden?', a: 'Doktersbrieven, ontslagbrieven, radiologieverslagen (MRI, CT, röntgen, echo), pathologieverslagen, labresultaten en brieven van de zorgverzekeraar, als PDF, foto of tekst.' },
      { q: 'Stelt Medyra diagnoses?', a: 'Nee. Medyra legt in duidelijke taal uit wat er in uw document staat. Diagnose en behandeling blijven in handen van artsen. Medyra stelt passende vragen voor uw doktersbezoek voor.' },
      { q: 'Wat gebeurt er met mijn gegevens?', a: 'Uw documenten worden versleuteld verwerkt, AVG-conform gehost in Frankfurt, en standaard na 30 dagen automatisch verwijderd.' },
      { q: 'Begrijpt Medyra ook handgeschreven of gefotografeerde brieven?', a: 'Ja. Fotografeer de brief gewoon met uw telefoon. Gedrukte tekst wordt betrouwbaar herkend; bij handschrift hangt het van de leesbaarheid af.' },
    ],
    ctaTitle: 'Begrijp wat uw artsen schrijven',
    ctaSub: '3 documenten per maand gratis. Geen creditcard nodig, AVG-conform, gegevens automatisch verwijderd.',
    ctaButton: 'Leg mijn brief nu uit',
    ctaNote: 'Medyra vervangt geen medisch advies. Bespreek uw bevindingen altijd met uw arts.',
  },

  pl: {
    headerTitle: 'Zrozumieć pisma lekarskie', headerCta: 'Prześlij pismo',
    badge: 'Pismo lekarskie · Wypis szpitalny · Wynik rezonansu',
    h1a: 'Twoje niemieckie pismo lekarskie,', h1b: 'wreszcie zrozumiałe',
    sub: 'Terminy medyczne, skróty, łacińskie diagnozy: Medyra tłumaczy każde zdanie Twojego niemieckiego raportu na prosty język i mówi, jakie pytania zadać lekarzowi. W mniej niż 60 sekund.',
    cta: 'Prześlij swoje pismo lekarskie teraz',
    mock: {
      labelIn: 'W raporcie napisano', quote: QUOTE, labelOut: 'Medyra wyjaśnia',
      lines: [
        'Podejrzenie zmian zwyrodnieniowych w odcinku lędźwiowym, bardzo częste od średniego wieku.',
        'Krążek między 4. a 5. kręgiem lędźwiowym lekko uwypukla się.',
        'Kanał nerwowy nie jest silnie zwężony, co jest dobrą wiadomością.',
      ],
    },
    cardsLabel: 'Dla każdego dokumentu', cardsTitle: 'Więcej niż tylko wyniki laboratoryjne',
    cards: [
      { icon: '📋', title: 'Pisma lekarskie i wypisy szpitalne', desc: 'Diagnozy, zalecenia terapeutyczne i zmiany leków ze szpitala lub od specjalisty, wyjaśnione akapit po akapicie.' },
      { icon: '🩻', title: 'Wyniki radiologiczne (rezonans, TK, RTG)', desc: 'Co oznacza "unauffällige Raumforderung" lub "degenerative Veränderung"? Każdy termin jest tłumaczony spokojnie i bez paniki.' },
      { icon: '🔬', title: 'Patologia i wyniki laboratoryjne', desc: 'Wyniki tkankowe i wartości laboratoryjne w kontekście: co zmierzono, co się wyróżnia i jakie pytania zadać.' },
    ],
    jargon: {
      label: 'Przykłady', title: 'Medyczny niemiecki, przetłumaczony', sub: 'Tak brzmi Twój raport po wyjaśnieniu przez Medyra.',
      pairs: [
        ['idiopathisch', 'bez rozpoznawalnej przyczyny'],
        ['Adhärenz', 'jak wiernie przestrzegasz terapii'],
        ['unauffällig', 'wszystko w porządku, brak nieprawidłowości'],
        ['Raumforderung', 'coś zajmującego miejsce, niekoniecznie złośliwe'],
        ['degenerativ', 'związane ze zużyciem, zwykle wiekowe'],
        ['V. a.', 'podejrzenie, jeszcze nie potwierdzona diagnoza'],
      ],
    },
    faqTitle: 'Najczęstsze pytania',
    faq: [
      { q: 'Jakie dokumenty mogę przesłać?', a: 'Pisma lekarskie, wypisy szpitalne, wyniki radiologiczne (rezonans, TK, RTG, USG), wyniki patologiczne, wyniki laboratoryjne i pisma od ubezpieczyciela zdrowotnego, jako PDF, zdjęcie lub tekst.' },
      { q: 'Czy Medyra stawia diagnozy?', a: 'Nie. Medyra wyjaśnia prostym językiem, co jest napisane w Twoim dokumencie. Diagnoza i leczenie pozostają w rękach lekarzy. Medyra proponuje odpowiednie pytania na wizytę.' },
      { q: 'Co dzieje się z moimi danymi?', a: 'Twoje dokumenty są przetwarzane w formie zaszyfrowanej, hostowane we Frankfurcie zgodnie z RODO i domyślnie automatycznie usuwane po 30 dniach.' },
      { q: 'Czy Medyra rozumie też odręczne lub sfotografowane pisma?', a: 'Tak. Po prostu sfotografuj pismo telefonem. Drukowany tekst jest rozpoznawany niezawodnie; w przypadku pisma odręcznego zależy to od czytelności.' },
    ],
    ctaTitle: 'Zrozum, co piszą Twoi lekarze',
    ctaSub: '3 dokumenty miesięcznie za darmo. Karta kredytowa niepotrzebna, zgodność z RODO, dane usuwane automatycznie.',
    ctaButton: 'Wyjaśnij moje pismo teraz',
    ctaNote: 'Medyra nie zastępuje porady lekarskiej. Zawsze omawiaj swoje wyniki z lekarzem.',
  },

  zh: {
    headerTitle: '看懂医生信件', headerCta: '上传信件',
    badge: '医生信件 · 出院报告 · 核磁共振结果',
    h1a: '您的德文医生信件，', h1b: '终于看得懂了',
    sub: '医学术语、缩写、拉丁文诊断：Medyra 将您德文报告中的每句话翻译成通俗易懂的语言，并告诉您该向医生提出哪些问题。不到60秒。',
    cta: '立即上传您的医生信件',
    mock: {
      labelIn: '报告中写道', quote: QUOTE, labelOut: 'Medyra 解释',
      lines: [
        '怀疑腰椎有磨损性改变，这在中年以后非常常见。',
        '第4和第5腰椎之间的椎间盘轻微膨出。',
        '神经管没有明显狭窄，这是个好消息。',
      ],
    },
    cardsLabel: '适用于每种文件', cardsTitle: '不仅仅是化验值',
    cards: [
      { icon: '📋', title: '医生信件和出院报告', desc: '来自医院或专科医生的诊断、治疗建议和用药变化，逐段解释。' },
      { icon: '🩻', title: '放射科报告（核磁共振、CT、X光）', desc: '"unauffällige Raumforderung"或"degenerative Veränderung"是什么意思？每个术语都会被冷静而不引起恐慌地翻译。' },
      { icon: '🔬', title: '病理和实验室报告', desc: '组织检查结果和化验值的背景说明：测量了什么，哪些异常，应该问哪些问题。' },
    ],
    jargon: {
      label: '示例', title: '医生用的德语，已翻译', sub: 'Medyra 解释后，您的报告听起来是这样的。',
      pairs: [
        ['idiopathisch', '原因不明'],
        ['Adhärenz', '您对治疗的依从程度'],
        ['unauffällig', '一切正常，未发现异常'],
        ['Raumforderung', '占位性病变，不一定是恶性的'],
        ['degenerativ', '因磨损引起，通常与年龄有关'],
        ['V. a.', '疑似，尚未确诊'],
      ],
    },
    faqTitle: '常见问题',
    faq: [
      { q: '我可以上传哪些文件？', a: '医生信件、出院报告、放射科报告（核磁共振、CT、X光、超声）、病理报告、化验结果和医疗保险信件，可以是PDF、照片或文本格式。' },
      { q: 'Medyra 会做诊断吗？', a: '不会。Medyra 用通俗语言解释您文件中的内容。诊断和治疗仍由医生负责。Medyra 会为您的就诊建议合适的问题。' },
      { q: '我的数据会怎样处理？', a: '您的文件经过加密处理，托管在符合GDPR标准的法兰克福服务器上，默认30天后自动删除。' },
      { q: 'Medyra 能看懂手写或拍照的信件吗？', a: '可以。只需用手机拍照即可。印刷文本能被可靠识别；手写文字则取决于清晰度。' },
    ],
    ctaTitle: '看懂您的医生写了什么',
    ctaSub: '每月3份文件免费。无需信用卡，符合GDPR，数据自动删除。',
    ctaButton: '立即解释我的信件',
    ctaNote: 'Medyra 不能替代医疗建议。请始终与您的医生讨论您的检查结果。',
  },

  ja: {
    headerTitle: '医師の手紙を理解する', headerCta: '手紙をアップロード',
    badge: '医師の手紙・退院報告書・MRI所見',
    h1a: 'あなたのドイツ語の医師の手紙が、', h1b: 'ついに理解できるように',
    sub: '医学用語、略語、ラテン語の診断名：Medyraはドイツ語の報告書の一文一文を分かりやすい言葉に翻訳し、医師にどんな質問をすべきか教えてくれます。60秒以内で。',
    cta: '今すぐ医師の手紙をアップロード',
    mock: {
      labelIn: '報告書にはこう書かれています', quote: QUOTE, labelOut: 'Medyraが説明します',
      lines: [
        '腰椎の摩耗性変化の疑い、中年以降非常によく見られます。',
        '第4腰椎と第5腰椎の間の椎間板がわずかに突出しています。',
        '神経管は強く狭窄していません、これは良い知らせです。',
      ],
    },
    cardsLabel: 'あらゆる文書に対応', cardsTitle: '検査値だけではありません',
    cards: [
      { icon: '📋', title: '医師の手紙と退院報告書', desc: '病院や専門医からの診断、治療の推奨事項、薬の変更を段落ごとに説明します。' },
      { icon: '🩻', title: '放射線科レポート（MRI、CT、レントゲン）', desc: '"unauffällige Raumforderung"や"degenerative Veränderung"とはどういう意味ですか？各用語は落ち着いて、パニックを起こさずに翻訳されます。' },
      { icon: '🔬', title: '病理・検査室レポート', desc: '組織の所見と検査値を背景とともに：何が測定されたか、何が目立つか、どんな質問をすべきか。' },
    ],
    jargon: {
      label: '例', title: '医師のドイツ語、翻訳済み', sub: 'Medyraが説明した後、あなたの報告書はこのように聞こえます。',
      pairs: [
        ['idiopathisch', '原因不明の'],
        ['Adhärenz', '治療をどれだけ忠実に守っているか'],
        ['unauffällig', '異常なし、問題ありません'],
        ['Raumforderung', '何かが場所を占めているもの、必ずしも悪性ではない'],
        ['degenerativ', '摩耗によるもの、通常は加齢に関連'],
        ['V. a.', '疑い、まだ確定診断ではない'],
      ],
    },
    faqTitle: 'よくある質問',
    faq: [
      { q: 'どんな文書をアップロードできますか？', a: '医師の手紙、退院報告書、放射線科レポート（MRI、CT、レントゲン、超音波）、病理レポート、検査結果、健康保険の書類を、PDF、写真、またはテキストでアップロードできます。' },
      { q: 'Medyraは診断をしますか？', a: 'いいえ。Medyraはあなたの文書に書かれていることを分かりやすい言葉で説明します。診断と治療は医師の役割です。Medyraは診察のための適切な質問を提案します。' },
      { q: '私のデータはどうなりますか？', a: 'あなたの文書は暗号化されて処理され、GDPRに準拠したフランクフルトでホストされ、デフォルトで30日後に自動的に削除されます。' },
      { q: '手書きや写真の手紙も理解できますか？', a: 'はい。手紙をスマートフォンで撮影するだけです。印刷されたテキストは確実に認識されます。手書きの場合は読みやすさによります。' },
    ],
    ctaTitle: '医師が書いたことを理解しましょう',
    ctaSub: '月3件の文書が無料。クレジットカード不要、GDPR準拠、データは自動削除されます。',
    ctaButton: '今すぐ手紙を説明する',
    ctaNote: 'Medyraは医療アドバイスの代わりにはなりません。検査結果については必ず医師と話し合ってください。',
  },

  ko: {
    headerTitle: '의사 편지 이해하기', headerCta: '편지 업로드',
    badge: '의사 편지 · 퇴원 보고서 · MRI 결과',
    h1a: '독일어 의사 편지를,', h1b: '드디어 이해할 수 있습니다',
    sub: '의학 용어, 약어, 라틴어 진단명: Medyra는 독일어 보고서의 모든 문장을 쉬운 언어로 번역하고 의사에게 물어봐야 할 질문을 알려줍니다. 60초 이내에.',
    cta: '지금 의사 편지 업로드하기',
    mock: {
      labelIn: '보고서 내용', quote: QUOTE, labelOut: 'Medyra 설명',
      lines: [
        '허리 척추의 마모성 변화 의심, 중년 이후 매우 흔합니다.',
        '4번과 5번 요추 사이의 디스크가 약간 돌출되어 있습니다.',
        '신경관이 심하게 좁아지지 않았으며, 이는 좋은 소식입니다.',
      ],
    },
    cardsLabel: '모든 문서에 대해', cardsTitle: '단순한 검사 수치 이상',
    cards: [
      { icon: '📋', title: '의사 편지 및 퇴원 보고서', desc: '병원이나 전문의의 진단, 치료 권장 사항, 약물 변경 사항을 단락별로 설명합니다.' },
      { icon: '🩻', title: '방사선과 보고서 (MRI, CT, X레이)', desc: '"unauffällige Raumforderung" 또는 "degenerative Veränderung"은 무슨 뜻인가요? 모든 용어는 차분하고 놀라지 않게 번역됩니다.' },
      { icon: '🔬', title: '병리 및 검사실 보고서', desc: '조직 소견과 검사 수치를 배경과 함께: 무엇을 측정했는지, 무엇이 눈에 띄는지, 어떤 질문을 해야 하는지.' },
    ],
    jargon: {
      label: '예시', title: '의사가 쓰는 독일어, 번역됨', sub: 'Medyra가 설명한 후 보고서는 이렇게 들립니다.',
      pairs: [
        ['idiopathisch', '원인을 알 수 없는'],
        ['Adhärenz', '치료를 얼마나 충실히 따르는지'],
        ['unauffällig', '모두 정상, 이상 소견 없음'],
        ['Raumforderung', '공간을 차지하는 것, 반드시 악성인 것은 아님'],
        ['degenerativ', '마모로 인한, 대개 나이와 관련됨'],
        ['V. a.', '의심, 아직 확정 진단은 아님'],
      ],
    },
    faqTitle: '자주 묻는 질문',
    faq: [
      { q: '어떤 문서를 업로드할 수 있나요?', a: '의사 편지, 퇴원 보고서, 방사선과 보고서(MRI, CT, X레이, 초음파), 병리 보고서, 검사 결과, 건강보험 서신을 PDF, 사진 또는 텍스트로 업로드할 수 있습니다.' },
      { q: 'Medyra가 진단을 내리나요?', a: '아니요. Medyra는 문서에 적힌 내용을 쉬운 언어로 설명합니다. 진단과 치료는 의사의 몫입니다. Medyra는 진료를 위한 적절한 질문을 제안합니다.' },
      { q: '제 데이터는 어떻게 되나요?', a: '문서는 암호화되어 처리되며, GDPR을 준수하는 프랑크푸르트에서 호스팅되고, 기본적으로 30일 후 자동 삭제됩니다.' },
      { q: '손글씨나 사진으로 찍은 편지도 이해하나요?', a: '네. 휴대폰으로 편지를 촬영하기만 하면 됩니다. 인쇄된 텍스트는 안정적으로 인식되며, 손글씨는 가독성에 따라 다릅니다.' },
    ],
    ctaTitle: '의사가 쓴 내용을 이해하세요',
    ctaSub: '월 3건 문서 무료. 신용카드 필요 없음, GDPR 준수, 데이터 자동 삭제.',
    ctaButton: '지금 편지 설명받기',
    ctaNote: 'Medyra는 의료 상담을 대체하지 않습니다. 검사 결과는 항상 의사와 상의하세요.',
  },

  hi: {
    headerTitle: 'डॉक्टर के पत्र समझें', headerCta: 'पत्र अपलोड करें',
    badge: 'डॉक्टर पत्र · डिस्चार्ज रिपोर्ट · MRI परिणाम',
    h1a: 'आपका जर्मन डॉक्टर पत्र,', h1b: 'आख़िरकार समझ में आने वाला',
    sub: 'चिकित्सा शब्द, संक्षिप्ताक्षर, लैटिन निदान: Medyra आपकी जर्मन रिपोर्ट के हर वाक्य को सरल भाषा में अनुवाद करता है और बताता है कि अपने डॉक्टर से कौन से सवाल पूछें। 60 सेकंड से भी कम समय में।',
    cta: 'अभी अपना डॉक्टर पत्र अपलोड करें',
    mock: {
      labelIn: 'रिपोर्ट में लिखा है', quote: QUOTE, labelOut: 'Medyra समझाता है',
      lines: [
        'कमर के निचले हिस्से में घिसाव संबंधी बदलाव का संदेह, मध्यम आयु से यह बहुत आम है।',
        '4वीं और 5वीं कमर की कशेरुका के बीच की डिस्क थोड़ी उभरी हुई है।',
        'तंत्रिका नलिका ज़्यादा संकुचित नहीं है, जो अच्छी खबर है।',
      ],
    },
    cardsLabel: 'हर दस्तावेज़ के लिए', cardsTitle: 'सिर्फ लैब वैल्यू से कहीं ज़्यादा',
    cards: [
      { icon: '📋', title: 'डॉक्टर पत्र और डिस्चार्ज रिपोर्ट', desc: 'अस्पताल या विशेषज्ञ से निदान, उपचार सिफारिशें और दवाओं में बदलाव, पैराग्राफ दर पैराग्राफ समझाया गया।' },
      { icon: '🩻', title: 'रेडियोलॉजी रिपोर्ट (MRI, CT, एक्स-रे)', desc: '"unauffällige Raumforderung" या "degenerative Veränderung" का क्या मतलब है? हर शब्द का अनुवाद शांति से, बिना घबराहट के किया जाता है।' },
      { icon: '🔬', title: 'पैथोलॉजी और लैब रिपोर्ट', desc: 'ऊतक निष्कर्ष और लैब वैल्यू संदर्भ सहित: क्या मापा गया, क्या असामान्य है और कौन से सवाल पूछने चाहिए।' },
    ],
    jargon: {
      label: 'उदाहरण', title: 'डॉक्टरी जर्मन, अनुवादित', sub: 'Medyra द्वारा समझाए जाने के बाद आपकी रिपोर्ट ऐसी लगती है।',
      pairs: [
        ['idiopathisch', 'बिना पहचानी गई वजह के'],
        ['Adhärenz', 'आप उपचार का कितनी ईमानदारी से पालन करते हैं'],
        ['unauffällig', 'सब सामान्य, कोई असामान्य निष्कर्ष नहीं'],
        ['Raumforderung', 'कुछ जो जगह घेरता है, ज़रूरी नहीं कि घातक हो'],
        ['degenerativ', 'घिसाव से संबंधित, आमतौर पर उम्र से जुड़ा'],
        ['V. a.', 'संदेह, अभी पुष्टि किया हुआ निदान नहीं'],
      ],
    },
    faqTitle: 'सामान्य प्रश्न',
    faq: [
      { q: 'मैं कौन से दस्तावेज़ अपलोड कर सकता हूं?', a: 'डॉक्टर पत्र, डिस्चार्ज रिपोर्ट, रेडियोलॉजी रिपोर्ट (MRI, CT, एक्स-रे, अल्ट्रासाउंड), पैथोलॉजी रिपोर्ट, लैब परिणाम और स्वास्थ्य बीमा पत्र, PDF, फोटो या टेक्स्ट के रूप में।' },
      { q: 'क्या Medyra निदान करता है?', a: 'नहीं। Medyra आपके दस्तावेज़ में जो लिखा है उसे सरल भाषा में समझाता है। निदान और उपचार डॉक्टरों के हाथ में रहता है। Medyra आपकी मुलाक़ात के लिए उपयुक्त सवाल सुझाता है।' },
      { q: 'मेरे डेटा का क्या होता है?', a: 'आपके दस्तावेज़ एन्क्रिप्ट करके प्रोसेस किए जाते हैं, GDPR के अनुरूप फ्रैंकफर्ट में होस्ट किए जाते हैं, और डिफ़ॉल्ट रूप से 30 दिनों के बाद अपने आप हटा दिए जाते हैं।' },
      { q: 'क्या यह हाथ से लिखे या फोटो खींचे गए पत्र भी समझता है?', a: 'हाँ। बस पत्र को अपने फोन से फोटो खींचें। छपे हुए टेक्स्ट को विश्वसनीय रूप से पहचाना जाता है; हस्तलिपि पढ़ने योग्यता पर निर्भर करती है।' },
    ],
    ctaTitle: 'समझें कि आपके डॉक्टर क्या लिखते हैं',
    ctaSub: 'हर महीने 3 दस्तावेज़ मुफ़्त। क्रेडिट कार्ड की आवश्यकता नहीं, GDPR अनुरूप, डेटा अपने आप हटाया जाता है।',
    ctaButton: 'अभी मेरा पत्र समझाएं',
    ctaNote: 'Medyra चिकित्सा सलाह का विकल्प नहीं है। हमेशा अपने निष्कर्षों पर अपने डॉक्टर से चर्चा करें।',
  },

  bn: {
    headerTitle: 'ডাক্তারের চিঠি বুঝুন', headerCta: 'চিঠি আপলোড করুন',
    badge: 'ডাক্তারের চিঠি · ডিসচার্জ রিপোর্ট · MRI ফলাফল',
    h1a: 'আপনার জার্মান ডাক্তারের চিঠি,', h1b: 'অবশেষে বোঝা সহজ',
    sub: 'চিকিৎসা পরিভাষা, সংক্ষিপ্ত রূপ, ল্যাটিন রোগ নির্ণয়: Medyra আপনার জার্মান রিপোর্টের প্রতিটি বাক্য সহজ ভাষায় অনুবাদ করে এবং আপনাকে বলে দেয় আপনার ডাক্তারকে কী প্রশ্ন করতে হবে। ৬০ সেকেন্ডেরও কম সময়ে।',
    cta: 'এখনই আপনার ডাক্তারের চিঠি আপলোড করুন',
    mock: {
      labelIn: 'রিপোর্টে লেখা আছে', quote: QUOTE, labelOut: 'Medyra ব্যাখ্যা করে',
      lines: [
        'কোমরের নিচের অংশে ক্ষয়জনিত পরিবর্তনের সন্দেহ, মধ্যবয়স থেকে এটি খুবই সাধারণ।',
        '৪র্থ ও ৫ম কোমরের কশেরুকার মধ্যবর্তী ডিস্ক সামান্য স্ফীত হয়ে আছে।',
        'স্নায়ু নালী খুব বেশি সংকুচিত নয়, যা একটি ভালো খবর।',
      ],
    },
    cardsLabel: 'প্রতিটি নথির জন্য', cardsTitle: 'শুধু ল্যাব মানের চেয়ে বেশি কিছু',
    cards: [
      { icon: '📋', title: 'ডাক্তারের চিঠি ও ডিসচার্জ রিপোর্ট', desc: 'হাসপাতাল বা বিশেষজ্ঞের কাছ থেকে রোগ নির্ণয়, চিকিৎসার সুপারিশ এবং ওষুধের পরিবর্তন, অনুচ্ছেদ অনুসারে ব্যাখ্যা করা হয়েছে।' },
      { icon: '🩻', title: 'রেডিওলজি রিপোর্ট (MRI, CT, এক্স-রে)', desc: '"unauffällige Raumforderung" বা "degenerative Veränderung" মানে কী? প্রতিটি পরিভাষা শান্তভাবে, আতঙ্ক ছাড়াই অনুবাদ করা হয়।' },
      { icon: '🔬', title: 'প্যাথলজি ও ল্যাব রিপোর্ট', desc: 'টিস্যুর ফলাফল ও ল্যাব মান প্রেক্ষাপটসহ: কী পরিমাপ করা হয়েছে, কী অস্বাভাবিক এবং কোন প্রশ্ন জিজ্ঞাসা করা উচিত।' },
    ],
    jargon: {
      label: 'উদাহরণ', title: 'ডাক্তারি জার্মান, অনূদিত', sub: 'Medyra ব্যাখ্যা করার পর আপনার রিপোর্ট এমন শোনায়।',
      pairs: [
        ['idiopathisch', 'অজানা কারণে'],
        ['Adhärenz', 'আপনি কতটা বিশ্বস্তভাবে চিকিৎসা মেনে চলছেন'],
        ['unauffällig', 'সব স্বাভাবিক, কোনো অস্বাভাবিকতা পাওয়া যায়নি'],
        ['Raumforderung', 'জায়গা দখল করে এমন কিছু, অগত্যা মারাত্মক নয়'],
        ['degenerativ', 'ক্ষয়জনিত, সাধারণত বয়সের সাথে সম্পর্কিত'],
        ['V. a.', 'সন্দেহ, এখনও নিশ্চিত রোগ নির্ণয় নয়'],
      ],
    },
    faqTitle: 'সাধারণ প্রশ্ন',
    faq: [
      { q: 'আমি কোন কোন নথি আপলোড করতে পারি?', a: 'ডাক্তারের চিঠি, ডিসচার্জ রিপোর্ট, রেডিওলজি রিপোর্ট (MRI, CT, এক্স-রে, আল্ট্রাসাউন্ড), প্যাথলজি রিপোর্ট, ল্যাব ফলাফল এবং স্বাস্থ্য বীমার চিঠি, PDF, ছবি বা টেক্সট আকারে।' },
      { q: 'Medyra কি রোগ নির্ণয় করে?', a: 'না। Medyra আপনার নথিতে যা লেখা আছে তা সহজ ভাষায় ব্যাখ্যা করে। রোগ নির্ণয় ও চিকিৎসা ডাক্তারদের হাতেই থাকে। Medyra আপনার ডাক্তার দেখানোর জন্য উপযুক্ত প্রশ্ন প্রস্তাব করে।' },
      { q: 'আমার তথ্যের কী হয়?', a: 'আপনার নথিগুলি এনক্রিপ্ট করে প্রক্রিয়া করা হয়, GDPR মেনে ফ্রাঙ্কফুর্টে হোস্ট করা হয়, এবং ডিফল্টভাবে ৩০ দিন পর স্বয়ংক্রিয়ভাবে মুছে ফেলা হয়।' },
      { q: 'হাতে লেখা বা ছবি তোলা চিঠিও কি বোঝে?', a: 'হ্যাঁ। শুধু আপনার ফোন দিয়ে চিঠির ছবি তুলুন। মুদ্রিত লেখা নির্ভরযোগ্যভাবে চেনা যায়; হাতের লেখা পাঠযোগ্যতার উপর নির্ভর করে।' },
    ],
    ctaTitle: 'আপনার ডাক্তাররা কী লেখেন তা বুঝুন',
    ctaSub: 'মাসে ৩টি নথি বিনামূল্যে। ক্রেডিট কার্ডের প্রয়োজন নেই, GDPR সম্মত, তথ্য স্বয়ংক্রিয়ভাবে মুছে ফেলা হয়।',
    ctaButton: 'এখনই আমার চিঠি ব্যাখ্যা করুন',
    ctaNote: 'Medyra চিকিৎসা পরামর্শের বিকল্প নয়। সবসময় আপনার ফলাফল নিয়ে আপনার ডাক্তারের সাথে আলোচনা করুন।',
  },

  ur: {
    headerTitle: 'ڈاکٹر کے خط سمجھیں', headerCta: 'خط اپ لوڈ کریں',
    badge: 'ڈاکٹر کا خط · ڈسچارج رپورٹ · MRI نتائج',
    h1a: 'آپ کا جرمن ڈاکٹر کا خط،', h1b: 'آخرکار سمجھ میں آنے والا',
    sub: 'طبی اصطلاحات، مخففات، لاطینی تشخیص: Medyra آپ کی جرمن رپورٹ کے ہر جملے کا آسان زبان میں ترجمہ کرتا ہے اور بتاتا ہے کہ اپنے ڈاکٹر سے کون سے سوالات پوچھنے ہیں۔ 60 سیکنڈ سے بھی کم وقت میں۔',
    cta: 'ابھی اپنا ڈاکٹر کا خط اپ لوڈ کریں',
    mock: {
      labelIn: 'رپورٹ میں لکھا ہے', quote: QUOTE, labelOut: 'Medyra وضاحت کرتا ہے',
      lines: [
        'کمر کے نچلے حصے میں گھسنے سے متعلق تبدیلیوں کا شبہ، درمیانی عمر سے بہت عام ہے۔',
        '4 اور 5 ویں کمر کی مہرے کے درمیان ڈسک تھوڑی سی ابھری ہوئی ہے۔',
        'اعصابی نالی زیادہ تنگ نہیں ہے، جو ایک اچھی خبر ہے۔',
      ],
    },
    cardsLabel: 'ہر دستاویز کے لیے', cardsTitle: 'صرف لیب ویلیوز سے کہیں زیادہ',
    cards: [
      { icon: '📋', title: 'ڈاکٹر کے خطوط اور ڈسچارج رپورٹس', desc: 'ہسپتال یا ماہر سے تشخیص، علاج کی سفارشات اور ادویات میں تبدیلیاں، پیراگراف بہ پیراگراف بیان کی گئی ہیں۔' },
      { icon: '🩻', title: 'ریڈیالوجی رپورٹس (MRI، CT، ایکسرے)', desc: '"unauffällige Raumforderung" یا "degenerative Veränderung" کا کیا مطلب ہے؟ ہر اصطلاح کا پرسکون انداز میں، بغیر گھبراہٹ کے ترجمہ کیا جاتا ہے۔' },
      { icon: '🔬', title: 'پیتھالوجی اور لیب رپورٹس', desc: 'ٹشو کے نتائج اور لیب ویلیوز سیاق و سباق کے ساتھ: کیا ناپا گیا، کیا نمایاں ہے اور کون سے سوالات پوچھنے چاہئیں۔' },
    ],
    jargon: {
      label: 'مثالیں', title: 'ڈاکٹری جرمن، ترجمہ شدہ', sub: 'Medyra کی وضاحت کے بعد آپ کی رپورٹ ایسی لگتی ہے۔',
      pairs: [
        ['idiopathisch', 'بغیر کسی معلوم وجہ کے'],
        ['Adhärenz', 'آپ علاج کی کتنی ایمانداری سے پیروی کرتے ہیں'],
        ['unauffällig', 'سب کچھ نارمل ہے، کوئی غیر معمولی بات نہیں'],
        ['Raumforderung', 'کوئی چیز جو جگہ گھیرتی ہے، لازمی نہیں کہ مہلک ہو'],
        ['degenerativ', 'گھسنے سے متعلق، عام طور پر عمر سے جڑا'],
        ['V. a.', 'شبہ، ابھی تک تصدیق شدہ تشخیص نہیں'],
      ],
    },
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faq: [
      { q: 'میں کون سی دستاویزات اپ لوڈ کر سکتا ہوں؟', a: 'ڈاکٹر کے خطوط، ڈسچارج رپورٹس، ریڈیالوجی رپورٹس (MRI، CT، ایکسرے، الٹراساؤنڈ)، پیتھالوجی رپورٹس، لیب نتائج اور صحت انشورنس کے خطوط، PDF، تصویر یا متن کی صورت میں۔' },
      { q: 'کیا Medyra تشخیص کرتا ہے؟', a: 'نہیں۔ Medyra آسان زبان میں بتاتا ہے کہ آپ کی دستاویز میں کیا لکھا ہے۔ تشخیص اور علاج ڈاکٹروں کے ہاتھ میں رہتا ہے۔ Medyra آپ کے دورے کے لیے موزوں سوالات تجویز کرتا ہے۔' },
      { q: 'میرے ڈیٹا کا کیا ہوتا ہے؟', a: 'آپ کی دستاویزات خفیہ کاری کے ساتھ پروسیس کی جاتی ہیں، GDPR کے مطابق فرینکفرٹ میں ہوسٹ کی جاتی ہیں، اور ڈیفالٹ کے طور پر 30 دن بعد خودکار طور پر حذف کر دی جاتی ہیں۔' },
      { q: 'کیا یہ ہاتھ سے لکھے یا تصویر کھینچے گئے خطوط بھی سمجھتا ہے؟', a: 'جی ہاں۔ بس اپنے فون سے خط کی تصویر کھینچیں۔ چھپی ہوئی تحریر قابل اعتماد طریقے سے پہچانی جاتی ہے؛ ہاتھ کی تحریر پڑھنے کی اہلیت پر منحصر ہے۔' },
    ],
    ctaTitle: 'سمجھیں کہ آپ کے ڈاکٹر کیا لکھتے ہیں',
    ctaSub: 'ماہانہ 3 دستاویزات مفت۔ کریڈٹ کارڈ کی ضرورت نہیں، GDPR کے مطابق، ڈیٹا خودکار طور پر حذف ہوتا ہے۔',
    ctaButton: 'ابھی میرا خط سمجھائیں',
    ctaNote: 'Medyra طبی مشورے کا متبادل نہیں ہے۔ ہمیشہ اپنے نتائج پر اپنے ڈاکٹر سے بات کریں۔',
  },
}
