// UI string translations for all Lexikon page components.
// Every language that can appear in /lexikon/:lang/:slug needs an entry here.
// 'de' is the baseline (German).

const UI = {
  de: {
    reviewed: 'Zuletzt überprüft',
    unit: 'Einheit',
    quickExplanation: 'Kurzerklärung',
    referenceValues: 'Referenzwerte',
    below: 'unter',
    above: 'über',
    rangeDisclaimer: 'Referenzwerte können je nach Labor leicht abweichen. Vergleichen Sie Ihren Wert immer mit dem Referenzbereich Ihres Labors.',
    possibleCauses: 'Mögliche Ursachen',
    tooHigh: 'Wert zu hoch — mögliche Ursachen',
    tooLow: 'Wert zu niedrig — mögliche Ursachen',
    causesDisclaimer: 'Diese Liste zeigt mögliche Ursachen — keine Diagnose. Nur Ihr Arzt kann Ihren Wert richtig einordnen.',
    ctaHeading: 'Sie haben einen kompletten Befund?',
    ctaBody: 'Medyra erklärt Ihren gesamten Laborbericht in einfacher Sprache und bereitet Fragen für Ihren Arzttermin vor — kostenlos, in Ihrer Sprache, in unter 60 Sekunden.',
    ctaButton: 'Jetzt kostenlos starten →',
    disclaimerTitle: 'Medizinischer Hinweis',
    disclaimerText: 'Die Inhalte dieser Seite dienen ausschließlich zur allgemeinen Information und ersetzen keine professionelle medizinische Beratung, Diagnose oder Behandlung. Wenden Sie sich bei gesundheitlichen Fragen immer an Ihren Arzt oder Apotheker. Laborwerte sollten stets im Kontext Ihrer persönlichen Krankengeschichte bewertet werden.',
    relatedValues: 'Verwandte Laborwerte',
    doctorQuestions: 'Fragen für Ihren Arzt',
  },
  en: {
    reviewed: 'Reviewed',
    unit: 'Unit',
    quickExplanation: 'Quick Explanation',
    referenceValues: 'Reference Values',
    below: 'below',
    above: 'above',
    rangeDisclaimer: 'Reference ranges may vary slightly between laboratories. Always compare your value with the reference range from your own lab report.',
    possibleCauses: 'Possible Causes',
    tooHigh: 'Value too high — possible causes',
    tooLow: 'Value too low — possible causes',
    causesDisclaimer: 'This list shows possible causes — not a diagnosis. Only your doctor can correctly interpret your result.',
    ctaHeading: 'Have a complete lab report?',
    ctaBody: 'Medyra explains your entire lab report in plain language and prepares questions for your doctor appointment — free, in your language, in under 60 seconds.',
    ctaButton: 'Start for free →',
    disclaimerTitle: 'Medical Disclaimer',
    disclaimerText: 'The content on this page is for general information only and does not replace professional medical advice, diagnosis, or treatment. Always consult your doctor or pharmacist for health-related questions. Lab values should always be assessed in the context of your personal medical history.',
    relatedValues: 'Related Lab Values',
    doctorQuestions: 'Questions for Your Doctor',
  },
  fr: {
    quickExplanation: 'Explication rapide',
    referenceValues: 'Valeurs de référence',
    below: 'inférieur à',
    above: 'supérieur à',
    rangeDisclaimer: 'Les valeurs de référence peuvent légèrement varier selon le laboratoire. Comparez toujours votre résultat avec la plage de référence de votre propre laboratoire.',
    possibleCauses: 'Causes possibles',
    tooHigh: 'Valeur trop élevée — causes possibles',
    tooLow: 'Valeur trop basse — causes possibles',
    causesDisclaimer: 'Cette liste présente des causes possibles — pas un diagnostic. Seul votre médecin peut interpréter correctement votre résultat.',
    ctaHeading: 'Vous avez un bilan complet ?',
    ctaBody: 'Medyra explique l\'intégralité de votre bilan en langage simple et prépare des questions pour votre rendez-vous médical — gratuitement, dans votre langue, en moins de 60 secondes.',
    ctaButton: 'Commencer gratuitement →',
    disclaimerTitle: 'Avertissement médical',
    disclaimerText: 'Le contenu de cette page est fourni à titre d\'information générale uniquement et ne remplace pas un avis médical professionnel, un diagnostic ou un traitement. Consultez toujours votre médecin ou pharmacien pour toute question de santé.',
    relatedValues: 'Valeurs connexes',
    doctorQuestions: 'Questions pour votre médecin',
  },
  tr: {
    quickExplanation: 'Kısa Açıklama',
    referenceValues: 'Referans Değerler',
    below: 'altında',
    above: 'üzerinde',
    rangeDisclaimer: 'Referans değerler laboratuvara göre hafifçe değişebilir. Değerinizi her zaman kendi laboratuvar raporunuzun referans aralığıyla karşılaştırın.',
    possibleCauses: 'Olası Nedenler',
    tooHigh: 'Değer çok yüksek — olası nedenler',
    tooLow: 'Değer çok düşük — olası nedenler',
    causesDisclaimer: 'Bu liste olası nedenleri gösterir — tanı koymaz. Yalnızca doktorunuz sonucunuzu doğru şekilde değerlendirebilir.',
    ctaHeading: 'Tam bir laboratuvar raporunuz var mı?',
    ctaBody: 'Medyra tüm laboratuvar raporunuzu sade bir dille açıklar ve doktor randevunuz için sorular hazırlar — ücretsiz, kendi dilinizde, 60 saniyeden kısa sürede.',
    ctaButton: 'Ücretsiz başla →',
    disclaimerTitle: 'Tıbbi Uyarı',
    disclaimerText: 'Bu sayfadaki içerik yalnızca genel bilgi amaçlıdır ve profesyonel tıbbi tavsiyenin, teşhisin veya tedavinin yerini tutmaz. Sağlıkla ilgili sorularınız için her zaman doktorunuza veya eczacınıza danışın.',
    relatedValues: 'İlgili Laboratuvar Değerleri',
    doctorQuestions: 'Doktorunuza Sorular',
  },
  ar: {
    quickExplanation: 'شرح مختصر',
    referenceValues: 'القيم المرجعية',
    below: 'أقل من',
    above: 'أكثر من',
    rangeDisclaimer: 'قد تختلف القيم المرجعية قليلاً بين المختبرات. قارن دائمًا قيمتك بالنطاق المرجعي الوارد في تقرير مختبرك.',
    possibleCauses: 'الأسباب المحتملة',
    tooHigh: 'القيمة مرتفعة جداً — الأسباب المحتملة',
    tooLow: 'القيمة منخفضة جداً — الأسباب المحتملة',
    causesDisclaimer: 'تُظهر هذه القائمة الأسباب المحتملة — وليست تشخيصاً. طبيبك وحده يمكنه تفسير نتيجتك بشكل صحيح.',
    ctaHeading: 'هل لديك تقرير مختبر كامل؟',
    ctaBody: 'يشرح Medyra تقريرك المختبري بالكامل بلغة بسيطة ويجهز أسئلة لموعدك الطبي — مجانًا، بلغتك، في أقل من 60 ثانية.',
    ctaButton: 'ابدأ مجانًا →',
    disclaimerTitle: 'إخلاء المسؤولية الطبية',
    disclaimerText: 'المحتوى الموجود في هذه الصفحة للمعلومات العامة فقط ولا يُعوض عن المشورة الطبية المهنية أو التشخيص أو العلاج. استشر طبيبك أو صيدلانيك دائمًا للأسئلة الصحية.',
    relatedValues: 'قيم مختبرية ذات صلة',
    doctorQuestions: 'أسئلة لطبيبك',
  },
  es: {
    quickExplanation: 'Explicación rápida',
    referenceValues: 'Valores de referencia',
    below: 'por debajo de',
    above: 'por encima de',
    rangeDisclaimer: 'Los valores de referencia pueden variar ligeramente según el laboratorio. Compare siempre su valor con el rango de referencia de su propio laboratorio.',
    possibleCauses: 'Causas posibles',
    tooHigh: 'Valor demasiado alto — causas posibles',
    tooLow: 'Valor demasiado bajo — causas posibles',
    causesDisclaimer: 'Esta lista muestra posibles causas, no un diagnóstico. Solo su médico puede interpretar correctamente su resultado.',
    ctaHeading: '¿Tiene un informe de laboratorio completo?',
    ctaBody: 'Medyra explica todo su informe de laboratorio en lenguaje sencillo y prepara preguntas para su cita médica — gratis, en su idioma, en menos de 60 segundos.',
    ctaButton: 'Comenzar gratis →',
    disclaimerTitle: 'Aviso médico',
    disclaimerText: 'El contenido de esta página es solo para información general y no reemplaza el consejo médico profesional, diagnóstico o tratamiento. Consulte siempre a su médico o farmacéutico.',
    relatedValues: 'Valores de laboratorio relacionados',
    doctorQuestions: 'Preguntas para su médico',
  },
  it: {
    quickExplanation: 'Spiegazione rapida',
    referenceValues: 'Valori di riferimento',
    below: 'sotto',
    above: 'sopra',
    rangeDisclaimer: 'I valori di riferimento possono variare leggermente da laboratorio a laboratorio. Confronta sempre il tuo valore con il range di riferimento del tuo laboratorio.',
    possibleCauses: 'Cause possibili',
    tooHigh: 'Valore troppo alto — cause possibili',
    tooLow: 'Valore troppo basso — cause possibili',
    causesDisclaimer: 'Questo elenco mostra possibili cause, non una diagnosi. Solo il tuo medico può interpretare correttamente il tuo risultato.',
    ctaHeading: 'Hai un referto completo?',
    ctaBody: 'Medyra spiega il tuo referto di laboratorio in linguaggio semplice e prepara domande per il tuo appuntamento medico — gratis, nella tua lingua, in meno di 60 secondi.',
    ctaButton: 'Inizia gratuitamente →',
    disclaimerTitle: 'Avviso medico',
    disclaimerText: 'Il contenuto di questa pagina è solo per informazione generale e non sostituisce la consulenza medica professionale, la diagnosi o il trattamento. Consulta sempre il tuo medico o farmacista.',
    relatedValues: 'Valori di laboratorio correlati',
    doctorQuestions: 'Domande per il tuo medico',
  },
  pt: {
    quickExplanation: 'Explicação rápida',
    referenceValues: 'Valores de referência',
    below: 'abaixo de',
    above: 'acima de',
    rangeDisclaimer: 'Os valores de referência podem variar ligeiramente entre laboratórios. Compare sempre o seu valor com o intervalo de referência do seu próprio laboratório.',
    possibleCauses: 'Causas possíveis',
    tooHigh: 'Valor muito alto — causas possíveis',
    tooLow: 'Valor muito baixo — causas possíveis',
    causesDisclaimer: 'Esta lista mostra possíveis causas — não um diagnóstico. Apenas o seu médico pode interpretar corretamente o seu resultado.',
    ctaHeading: 'Tem um relatório laboratorial completo?',
    ctaBody: 'O Medyra explica todo o seu relatório laboratorial em linguagem simples e prepara perguntas para a sua consulta — gratuitamente, no seu idioma, em menos de 60 segundos.',
    ctaButton: 'Começar gratuitamente →',
    disclaimerTitle: 'Aviso médico',
    disclaimerText: 'O conteúdo desta página é apenas para informação geral e não substitui aconselhamento médico profissional, diagnóstico ou tratamento. Consulte sempre o seu médico ou farmacêutico.',
    relatedValues: 'Valores laboratoriais relacionados',
    doctorQuestions: 'Perguntas para o seu médico',
  },
  nl: {
    quickExplanation: 'Korte uitleg',
    referenceValues: 'Referentiewaarden',
    below: 'onder',
    above: 'boven',
    rangeDisclaimer: 'Referentiewaarden kunnen per laboratorium iets verschillen. Vergelijk uw waarde altijd met het referentiebereik van uw eigen laboratorium.',
    possibleCauses: 'Mogelijke oorzaken',
    tooHigh: 'Waarde te hoog — mogelijke oorzaken',
    tooLow: 'Waarde te laag — mogelijke oorzaken',
    causesDisclaimer: 'Deze lijst toont mogelijke oorzaken — geen diagnose. Alleen uw arts kan uw resultaat correct beoordelen.',
    ctaHeading: 'Heeft u een volledig laboratoriumrapport?',
    ctaBody: 'Medyra legt uw volledige laboratoriumrapport uit in eenvoudige taal en bereidt vragen voor uw artsbezoek voor — gratis, in uw taal, in minder dan 60 seconden.',
    ctaButton: 'Gratis beginnen →',
    disclaimerTitle: 'Medische disclaimer',
    disclaimerText: 'De inhoud van deze pagina is uitsluitend voor algemene informatie en vervangt geen professioneel medisch advies, diagnose of behandeling. Raadpleeg altijd uw arts of apotheker.',
    relatedValues: 'Gerelateerde laboratoriumwaarden',
    doctorQuestions: 'Vragen voor uw arts',
  },
  pl: {
    quickExplanation: 'Krótkie wyjaśnienie',
    referenceValues: 'Wartości referencyjne',
    below: 'poniżej',
    above: 'powyżej',
    rangeDisclaimer: 'Wartości referencyjne mogą się nieznacznie różnić między laboratoriami. Zawsze porównuj swój wynik z zakresem referencyjnym swojego laboratorium.',
    possibleCauses: 'Możliwe przyczyny',
    tooHigh: 'Wartość za wysoka — możliwe przyczyny',
    tooLow: 'Wartość za niska — możliwe przyczyny',
    causesDisclaimer: 'Lista pokazuje możliwe przyczyny — nie diagnozę. Tylko lekarz może prawidłowo zinterpretować Twój wynik.',
    ctaHeading: 'Masz kompletny wynik badań?',
    ctaBody: 'Medyra wyjaśni cały Twój wynik laboratoryjny w prostym języku i przygotuje pytania na wizytę u lekarza — bezpłatnie, w Twoim języku, w mniej niż 60 sekund.',
    ctaButton: 'Zacznij bezpłatnie →',
    disclaimerTitle: 'Zastrzeżenie medyczne',
    disclaimerText: 'Treści tej strony służą wyłącznie do celów informacyjnych i nie zastępują profesjonalnej porady medycznej, diagnozy ani leczenia. Zawsze konsultuj się z lekarzem lub farmaceutą.',
    relatedValues: 'Powiązane wartości laboratoryjne',
    doctorQuestions: 'Pytania do lekarza',
  },
  zh: {
    quickExplanation: '简短说明',
    referenceValues: '参考值',
    below: '低于',
    above: '高于',
    rangeDisclaimer: '参考范围可能因实验室而略有不同。请始终将您的值与您自己实验室报告中的参考范围进行比较。',
    possibleCauses: '可能原因',
    tooHigh: '值偏高 — 可能原因',
    tooLow: '值偏低 — 可能原因',
    causesDisclaimer: '此列表显示可能的原因，而非诊断。只有您的医生才能正确解读您的结果。',
    ctaHeading: '有完整的化验报告？',
    ctaBody: 'Medyra 用通俗语言解释您的整份化验报告，并为您的就诊预约准备问题——免费、用您的语言、在60秒内完成。',
    ctaButton: '免费开始 →',
    disclaimerTitle: '医疗免责声明',
    disclaimerText: '本页内容仅供一般信息参考，不能替代专业医疗建议、诊断或治疗。如有健康问题，请始终咨询医生或药剂师。',
    relatedValues: '相关化验值',
    doctorQuestions: '向医生提问',
  },
  ja: {
    quickExplanation: '簡単な説明',
    referenceValues: '基準値',
    below: '未満',
    above: '超',
    rangeDisclaimer: '基準値は検査機関によって若干異なる場合があります。常にご自身の検査報告書の基準範囲と比較してください。',
    possibleCauses: '考えられる原因',
    tooHigh: '値が高すぎる — 考えられる原因',
    tooLow: '値が低すぎる — 考えられる原因',
    causesDisclaimer: 'このリストは考えられる原因を示しています — 診断ではありません。結果を正しく解釈できるのは医師だけです。',
    ctaHeading: '完全な検査報告書をお持ちですか？',
    ctaBody: 'Medyraは検査報告書全体をわかりやすい言葉で説明し、診察の予約に向けた質問を準備します — 無料、あなたの言語で、60秒以内に。',
    ctaButton: '無料で始める →',
    disclaimerTitle: '医療上の免責事項',
    disclaimerText: 'このページのコンテンツは一般的な情報提供のみを目的としており、専門的な医療アドバイス、診断、または治療の代替となるものではありません。健康上の質問については、必ず医師または薬剤師に相談してください。',
    relatedValues: '関連する検査値',
    doctorQuestions: '医師への質問',
  },
  ko: {
    quickExplanation: '간단한 설명',
    referenceValues: '참고 수치',
    below: '미만',
    above: '초과',
    rangeDisclaimer: '참고 범위는 검사기관마다 약간 다를 수 있습니다. 항상 본인의 검사 보고서에 있는 참고 범위와 비교하세요.',
    possibleCauses: '가능한 원인',
    tooHigh: '수치가 너무 높음 — 가능한 원인',
    tooLow: '수치가 너무 낮음 — 가능한 원인',
    causesDisclaimer: '이 목록은 가능한 원인을 보여줍니다 — 진단이 아닙니다. 결과를 올바르게 해석할 수 있는 사람은 의사뿐입니다.',
    ctaHeading: '전체 검사 보고서가 있으신가요?',
    ctaBody: 'Medyra는 전체 검사 보고서를 알기 쉬운 언어로 설명하고 진료 예약을 위한 질문을 준비합니다 — 무료, 귀하의 언어로, 60초 이내에.',
    ctaButton: '무료로 시작하기 →',
    disclaimerTitle: '의료 면책 조항',
    disclaimerText: '이 페이지의 내용은 일반 정보 제공 목적으로만 제공되며 전문적인 의료 조언, 진단 또는 치료를 대체하지 않습니다. 건강 관련 질문은 항상 의사나 약사에게 문의하세요.',
    relatedValues: '관련 검사 수치',
    doctorQuestions: '의사에게 물어볼 질문',
  },
  hi: {
    quickExplanation: 'संक्षिप्त व्याख्या',
    referenceValues: 'संदर्भ मान',
    below: 'से कम',
    above: 'से अधिक',
    rangeDisclaimer: 'संदर्भ मान विभिन्न प्रयोगशालाओं में थोड़े अलग हो सकते हैं। अपने मूल्य की तुलना हमेशा अपनी प्रयोगशाला की संदर्भ सीमा से करें।',
    possibleCauses: 'संभावित कारण',
    tooHigh: 'मान बहुत अधिक — संभावित कारण',
    tooLow: 'मान बहुत कम — संभावित कारण',
    causesDisclaimer: 'यह सूची संभावित कारण दिखाती है — निदान नहीं। केवल आपका डॉक्टर आपके परिणाम की सही व्याख्या कर सकता है।',
    ctaHeading: 'क्या आपके पास पूरी लैब रिपोर्ट है?',
    ctaBody: 'Medyra आपकी पूरी लैब रिपोर्ट को सरल भाषा में समझाता है और आपके डॉक्टर की अपॉइंटमेंट के लिए प्रश्न तैयार करता है — मुफ्त, आपकी भाषा में, 60 सेकंड में।',
    ctaButton: 'मुफ्त शुरू करें →',
    disclaimerTitle: 'चिकित्सा अस्वीकरण',
    disclaimerText: 'इस पृष्ठ की सामग्री केवल सामान्य जानकारी के लिए है और पेशेवर चिकित्सा सलाह, निदान या उपचार का विकल्प नहीं है। स्वास्थ्य संबंधी प्रश्नों के लिए हमेशा अपने डॉक्टर या फार्मासिस्ट से परामर्श करें।',
    relatedValues: 'संबंधित प्रयोगशाला मान',
    doctorQuestions: 'अपने डॉक्टर से प्रश्न',
  },
  bn: {
    quickExplanation: 'সংক্ষিপ্ত ব্যাখ্যা',
    referenceValues: 'রেফারেন্স মান',
    below: 'এর নিচে',
    above: 'এর উপরে',
    rangeDisclaimer: 'রেফারেন্স মান বিভিন্ন ল্যাবরেটরিতে সামান্য ভিন্ন হতে পারে। সবসময় আপনার নিজস্ব ল্যাব রিপোর্টের রেফারেন্স রেঞ্জের সাথে তুলনা করুন।',
    possibleCauses: 'সম্ভাব্য কারণ',
    tooHigh: 'মান অনেক বেশি — সম্ভাব্য কারণ',
    tooLow: 'মান অনেক কম — সম্ভাব্য কারণ',
    causesDisclaimer: 'এই তালিকায় সম্ভাব্য কারণ দেখানো হয়েছে — রোগ নির্ণয় নয়। শুধুমাত্র আপনার ডাক্তার আপনার ফলাফল সঠিকভাবে ব্যাখ্যা করতে পারেন।',
    ctaHeading: 'সম্পূর্ণ ল্যাব রিপোর্ট আছে?',
    ctaBody: 'Medyra আপনার সম্পূর্ণ ল্যাব রিপোর্ট সহজ ভাষায় ব্যাখ্যা করে এবং আপনার ডাক্তারের অ্যাপয়েন্টমেন্টের জন্য প্রশ্ন তৈরি করে — বিনামূল্যে, আপনার ভাষায়, ৬০ সেকেন্ডের মধ্যে।',
    ctaButton: 'বিনামূল্যে শুরু করুন →',
    disclaimerTitle: 'চিকিৎসা দাবিত্যাগ',
    disclaimerText: 'এই পৃষ্ঠার বিষয়বস্তু শুধুমাত্র সাধারণ তথ্যের জন্য এবং পেশাদার চিকিৎসা পরামর্শ, রোগ নির্ণয় বা চিকিৎসার বিকল্প নয়। স্বাস্থ্য সম্পর্কিত প্রশ্নের জন্য সবসময় আপনার ডাক্তার বা ফার্মাসিস্টের সাথে পরামর্শ করুন।',
    relatedValues: 'সম্পর্কিত ল্যাব মান',
    doctorQuestions: 'আপনার ডাক্তারের জন্য প্রশ্ন',
  },
  ur: {
    quickExplanation: 'مختصر وضاحت',
    referenceValues: 'حوالہ اقدار',
    below: 'سے کم',
    above: 'سے زیادہ',
    rangeDisclaimer: 'حوالہ اقدار مختلف لیبارٹریوں میں تھوڑی مختلف ہو سکتی ہیں۔ اپنی قدر کو ہمیشہ اپنی لیبارٹری کی حوالہ حد سے موازنہ کریں۔',
    possibleCauses: 'ممکنہ اسباب',
    tooHigh: 'قدر بہت زیادہ — ممکنہ اسباب',
    tooLow: 'قدر بہت کم — ممکنہ اسباب',
    causesDisclaimer: 'یہ فہرست ممکنہ اسباب دکھاتی ہے — تشخیص نہیں۔ صرف آپ کا ڈاکٹر آپ کے نتیجے کی صحیح تشریح کر سکتا ہے۔',
    ctaHeading: 'کیا آپ کے پاس مکمل لیب رپورٹ ہے؟',
    ctaBody: 'Medyra آپ کی پوری لیب رپورٹ کو سادہ زبان میں سمجھاتا ہے اور ڈاکٹر کی ملاقات کے لیے سوالات تیار کرتا ہے — مفت، آپ کی زبان میں، 60 سیکنڈ میں۔',
    ctaButton: 'مفت شروع کریں →',
    disclaimerTitle: 'طبی اعلانِ لاتعلقی',
    disclaimerText: 'اس صفحے کا مواد صرف عمومی معلومات کے لیے ہے اور پیشہ ورانہ طبی مشورے، تشخیص یا علاج کا متبادل نہیں ہے۔ صحت سے متعلق سوالات کے لیے ہمیشہ اپنے ڈاکٹر یا فارماسسٹ سے مشورہ کریں۔',
    relatedValues: 'متعلقہ لیب اقدار',
    doctorQuestions: 'اپنے ڈاکٹر کے لیے سوالات',
  },
  ru: {
    quickExplanation: 'Краткое объяснение',
    referenceValues: 'Референсные значения',
    below: 'ниже',
    above: 'выше',
    rangeDisclaimer: 'Референсные значения могут немного различаться в разных лабораториях. Всегда сравнивайте свой результат с диапазоном вашей лаборатории.',
    possibleCauses: 'Возможные причины',
    tooHigh: 'Значение слишком высокое — возможные причины',
    tooLow: 'Значение слишком низкое — возможные причины',
    causesDisclaimer: 'Этот список показывает возможные причины — не диагноз. Только ваш врач может правильно интерпретировать ваш результат.',
    ctaHeading: 'Есть полный результат анализов?',
    ctaBody: 'Medyra объяснит весь ваш лабораторный отчёт простым языком и подготовит вопросы для визита к врачу — бесплатно, на вашем языке, менее чем за 60 секунд.',
    ctaButton: 'Начать бесплатно →',
    disclaimerTitle: 'Медицинский дисклеймер',
    disclaimerText: 'Содержимое этой страницы предназначено только для общей информации и не заменяет профессиональную медицинскую консультацию, диагноз или лечение. По вопросам здоровья всегда обращайтесь к врачу или фармацевту.',
    relatedValues: 'Связанные показатели',
    doctorQuestions: 'Вопросы для вашего врача',
  },
}

export function getLexikonUI(lang) {
  return UI[lang] || UI['en']
}
