// UI string translations for all Lexikon page components.
// Every language that can appear in /lexikon/:lang/:slug needs an entry here.
// 'de' is the baseline (German).

const UI = {
  de: {
    reviewed: 'Zuletzt überprüft',
    unit: 'Einheit',
    quickExplanation: 'Kurzerklärung',
    referenceValues: 'Referenzwerte',
    below: 'unter',
    above: 'über',
    rangeDisclaimer: 'Referenzwerte können je nach Labor leicht abweichen. Vergleichen Sie Ihren Wert immer mit dem Referenzbereich Ihres Labors.',
    possibleCauses: 'Mögliche Ursachen',
    tooHigh: 'Wert zu hoch — mögliche Ursachen',
    tooLow: 'Wert zu niedrig — mögliche Ursachen',
    causesDisclaimer: 'Diese Liste zeigt mögliche Ursachen — keine Diagnose. Nur Ihr Arzt kann Ihren Wert richtig einordnen.',
    ctaHeading: 'Sie haben einen kompletten Befund?',
    ctaBody: 'Medyra erklärt Ihren gesamten Laborbericht in einfacher Sprache und bereitet Fragen für Ihren Arzttermin vor — kostenlos, in Ihrer Sprache, in unter 60 Sekunden.',
    ctaButton: 'Jetzt kostenlos starten →',
    disclaimerTitle: 'Medizinischer Hinweis',
    disclaimerText: 'Die Inhalte dieser Seite dienen ausschließlich zur allgemeinen Information und ersetzen keine professionelle medizinische Beratung, Diagnose oder Behandlung. Wenden Sie sich bei gesundheitlichen Fragen immer an Ihren Arzt oder Apotheker. Laborwerte sollten stets im Kontext Ihrer persönlichen Krankengeschichte bewertet werden.',
    relatedValues: 'Verwandte Laborwerte',
    doctorQuestions: 'Fragen für Ihren Arzt',
  },
  en: {
    reviewed: 'Reviewed',
    unit: 'Unit',
    quickExplanation: 'Quick Explanation',
    referenceValues: 'Reference Values',
    below: 'below',
    above: 'above',
    rangeDisclaimer: 'Reference ranges may vary slightly between laboratories. Always compare your value with the reference range from your own lab report.',
    possibleCauses: 'Possible Causes',
    tooHigh: 'Value too high — possible causes',
    tooLow: 'Value too low — possible causes',
    causesDisclaimer: 'This list shows possible causes — not a diagnosis. Only your doctor can correctly interpret your result.',
    ctaHeading: 'Have a complete lab report?',
    ctaBody: 'Medyra explains your entire lab report in plain language and prepares questions for your doctor appointment — free, in your language, in under 60 seconds.',
    ctaButton: 'Start for free →',
    disclaimerTitle: 'Medical Disclaimer',
    disclaimerText: 'The content on this page is for general information only and does not replace professional medical advice, diagnosis, or treatment. Always consult your doctor or pharmacist for health-related questions. Lab values should always be assessed in the context of your personal medical history.',
    relatedValues: 'Related Lab Values',
    doctorQuestions: 'Questions for Your Doctor',
  },
  fr: {
    quickExplanation: 'Explication rapide',
    referenceValues: 'Valeurs de référence',
    below: 'inférieur à',
    above: 'supérieur à',
    rangeDisclaimer: 'Les valeurs de référence peuvent légèrement varier selon le laboratoire. Comparez toujours votre résultat avec la plage de référence de votre propre laboratoire.',
    possibleCauses: 'Causes possibles',
    tooHigh: 'Valeur trop élevée — causes possibles',
    tooLow: 'Valeur trop basse — causes possibles',
    causesDisclaimer: 'Cette liste présente des causes possibles — pas un diagnostic. Seul votre médecin peut interpréter correctement votre résultat.',
    ctaHeading: 'Vous avez un bilan complet ?',
    ctaBody: 'Medyra explique l\'intégralité de votre bilan en langage simple et prépare des questions pour votre rendez-vous médical — gratuitement, dans votre langue, en moins de 60 secondes.',
    ctaButton: 'Commencer gratuitement →',
    disclaimerTitle: 'Avertissement médical',
    disclaimerText: 'Le contenu de cette page est fourni à titre d\'information générale uniquement et ne remplace pas un avis médical professionnel, un diagnostic ou un traitement. Consultez toujours votre médecin ou pharmacien pour toute question de santé.',
    relatedValues: 'Valeurs connexes',
    doctorQuestions: 'Questions pour votre médecin',
  },
  tr: {
    quickExplanation: 'Kısa Açıklama',
    referenceValues: 'Referans Değerler',
    below: 'altında',
    above: 'üzerinde',
    rangeDisclaimer: 'Referans değerler laboratuvara göre hafifçe değişebilir. Değerinizi her zaman kendi laboratuvar raporunuzun referans aralığıyla karşılaştırın.',
    possibleCauses: 'Olası Nedenler',
    tooHigh: 'Değer çok yüksek — olası nedenler',
    tooLow: 'Değer çok düşük — olası nedenler',
    causesDisclaimer: 'Bu liste olası nedenleri gösterir — tanı koymaz. Yalnızca doktorunuz sonucunuzu doğru şekilde değerlendirebilir.',
    ctaHeading: 'Tam bir laboratuvar raporunuz var mı?',
    ctaBody: 'Medyra tüm laboratuvar raporunuzu sade bir dille açıklar ve doktor randevunuz için sorular hazırlar — ücretsiz, kendi dilinizde, 60 saniyeden kısa sürede.',
    ctaButton: 'Ücretsiz başla →',
    disclaimerTitle: 'Tıbbi Uyarı',
    disclaimerText: 'Bu sayfadaki içerik yalnızca genel bilgi amaçlıdır ve profesyonel tıbbi tavsiyenin, teşhisin veya tedavinin yerini tutmaz. Sağlıkla ilgili sorularınız için her zaman doktorunuza veya eczacınıza danışın.',
    relatedValues: 'İlgili Laboratuvar Değerleri',
    doctorQuestions: 'Doktorunuza Sorular',
  },
  ar: {
    quickExplanation: 'شرح مختصر',
    referenceValues: 'القيم المرجعية',
    below: 'أقل من',
    above: 'أكثر من',
    rangeDisclaimer: 'قد تختلف القيم المرجعية قليلاً بين المختبرات. قارن دائمًا قيمتك بالنطاق المرجعي الوارد في تقرير مختبرك.',
    possibleCauses: 'الأسباب المحتملة',
    tooHigh: 'القيمة مرتفعة جداً — الأسباب المحتملة',
    tooLow: 'القيمة منخفضة جداً — الأسباب المحتملة',
    causesDisclaimer: 'تُظهر هذه القائمة الأسباب المحتملة — وليست تشخيصاً. طبيبك وحده يمكنه تفسير نتيجتك بشكل صحيح.',
    ctaHeading: 'هل لديك تقرير مختبر كامل؟',
    ctaBody: 'يشرح Medyra تقريرك المختبري بالكامل بلغة بسيطة ويجهز أسئلة لموعدك الطبي — مجانًا، بلغتك، في أقل من 60 ثانية.',
    ctaButton: 'ابدأ مجانًا →',
    disclaimerTitle: 'إخلاء المسؤولية الطبية',
    disclaimerText: 'المحتوى الموجود في هذه الصفحة للمعلومات العامة فقط ولا يُعوض عن المشورة الطبية المهنية أو التشخيص أو العلاج. استشر طبيبك أو صيدلانيك دائمًا للأسئلة الصحية.',
    relatedValues: 'قيم مختبرية ذات صلة',
    doctorQuestions: 'أسئلة لطبيبك',
  },
  es: {
    quickExplanation: 'Explicación rápida',
    referenceValues: 'Valores de referencia',
    below: 'por debajo de',
    above: 'por encima de',
    rangeDisclaimer: 'Los valores de referencia pueden variar ligeramente según el laboratorio. Compare siempre su valor con el rango de referencia de su propio laboratorio.',
    possibleCauses: 'Causas posibles',
    tooHigh: 'Valor demasiado alto — causas posibles',
    tooLow: 'Valor demasiado bajo — causas posibles',
    causesDisclaimer: 'Esta lista muestra posibles causas, no un diagnóstico. Solo su médico puede interpretar correctamente su resultado.',
    ctaHeading: '¿Tiene un informe de laboratorio completo?',
    ctaBody: 'Medyra explica todo su informe de laboratorio en lenguaje sencillo y prepara preguntas para su cita médica — gratis, en su idioma, en menos de 60 segundos.',
    ctaButton: 'Comenzar gratis →',
    disclaimerTitle: 'Aviso médico',
    disclaimerText: 'El contenido de esta página es solo para información general y no reemplaza el consejo médico profesional, diagnóstico o tratamiento. Consulte siempre a su médico o farmacéutico.',
    relatedValues: 'Valores de laboratorio relacionados',
    doctorQuestions: 'Preguntas para su médico',
  },
  it: {
    quickExplanation: 'Spiegazione rapida',
    referenceValues: 'Valori di riferimento',
    below: 'sotto',
    above: 'sopra',
    rangeDisclaimer: 'I valori di riferimento possono variare leggermente da laboratorio a laboratorio. Confronta sempre il tuo valore con il range di riferimento del tuo laboratorio.',
    possibleCauses: 'Cause possibili',
    tooHigh: 'Valore troppo alto — cause possibili',
    tooLow: 'Valore troppo basso — cause possibili',
    causesDisclaimer: 'Questo elenco mostra possibili cause, non una diagnosi. Solo il tuo medico può interpretare correttamente il tuo risultato.',
    ctaHeading: 'Hai un referto completo?',
    ctaBody: 'Medyra spiega il tuo referto di laboratorio in linguaggio semplice e prepara domande per il tuo appuntamento medico — gratis, nella tua lingua, in meno di 60 secondi.',
    ctaButton: 'Inizia gratuitamente →',
    disclaimerTitle: 'Avviso medico',
    disclaimerText: 'Il contenuto di questa pagina è solo per informazione generale e non sostituisce la consulenza medica professionale, la diagnosi o il trattamento. Consulta sempre il tuo medico o farmacista.',
    relatedValues: 'Valori di laboratorio correlati',
    doctorQuestions: 'Domande per il tuo medico',
  },
  pt: {
    quickExplanation: 'Explicação rápida',
    referenceValues: 'Valores de referência',
    below: 'abaixo de',
    above: 'acima de',
    rangeDisclaimer: 'Os valores de referência podem variar ligeiramente entre laboratórios. Compare sempre o seu valor com o intervalo de referência do seu próprio laboratório.',
    possibleCauses: 'Causas possíveis',
    tooHigh: 'Valor muito alto — causas possíveis',
    tooLow: 'Valor muito baixo — causas possíveis',
    causesDisclaimer: 'Esta lista mostra possíveis causas — não um diagnóstico. Apenas o seu médico pode interpretar corretamente o seu resultado.',
    ctaHeading: 'Tem um relatório laboratorial completo?',
    ctaBody: 'O Medyra explica todo o seu relatório laboratorial em linguagem simples e prepara perguntas para a sua consulta — gratuitamente, no seu idioma, em menos de 60 segundos.',
    ctaButton: 'Começar gratuitamente →',
    disclaimerTitle: 'Aviso médico',
    disclaimerText: 'O conteúdo desta página é apenas para informação geral e não substitui aconselhamento médico profissional, diagnóstico ou tratamento. Consulte sempre o seu médico ou farmacêutico.',
    relatedValues: 'Valores laboratoriais relacionados',
    doctorQuestions: 'Perguntas para o seu médico',
  },
  nl: {
    quickExplanation: 'Korte uitleg',
    referenceValues: 'Referentiewaarden',
    below: 'onder',
    above: 'boven',
    rangeDisclaimer: 'Referentiewaarden kunnen per laboratorium iets verschillen. Vergelijk uw waarde altijd met het referentiebereik van uw eigen laboratorium.',
    possibleCauses: 'Mogelijke oorzaken',
    tooHigh: 'Waarde te hoog — mogelijke oorzaken',
    tooLow: 'Waarde te laag — mogelijke oorzaken',
    causesDisclaimer: 'Deze lijst toont mogelijke oorzaken — geen diagnose. Alleen uw arts kan uw resultaat correct beoordelen.',
    ctaHeading: 'Heeft u een volledig laboratoriumrapport?',
    ctaBody: 'Medyra legt uw volledige laboratoriumrapport uit in eenvoudige taal en bereidt vragen voor uw artsbezoek voor — gratis, in uw taal, in minder dan 60 seconden.',
    ctaButton: 'Gratis beginnen →',
    disclaimerTitle: 'Medische disclaimer',
    disclaimerText: 'De inhoud van deze pagina is uitsluitend voor algemene informatie en vervangt geen professioneel medisch advies, diagnose of behandeling. Raadpleeg altijd uw arts of apotheker.',
    relatedValues: 'Gerelateerde laboratoriumwaarden',
    doctorQuestions: 'Vragen voor uw arts',
  },
  pl: {
    quickExplanation: 'Krótkie wyjaśnienie',
    referenceValues: 'Wartości referencyjne',
    below: 'poniżej',
    above: 'powyżej',
    rangeDisclaimer: 'Wartości referencyjne mogą się nieznacznie różnić między laboratoriami. Zawsze porównuj swój wynik z zakresem referencyjnym swojego laboratorium.',
    possibleCauses: 'Możliwe przyczyny',
    tooHigh: 'Wartość za wysoka — możliwe przyczyny',
    tooLow: 'Wartość za niska — możliwe przyczyny',
    causesDisclaimer: 'Lista pokazuje możliwe przyczyny — nie diagnozę. Tylko lekarz może prawidłowo zinterpretować Twój wynik.',
    ctaHeading: 'Masz kompletny wynik badań?',
    ctaBody: 'Medyra wyjaśni cały Twój wynik laboratoryjny w prostym języku i przygotuje pytania na wizytę u lekarza — bezpłatnie, w Twoim języku, w mniej niż 60 sekund.',
    ctaButton: 'Zacznij bezpłatnie →',
    disclaimerTitle: 'Zastrzeżenie medyczne',
    disclaimerText: 'Treści tej strony służą wyłącznie do celów informacyjnych i nie zastępują profesjonalnej porady medycznej, diagnozy ani leczenia. Zawsze konsultuj się z lekarzem lub farmaceutą.',
    relatedValues: 'Powiązane wartości laboratoryjne',
    doctorQuestions: 'Pytania do lekarza',
  },
  zh: {
    quickExplanation: '简短说明',
    referenceValues: '参考值',
    below: '低于',
    above: '高于',
    rangeDisclaimer: '参考范围可能因实验室而略有不同。请始终将您的值与您自己实验室报告中的参考范围进行比较。',
    possibleCauses: '可能原因',
    tooHigh: '值偏高 — 可能原因',
    tooLow: '值偏低 — 可能原因',
    causesDisclaimer: '此列表显示可能的原因，而非诊断。只有您的医生才能正确解读您的结果。',
    ctaHeading: '有完整的化验报告？',
    ctaBody: 'Medyra 用通俗语言解释您的整份化验报告，并为您的就诊预约准备问题——免费、用您的语言、在60秒内完成。',
    ctaButton: '免费开始 →',
    disclaimerTitle: '医疗免责声明',
    disclaimerText: '本页内容仅供一般信息参考，不能替代专业医疗建议、诊断或治疗。如有健康问题，请始终咨询医生或药剂师。',
    relatedValues: '相关化验值',
    doctorQuestions: '向医生提问',
  },
  ja: {
    quickExplanation: '簡単な説明',
    referenceValues: '基準値',
    below: '未満',
    above: '超',
    rangeDisclaimer: '基準値は検査機関によって若干異なる場合があります。常にご自身の検査報告書の基準範囲と比較してください。',
    possibleCauses: '考えられる原因',
    tooHigh: '値が高すぎる — 考えられる原因',
    tooLow: '値が低すぎる — 考えられる原因',
    causesDisclaimer: 'このリストは考えられる原因を示しています — 診断ではありません。結果を正しく解釈できるのは医師だけです。',
    ctaHeading: '完全な検査報告書をお持ちですか？',
    ctaBody: 'Medyraは検査報告書全体をわかりやすい言葉で説明し、診察の予約に向けた質問を準備します — 無料、あなたの言語で、60秒以内に。',
    ctaButton: '無料で始める →',
    disclaimerTitle: '医療上の免責事項',
    disclaimerText: 'このページのコンテンツは一般的な情報提供のみを目的としており、専門的な医療アドバイス、診断、または治療の代替となるものではありません。健康上の質問については、必ず医師または薬剤師に相談してください。',
    relatedValues: '関連する検査値',
    doctorQuestions: '医師への質問',
  },
  ko: {
    quickExplanation: '간단한 설명',
    referenceValues: '참고 수치',
    below: '미만',
    above: '초과',
    rangeDisclaimer: '참고 범위는 검사기관마다 약간 다를 수 있습니다. 항상 본인의 검사 보고서에 있는 참고 범위와 비교하세요.',
    possibleCauses: '가능한 원인',
    tooHigh: '수치가 너무 높음 — 가능한 원인',
    tooLow: '수치가 너무 낮음 — 가능한 원인',
    causesDisclaimer: '이 목록은 가능한 원인을 보여줍니다 — 진단이 아닙니다. 결과를 올바르게 해석할 수 있는 사람은 의사뿐입니다.',
    ctaHeading: '전체 검사 보고서가 있으신가요?',
    ctaBody: 'Medyra는 전체 검사 보고서를 알기 쉬운 언어로 설명하고 진료 예약을 위한 질문을 준비합니다 — 무료, 귀하의 언어로, 60초 이내에.',
    ctaButton: '무료로 시작하기 →',
    disclaimerTitle: '의료 면책 조항',
    disclaimerText: '이 페이지의 내용은 일반 정보 제공 목적으로만 제공되며 전문적인 의료 조언, 진단 또는 치료를 대체하지 않습니다. 건강 관련 질문은 항상 의사나 약사에게 문의하세요.',
    relatedValues: '관련 검사 수치',
    doctorQuestions: '의사에게 물어볼 질문',
  },
  hi: {
    quickExplanation: 'संक्षिप्त व्याख्या',
    referenceValues: 'संदर्भ मान',
    below: 'से कम',
    above: 'से अधिक',
    rangeDisclaimer: 'संदर्भ मान विभिन्न प्रयोगशालाओं में थोड़े अलग हो सकते हैं। अपने मूल्य की तुलना हमेशा अपनी प्रयोगशाला की संदर्भ सीमा से करें।',
    possibleCauses: 'संभावित कारण',
    tooHigh: 'मान बहुत अधिक — संभावित कारण',
    tooLow: 'मान बहुत कम — संभावित कारण',
    causesDisclaimer: 'यह सूची संभावित कारण दिखाती है — निदान नहीं। केवल आपका डॉक्टर आपके परिणाम की सही व्याख्या कर सकता है।',
    ctaHeading: 'क्या आपके पास पूरी लैब रिपोर्ट है?',
    ctaBody: 'Medyra आपकी पूरी लैब रिपोर्ट को सरल भाषा में समझाता है और आपके डॉक्टर की अपॉइंटमेंट के लिए प्रश्न तैयार करता है — मुफ्त, आपकी भाषा में, 60 सेकंड में।',
    ctaButton: 'मुफ्त शुरू करें →',
    disclaimerTitle: 'चिकित्सा अस्वीकरण',
    disclaimerText: 'इस पृष्ठ की सामग्री केवल सामान्य जानकारी के लिए है और पेशेवर चिकित्सा सलाह, निदान या उपचार का विकल्प नहीं है। स्वास्थ्य संबंधी प्रश्नों के लिए हमेशा अपने डॉक्टर या फार्मासिस्ट से परामर्श करें।',
    relatedValues: 'संबंधित प्रयोगशाला मान',
    doctorQuestions: 'अपने डॉक्टर से प्रश्न',
  },
  bn: {
    quickExplanation: 'সংক্ষিপ্ত ব্যাখ্যা',
    referenceValues: 'রেফারেন্স মান',
    below: 'এর নিচে',
    above: 'এর উপরে',
    rangeDisclaimer: 'রেফারেন্স মান বিভিন্ন ল্যাবরেটরিতে সামান্য ভিন্ন হতে পারে। সবসময় আপনার নিজস্ব ল্যাব রিপোর্টের রেফারেন্স রেঞ্জের সাথে তুলনা করুন।',
    possibleCauses: 'সম্ভাব্য কারণ',
    tooHigh: 'মান অনেক বেশি — সম্ভাব্য কারণ',
    tooLow: 'মান অনেক কম — সম্ভাব্য কারণ',
    causesDisclaimer: 'এই তালিকায় সম্ভাব্য কারণ দেখানো হয়েছে — রোগ নির্ণয় নয়। শুধুমাত্র আপনার ডাক্তার আপনার ফলাফল সঠিকভাবে ব্যাখ্যা করতে পারেন।',
    ctaHeading: 'সম্পূর্ণ ল্যাব রিপোর্ট আছে?',
    ctaBody: 'Medyra আপনার সম্পূর্ণ ল্যাব রিপোর্ট সহজ ভাষায় ব্যাখ্যা করে এবং আপনার ডাক্তারের অ্যাপয়েন্টমেন্টের জন্য প্রশ্ন তৈরি করে — বিনামূল্যে, আপনার ভাষায়, ৬০ সেকেন্ডের মধ্যে।',
    ctaButton: 'বিনামূল্যে শুরু করুন →',
    disclaimerTitle: 'চিকিৎসা দাবিত্যাগ',
    disclaimerText: 'এই পৃষ্ঠার বিষয়বস্তু শুধুমাত্র সাধারণ তথ্যের জন্য এবং পেশাদার চিকিৎসা পরামর্শ, রোগ নির্ণয় বা চিকিৎসার বিকল্প নয়। স্বাস্থ্য সম্পর্কিত প্রশ্নের জন্য সবসময় আপনার ডাক্তার বা ফার্মাসিস্টের সাথে পরামর্শ করুন।',
    relatedValues: 'সম্পর্কিত ল্যাব মান',
    doctorQuestions: 'আপনার ডাক্তারের জন্য প্রশ্ন',
  },
  ur: {
    quickExplanation: 'مختصر وضاحت',
    referenceValues: 'حوالہ اقدار',
    below: 'سے کم',
    above: 'سے زیادہ',
    rangeDisclaimer: 'حوالہ اقدار مختلف لیبارٹریوں میں تھوڑی مختلف ہو سکتی ہیں۔ اپنی قدر کو ہمیشہ اپنی لیبارٹری کی حوالہ حد سے موازنہ کریں۔',
    possibleCauses: 'ممکنہ اسباب',
    tooHigh: 'قدر بہت زیادہ — ممکنہ اسباب',
    tooLow: 'قدر بہت کم — ممکنہ اسباب',
    causesDisclaimer: 'یہ فہرست ممکنہ اسباب دکھاتی ہے — تشخیص نہیں۔ صرف آپ کا ڈاکٹر آپ کے نتیجے کی صحیح تشریح کر سکتا ہے۔',
    ctaHeading: 'کیا آپ کے پاس مکمل لیب رپورٹ ہے؟',
    ctaBody: 'Medyra آپ کی پوری لیب رپورٹ کو سادہ زبان میں سمجھاتا ہے اور ڈاکٹر کی ملاقات کے لیے سوالات تیار کرتا ہے — مفت، آپ کی زبان میں، 60 سیکنڈ میں۔',
    ctaButton: 'مفت شروع کریں →',
    disclaimerTitle: 'طبی اعلانِ لاتعلقی',
    disclaimerText: 'اس صفحے کا مواد صرف عمومی معلومات کے لیے ہے اور پیشہ ورانہ طبی مشورے، تشخیص یا علاج کا متبادل نہیں ہے۔ صحت سے متعلق سوالات کے لیے ہمیشہ اپنے ڈاکٹر یا فارماسسٹ سے مشورہ کریں۔',
    relatedValues: 'متعلقہ لیب اقدار',
    doctorQuestions: 'اپنے ڈاکٹر کے لیے سوالات',
  },
  ru: {
    quickExplanation: 'Краткое объяснение',
    referenceValues: 'Референсные значения',
    below: 'ниже',
    above: 'выше',
    rangeDisclaimer: 'Референсные значения могут немного различаться в разных лабораториях. Всегда сравнивайте свой результат с диапазоном вашей лаборатории.',
    possibleCauses: 'Возможные причины',
    tooHigh: 'Значение слишком высокое — возможные причины',
    tooLow: 'Значение слишком низкое — возможные причины',
    causesDisclaimer: 'Этот список показывает возможные причины — не диагноз. Только ваш врач может правильно интерпретировать ваш результат.',
    ctaHeading: 'Есть полный результат анализов?',
    ctaBody: 'Medyra объяснит весь ваш лабораторный отчёт простым языком и подготовит вопросы для визита к врачу — бесплатно, на вашем языке, менее чем за 60 секунд.',
    ctaButton: 'Начать бесплатно →',
    disclaimerTitle: 'Медицинский дисклеймер',
    disclaimerText: 'Содержимое этой страницы предназначено только для общей информации и не заменяет профессиональную медицинскую консультацию, диагноз или лечение. По вопросам здоровья всегда обращайтесь к врачу или фармацевту.',
    relatedValues: 'Связанные показатели',
    doctorQuestions: 'Вопросы для вашего врача',
  },
}

export function getLexikonUI(lang) {
  return UI[lang] || UI['en']
}

// English full names for all 46 terms — used for all non-DE languages
export const TERM_NAMES_EN = {
  'erythrozyten':        'Red Blood Cells (Erythrocytes)',
  'haematokrit':         'Hematocrit',
  'haemoglobin':         'Hemoglobin',
  'leukozyten':          'White Blood Cells (Leukocytes)',
  'mch':                 'Mean Corpuscular Hemoglobin (MCH)',
  'mchc':                'Mean Corpuscular Hemoglobin Concentration (MCHC)',
  'mcv':                 'Mean Corpuscular Volume (MCV)',
  'thrombozyten':        'Platelets (Thrombocytes)',
  'alkalische-phosphatase': 'Alkaline Phosphatase (ALP)',
  'bilirubin':           'Bilirubin',
  'ggt':                 'Gamma-Glutamyl Transferase (GGT)',
  'got-ast':             'Aspartate Aminotransferase (AST)',
  'gpt-alt':             'Alanine Aminotransferase (ALT)',
  'gfr':                 'Glomerular Filtration Rate (GFR)',
  'harnsaeure':          'Uric Acid',
  'harnstoff':           'Blood Urea Nitrogen (BUN)',
  'kreatinin':           'Creatinine',
  'bsg':                 'Erythrocyte Sedimentation Rate (ESR)',
  'crp':                 'C-Reactive Protein (CRP)',
  'procalcitonin':       'Procalcitonin (PCT)',
  'blutzucker':          'Fasting Blood Glucose',
  'cholesterin':         'Total Cholesterol',
  'hba1c':               'Glycated Hemoglobin (HbA1c)',
  'hdl':                 'High-Density Lipoprotein (HDL)',
  'ldl':                 'Low-Density Lipoprotein (LDL)',
  'triglyzeride':        'Triglycerides',
  'ft3':                 'Free Triiodothyronine (FT3)',
  'ft4':                 'Free Thyroxine (FT4)',
  'tsh':                 'Thyroid-Stimulating Hormone (TSH)',
  'calcium':             'Calcium',
  'chlorid':             'Chloride',
  'kalium':              'Potassium',
  'magnesium':           'Magnesium',
  'natrium':             'Sodium',
  'eisen':               'Serum Iron',
  'ferritin':            'Ferritin',
  'transferrin':         'Transferrin',
  'folsaeure':           'Folic Acid (Folate)',
  'vitamin-b12':         'Vitamin B12 (Cobalamin)',
  'vitamin-d':           'Vitamin D (25-OH-D)',
  'inr':                 'International Normalized Ratio (INR)',
  'ptt':                 'Partial Thromboplastin Time (PTT)',
  'quick':               'Prothrombin Time (Quick)',
  'erythrozyten-urin':   'Red Blood Cells in Urine (Hematuria)',
  'leukozyten-urin':     'White Blood Cells in Urine',
  'protein-urin':        'Protein in Urine (Proteinuria)',
}

// English category names for all non-DE languages
export const CATEGORY_NAMES_EN = {
  'Blutbild':         'Blood Count',
  'Leberwerte':       'Liver Values',
  'Nierenwerte':      'Kidney Values',
  'Entzündungswerte': 'Inflammatory Markers',
  'Stoffwechsel':     'Metabolism',
  'Schilddrüse':      'Thyroid',
  'Elektrolyte':      'Electrolytes',
  'Eisenwerte':       'Iron Values',
  'Vitamine':         'Vitamins',
  'Gerinnung':        'Coagulation',
  'Urinwerte':        'Urine Values',
}

// Index page translations (hero, search, etc.)
export const INDEX_UI = {
  de: {
    badge: 'Laborwerte erklärt — kostenlos & ohne Anmeldung',
    title1: 'Medizinisches Lexikon',
    title2: 'Laborwerte',
    title3: 'einfach erklärt',
    subtitle: 'Was bedeutet mein CRP-Wert? Warum ist TSH erhöht? Dieses Lexikon erklärt Ihre Laborwerte in verständlichem Deutsch — mit Normwerten, möglichen Ursachen und Fragen für Ihren nächsten Arzttermin.',
    searchPlaceholder: 'Laborwert suchen, z. B. CRP, Hämoglobin, TSH …',
    noResults: 'Kein Laborwert gefunden — versuchen Sie einen anderen Suchbegriff.',
    results: (n, q) => `${n} Ergebnis${n !== 1 ? 'se' : ''} für „${q}"`,
    emptyTitle: 'Kein Laborwert gefunden',
    emptySubtitle: 'Versuchen Sie einen anderen Suchbegriff, z. B. CRP, TSH oder Cholesterin.',
    unit: 'Einheit',
  },
  en: {
    badge: 'Lab values explained — free & without registration',
    title1: 'Medical Lexicon',
    title2: 'Lab Values',
    title3: 'Simply Explained',
    subtitle: 'What does my CRP value mean? Why is TSH elevated? This lexicon explains your lab values in plain English — with normal ranges, possible causes, and questions for your next doctor appointment.',
    searchPlaceholder: 'Search lab value, e.g. CRP, Hemoglobin, TSH …',
    noResults: 'No lab value found — try a different search term.',
    results: (n, q) => `${n} result${n !== 1 ? 's' : ''} for "${q}"`,
    emptyTitle: 'No lab value found',
    emptySubtitle: 'Try a different search term, e.g. CRP, TSH or Cholesterol.',
    unit: 'Unit',
  },
  fr: {
    badge: 'Valeurs de laboratoire expliquées — gratuites & sans inscription',
    title1: 'Lexique médical',
    title2: 'Valeurs de labo',
    title3: 'expliquées simplement',
    subtitle: 'Que signifie ma valeur CRP ? Pourquoi la TSH est-elle élevée ? Ce lexique explique vos valeurs de laboratoire en termes simples — avec des valeurs normales, des causes possibles et des questions pour votre prochain rendez-vous médical.',
    searchPlaceholder: 'Rechercher une valeur, ex. CRP, Hémoglobine, TSH …',
    noResults: 'Aucune valeur trouvée — essayez un autre terme.',
    results: (n, q) => `${n} résultat${n !== 1 ? 's' : ''} pour « ${q} »`,
    emptyTitle: 'Aucune valeur trouvée',
    emptySubtitle: 'Essayez un autre terme, ex. CRP, TSH ou Cholestérol.',
    unit: 'Unité',
  },
  tr: {
    badge: 'Laboratuvar değerleri açıklandı — ücretsiz & kayıt gerekmez',
    title1: 'Tıbbi Sözlük',
    title2: 'Laboratuvar Değerleri',
    title3: 'Basitçe Açıklandı',
    subtitle: 'CRP değerim ne anlama geliyor? TSH neden yüksek? Bu sözlük laboratuvar değerlerinizi sade bir dille açıklar — normal aralıklar, olası nedenler ve doktor randevunuz için sorularla.',
    searchPlaceholder: 'Laboratuvar değeri ara, örn. CRP, Hemoglobin, TSH …',
    noResults: 'Sonuç bulunamadı — farklı bir arama terimi deneyin.',
    results: (n, q) => `"${q}" için ${n} sonuç`,
    emptyTitle: 'Sonuç bulunamadı',
    emptySubtitle: 'Farklı bir terim deneyin, örn. CRP, TSH veya Kolesterol.',
    unit: 'Birim',
  },
  ar: {
    badge: 'قيم المختبر موضحة — مجاناً وبدون تسجيل',
    title1: 'القاموس الطبي',
    title2: 'قيم المختبر',
    title3: 'مشروحة ببساطة',
    subtitle: 'ماذا تعني قيمة CRP الخاصة بي؟ لماذا يرتفع TSH؟ يشرح هذا القاموس قيم مختبرك بلغة بسيطة — مع النطاقات الطبيعية والأسباب المحتملة وأسئلة لموعدك الطبي.',
    searchPlaceholder: 'ابحث عن قيمة مختبرية، مثل CRP أو الهيموغلوبين أو TSH …',
    noResults: 'لم يتم العثور على قيمة — جرب مصطلحاً آخر.',
    results: (n, q) => `${n} نتيجة لـ "${q}"`,
    emptyTitle: 'لا توجد نتائج',
    emptySubtitle: 'جرب مصطلحاً آخر مثل CRP أو TSH أو الكوليسترول.',
    unit: 'الوحدة',
  },
  es: {
    badge: 'Valores de laboratorio explicados — gratis y sin registro',
    title1: 'Léxico médico',
    title2: 'Valores de laboratorio',
    title3: 'explicados fácilmente',
    subtitle: '¿Qué significa mi valor de CRP? ¿Por qué está elevado el TSH? Este léxico explica sus valores de laboratorio en términos sencillos — con rangos normales, posibles causas y preguntas para su próxima cita médica.',
    searchPlaceholder: 'Buscar valor, ej. CRP, Hemoglobina, TSH …',
    noResults: 'No se encontró ningún valor — pruebe con otro término.',
    results: (n, q) => `${n} resultado${n !== 1 ? 's' : ''} para "${q}"`,
    emptyTitle: 'No se encontró ningún valor',
    emptySubtitle: 'Pruebe con otro término, ej. CRP, TSH o Colesterol.',
    unit: 'Unidad',
  },
  it: {
    badge: 'Valori di laboratorio spiegati — gratis e senza registrazione',
    title1: 'Lessico medico',
    title2: 'Valori di laboratorio',
    title3: 'spiegati semplicemente',
    subtitle: 'Cosa significa il mio valore di CRP? Perché il TSH è elevato? Questo lessico spiega i tuoi valori di laboratorio in termini semplici — con intervalli normali, cause possibili e domande per il tuo prossimo appuntamento medico.',
    searchPlaceholder: 'Cerca valore, es. CRP, Emoglobina, TSH …',
    noResults: 'Nessun valore trovato — prova un altro termine.',
    results: (n, q) => `${n} risultato${n !== 1 ? 'i' : ''} per "${q}"`,
    emptyTitle: 'Nessun valore trovato',
    emptySubtitle: 'Prova un altro termine, es. CRP, TSH o Colesterolo.',
    unit: 'Unità',
  },
  pt: {
    badge: 'Valores laboratoriais explicados — grátis e sem registo',
    title1: 'Léxico médico',
    title2: 'Valores laboratoriais',
    title3: 'explicados de forma simples',
    subtitle: 'O que significa o meu valor de CRP? Por que está elevado o TSH? Este léxico explica os seus valores laboratoriais em linguagem simples — com intervalos normais, causas possíveis e perguntas para a sua próxima consulta.',
    searchPlaceholder: 'Pesquisar valor, ex. CRP, Hemoglobina, TSH …',
    noResults: 'Nenhum valor encontrado — tente outro termo.',
    results: (n, q) => `${n} resultado${n !== 1 ? 's' : ''} para "${q}"`,
    emptyTitle: 'Nenhum valor encontrado',
    emptySubtitle: 'Tente outro termo, ex. CRP, TSH ou Colesterol.',
    unit: 'Unidade',
  },
  nl: {
    badge: 'Laboratoriumwaarden uitgelegd — gratis & zonder registratie',
    title1: 'Medisch lexicon',
    title2: 'Laboratoriumwaarden',
    title3: 'eenvoudig uitgelegd',
    subtitle: 'Wat betekent mijn CRP-waarde? Waarom is TSH verhoogd? Dit lexicon legt uw laboratoriumwaarden uit in begrijpelijke taal — met normale waarden, mogelijke oorzaken en vragen voor uw volgende artsbezoek.',
    searchPlaceholder: 'Zoek laboratoriumwaarde, bijv. CRP, Hemoglobine, TSH …',
    noResults: 'Geen waarde gevonden — probeer een andere zoekterm.',
    results: (n, q) => `${n} resultaat${n !== 1 ? 'en' : ''} voor "${q}"`,
    emptyTitle: 'Geen waarde gevonden',
    emptySubtitle: 'Probeer een andere zoekterm, bijv. CRP, TSH of Cholesterol.',
    unit: 'Eenheid',
  },
  pl: {
    badge: 'Wartości laboratoryjne wyjaśnione — bezpłatnie i bez rejestracji',
    title1: 'Leksykon medyczny',
    title2: 'Wartości laboratoryjne',
    title3: 'wyjaśnione prosto',
    subtitle: 'Co oznacza mój wynik CRP? Dlaczego TSH jest podwyższone? Ten leksykon wyjaśnia Twoje wyniki laboratoryjne prostym językiem — z normami, możliwymi przyczynami i pytaniami na wizytę u lekarza.',
    searchPlaceholder: 'Szukaj wartości, np. CRP, Hemoglobina, TSH …',
    noResults: 'Nie znaleziono wartości — spróbuj innego terminu.',
    results: (n, q) => `${n} wynik${n !== 1 ? 'i' : ''} dla „${q}"`,
    emptyTitle: 'Nie znaleziono wartości',
    emptySubtitle: 'Spróbuj innego terminu, np. CRP, TSH lub Cholesterol.',
    unit: 'Jednostka',
  },
  zh: {
    badge: '化验值解释 — 免费且无需注册',
    title1: '医学词典',
    title2: '化验值',
    title3: '简单解释',
    subtitle: 'CRP值是什么意思？为什么TSH升高？本词典用通俗语言解释您的化验值——含正常范围、可能原因以及下次就诊的问题。',
    searchPlaceholder: '搜索化验值，例如 CRP、血红蛋白、TSH …',
    noResults: '未找到化验值 — 请尝试其他搜索词。',
    results: (n, q) => `"${q}" 的 ${n} 个结果`,
    emptyTitle: '未找到化验值',
    emptySubtitle: '请尝试其他搜索词，例如 CRP、TSH 或胆固醇。',
    unit: '单位',
  },
  ja: {
    badge: '検査値の説明 — 無料・登録不要',
    title1: '医学辞典',
    title2: '検査値',
    title3: 'わかりやすく解説',
    subtitle: 'CRP値の意味は？TSHが高い理由は？この辞典では検査値をわかりやすく説明します — 基準値・考えられる原因・次回の受診に向けた質問付き。',
    searchPlaceholder: '検査値を検索、例: CRP, ヘモグロビン, TSH …',
    noResults: '見つかりませんでした — 別の検索語をお試しください。',
    results: (n, q) => `"${q}" の検索結果: ${n}件`,
    emptyTitle: '見つかりませんでした',
    emptySubtitle: '別の検索語をお試しください（例: CRP, TSH, コレステロール）。',
    unit: '単位',
  },
  ko: {
    badge: '검사 수치 설명 — 무료 & 회원가입 불필요',
    title1: '의학 사전',
    title2: '검사 수치',
    title3: '쉽게 설명',
    subtitle: 'CRP 수치는 무슨 의미인가요? TSH가 높은 이유는? 이 사전은 검사 수치를 쉬운 말로 설명합니다 — 정상 범위, 가능한 원인, 다음 진료를 위한 질문 포함.',
    searchPlaceholder: '검사 수치 검색, 예: CRP, 헤모글로빈, TSH …',
    noResults: '검색 결과가 없습니다 — 다른 검색어를 시도하세요.',
    results: (n, q) => `"${q}" 검색 결과 ${n}건`,
    emptyTitle: '검색 결과 없음',
    emptySubtitle: '다른 검색어를 시도하세요. 예: CRP, TSH, 콜레스테롤.',
    unit: '단위',
  },
  hi: {
    badge: 'लैब मान समझाए गए — निःशुल्क और पंजीकरण के बिना',
    title1: 'चिकित्सा शब्दकोश',
    title2: 'लैब मान',
    title3: 'सरल भाषा में',
    subtitle: 'मेरा CRP मान क्या दर्शाता है? TSH क्यों बढ़ा है? यह शब्दकोश आपके लैब मानों को सरल भाषा में समझाता है — सामान्य सीमाएं, संभावित कारण और आपके अगले डॉक्टर अपॉइंटमेंट के लिए प्रश्नों के साथ।',
    searchPlaceholder: 'लैब मान खोजें, जैसे CRP, हीमोग्लोबिन, TSH …',
    noResults: 'कोई मान नहीं मिला — दूसरा खोज शब्द आज़माएं।',
    results: (n, q) => `"${q}" के लिए ${n} परिणाम`,
    emptyTitle: 'कोई मान नहीं मिला',
    emptySubtitle: 'दूसरा शब्द आज़माएं, जैसे CRP, TSH या Cholesterol।',
    unit: 'इकाई',
  },
  bn: {
    badge: 'ল্যাব মান ব্যাখ্যা করা হয়েছে — বিনামূল্যে এবং নিবন্ধন ছাড়াই',
    title1: 'চিকিৎসা অভিধান',
    title2: 'ল্যাব মান',
    title3: 'সহজভাবে ব্যাখ্যা',
    subtitle: 'আমার CRP মান কী বোঝায়? TSH কেন বেশি? এই অভিধান আপনার ল্যাব মানগুলি সহজ ভাষায় ব্যাখ্যা করে — স্বাভাবিক সীমা, সম্ভাব্য কারণ এবং আপনার পরবর্তী ডাক্তার অ্যাপয়েন্টমেন্টের জন্য প্রশ্নসহ।',
    searchPlaceholder: 'ল্যাব মান অনুসন্ধান করুন, যেমন CRP, হিমোগ্লোবিন, TSH …',
    noResults: 'কোনো মান পাওয়া যায়নি — অন্য শব্দ চেষ্টা করুন।',
    results: (n, q) => `"${q}" এর জন্য ${n}টি ফলাফল`,
    emptyTitle: 'কোনো মান পাওয়া যায়নি',
    emptySubtitle: 'অন্য শব্দ চেষ্টা করুন, যেমন CRP, TSH বা Cholesterol।',
    unit: 'একক',
  },
  ur: {
    badge: 'لیب اقدار وضاحت — مفت اور بغیر رجسٹریشن',
    title1: 'طبی لغت',
    title2: 'لیب اقدار',
    title3: 'آسان وضاحت',
    subtitle: 'میری CRP قدر کا کیا مطلب ہے؟ TSH کیوں بلند ہے؟ یہ لغت آپ کی لیب اقدار کو سادہ زبان میں بیان کرتی ہے — معمول کی حد، ممکنہ اسباب اور اگلے ڈاکٹر کے دورے کے لیے سوالات کے ساتھ۔',
    searchPlaceholder: 'لیب قدر تلاش کریں، جیسے CRP, Hemoglobin, TSH …',
    noResults: 'کوئی قدر نہیں ملی — دوسرا لفظ آزمائیں۔',
    results: (n, q) => `"${q}" کے لیے ${n} نتائج`,
    emptyTitle: 'کوئی قدر نہیں ملی',
    emptySubtitle: 'دوسرا لفظ آزمائیں، جیسے CRP, TSH یا Cholesterol۔',
    unit: 'اکائی',
  },
  ru: {
    badge: 'Показатели анализов объяснены — бесплатно и без регистрации',
    title1: 'Медицинский словарь',
    title2: 'Показатели анализов',
    title3: 'простым языком',
    subtitle: 'Что означает мой CRP? Почему повышен ТТГ? Этот словарь объясняет ваши показатели анализов простым языком — с нормами, возможными причинами и вопросами для следующего визита к врачу.',
    searchPlaceholder: 'Искать показатель, напр. CRP, Гемоглобин, ТТГ …',
    noResults: 'Показатель не найден — попробуйте другой запрос.',
    results: (n, q) => `${n} результат${n > 1 ? 'а' : ''} для «${q}»`,
    emptyTitle: 'Показатель не найден',
    emptySubtitle: 'Попробуйте другой запрос, напр. CRP, TSH или Холестерин.',
    unit: 'Единица',
  },
}

export function getIndexUI(lang) {
  return INDEX_UI[lang] || INDEX_UI['en']
}
