const fs = require('fs')
const path = require('path')

const MESSAGES_DIR = path.join(__dirname, '../messages')

const T = {
  de: { tagline:"Laborwerte verstehen — in Ihrer Sprache, in 60 Sekunden.", product:"Produkt", upload:"Befund hochladen", prep:"Arzttermin vorbereiten", healthVault:"Health Vault", pricing:"Preise", learn:"Wissen", lexikon:"Medizinisches Lexikon", blog:"Blog", verstehen:"Arztbrief verstehen", company:"Unternehmen", privacy:"Datenschutz", terms:"AGB", contact:"Kontakt", disclaimer:"Kein Ersatz für ärztliche Beratung · DSGVO-konform", copyright:"© 2026 Medyra. Alle Rechte vorbehalten. Made in Germany." },
  en: { tagline:"Understand your lab results — in your language, in 60 seconds.", product:"Product", upload:"Upload Report", prep:"Prepare Doctor Visit", healthVault:"Health Vault", pricing:"Pricing", learn:"Learn", lexikon:"Medical Lexicon", blog:"Blog", verstehen:"Understand Medical Letters", company:"Company", privacy:"Privacy Policy", terms:"Terms", contact:"Contact", disclaimer:"Not a substitute for medical advice · GDPR-compliant", copyright:"© 2026 Medyra. All rights reserved. Made in Germany." },
  fr: { tagline:"Comprenez vos analyses — dans votre langue, en 60 secondes.", product:"Produit", upload:"Télécharger un rapport", prep:"Préparer une consultation", healthVault:"Health Vault", pricing:"Tarifs", learn:"Apprendre", lexikon:"Lexique médical", blog:"Blog", verstehen:"Comprendre les courriers médicaux", company:"Entreprise", privacy:"Confidentialité", terms:"CGU", contact:"Contact", disclaimer:"Ne remplace pas un avis médical · Conforme RGPD", copyright:"© 2026 Medyra. Tous droits réservés. Fabriqué en Allemagne." },
  tr: { tagline:"Laboratuvar sonuçlarınızı anlayın — kendi dilinizde, 60 saniyede.", product:"Ürün", upload:"Rapor Yükle", prep:"Doktor Ziyareti Hazırlığı", healthVault:"Sağlık Kasası", pricing:"Fiyatlar", learn:"Öğren", lexikon:"Tıbbi Sözlük", blog:"Blog", verstehen:"Tıbbi Mektupları Anla", company:"Şirket", privacy:"Gizlilik", terms:"Şartlar", contact:"İletişim", disclaimer:"Tıbbi tavsiyenin yerini tutmaz · GDPR uyumlu", copyright:"© 2026 Medyra. Tüm hakları saklıdır. Almanyada üretilmiştir." },
  ar: { tagline:"افهم نتائج تحاليلك — بلغتك، في 60 ثانية.", product:"المنتج", upload:"رفع التقرير", prep:"التحضير لزيارة الطبيب", healthVault:"خزنة الصحة", pricing:"الأسعار", learn:"تعلم", lexikon:"القاموس الطبي", blog:"المدونة", verstehen:"فهم الرسائل الطبية", company:"الشركة", privacy:"الخصوصية", terms:"الشروط", contact:"تواصل", disclaimer:"لا يغني عن الاستشارة الطبية · متوافق مع GDPR", copyright:"© 2026 Medyra. جميع الحقوق محفوظة. صنع في ألمانيا." },
  es: { tagline:"Entiende tus análisis — en tu idioma, en 60 segundos.", product:"Producto", upload:"Subir informe", prep:"Preparar visita médica", healthVault:"Health Vault", pricing:"Precios", learn:"Aprender", lexikon:"Léxico médico", blog:"Blog", verstehen:"Entender cartas médicas", company:"Empresa", privacy:"Privacidad", terms:"Términos", contact:"Contacto", disclaimer:"No sustituye el consejo médico · Conforme al RGPD", copyright:"© 2026 Medyra. Todos los derechos reservados. Hecho en Alemania." },
  it: { tagline:"Capisci i tuoi esami — nella tua lingua, in 60 secondi.", product:"Prodotto", upload:"Carica referto", prep:"Prepara visita medica", healthVault:"Health Vault", pricing:"Prezzi", learn:"Impara", lexikon:"Lessico medico", blog:"Blog", verstehen:"Capire lettere mediche", company:"Azienda", privacy:"Privacy", terms:"Termini", contact:"Contatti", disclaimer:"Non sostituisce il parere medico · Conforme al GDPR", copyright:"© 2026 Medyra. Tutti i diritti riservati. Prodotto in Germania." },
  pt: { tagline:"Entenda seus exames — no seu idioma, em 60 segundos.", product:"Produto", upload:"Enviar relatório", prep:"Preparar consulta", healthVault:"Health Vault", pricing:"Preços", learn:"Aprender", lexikon:"Léxico médico", blog:"Blog", verstehen:"Entender cartas médicas", company:"Empresa", privacy:"Privacidade", terms:"Termos", contact:"Contato", disclaimer:"Não substitui aconselhamento médico · Conforme ao GDPR", copyright:"© 2026 Medyra. Todos os direitos reservados. Feito na Alemanha." },
  nl: { tagline:"Begrijp uw bloedwaarden — in uw taal, in 60 seconden.", product:"Product", upload:"Rapport uploaden", prep:"Doktersbezoek voorbereiden", healthVault:"Health Vault", pricing:"Prijzen", learn:"Leren", lexikon:"Medisch lexicon", blog:"Blog", verstehen:"Medische brieven begrijpen", company:"Bedrijf", privacy:"Privacy", terms:"Voorwaarden", contact:"Contact", disclaimer:"Geen vervanging voor medisch advies · AVG-conform", copyright:"© 2026 Medyra. Alle rechten voorbehouden. Gemaakt in Duitsland." },
  pl: { tagline:"Zrozum swoje wyniki — w swoim języku, w 60 sekund.", product:"Produkt", upload:"Prześlij raport", prep:"Przygotuj wizytę", healthVault:"Health Vault", pricing:"Cennik", learn:"Ucz się", lexikon:"Leksykon medyczny", blog:"Blog", verstehen:"Zrozum listy medyczne", company:"Firma", privacy:"Prywatność", terms:"Warunki", contact:"Kontakt", disclaimer:"Nie zastępuje porady lekarskiej · Zgodny z RODO", copyright:"© 2026 Medyra. Wszelkie prawa zastrzeżone. Wyprodukowano w Niemczech." },
  zh: { tagline:"用您的语言理解化验结果——60秒内完成。", product:"产品", upload:"上传报告", prep:"准备就诊", healthVault:"健康保险库", pricing:"定价", learn:"学习", lexikon:"医学词典", blog:"博客", verstehen:"理解医疗信件", company:"公司", privacy:"隐私政策", terms:"条款", contact:"联系我们", disclaimer:"不能替代医疗建议 · 符合GDPR", copyright:"© 2026 Medyra. 保留所有权利。德国制造。" },
  ja: { tagline:"検査結果をあなたの言語で理解しましょう — 60秒で。", product:"製品", upload:"レポートをアップロード", prep:"診察の準備", healthVault:"ヘルスボルト", pricing:"料金", learn:"学ぶ", lexikon:"医学辞典", blog:"ブログ", verstehen:"医療書類を理解する", company:"会社", privacy:"プライバシー", terms:"利用規約", contact:"お問い合わせ", disclaimer:"医療アドバイスの代わりにはなりません · GDPR準拠", copyright:"© 2026 Medyra. 全著作権所有。ドイツ製。" },
  ko: { tagline:"검사 결과를 내 언어로 이해하세요 — 60초 안에.", product:"제품", upload:"보고서 업로드", prep:"진료 준비", healthVault:"헬스 볼트", pricing:"가격", learn:"학습", lexikon:"의학 사전", blog:"블로그", verstehen:"의료 서신 이해", company:"회사", privacy:"개인정보", terms:"이용약관", contact:"문의", disclaimer:"의료 조언을 대체하지 않습니다 · GDPR 준수", copyright:"© 2026 Medyra. 모든 권리 보유. 독일 제조." },
  hi: { tagline:"अपने परीक्षण परिणाम समझें — अपनी भाषा में, 60 सेकंड में।", product:"उत्पाद", upload:"रिपोर्ट अपलोड करें", prep:"डॉक्टर की यात्रा तैयार करें", healthVault:"हेल्थ वॉल्ट", pricing:"मूल्य निर्धारण", learn:"जानें", lexikon:"चिकित्सा शब्दकोश", blog:"ब्लॉग", verstehen:"चिकित्सा पत्र समझें", company:"कंपनी", privacy:"गोपनीयता", terms:"नियम", contact:"संपर्क", disclaimer:"चिकित्सा सलाह का विकल्प नहीं · GDPR अनुपालक", copyright:"© 2026 Medyra. सर्वाधिकार सुरक्षित। जर्मनी में निर्मित।" },
  ur: { tagline:"اپنے ٹیسٹ کے نتائج سمجھیں — اپنی زبان میں، 60 سیکنڈ میں۔", product:"مصنوع", upload:"رپورٹ اپلوڈ کریں", prep:"ڈاکٹر کے دورے کی تیاری", healthVault:"ہیلتھ والٹ", pricing:"قیمتیں", learn:"سیکھیں", lexikon:"طبی لغت", blog:"بلاگ", verstehen:"طبی خطوط سمجھیں", company:"کمپنی", privacy:"رازداری", terms:"شرائط", contact:"رابطہ", disclaimer:"طبی مشورے کا متبادل نہیں · GDPR کے مطابق", copyright:"© 2026 Medyra. جملہ حقوق محفوظ ہیں۔ جرمنی میں بنایا گیا۔" },
  ru: { tagline:"Понимайте результаты анализов — на вашем языке, за 60 секунд.", product:"Продукт", upload:"Загрузить отчёт", prep:"Подготовка к врачу", healthVault:"Хранилище здоровья", pricing:"Цены", learn:"Учиться", lexikon:"Медицинский словарь", blog:"Блог", verstehen:"Понять медицинские письма", company:"Компания", privacy:"Конфиденциальность", terms:"Условия", contact:"Контакт", disclaimer:"Не заменяет медицинскую консультацию · Соответствует GDPR", copyright:"© 2026 Medyra. Все права защищены. Сделано в Германии." },
  bn: { tagline:"আপনার পরীক্ষার ফলাফল বুঝুন — আপনার ভাষায়, ৬০ সেকেন্ডে।", product:"পণ্য", upload:"রিপোর্ট আপলোড করুন", prep:"ডাক্তারের সফরের প্রস্তুতি", healthVault:"হেলথ ভল্ট", pricing:"মূল্য নির্ধারণ", learn:"জানুন", lexikon:"চিকিৎসা অভিধান", blog:"ব্লগ", verstehen:"চিকিৎসা পত্র বুঝুন", company:"কোম্পানি", privacy:"গোপনীয়তা", terms:"শর্তাবলী", contact:"যোগাযোগ", disclaimer:"চিকিৎসা পরামর্শের বিকল্প নয় · GDPR সম্মত", copyright:"© 2026 Medyra. সর্বস্বত্ব সংরক্ষিত। জার্মানিতে তৈরি।" }
}

const files = fs.readdirSync(MESSAGES_DIR).filter(f => f.endsWith('.json'))
for (const file of files) {
  const lang = file.replace('.json', '')
  const t = T[lang]
  if (!t) { console.log('SKIP', lang); continue }
  const fp = path.join(MESSAGES_DIR, file)
  const json = JSON.parse(fs.readFileSync(fp, 'utf8'))
  json.siteFooter = t
  fs.writeFileSync(fp, JSON.stringify(json, null, 2) + '\n', 'utf8')
  console.log('UPDATED', lang)
}
