// Localized content for /medikamente. German is the SEO base; unlisted
// languages fall back to English. Medication names stay as printed on plans.
export const CONTENT = {
  de: {
    headerTitle: 'Medikamente verstehen',
    headerCta: 'Plan hochladen',
    badge: 'Medikationsplan · Rezept · BMP',
    h1a: 'Wissen, was Sie',
    h1b: 'einnehmen und warum',
    sub: '"1-0-1", "nüchtern", Wirkstoffnamen in Latein: Medyra erklärt Ihren Medikationsplan Medikament für Medikament, in klarer Sprache und in unter 60 Sekunden.',
    cta: 'Medikationsplan hochladen',
    mock: {
      labelOut: 'Medyra erklärt Ihren Plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Blutdrucksenker. Morgens eine Tablette, am besten immer zur gleichen Zeit.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Senkt den Blutzucker. Morgens und abends je eine Tablette zum Essen.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Magenschutz. Eine Tablette 30 Minuten vor dem Frühstück.' },
      ],
    },
    cardsLabel: 'Was Sie bekommen',
    cardsTitle: 'Jedes Medikament, klar erklärt',
    cards: [
      { icon: '💊', title: 'Wofür ist das Medikament?', desc: 'Jeder Wirkstoff auf Ihrem Plan wird erklärt: was er bewirkt und warum er Ihnen wahrscheinlich verschrieben wurde.' },
      { icon: '🕐', title: 'Einnahme, verständlich', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra übersetzt das Dosierschema in einen klaren Tagesablauf.' },
      { icon: '⚠️', title: 'Worauf Sie achten sollten', desc: 'Hinweise aus Ihrem Plan, verständlich zusammengefasst, plus die richtigen Fragen für Ihre Apotheke oder Arztpraxis.' },
    ],
    note: {
      icon: '🛡️', title: 'Sicherheit zuerst',
      text: 'Medyra ändert niemals Dosierungen und gibt keine Therapieempfehlungen. Es erklärt, was Ihre Ärztin verordnet hat, damit Sie in der Apotheke und im Arztgespräch die richtigen Fragen stellen können. Setzen Sie Medikamente nie ohne ärztliche Rücksprache ab.',
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Was kann ich hochladen?', a: 'Ihren bundeseinheitlichen Medikationsplan (BMP), Rezepte, Entlassungs-Medikationslisten oder ein Foto der Packungen mit Einnahmehinweisen, als PDF, Foto oder Text.' },
      { q: 'Erkennt Medyra Wechselwirkungen?', a: 'Medyra erklärt, was auf Ihrem Plan steht, und weist auf Hinweise im Dokument hin. Eine verbindliche Wechselwirkungsprüfung ersetzt das nicht: Die abschließende Prüfung gehört in Ihre Apotheke oder Arztpraxis. Medyra gibt Ihnen die richtigen Fragen dafür mit.' },
      { q: 'Ändert Medyra meine Dosierung?', a: 'Niemals. Medyra gibt keine Dosierungs- oder Therapieempfehlungen. Es erklärt ausschließlich verständlich, was Ihre Ärztin verordnet hat.' },
      { q: 'Sind meine Gesundheitsdaten sicher?', a: 'Ja. Verschlüsselte Verarbeitung, DSGVO-konformes Hosting in Frankfurt, automatische Löschung nach 30 Tagen (auf Wunsch sofort).' },
    ],
    ctaTitle: 'Nie wieder raten, wofür die Tablette ist',
    ctaSub: '3 Dokumente pro Monat kostenlos. DSGVO-konform, verschlüsselt, automatisch gelöscht.',
    ctaButton: 'Medikationsplan erklären lassen',
    ctaNote: 'Medyra ersetzt keine ärztliche oder pharmazeutische Beratung.',
  },

  en: {
    headerTitle: 'Understand medications',
    headerCta: 'Upload plan',
    badge: 'Medication plan · Prescription · BMP',
    h1a: 'Know what you take',
    h1b: 'and why',
    sub: '"1-0-1", "nüchtern", active ingredients in Latin: Medyra explains your German medication plan drug by drug, in plain language and in under 60 seconds.',
    cta: 'Upload medication plan',
    mock: {
      labelOut: 'Medyra explains your plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Blood pressure medication. One tablet in the morning, ideally always at the same time.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Lowers blood sugar. One tablet with breakfast and one with dinner.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Stomach protection. One tablet 30 minutes before breakfast.' },
      ],
    },
    cardsLabel: 'What you get',
    cardsTitle: 'Every medication, clearly explained',
    cards: [
      { icon: '💊', title: 'What is this medication for?', desc: 'Every active ingredient on your plan gets explained: what it does and why it was likely prescribed to you.' },
      { icon: '🕐', title: 'Dosing, made understandable', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra translates the dosing scheme into a clear daily routine.' },
      { icon: '⚠️', title: 'What to watch out for', desc: 'Notes from your plan, summarized clearly, plus the right questions for your pharmacy or doctor.' },
    ],
    note: {
      icon: '🛡️', title: 'Safety first',
      text: 'Medyra never changes dosages and gives no therapy recommendations. It explains what your doctor prescribed so you can ask the right questions at the pharmacy and in your appointment. Never stop a medication without talking to your doctor.',
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'What can I upload?', a: 'Your German standardized medication plan (BMP), prescriptions, discharge medication lists or a photo of the packages with dosing notes, as PDF, photo or text.' },
      { q: 'Does Medyra detect interactions?', a: 'Medyra explains what is on your plan and points out notes in the document. It does not replace a binding interaction check: the final check belongs with your pharmacy or doctor. Medyra gives you the right questions for that.' },
      { q: 'Does Medyra change my dosage?', a: 'Never. Medyra gives no dosage or therapy recommendations. It only explains, in plain language, what your doctor prescribed.' },
      { q: 'Is my health data safe?', a: 'Yes. Encrypted processing, GDPR compliant hosting in Frankfurt, automatic deletion after 30 days (immediately on request).' },
    ],
    ctaTitle: 'Never guess again what a pill is for',
    ctaSub: '3 documents per month free. GDPR compliant, encrypted, deleted automatically.',
    ctaButton: 'Explain my medication plan',
    ctaNote: 'Medyra does not replace medical or pharmaceutical advice.',
  },

  tr: {
    headerTitle: 'İlaçlarınızı anlayın',
    headerCta: 'Plan yükle',
    badge: 'İlaç planı · Reçete · BMP',
    h1a: 'Ne aldığınızı',
    h1b: 've neden aldığınızı bilin',
    sub: '"1-0-1", "nüchtern", Latince etken maddeler: Medyra Almanca ilaç planınızı ilaç ilaç, anlaşılır dille ve 60 saniyeden kısa sürede açıklar.',
    cta: 'İlaç planını yükle',
    mock: {
      labelOut: 'Medyra planınızı açıklıyor',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Tansiyon ilacı. Sabahları bir tablet, mümkünse hep aynı saatte.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Kan şekerini düşürür. Sabah ve akşam yemekle birer tablet.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Mide koruyucu. Kahvaltıdan 30 dakika önce bir tablet.' },
      ],
    },
    cardsLabel: 'Ne alırsınız',
    cardsTitle: 'Her ilaç, net açıklanmış',
    cards: [
      { icon: '💊', title: 'Bu ilaç ne için?', desc: 'Planınızdaki her etken madde açıklanır: ne işe yarar ve size neden yazılmış olabilir.' },
      { icon: '🕐', title: 'Kullanım, anlaşılır', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra doz şemasını net bir günlük düzene çevirir.' },
      { icon: '⚠️', title: 'Nelere dikkat etmelisiniz', desc: 'Planınızdaki notlar anlaşılır şekilde özetlenir; eczaneniz veya doktorunuz için doğru sorularla birlikte.' },
    ],
    note: {
      icon: '🛡️', title: 'Önce güvenlik',
      text: 'Medyra asla doz değiştirmez ve tedavi önerisi vermez. Doktorunuzun ne yazdığını açıklar; böylece eczanede ve muayenede doğru soruları sorabilirsiniz. İlaçları asla doktorunuza danışmadan bırakmayın.',
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Neler yükleyebilirim?', a: 'Standart Alman ilaç planınızı (BMP), reçeteleri, taburcu ilaç listelerini veya kullanım notlu kutu fotoğraflarını; PDF, fotoğraf veya metin olarak.' },
      { q: 'Medyra etkileşimleri tanır mı?', a: 'Medyra planınızda yazanları açıklar ve belgedeki uyarılara dikkat çeker. Bağlayıcı bir etkileşim kontrolünün yerine geçmez: son kontrol eczanenizin veya doktorunuzun işidir. Medyra bunun için doğru soruları verir.' },
      { q: 'Medyra dozumu değiştirir mi?', a: 'Asla. Medyra doz veya tedavi önerisi vermez. Yalnızca doktorunuzun yazdığını anlaşılır şekilde açıklar.' },
      { q: 'Sağlık verilerim güvende mi?', a: 'Evet. Şifreli işleme, Frankfurt’ta GDPR uyumlu barındırma, 30 gün sonra otomatik silme (istekle hemen).' },
    ],
    ctaTitle: 'Hangi hap ne için, bir daha tahmin etmeyin',
    ctaSub: 'Ayda 3 belge ücretsiz. GDPR uyumlu, şifreli, otomatik silinir.',
    ctaButton: 'İlaç planımı açıkla',
    ctaNote: 'Medyra tıbbi veya eczacılık danışmanlığının yerini tutmaz.',
  },

  ar: {
    headerTitle: 'افهم أدويتك',
    headerCta: 'ارفع الخطة',
    badge: 'خطة أدوية · وصفة · BMP',
    h1a: 'اعرف ماذا تتناول',
    h1b: 'ولماذا',
    sub: '"1-0-1"، "nüchtern"، أسماء لاتينية: يشرح Medyra خطة أدويتك الألمانية دواءً دواءً، بلغة واضحة وفي أقل من 60 ثانية.',
    cta: 'ارفع خطة الأدوية',
    mock: {
      labelOut: 'Medyra يشرح خطتك',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'دواء لضغط الدم. قرص واحد صباحاً، ويفضل في نفس الوقت دائماً.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'يخفض سكر الدم. قرص مع الفطور وقرص مع العشاء.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'حماية للمعدة. قرص قبل الفطور بـ 30 دقيقة.' },
      ],
    },
    cardsLabel: 'ما تحصل عليه',
    cardsTitle: 'كل دواء، مشروح بوضوح',
    cards: [
      { icon: '💊', title: 'لماذا هذا الدواء؟', desc: 'كل مادة فعالة في خطتك تُشرح: ماذا تفعل ولماذا وُصفت لك على الأرجح.' },
      { icon: '🕐', title: 'طريقة التناول، بوضوح', desc: '"1-0-1"، "nüchtern": يحول Medyra جدول الجرعات إلى روتين يومي واضح.' },
      { icon: '⚠️', title: 'ما الذي تنتبه له', desc: 'ملاحظات خطتك ملخصة بوضوح، مع الأسئلة الصحيحة لصيدليتك أو طبيبك.' },
    ],
    note: {
      icon: '🛡️', title: 'السلامة أولاً',
      text: 'لا يغيّر Medyra الجرعات أبداً ولا يقدم توصيات علاجية. إنه يشرح ما وصفه طبيبك لتطرح الأسئلة الصحيحة في الصيدلية وفي الموعد. لا توقف دواءً أبداً دون استشارة طبيبك.',
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما الذي يمكنني رفعه؟', a: 'خطة الأدوية الألمانية الموحدة (BMP)، الوصفات، قوائم أدوية الخروج أو صورة للعبوات مع ملاحظات التناول؛ كملف PDF أو صورة أو نص.' },
      { q: 'هل يكشف Medyra التداخلات الدوائية؟', a: 'يشرح Medyra ما في خطتك وينبه إلى الملاحظات في المستند. هذا لا يغني عن فحص تداخلات ملزم: الفحص النهائي من اختصاص صيدليتك أو طبيبك. يمنحك Medyra الأسئلة الصحيحة لذلك.' },
      { q: 'هل يغيّر Medyra جرعتي؟', a: 'أبداً. لا يقدم Medyra توصيات جرعات أو علاج. إنه يشرح فقط بوضوح ما وصفه طبيبك.' },
      { q: 'هل بياناتي الصحية آمنة؟', a: 'نعم. معالجة مشفرة، استضافة متوافقة مع GDPR في فرانكفورت، حذف تلقائي بعد 30 يوماً (وفوراً عند الطلب).' },
    ],
    ctaTitle: 'لا تخمن بعد اليوم لماذا هذا القرص',
    ctaSub: '3 مستندات شهرياً مجاناً. متوافق مع GDPR، مشفر، يُحذف تلقائياً.',
    ctaButton: 'اشرح خطة أدويتي',
    ctaNote: 'لا يحل Medyra محل الاستشارة الطبية أو الصيدلانية.',
  },

  ru: {
    headerTitle: 'Понять лекарства',
    headerCta: 'Загрузить план',
    badge: 'План приёма · Рецепт · BMP',
    h1a: 'Знайте, что вы принимаете',
    h1b: 'и зачем',
    sub: '"1-0-1", "nüchtern", действующие вещества на латыни: Medyra объясняет ваш немецкий план приёма лекарство за лекарством, простым языком и меньше чем за 60 секунд.',
    cta: 'Загрузить план приёма',
    mock: {
      labelOut: 'Medyra объясняет ваш план',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Препарат от давления. Одна таблетка утром, желательно всегда в одно время.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Снижает сахар в крови. По таблетке утром и вечером во время еды.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Защита желудка. Одна таблетка за 30 минут до завтрака.' },
      ],
    },
    cardsLabel: 'Что вы получаете',
    cardsTitle: 'Каждое лекарство, понятно объяснённое',
    cards: [
      { icon: '💊', title: 'Для чего это лекарство?', desc: 'Каждое действующее вещество в плане объясняется: что оно делает и почему его, вероятно, вам назначили.' },
      { icon: '🕐', title: 'Приём, понятным языком', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra превращает схему дозирования в понятный распорядок дня.' },
      { icon: '⚠️', title: 'На что обратить внимание', desc: 'Примечания из вашего плана, понятно резюмированные, плюс правильные вопросы для аптеки или врача.' },
    ],
    note: {
      icon: '🛡️', title: 'Безопасность прежде всего',
      text: 'Medyra никогда не меняет дозировки и не даёт рекомендаций по лечению. Он объясняет назначения врача, чтобы вы могли задать правильные вопросы в аптеке и на приёме. Никогда не отменяйте лекарства без согласования с врачом.',
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Что можно загрузить?', a: 'Немецкий стандартизированный план приёма (BMP), рецепты, списки лекарств из выписки или фото упаковок с указаниями; как PDF, фото или текст.' },
      { q: 'Определяет ли Medyra взаимодействия?', a: 'Medyra объясняет содержание плана и обращает внимание на примечания в документе. Это не заменяет обязательную проверку взаимодействий: финальная проверка остаётся за аптекой или врачом. Medyra даёт вам правильные вопросы для этого.' },
      { q: 'Меняет ли Medyra мою дозировку?', a: 'Никогда. Medyra не даёт рекомендаций по дозировкам или лечению. Он лишь понятно объясняет, что назначил ваш врач.' },
      { q: 'Мои данные о здоровье в безопасности?', a: 'Да. Зашифрованная обработка, GDPR совместимый хостинг во Франкфурте, автоматическое удаление через 30 дней (по желанию сразу).' },
    ],
    ctaTitle: 'Больше не гадайте, зачем эта таблетка',
    ctaSub: '3 документа в месяц бесплатно. GDPR, шифрование, автоматическое удаление.',
    ctaButton: 'Объяснить мой план приёма',
    ctaNote: 'Medyra не заменяет медицинскую или фармацевтическую консультацию.',
  },

  fr: {
    headerTitle: 'Comprendre vos médicaments', headerCta: 'Télécharger le plan',
    badge: 'Plan de médication · Ordonnance · BMP',
    h1a: 'Savoir ce que vous', h1b: 'prenez et pourquoi',
    sub: '"1-0-1", "nüchtern", noms de substances en latin : Medyra explique votre plan de médication allemand médicament par médicament, en langage clair et en moins de 60 secondes.',
    cta: 'Télécharger le plan de médication',
    mock: {
      labelOut: 'Medyra explique votre plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Médicament pour la tension artérielle. Un comprimé le matin, idéalement toujours à la même heure.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Réduit la glycémie. Un comprimé avec le petit-déjeuner et un avec le dîner.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: "Protection de l'estomac. Un comprimé 30 minutes avant le petit-déjeuner." },
      ],
    },
    cardsLabel: 'Ce que vous obtenez', cardsTitle: 'Chaque médicament, clairement expliqué',
    cards: [
      { icon: '💊', title: 'À quoi sert ce médicament ?', desc: 'Chaque substance active de votre plan est expliquée : ce qu’elle fait et pourquoi elle vous a probablement été prescrite.' },
      { icon: '🕐', title: 'La prise, rendue compréhensible', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten" : Medyra traduit le schéma posologique en routine quotidienne claire.' },
      { icon: '⚠️', title: 'À quoi faire attention', desc: 'Les notes de votre plan, résumées clairement, plus les bonnes questions pour votre pharmacie ou votre médecin.' },
    ],
    note: {
      icon: '🛡️', title: 'La sécurité avant tout',
      text: "Medyra ne modifie jamais les dosages et ne donne aucune recommandation thérapeutique. Il explique ce que votre médecin a prescrit afin que vous puissiez poser les bonnes questions à la pharmacie et lors de votre consultation. N'arrêtez jamais un médicament sans en parler à votre médecin.",
    },
    faqTitle: 'Questions fréquentes',
    faq: [
      { q: 'Que puis-je télécharger ?', a: 'Votre plan de médication standardisé allemand (BMP), ordonnances, listes de médication de sortie ou une photo des emballages avec les indications de prise, en PDF, photo ou texte.' },
      { q: 'Medyra détecte-t-il les interactions ?', a: "Medyra explique ce qui figure sur votre plan et signale les remarques du document. Cela ne remplace pas une vérification d'interaction contraignante : la vérification finale relève de votre pharmacie ou de votre médecin. Medyra vous donne les bonnes questions pour cela." },
      { q: 'Medyra modifie-t-il mon dosage ?', a: 'Jamais. Medyra ne donne aucune recommandation de dosage ou de traitement. Il explique uniquement, en langage clair, ce que votre médecin a prescrit.' },
      { q: 'Mes données de santé sont-elles en sécurité ?', a: 'Oui. Traitement chiffré, hébergement conforme au RGPD à Francfort, suppression automatique après 30 jours (immédiatement sur demande).' },
    ],
    ctaTitle: 'Ne devinez plus jamais à quoi sert un comprimé',
    ctaSub: '3 documents par mois gratuits. Conforme au RGPD, chiffré, supprimé automatiquement.',
    ctaButton: 'Expliquer mon plan de médication',
    ctaNote: 'Medyra ne remplace pas un avis médical ou pharmaceutique.',
  },

  es: {
    headerTitle: 'Entender sus medicamentos', headerCta: 'Subir plan',
    badge: 'Plan de medicación · Receta · BMP',
    h1a: 'Sepa qué toma', h1b: 'y por qué',
    sub: '"1-0-1", "nüchtern", principios activos en latín: Medyra explica su plan de medicación alemán medicamento por medicamento, en lenguaje claro y en menos de 60 segundos.',
    cta: 'Subir plan de medicación',
    mock: {
      labelOut: 'Medyra explica su plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Medicamento para la presión arterial. Un comprimido por la mañana, idealmente siempre a la misma hora.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Reduce el azúcar en sangre. Un comprimido con el desayuno y otro con la cena.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Protección del estómago. Un comprimido 30 minutos antes del desayuno.' },
      ],
    },
    cardsLabel: 'Lo que obtiene', cardsTitle: 'Cada medicamento, claramente explicado',
    cards: [
      { icon: '💊', title: '¿Para qué es este medicamento?', desc: 'Se explica cada principio activo de su plan: qué hace y por qué probablemente se lo recetaron.' },
      { icon: '🕐', title: 'Toma, comprensible', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra traduce el esquema de dosificación en una rutina diaria clara.' },
      { icon: '⚠️', title: 'A qué prestar atención', desc: 'Notas de su plan, resumidas con claridad, además de las preguntas correctas para su farmacia o médico.' },
    ],
    note: {
      icon: '🛡️', title: 'La seguridad primero',
      text: 'Medyra nunca cambia dosis ni da recomendaciones terapéuticas. Explica lo que su médico recetó para que pueda hacer las preguntas correctas en la farmacia y en su consulta. Nunca suspenda un medicamento sin hablar con su médico.',
    },
    faqTitle: 'Preguntas frecuentes',
    faq: [
      { q: '¿Qué puedo subir?', a: 'Su plan de medicación estandarizado alemán (BMP), recetas, listas de medicación de alta o una foto de los envases con las indicaciones, en PDF, foto o texto.' },
      { q: '¿Medyra detecta interacciones?', a: 'Medyra explica lo que hay en su plan y señala las notas del documento. Esto no sustituye una verificación vinculante de interacciones: la verificación final corresponde a su farmacia o médico. Medyra le da las preguntas correctas para ello.' },
      { q: '¿Medyra cambia mi dosis?', a: 'Nunca. Medyra no da recomendaciones de dosis ni de tratamiento. Solo explica, en lenguaje claro, lo que su médico recetó.' },
      { q: '¿Están seguros mis datos de salud?', a: 'Sí. Procesamiento cifrado, alojamiento conforme al RGPD en Fráncfort, eliminación automática después de 30 días (inmediata si se solicita).' },
    ],
    ctaTitle: 'No vuelva a adivinar para qué es una pastilla',
    ctaSub: '3 documentos al mes gratis. Conforme al RGPD, cifrado, eliminado automáticamente.',
    ctaButton: 'Explicar mi plan de medicación',
    ctaNote: 'Medyra no sustituye el consejo médico o farmacéutico.',
  },

  it: {
    headerTitle: 'Capire i tuoi farmaci', headerCta: 'Carica il piano',
    badge: 'Piano terapeutico · Ricetta · BMP',
    h1a: 'Sapere cosa', h1b: 'prendi e perché',
    sub: '"1-0-1", "nüchtern", principi attivi in latino: Medyra spiega il tuo piano terapeutico tedesco farmaco per farmaco, in linguaggio semplice e in meno di 60 secondi.',
    cta: 'Carica il piano terapeutico',
    mock: {
      labelOut: 'Medyra spiega il tuo piano',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Farmaco per la pressione. Una compressa al mattino, idealmente sempre alla stessa ora.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Riduce la glicemia. Una compressa a colazione e una a cena.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Protezione dello stomaco. Una compressa 30 minuti prima di colazione.' },
      ],
    },
    cardsLabel: 'Cosa ottieni', cardsTitle: 'Ogni farmaco, spiegato chiaramente',
    cards: [
      { icon: '💊', title: 'A cosa serve questo farmaco?', desc: 'Ogni principio attivo nel tuo piano viene spiegato: cosa fa e perché probabilmente ti è stato prescritto.' },
      { icon: '🕐', title: 'Assunzione, resa comprensibile', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra traduce lo schema posologico in una routine giornaliera chiara.' },
      { icon: '⚠️', title: 'A cosa fare attenzione', desc: 'Note dal tuo piano, riassunte chiaramente, più le domande giuste per la tua farmacia o il tuo medico.' },
    ],
    note: {
      icon: '🛡️', title: 'Prima la sicurezza',
      text: 'Medyra non modifica mai i dosaggi e non dà raccomandazioni terapeutiche. Spiega cosa ha prescritto il tuo medico così puoi fare le domande giuste in farmacia e durante la visita. Non sospendere mai un farmaco senza parlarne con il tuo medico.',
    },
    faqTitle: 'Domande frequenti',
    faq: [
      { q: 'Cosa posso caricare?', a: 'Il tuo piano terapeutico standardizzato tedesco (BMP), ricette, liste di farmaci alla dimissione o una foto delle confezioni con le indicazioni, come PDF, foto o testo.' },
      { q: 'Medyra rileva le interazioni?', a: 'Medyra spiega cosa c’è nel tuo piano e segnala le note nel documento. Questo non sostituisce un controllo vincolante delle interazioni: il controllo finale spetta alla tua farmacia o al tuo medico. Medyra ti fornisce le domande giuste per questo.' },
      { q: 'Medyra modifica il mio dosaggio?', a: 'Mai. Medyra non dà raccomandazioni su dosaggio o terapia. Spiega solo, in linguaggio semplice, cosa ha prescritto il tuo medico.' },
      { q: 'I miei dati sanitari sono al sicuro?', a: 'Sì. Elaborazione crittografata, hosting conforme al GDPR a Francoforte, eliminazione automatica dopo 30 giorni (subito su richiesta).' },
    ],
    ctaTitle: 'Non indovinare più a cosa serve una pillola',
    ctaSub: '3 documenti al mese gratis. Conforme al GDPR, crittografato, eliminato automaticamente.',
    ctaButton: 'Spiega il mio piano terapeutico',
    ctaNote: 'Medyra non sostituisce il consiglio medico o farmaceutico.',
  },

  pt: {
    headerTitle: 'Entender seus medicamentos', headerCta: 'Enviar plano',
    badge: 'Plano de medicação · Receita · BMP',
    h1a: 'Saiba o que você', h1b: 'toma e por quê',
    sub: '"1-0-1", "nüchtern", princípios ativos em latim: a Medyra explica seu plano de medicação alemão medicamento por medicamento, em linguagem clara e em menos de 60 segundos.',
    cta: 'Enviar plano de medicação',
    mock: {
      labelOut: 'A Medyra explica seu plano',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Medicamento para pressão arterial. Um comprimido pela manhã, idealmente sempre no mesmo horário.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Reduz o açúcar no sangue. Um comprimido no café da manhã e outro no jantar.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Proteção estomacal. Um comprimido 30 minutos antes do café da manhã.' },
      ],
    },
    cardsLabel: 'O que você recebe', cardsTitle: 'Cada medicamento, claramente explicado',
    cards: [
      { icon: '💊', title: 'Para que serve este medicamento?', desc: 'Cada princípio ativo do seu plano é explicado: o que faz e por que provavelmente foi receitado a você.' },
      { icon: '🕐', title: 'Uso, de forma compreensível', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": a Medyra traduz o esquema de dosagem em uma rotina diária clara.' },
      { icon: '⚠️', title: 'O que observar', desc: 'Notas do seu plano, resumidas claramente, além das perguntas certas para sua farmácia ou médico.' },
    ],
    note: {
      icon: '🛡️', title: 'Segurança em primeiro lugar',
      text: 'A Medyra nunca altera dosagens e não faz recomendações terapêuticas. Ela explica o que seu médico prescreveu para que você possa fazer as perguntas certas na farmácia e na consulta. Nunca interrompa um medicamento sem falar com seu médico.',
    },
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'O que posso enviar?', a: 'Seu plano de medicação padronizado alemão (BMP), receitas, listas de medicação de alta ou uma foto das embalagens com as instruções, em PDF, foto ou texto.' },
      { q: 'A Medyra detecta interações?', a: 'A Medyra explica o que está no seu plano e aponta notas no documento. Isso não substitui uma verificação vinculante de interações: a verificação final cabe à sua farmácia ou médico. A Medyra fornece as perguntas certas para isso.' },
      { q: 'A Medyra altera minha dosagem?', a: 'Nunca. A Medyra não faz recomendações de dosagem ou tratamento. Ela apenas explica, em linguagem clara, o que seu médico prescreveu.' },
      { q: 'Meus dados de saúde estão seguros?', a: 'Sim. Processamento criptografado, hospedagem em conformidade com o RGPD em Frankfurt, exclusão automática após 30 dias (imediatamente a pedido).' },
    ],
    ctaTitle: 'Nunca mais tenha que adivinhar para que serve um comprimido',
    ctaSub: '3 documentos por mês grátis. Conforme o RGPD, criptografado, excluído automaticamente.',
    ctaButton: 'Explicar meu plano de medicação',
    ctaNote: 'A Medyra não substitui o aconselhamento médico ou farmacêutico.',
  },

  nl: {
    headerTitle: 'Uw medicijnen begrijpen', headerCta: 'Schema uploaden',
    badge: 'Medicatieschema · Recept · BMP',
    h1a: 'Weet wat u', h1b: 'inneemt en waarom',
    sub: '"1-0-1", "nüchtern", werkzame stoffen in het Latijn: Medyra legt uw Duitse medicatieschema medicijn voor medicijn uit, in duidelijke taal en in minder dan 60 seconden.',
    cta: 'Medicatieschema uploaden',
    mock: {
      labelOut: 'Medyra legt uw schema uit',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Bloeddrukmedicijn. Eén tablet ’s ochtends, idealiter altijd op hetzelfde tijdstip.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Verlaagt de bloedsuiker. Eén tablet bij het ontbijt en één bij het avondeten.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Maagbescherming. Eén tablet 30 minuten voor het ontbijt.' },
      ],
    },
    cardsLabel: 'Wat u krijgt', cardsTitle: 'Elk medicijn, duidelijk uitgelegd',
    cards: [
      { icon: '💊', title: 'Waarvoor is dit medicijn?', desc: 'Elke werkzame stof op uw schema wordt uitgelegd: wat het doet en waarom het u waarschijnlijk is voorgeschreven.' },
      { icon: '🕐', title: 'Inname, begrijpelijk gemaakt', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra vertaalt het doseringsschema naar een duidelijke dagelijkse routine.' },
      { icon: '⚠️', title: 'Waar u op moet letten', desc: 'Notities uit uw schema, duidelijk samengevat, plus de juiste vragen voor uw apotheek of arts.' },
    ],
    note: {
      icon: '🛡️', title: 'Veiligheid voorop',
      text: 'Medyra wijzigt nooit doseringen en geeft geen therapieadvies. Het legt uit wat uw arts heeft voorgeschreven, zodat u de juiste vragen kunt stellen bij de apotheek en tijdens uw afspraak. Stop nooit met een medicijn zonder overleg met uw arts.',
    },
    faqTitle: 'Veelgestelde vragen',
    faq: [
      { q: 'Wat kan ik uploaden?', a: 'Uw Duitse gestandaardiseerde medicatieschema (BMP), recepten, ontslagmedicatielijsten of een foto van de verpakkingen met doseringsinstructies, als PDF, foto of tekst.' },
      { q: 'Herkent Medyra interacties?', a: 'Medyra legt uit wat er op uw schema staat en wijst op opmerkingen in het document. Dit vervangt geen bindende interactiecontrole: de definitieve controle hoort bij uw apotheek of arts. Medyra geeft u daarvoor de juiste vragen.' },
      { q: 'Wijzigt Medyra mijn dosering?', a: 'Nooit. Medyra geeft geen doserings- of behandeladvies. Het legt alleen in duidelijke taal uit wat uw arts heeft voorgeschreven.' },
      { q: 'Zijn mijn gezondheidsgegevens veilig?', a: 'Ja. Versleutelde verwerking, AVG-conforme hosting in Frankfurt, automatische verwijdering na 30 dagen (direct op verzoek).' },
    ],
    ctaTitle: 'Nooit meer gissen waarvoor een pil dient',
    ctaSub: '3 documenten per maand gratis. AVG-conform, versleuteld, automatisch verwijderd.',
    ctaButton: 'Leg mijn medicatieschema uit',
    ctaNote: 'Medyra vervangt geen medisch of farmaceutisch advies.',
  },

  pl: {
    headerTitle: 'Zrozumieć swoje leki', headerCta: 'Prześlij plan',
    badge: 'Plan leków · Recepta · BMP',
    h1a: 'Wiedz, co', h1b: 'zażywasz i dlaczego',
    sub: '"1-0-1", "nüchtern", nazwy substancji po łacinie: Medyra wyjaśnia twój niemiecki plan leków, lek po leku, prostym językiem i w mniej niż 60 sekund.',
    cta: 'Prześlij plan leków',
    mock: {
      labelOut: 'Medyra wyjaśnia twój plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Lek na ciśnienie krwi. Jedna tabletka rano, najlepiej zawsze o tej samej porze.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Obniża poziom cukru we krwi. Jedna tabletka ze śniadaniem i jedna z kolacją.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Ochrona żołądka. Jedna tabletka 30 minut przed śniadaniem.' },
      ],
    },
    cardsLabel: 'Co otrzymujesz', cardsTitle: 'Każdy lek, jasno wyjaśniony',
    cards: [
      { icon: '💊', title: 'Do czego służy ten lek?', desc: 'Każda substancja czynna w twoim planie jest wyjaśniona: co robi i dlaczego prawdopodobnie została ci przepisana.' },
      { icon: '🕐', title: 'Dawkowanie, zrozumiałe', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra tłumaczy schemat dawkowania na jasny codzienny rytm.' },
      { icon: '⚠️', title: 'Na co zwrócić uwagę', desc: 'Notatki z twojego planu, jasno podsumowane, plus właściwe pytania do apteki lub lekarza.' },
    ],
    note: {
      icon: '🛡️', title: 'Bezpieczeństwo przede wszystkim',
      text: 'Medyra nigdy nie zmienia dawek i nie udziela zaleceń terapeutycznych. Wyjaśnia, co przepisał twój lekarz, abyś mógł zadać właściwe pytania w aptece i podczas wizyty. Nigdy nie odstawiaj leku bez konsultacji z lekarzem.',
    },
    faqTitle: 'Najczęstsze pytania',
    faq: [
      { q: 'Co mogę przesłać?', a: 'Twój niemiecki znormalizowany plan leków (BMP), recepty, listy leków przy wypisie lub zdjęcie opakowań z instrukcjami dawkowania, jako PDF, zdjęcie lub tekst.' },
      { q: 'Czy Medyra wykrywa interakcje?', a: 'Medyra wyjaśnia, co jest w twoim planie, i wskazuje uwagi w dokumencie. Nie zastępuje to wiążącej kontroli interakcji: ostateczna kontrola należy do twojej apteki lub lekarza. Medyra podaje ci właściwe pytania do tego.' },
      { q: 'Czy Medyra zmienia moją dawkę?', a: 'Nigdy. Medyra nie udziela zaleceń dotyczących dawkowania ani leczenia. Wyjaśnia jedynie prostym językiem, co przepisał twój lekarz.' },
      { q: 'Czy moje dane zdrowotne są bezpieczne?', a: 'Tak. Szyfrowane przetwarzanie, hosting zgodny z RODO we Frankfurcie, automatyczne usunięcie po 30 dniach (natychmiast na żądanie).' },
    ],
    ctaTitle: 'Nie zgaduj już, do czego jest ta tabletka',
    ctaSub: '3 dokumenty miesięcznie za darmo. Zgodność z RODO, szyfrowanie, automatyczne usuwanie.',
    ctaButton: 'Wyjaśnij mój plan leków',
    ctaNote: 'Medyra nie zastępuje porady medycznej ani farmaceutycznej.',
  },

  zh: {
    headerTitle: '看懂您的药物', headerCta: '上传用药计划',
    badge: '用药计划 · 处方 · BMP',
    h1a: '了解您正在服用', h1b: '什么药以及为什么',
    sub: '"1-0-1"、"nüchtern"（空腹）、拉丁文药物成分名称：Medyra逐一解释您的德文用药计划，用通俗语言，不到60秒。',
    cta: '上传用药计划',
    mock: {
      labelOut: 'Medyra 解释您的计划',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: '降血压药。早上一片，最好每天固定时间服用。' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: '降低血糖。早餐和晚餐各服一片。' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: '胃部保护剂。早餐前30分钟服用一片。' },
      ],
    },
    cardsLabel: '您将获得', cardsTitle: '每种药物，清晰解释',
    cards: [
      { icon: '💊', title: '这种药是治什么的？', desc: '解释您计划中的每种活性成分：它的作用是什么，为什么很可能给您开了这个药。' },
      { icon: '🕐', title: '用法用量，通俗易懂', desc: '"1-0-1"、"nüchtern"（空腹）、"zu den Mahlzeiten"（随餐）：Medyra将用药方案翻译成清晰的日常安排。' },
      { icon: '⚠️', title: '需要注意什么', desc: '清晰总结您计划中的注意事项，以及向药房或医生咨询的正确问题。' },
    ],
    note: {
      icon: '🛡️', title: '安全第一',
      text: 'Medyra 绝不会更改剂量，也不会提供治疗建议。它只是解释您的医生开了什么药，以便您在药房和就诊时提出正确的问题。切勿在未咨询医生的情况下自行停药。',
    },
    faqTitle: '常见问题',
    faq: [
      { q: '我可以上传什么？', a: '您的德国标准化用药计划（BMP）、处方、出院用药清单，或药品包装带用法说明的照片，可以是PDF、照片或文本格式。' },
      { q: 'Medyra能识别药物相互作用吗？', a: 'Medyra解释您计划中的内容，并指出文件中的注意事项。这不能替代具有约束力的相互作用检查：最终检查应由您的药房或医生进行。Medyra会为此提供正确的问题。' },
      { q: 'Medyra会更改我的剂量吗？', a: '绝不会。Medyra不提供剂量或治疗建议，只用通俗语言解释您的医生开了什么药。' },
      { q: '我的健康数据安全吗？', a: '是的。加密处理，符合GDPR标准，托管在法兰克福，30天后自动删除（应要求可立即删除）。' },
    ],
    ctaTitle: '再也不用猜测一片药是做什么的',
    ctaSub: '每月3份文件免费。符合GDPR，加密处理，自动删除。',
    ctaButton: '解释我的用药计划',
    ctaNote: 'Medyra 不能替代医疗或药学建议。',
  },

  ja: {
    headerTitle: 'お薬を理解する', headerCta: 'プランをアップロード',
    badge: '服薬プラン・処方箋・BMP',
    h1a: '何を服用しているか、', h1b: 'そしてなぜかを知る',
    sub: '"1-0-1"、"nüchtern"（空腹時）、ラテン語の有効成分名：Medyraはあなたのドイツ語の服薬プランを薬ごとに、分かりやすい言葉で60秒以内に説明します。',
    cta: '服薬プランをアップロード',
    mock: {
      labelOut: 'Medyraがあなたのプランを説明します',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: '血圧の薬です。朝1錠、できれば毎日同じ時間に服用してください。' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: '血糖値を下げます。朝食時と夕食時にそれぞれ1錠。' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: '胃の保護薬です。朝食の30分前に1錠。' },
      ],
    },
    cardsLabel: '得られるもの', cardsTitle: 'すべての薬を明確に説明',
    cards: [
      { icon: '💊', title: 'この薬は何のためのものですか？', desc: 'プラン上の各有効成分を説明します：何をするのか、なぜあなたに処方された可能性が高いのか。' },
      { icon: '🕐', title: '服用方法を分かりやすく', desc: '"1-0-1"、"nüchtern"（空腹時）、"zu den Mahlzeiten"（食事とともに）：Medyraは服用スケジュールを明確な毎日のルーティンに翻訳します。' },
      { icon: '⚠️', title: '注意すべきこと', desc: 'プランからの注意事項を分かりやすくまとめ、薬局や医師への適切な質問も提供します。' },
    ],
    note: {
      icon: '🛡️', title: '安全第一',
      text: 'Medyraは決して用量を変更したり、治療の推奨をしたりしません。医師が処方した内容を説明し、薬局や診察で正しい質問ができるようにします。医師に相談せずに薬を中止しないでください。',
    },
    faqTitle: 'よくある質問',
    faq: [
      { q: '何をアップロードできますか？', a: 'ドイツの標準化された服薬プラン（BMP）、処方箋、退院時の投薬リスト、または用法が書かれたパッケージの写真を、PDF、写真、またはテキストでアップロードできます。' },
      { q: 'Medyraは相互作用を検出しますか？', a: 'Medyraはプランに記載されている内容を説明し、文書内の注意事項を指摘します。これは拘束力のある相互作用チェックの代わりにはなりません：最終的な確認は薬局または医師の役割です。Medyraはそのための適切な質問を提供します。' },
      { q: 'Medyraは私の用量を変更しますか？', a: '決してしません。Medyraは用量や治療の推奨を行いません。医師が処方した内容を分かりやすい言葉で説明するだけです。' },
      { q: '私の健康データは安全ですか？', a: 'はい。暗号化処理、GDPRに準拠したフランクフルトでのホスティング、30日後の自動削除（希望すれば即時）。' },
    ],
    ctaTitle: 'もう錠剤が何のためか推測する必要はありません',
    ctaSub: '月3件の文書が無料。GDPR準拠、暗号化、自動削除。',
    ctaButton: '服薬プランを説明する',
    ctaNote: 'Medyraは医療または薬学的アドバイスの代わりにはなりません。',
  },

  ko: {
    headerTitle: '약물 이해하기', headerCta: '계획표 업로드',
    badge: '복약 계획표 · 처방전 · BMP',
    h1a: '무엇을 복용하는지,', h1b: '그리고 왜 복용하는지 알기',
    sub: '"1-0-1", "nüchtern"(공복), 라틴어 유효 성분명: Medyra는 독일어 복약 계획표를 약물별로, 쉬운 언어로 60초 이내에 설명합니다.',
    cta: '복약 계획표 업로드',
    mock: {
      labelOut: 'Medyra가 계획표를 설명합니다',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: '혈압약. 아침에 한 알, 가능하면 항상 같은 시간에.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: '혈당을 낮춥니다. 아침 식사와 저녁 식사에 각각 한 알씩.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: '위 보호제. 아침 식사 30분 전에 한 알.' },
      ],
    },
    cardsLabel: '받게 되는 것', cardsTitle: '모든 약물을 명확하게 설명',
    cards: [
      { icon: '💊', title: '이 약은 무엇을 위한 것인가요?', desc: '계획표의 각 유효 성분을 설명합니다: 무엇을 하는지, 왜 처방되었을 가능성이 있는지.' },
      { icon: '🕐', title: '복용법을 이해하기 쉽게', desc: '"1-0-1", "nüchtern"(공복), "zu den Mahlzeiten"(식사와 함께): Medyra는 복용 스케줄을 명확한 일상 루틴으로 번역합니다.' },
      { icon: '⚠️', title: '주의해야 할 사항', desc: '계획표의 참고 사항을 명확하게 요약하고, 약국이나 의사에게 물어볼 올바른 질문도 제공합니다.' },
    ],
    note: {
      icon: '🛡️', title: '안전 최우선',
      text: 'Medyra는 절대 용량을 변경하거나 치료를 권장하지 않습니다. 의사가 처방한 내용을 설명하여 약국과 진료 시 올바른 질문을 할 수 있도록 돕습니다. 의사와 상의 없이 절대 약 복용을 중단하지 마세요.',
    },
    faqTitle: '자주 묻는 질문',
    faq: [
      { q: '무엇을 업로드할 수 있나요?', a: '독일 표준화 복약 계획표(BMP), 처방전, 퇴원 시 약물 목록 또는 복용 안내가 있는 포장 사진을 PDF, 사진 또는 텍스트로 업로드할 수 있습니다.' },
      { q: 'Medyra가 상호작용을 감지하나요?', a: 'Medyra는 계획표에 있는 내용을 설명하고 문서 내 참고 사항을 짚어줍니다. 이는 구속력 있는 상호작용 검사를 대체하지 않습니다: 최종 확인은 약국이나 의사의 몫입니다. Medyra는 이를 위한 올바른 질문을 제공합니다.' },
      { q: 'Medyra가 제 용량을 변경하나요?', a: '절대 아닙니다. Medyra는 용량이나 치료 권장을 하지 않습니다. 의사가 처방한 내용을 쉬운 언어로 설명할 뿐입니다.' },
      { q: '제 건강 데이터는 안전한가요?', a: '네. 암호화된 처리, GDPR을 준수하는 프랑크푸르트 호스팅, 30일 후 자동 삭제(요청 시 즉시 삭제).' },
    ],
    ctaTitle: '더 이상 알약이 무엇을 위한 것인지 추측하지 마세요',
    ctaSub: '월 3건 문서 무료. GDPR 준수, 암호화, 자동 삭제.',
    ctaButton: '복약 계획표 설명받기',
    ctaNote: 'Medyra는 의료 또는 약학적 조언을 대체하지 않습니다.',
  },

  hi: {
    headerTitle: 'अपनी दवाएं समझें', headerCta: 'योजना अपलोड करें',
    badge: 'दवा योजना · नुस्खा · BMP',
    h1a: 'जानें कि आप क्या', h1b: 'ले रहे हैं और क्यों',
    sub: '"1-0-1", "nüchtern" (खाली पेट), लैटिन में सक्रिय तत्व: Medyra आपकी जर्मन दवा योजना को दवा दर दवा, सरल भाषा में और 60 सेकंड से कम समय में समझाता है।',
    cta: 'दवा योजना अपलोड करें',
    mock: {
      labelOut: 'Medyra आपकी योजना समझाता है',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'रक्तचाप की दवा। सुबह एक गोली, आदर्श रूप से हमेशा एक ही समय पर।' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'रक्त शर्करा कम करता है। नाश्ते के साथ एक गोली और रात के खाने के साथ एक गोली।' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'पेट की सुरक्षा। नाश्ते से 30 मिनट पहले एक गोली।' },
      ],
    },
    cardsLabel: 'आपको क्या मिलता है', cardsTitle: 'हर दवा, स्पष्ट रूप से समझाई गई',
    cards: [
      { icon: '💊', title: 'यह दवा किसलिए है?', desc: 'आपकी योजना में हर सक्रिय तत्व समझाया गया है: यह क्या करता है और यह आपको संभवतः क्यों निर्धारित किया गया।' },
      { icon: '🕐', title: 'सेवन, समझने योग्य', desc: '"1-0-1", "nüchtern" (खाली पेट), "zu den Mahlzeiten" (भोजन के साथ): Medyra खुराक योजना को एक स्पष्ट दैनिक दिनचर्या में अनुवाद करता है।' },
      { icon: '⚠️', title: 'किन बातों पर ध्यान दें', desc: 'आपकी योजना से नोट्स स्पष्ट रूप से संक्षेपित, साथ ही आपकी फार्मेसी या डॉक्टर के लिए सही सवाल।' },
    ],
    note: {
      icon: '🛡️', title: 'सुरक्षा सबसे पहले',
      text: 'Medyra कभी भी खुराक नहीं बदलता और कोई उपचार सिफारिश नहीं देता। यह बताता है कि आपके डॉक्टर ने क्या निर्धारित किया है ताकि आप फार्मेसी और अपनी मुलाकात में सही सवाल पूछ सकें। अपने डॉक्टर से बात किए बिना कभी भी दवा बंद न करें।',
    },
    faqTitle: 'सामान्य प्रश्न',
    faq: [
      { q: 'मैं क्या अपलोड कर सकता हूं?', a: 'आपकी जर्मन मानकीकृत दवा योजना (BMP), नुस्खे, डिस्चार्ज दवा सूचियां, या उपयोग निर्देशों के साथ पैकेजों की फोटो, PDF, फोटो या टेक्स्ट के रूप में।' },
      { q: 'क्या Medyra इंटरैक्शन का पता लगाता है?', a: 'Medyra बताता है कि आपकी योजना में क्या है और दस्तावेज़ में नोट्स की ओर इशारा करता है। यह एक बाध्यकारी इंटरैक्शन जांच का विकल्प नहीं है: अंतिम जांच आपकी फार्मेसी या डॉक्टर के पास होती है। Medyra आपको इसके लिए सही सवाल देता है।' },
      { q: 'क्या Medyra मेरी खुराक बदलता है?', a: 'कभी नहीं। Medyra कोई खुराक या उपचार सिफारिश नहीं देता। यह केवल सरल भाषा में बताता है कि आपके डॉक्टर ने क्या निर्धारित किया है।' },
      { q: 'क्या मेरा स्वास्थ्य डेटा सुरक्षित है?', a: 'हां। एन्क्रिप्टेड प्रोसेसिंग, GDPR के अनुरूप फ्रैंकफर्ट में होस्टिंग, 30 दिनों के बाद स्वचालित रूप से हटाना (अनुरोध पर तुरंत)।' },
    ],
    ctaTitle: 'अब कभी अंदाज़ा न लगाएं कि एक गोली किसलिए है',
    ctaSub: 'हर महीने 3 दस्तावेज़ मुफ़्त। GDPR अनुरूप, एन्क्रिप्टेड, स्वचालित रूप से हटाया गया।',
    ctaButton: 'मेरी दवा योजना समझाएं',
    ctaNote: 'Medyra चिकित्सा या फार्मास्युटिकल सलाह का विकल्प नहीं है।',
  },

  bn: {
    headerTitle: 'আপনার ওষুধ বুঝুন', headerCta: 'পরিকল্পনা আপলোড করুন',
    badge: 'ওষুধের পরিকল্পনা · প্রেসক্রিপশন · BMP',
    h1a: 'জানুন আপনি কী', h1b: 'গ্রহণ করছেন এবং কেন',
    sub: '"１-０-１", "nüchtern" (খালি পেটে), লাতিন ভাষায় সক্রিয় উপাদান: Medyra আপনার জার্মান ওষুধের পরিকল্পনা ওষুধ ধরে ধরে, সহজ ভাষায় এবং ৬০ সেকেন্ডেরও কম সময়ে ব্যাখ্যা করে।',
    cta: 'ওষুধের পরিকল্পনা আপলোড করুন',
    mock: {
      labelOut: 'Medyra আপনার পরিকল্পনা ব্যাখ্যা করে',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'রক্তচাপের ওষুধ। সকালে একটি ট্যাবলেট, আদর্শভাবে সবসময় একই সময়ে।' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'রক্তে শর্করা কমায়। সকালের নাশতা ও রাতের খাবারের সাথে একটি করে ট্যাবলেট।' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'পেটের সুরক্ষা। নাশতার ৩০ মিনিট আগে একটি ট্যাবলেট।' },
      ],
    },
    cardsLabel: 'আপনি যা পাবেন', cardsTitle: 'প্রতিটি ওষুধ, স্পষ্টভাবে ব্যাখ্যা করা',
    cards: [
      { icon: '💊', title: 'এই ওষুধ কীসের জন্য?', desc: 'আপনার পরিকল্পনার প্রতিটি সক্রিয় উপাদান ব্যাখ্যা করা হয়েছে: এটি কী করে এবং কেন সম্ভবত এটি আপনাকে নির্ধারণ করা হয়েছে।' },
      { icon: '🕐', title: 'গ্রহণ, বোধগম্যভাবে', desc: '"1-0-1", "nüchtern" (খালি পেটে), "zu den Mahlzeiten" (খাবারের সাথে): Medyra ডোজ পরিকল্পনাকে একটি স্পষ্ট দৈনিক রুটিনে অনুবাদ করে।' },
      { icon: '⚠️', title: 'কী বিষয়ে সতর্ক থাকবেন', desc: 'আপনার পরিকল্পনার নোটগুলি স্পষ্টভাবে সংক্ষিপ্ত, সাথে আপনার ফার্মেসি বা ডাক্তারের জন্য সঠিক প্রশ্ন।' },
    ],
    note: {
      icon: '🛡️', title: 'নিরাপত্তা প্রথমে',
      text: 'Medyra কখনও ডোজ পরিবর্তন করে না এবং কোনো চিকিৎসা সুপারিশ দেয় না। এটি ব্যাখ্যা করে আপনার ডাক্তার কী নির্ধারণ করেছেন যাতে আপনি ফার্মেসি এবং আপনার সাক্ষাতে সঠিক প্রশ্ন জিজ্ঞাসা করতে পারেন। আপনার ডাক্তারের সাথে কথা না বলে কখনও ওষুধ বন্ধ করবেন না।',
    },
    faqTitle: 'সাধারণ প্রশ্ন',
    faq: [
      { q: 'আমি কী আপলোড করতে পারি?', a: 'আপনার জার্মান প্রমিত ওষুধ পরিকল্পনা (BMP), প্রেসক্রিপশন, ডিসচার্জ ওষুধের তালিকা, বা ব্যবহারের নির্দেশাবলীসহ প্যাকেজের ছবি, PDF, ছবি বা টেক্সট আকারে।' },
      { q: 'Medyra কি মিথস্ক্রিয়া শনাক্ত করে?', a: 'Medyra আপনার পরিকল্পনায় যা আছে তা ব্যাখ্যা করে এবং নথিতে নোটগুলি নির্দেশ করে। এটি একটি বাধ্যতামূলক মিথস্ক্রিয়া পরীক্ষার বিকল্প নয়: চূড়ান্ত পরীক্ষা আপনার ফার্মেসি বা ডাক্তারের কাছে থাকে। Medyra আপনাকে এর জন্য সঠিক প্রশ্ন দেয়।' },
      { q: 'Medyra কি আমার ডোজ পরিবর্তন করে?', a: 'কখনোই না। Medyra কোনো ডোজ বা চিকিৎসা সুপারিশ দেয় না। এটি শুধু সহজ ভাষায় ব্যাখ্যা করে আপনার ডাক্তার কী নির্ধারণ করেছেন।' },
      { q: 'আমার স্বাস্থ্য তথ্য কি নিরাপদ?', a: 'হ্যাঁ। এনক্রিপ্ট করা প্রক্রিয়াকরণ, GDPR সম্মত ফ্রাঙ্কফুর্ট হোস্টিং, ৩০ দিন পর স্বয়ংক্রিয় মুছে ফেলা (অনুরোধে তাৎক্ষণিক)।' },
    ],
    ctaTitle: 'আর কখনো অনুমান করতে হবে না একটি বড়ি কীসের জন্য',
    ctaSub: 'মাসে ৩টি নথি বিনামূল্যে। GDPR সম্মত, এনক্রিপ্টেড, স্বয়ংক্রিয়ভাবে মুছে ফেলা।',
    ctaButton: 'আমার ওষুধের পরিকল্পনা ব্যাখ্যা করুন',
    ctaNote: 'Medyra চিকিৎসা বা ফার্মাসিউটিক্যাল পরামর্শের বিকল্প নয়।',
  },

  ur: {
    headerTitle: 'اپنی دوائیں سمجھیں', headerCta: 'منصوبہ اپ لوڈ کریں',
    badge: 'ادویات کا منصوبہ · نسخہ · BMP',
    h1a: 'جانیں کہ آپ کیا', h1b: 'لے رہے ہیں اور کیوں',
    sub: '"1-0-1"، "nüchtern" (خالی پیٹ)، لاطینی میں فعال اجزاء: Medyra آپ کے جرمن ادویاتی منصوبے کو دوا بہ دوا، آسان زبان میں اور 60 سیکنڈ سے کم وقت میں بیان کرتا ہے۔',
    cta: 'ادویات کا منصوبہ اپ لوڈ کریں',
    mock: {
      labelOut: 'Medyra آپ کا منصوبہ بیان کرتا ہے',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'بلڈ پریشر کی دوا۔ صبح ایک گولی، مثالی طور پر ہمیشہ ایک ہی وقت پر۔' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'بلڈ شوگر کم کرتی ہے۔ ناشتے اور رات کے کھانے کے ساتھ ایک ایک گولی۔' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'معدے کا تحفظ۔ ناشتے سے 30 منٹ پہلے ایک گولی۔' },
      ],
    },
    cardsLabel: 'آپ کو کیا ملتا ہے', cardsTitle: 'ہر دوا، واضح طور پر بیان کی گئی',
    cards: [
      { icon: '💊', title: 'یہ دوا کس لیے ہے؟', desc: 'آپ کے منصوبے میں ہر فعال جزو بیان کیا گیا ہے: یہ کیا کرتا ہے اور کیوں شاید آپ کو تجویز کیا گیا۔' },
      { icon: '🕐', title: 'استعمال، قابل فہم', desc: '"1-0-1"، "nüchtern" (خالی پیٹ)، "zu den Mahlzeiten" (کھانے کے ساتھ): Medyra خوراک کے شیڈول کو ایک واضح روزمرہ معمول میں ترجمہ کرتا ہے۔' },
      { icon: '⚠️', title: 'کن باتوں پر توجہ دیں', desc: 'آپ کے منصوبے سے نوٹس واضح طور پر خلاصہ کیے گئے، ساتھ ہی آپ کی فارمیسی یا ڈاکٹر کے لیے صحیح سوالات۔' },
    ],
    note: {
      icon: '🛡️', title: 'حفاظت سب سے پہلے',
      text: 'Medyra کبھی بھی خوراک تبدیل نہیں کرتا اور کوئی علاج کی سفارش نہیں دیتا۔ یہ بتاتا ہے کہ آپ کے ڈاکٹر نے کیا تجویز کیا ہے تاکہ آپ فارمیسی اور اپنی ملاقات میں صحیح سوالات پوچھ سکیں۔ اپنے ڈاکٹر سے بات کیے بغیر کبھی بھی دوا بند نہ کریں۔',
    },
    faqTitle: 'اکثر پوچھے گئے سوالات',
    faq: [
      { q: 'میں کیا اپ لوڈ کر سکتا ہوں؟', a: 'آپ کا جرمن معیاری ادویاتی منصوبہ (BMP)، نسخے، ڈسچارج ادویات کی فہرستیں، یا استعمال کی ہدایات کے ساتھ پیکجوں کی تصویر، PDF، تصویر یا متن کی صورت میں۔' },
      { q: 'کیا Medyra تعاملات کا پتہ لگاتا ہے؟', a: 'Medyra بتاتا ہے کہ آپ کے منصوبے میں کیا ہے اور دستاویز میں نوٹس کی نشاندہی کرتا ہے۔ یہ ایک پابند تعامل چیک کا متبادل نہیں ہے: حتمی چیک آپ کی فارمیسی یا ڈاکٹر کے پاس ہوتا ہے۔ Medyra آپ کو اس کے لیے صحیح سوالات دیتا ہے۔' },
      { q: 'کیا Medyra میری خوراک تبدیل کرتا ہے؟', a: 'کبھی نہیں۔ Medyra کوئی خوراک یا علاج کی سفارش نہیں دیتا۔ یہ صرف آسان زبان میں بتاتا ہے کہ آپ کے ڈاکٹر نے کیا تجویز کیا ہے۔' },
      { q: 'کیا میرا صحت کا ڈیٹا محفوظ ہے؟', a: 'جی ہاں۔ خفیہ کاری کے ساتھ پروسیسنگ، GDPR کے مطابق فرینکفرٹ میں ہوسٹنگ، 30 دن بعد خودکار حذف (درخواست پر فوری)۔' },
    ],
    ctaTitle: 'اب کبھی اندازہ نہیں لگانا پڑے گا کہ ایک گولی کس لیے ہے',
    ctaSub: 'ماہانہ 3 دستاویزات مفت۔ GDPR کے مطابق، خفیہ کاری، خودکار حذف۔',
    ctaButton: 'میرا ادویاتی منصوبہ سمجھائیں',
    ctaNote: 'Medyra طبی یا دوا سازی کے مشورے کا متبادل نہیں ہے۔',
  },
}
