// Localized content for /medikamente. German is the SEO base; unlisted
// languages fall back to English. Medication names stay as printed on plans.
export const CONTENT = {
  de: {
    headerTitle: 'Medikamente verstehen',
    headerCta: 'Plan hochladen',
    badge: 'Medikationsplan · Rezept · BMP',
    h1a: 'Wissen, was Sie',
    h1b: 'einnehmen und warum',
    sub: '"1-0-1", "nüchtern", Wirkstoffnamen in Latein: Medyra erklärt Ihren Medikationsplan Medikament für Medikament, in klarer Sprache und in unter 60 Sekunden.',
    cta: 'Medikationsplan hochladen',
    mock: {
      labelOut: 'Medyra erklärt Ihren Plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Blutdrucksenker. Morgens eine Tablette, am besten immer zur gleichen Zeit.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Senkt den Blutzucker. Morgens und abends je eine Tablette zum Essen.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Magenschutz. Eine Tablette 30 Minuten vor dem Frühstück.' },
      ],
    },
    cardsLabel: 'Was Sie bekommen',
    cardsTitle: 'Jedes Medikament, klar erklärt',
    cards: [
      { icon: '💊', title: 'Wofür ist das Medikament?', desc: 'Jeder Wirkstoff auf Ihrem Plan wird erklärt: was er bewirkt und warum er Ihnen wahrscheinlich verschrieben wurde.' },
      { icon: '🕐', title: 'Einnahme, verständlich', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra übersetzt das Dosierschema in einen klaren Tagesablauf.' },
      { icon: '⚠️', title: 'Worauf Sie achten sollten', desc: 'Hinweise aus Ihrem Plan, verständlich zusammengefasst, plus die richtigen Fragen für Ihre Apotheke oder Arztpraxis.' },
    ],
    note: {
      icon: '🛡️', title: 'Sicherheit zuerst',
      text: 'Medyra ändert niemals Dosierungen und gibt keine Therapieempfehlungen. Es erklärt, was Ihre Ärztin verordnet hat, damit Sie in der Apotheke und im Arztgespräch die richtigen Fragen stellen können. Setzen Sie Medikamente nie ohne ärztliche Rücksprache ab.',
    },
    faqTitle: 'Häufige Fragen',
    faq: [
      { q: 'Was kann ich hochladen?', a: 'Ihren bundeseinheitlichen Medikationsplan (BMP), Rezepte, Entlassungs-Medikationslisten oder ein Foto der Packungen mit Einnahmehinweisen, als PDF, Foto oder Text.' },
      { q: 'Erkennt Medyra Wechselwirkungen?', a: 'Medyra erklärt, was auf Ihrem Plan steht, und weist auf Hinweise im Dokument hin. Eine verbindliche Wechselwirkungsprüfung ersetzt das nicht: Die abschließende Prüfung gehört in Ihre Apotheke oder Arztpraxis. Medyra gibt Ihnen die richtigen Fragen dafür mit.' },
      { q: 'Ändert Medyra meine Dosierung?', a: 'Niemals. Medyra gibt keine Dosierungs- oder Therapieempfehlungen. Es erklärt ausschließlich verständlich, was Ihre Ärztin verordnet hat.' },
      { q: 'Sind meine Gesundheitsdaten sicher?', a: 'Ja. Verschlüsselte Verarbeitung, DSGVO-konformes Hosting in Frankfurt, automatische Löschung nach 30 Tagen (auf Wunsch sofort).' },
    ],
    ctaTitle: 'Nie wieder raten, wofür die Tablette ist',
    ctaSub: '3 Dokumente pro Monat kostenlos. DSGVO-konform, verschlüsselt, automatisch gelöscht.',
    ctaButton: 'Medikationsplan erklären lassen',
    ctaNote: 'Medyra ersetzt keine ärztliche oder pharmazeutische Beratung.',
  },

  en: {
    headerTitle: 'Understand medications',
    headerCta: 'Upload plan',
    badge: 'Medication plan · Prescription · BMP',
    h1a: 'Know what you take',
    h1b: 'and why',
    sub: '"1-0-1", "nüchtern", active ingredients in Latin: Medyra explains your German medication plan drug by drug, in plain language and in under 60 seconds.',
    cta: 'Upload medication plan',
    mock: {
      labelOut: 'Medyra explains your plan',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Blood pressure medication. One tablet in the morning, ideally always at the same time.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Lowers blood sugar. One tablet with breakfast and one with dinner.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Stomach protection. One tablet 30 minutes before breakfast.' },
      ],
    },
    cardsLabel: 'What you get',
    cardsTitle: 'Every medication, clearly explained',
    cards: [
      { icon: '💊', title: 'What is this medication for?', desc: 'Every active ingredient on your plan gets explained: what it does and why it was likely prescribed to you.' },
      { icon: '🕐', title: 'Dosing, made understandable', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra translates the dosing scheme into a clear daily routine.' },
      { icon: '⚠️', title: 'What to watch out for', desc: 'Notes from your plan, summarized clearly, plus the right questions for your pharmacy or doctor.' },
    ],
    note: {
      icon: '🛡️', title: 'Safety first',
      text: 'Medyra never changes dosages and gives no therapy recommendations. It explains what your doctor prescribed so you can ask the right questions at the pharmacy and in your appointment. Never stop a medication without talking to your doctor.',
    },
    faqTitle: 'Frequent questions',
    faq: [
      { q: 'What can I upload?', a: 'Your German standardized medication plan (BMP), prescriptions, discharge medication lists or a photo of the packages with dosing notes, as PDF, photo or text.' },
      { q: 'Does Medyra detect interactions?', a: 'Medyra explains what is on your plan and points out notes in the document. It does not replace a binding interaction check: the final check belongs with your pharmacy or doctor. Medyra gives you the right questions for that.' },
      { q: 'Does Medyra change my dosage?', a: 'Never. Medyra gives no dosage or therapy recommendations. It only explains, in plain language, what your doctor prescribed.' },
      { q: 'Is my health data safe?', a: 'Yes. Encrypted processing, GDPR compliant hosting in Frankfurt, automatic deletion after 30 days (immediately on request).' },
    ],
    ctaTitle: 'Never guess again what a pill is for',
    ctaSub: '3 documents per month free. GDPR compliant, encrypted, deleted automatically.',
    ctaButton: 'Explain my medication plan',
    ctaNote: 'Medyra does not replace medical or pharmaceutical advice.',
  },

  tr: {
    headerTitle: 'İlaçlarınızı anlayın',
    headerCta: 'Plan yükle',
    badge: 'İlaç planı · Reçete · BMP',
    h1a: 'Ne aldığınızı',
    h1b: 've neden aldığınızı bilin',
    sub: '"1-0-1", "nüchtern", Latince etken maddeler: Medyra Almanca ilaç planınızı ilaç ilaç, anlaşılır dille ve 60 saniyeden kısa sürede açıklar.',
    cta: 'İlaç planını yükle',
    mock: {
      labelOut: 'Medyra planınızı açıklıyor',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Tansiyon ilacı. Sabahları bir tablet, mümkünse hep aynı saatte.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Kan şekerini düşürür. Sabah ve akşam yemekle birer tablet.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Mide koruyucu. Kahvaltıdan 30 dakika önce bir tablet.' },
      ],
    },
    cardsLabel: 'Ne alırsınız',
    cardsTitle: 'Her ilaç, net açıklanmış',
    cards: [
      { icon: '💊', title: 'Bu ilaç ne için?', desc: 'Planınızdaki her etken madde açıklanır: ne işe yarar ve size neden yazılmış olabilir.' },
      { icon: '🕐', title: 'Kullanım, anlaşılır', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra doz şemasını net bir günlük düzene çevirir.' },
      { icon: '⚠️', title: 'Nelere dikkat etmelisiniz', desc: 'Planınızdaki notlar anlaşılır şekilde özetlenir; eczaneniz veya doktorunuz için doğru sorularla birlikte.' },
    ],
    note: {
      icon: '🛡️', title: 'Önce güvenlik',
      text: 'Medyra asla doz değiştirmez ve tedavi önerisi vermez. Doktorunuzun ne yazdığını açıklar; böylece eczanede ve muayenede doğru soruları sorabilirsiniz. İlaçları asla doktorunuza danışmadan bırakmayın.',
    },
    faqTitle: 'Sık sorulan sorular',
    faq: [
      { q: 'Neler yükleyebilirim?', a: 'Standart Alman ilaç planınızı (BMP), reçeteleri, taburcu ilaç listelerini veya kullanım notlu kutu fotoğraflarını; PDF, fotoğraf veya metin olarak.' },
      { q: 'Medyra etkileşimleri tanır mı?', a: 'Medyra planınızda yazanları açıklar ve belgedeki uyarılara dikkat çeker. Bağlayıcı bir etkileşim kontrolünün yerine geçmez: son kontrol eczanenizin veya doktorunuzun işidir. Medyra bunun için doğru soruları verir.' },
      { q: 'Medyra dozumu değiştirir mi?', a: 'Asla. Medyra doz veya tedavi önerisi vermez. Yalnızca doktorunuzun yazdığını anlaşılır şekilde açıklar.' },
      { q: 'Sağlık verilerim güvende mi?', a: 'Evet. Şifreli işleme, Frankfurt’ta GDPR uyumlu barındırma, 30 gün sonra otomatik silme (istekle hemen).' },
    ],
    ctaTitle: 'Hangi hap ne için, bir daha tahmin etmeyin',
    ctaSub: 'Ayda 3 belge ücretsiz. GDPR uyumlu, şifreli, otomatik silinir.',
    ctaButton: 'İlaç planımı açıkla',
    ctaNote: 'Medyra tıbbi veya eczacılık danışmanlığının yerini tutmaz.',
  },

  ar: {
    headerTitle: 'افهم أدويتك',
    headerCta: 'ارفع الخطة',
    badge: 'خطة أدوية · وصفة · BMP',
    h1a: 'اعرف ماذا تتناول',
    h1b: 'ولماذا',
    sub: '"1-0-1"، "nüchtern"، أسماء لاتينية: يشرح Medyra خطة أدويتك الألمانية دواءً دواءً، بلغة واضحة وفي أقل من 60 ثانية.',
    cta: 'ارفع خطة الأدوية',
    mock: {
      labelOut: 'Medyra يشرح خطتك',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'دواء لضغط الدم. قرص واحد صباحاً، ويفضل في نفس الوقت دائماً.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'يخفض سكر الدم. قرص مع الفطور وقرص مع العشاء.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'حماية للمعدة. قرص قبل الفطور بـ 30 دقيقة.' },
      ],
    },
    cardsLabel: 'ما تحصل عليه',
    cardsTitle: 'كل دواء، مشروح بوضوح',
    cards: [
      { icon: '💊', title: 'لماذا هذا الدواء؟', desc: 'كل مادة فعالة في خطتك تُشرح: ماذا تفعل ولماذا وُصفت لك على الأرجح.' },
      { icon: '🕐', title: 'طريقة التناول، بوضوح', desc: '"1-0-1"، "nüchtern": يحول Medyra جدول الجرعات إلى روتين يومي واضح.' },
      { icon: '⚠️', title: 'ما الذي تنتبه له', desc: 'ملاحظات خطتك ملخصة بوضوح، مع الأسئلة الصحيحة لصيدليتك أو طبيبك.' },
    ],
    note: {
      icon: '🛡️', title: 'السلامة أولاً',
      text: 'لا يغيّر Medyra الجرعات أبداً ولا يقدم توصيات علاجية. إنه يشرح ما وصفه طبيبك لتطرح الأسئلة الصحيحة في الصيدلية وفي الموعد. لا توقف دواءً أبداً دون استشارة طبيبك.',
    },
    faqTitle: 'أسئلة شائعة',
    faq: [
      { q: 'ما الذي يمكنني رفعه؟', a: 'خطة الأدوية الألمانية الموحدة (BMP)، الوصفات، قوائم أدوية الخروج أو صورة للعبوات مع ملاحظات التناول؛ كملف PDF أو صورة أو نص.' },
      { q: 'هل يكشف Medyra التداخلات الدوائية؟', a: 'يشرح Medyra ما في خطتك وينبه إلى الملاحظات في المستند. هذا لا يغني عن فحص تداخلات ملزم: الفحص النهائي من اختصاص صيدليتك أو طبيبك. يمنحك Medyra الأسئلة الصحيحة لذلك.' },
      { q: 'هل يغيّر Medyra جرعتي؟', a: 'أبداً. لا يقدم Medyra توصيات جرعات أو علاج. إنه يشرح فقط بوضوح ما وصفه طبيبك.' },
      { q: 'هل بياناتي الصحية آمنة؟', a: 'نعم. معالجة مشفرة، استضافة متوافقة مع GDPR في فرانكفورت، حذف تلقائي بعد 30 يوماً (وفوراً عند الطلب).' },
    ],
    ctaTitle: 'لا تخمن بعد اليوم لماذا هذا القرص',
    ctaSub: '3 مستندات شهرياً مجاناً. متوافق مع GDPR، مشفر، يُحذف تلقائياً.',
    ctaButton: 'اشرح خطة أدويتي',
    ctaNote: 'لا يحل Medyra محل الاستشارة الطبية أو الصيدلانية.',
  },

  ru: {
    headerTitle: 'Понять лекарства',
    headerCta: 'Загрузить план',
    badge: 'План приёма · Рецепт · BMP',
    h1a: 'Знайте, что вы принимаете',
    h1b: 'и зачем',
    sub: '"1-0-1", "nüchtern", действующие вещества на латыни: Medyra объясняет ваш немецкий план приёма лекарство за лекарством, простым языком и меньше чем за 60 секунд.',
    cta: 'Загрузить план приёма',
    mock: {
      labelOut: 'Medyra объясняет ваш план',
      meds: [
        { name: 'Ramipril 5 mg', schedule: '1-0-0', plain: 'Препарат от давления. Одна таблетка утром, желательно всегда в одно время.' },
        { name: 'Metformin 850 mg', schedule: '1-0-1', plain: 'Снижает сахар в крови. По таблетке утром и вечером во время еды.' },
        { name: 'Pantoprazol 20 mg', schedule: '1-0-0 nüchtern', plain: 'Защита желудка. Одна таблетка за 30 минут до завтрака.' },
      ],
    },
    cardsLabel: 'Что вы получаете',
    cardsTitle: 'Каждое лекарство, понятно объяснённое',
    cards: [
      { icon: '💊', title: 'Для чего это лекарство?', desc: 'Каждое действующее вещество в плане объясняется: что оно делает и почему его, вероятно, вам назначили.' },
      { icon: '🕐', title: 'Приём, понятным языком', desc: '"1-0-1", "nüchtern", "zu den Mahlzeiten": Medyra превращает схему дозирования в понятный распорядок дня.' },
      { icon: '⚠️', title: 'На что обратить внимание', desc: 'Примечания из вашего плана, понятно резюмированные, плюс правильные вопросы для аптеки или врача.' },
    ],
    note: {
      icon: '🛡️', title: 'Безопасность прежде всего',
      text: 'Medyra никогда не меняет дозировки и не даёт рекомендаций по лечению. Он объясняет назначения врача, чтобы вы могли задать правильные вопросы в аптеке и на приёме. Никогда не отменяйте лекарства без согласования с врачом.',
    },
    faqTitle: 'Частые вопросы',
    faq: [
      { q: 'Что можно загрузить?', a: 'Немецкий стандартизированный план приёма (BMP), рецепты, списки лекарств из выписки или фото упаковок с указаниями; как PDF, фото или текст.' },
      { q: 'Определяет ли Medyra взаимодействия?', a: 'Medyra объясняет содержание плана и обращает внимание на примечания в документе. Это не заменяет обязательную проверку взаимодействий: финальная проверка остаётся за аптекой или врачом. Medyra даёт вам правильные вопросы для этого.' },
      { q: 'Меняет ли Medyra мою дозировку?', a: 'Никогда. Medyra не даёт рекомендаций по дозировкам или лечению. Он лишь понятно объясняет, что назначил ваш врач.' },
      { q: 'Мои данные о здоровье в безопасности?', a: 'Да. Зашифрованная обработка, GDPR совместимый хостинг во Франкфурте, автоматическое удаление через 30 дней (по желанию сразу).' },
    ],
    ctaTitle: 'Больше не гадайте, зачем эта таблетка',
    ctaSub: '3 документа в месяц бесплатно. GDPR, шифрование, автоматическое удаление.',
    ctaButton: 'Объяснить мой план приёма',
    ctaNote: 'Medyra не заменяет медицинскую или фармацевтическую консультацию.',
  },
}
